/* FIREFLY FUTURES PROMPT BANK
   Every prompt is a YES or NO question about YOURSELF. The room then bets on how
   many people said yes. So a good prompt is one where nobody can guess the count.

   Regenerate or extend with this exact prompt, then hand-audit every entry:

   "Write N yes or no questions for a cozy family party game. Each one asks the
   player something about their own life that they can answer instantly and
   honestly. Rules: one sentence under 80 characters, starts with Have you,
   Do you, Can you, Did you, or Would you. General audience, safe for a
   grandparent and an eight year old in the same room. NOTHING about money,
   income, appearance, weight, health, bodies, romance, relationships, politics,
   religion, alcohol, or anything embarrassing to admit out loud. Nothing that
   could out a private thing about a person. No brand names. No dash characters
   of any kind. Favour questions where you genuinely cannot predict how many
   people would say yes, because the guessing is the game. Output a JS array of
   objects with fields id, text, category. Categories: experiences, skills,
   habits, tastes, childhood, home, travel, nature."

   AUDIT RULE: read every prompt out loud and ask whether the shyest person at
   the table would be happy to answer it in front of everyone. If not, cut it.

   ⚖ STANDING DECISION (WHACKBOX_PLAN flag, resolved 2026-08-08): the "spicy or
   slightly dangerous" prompt tier described in the original pitch is CUT. It is
   not toggled off, it is not written, it does not exist in this file. We are a
   general audience studio. Do not add it later without the Director saying so.

   Launch bank 2026-08-08: 120 entries. */
window.FIREFLY_BANK = [
  {id:'ff-0001', text:'Have you ever ridden a horse?', category:'experiences'},
  {id:'ff-0002', text:'Can you whistle?', category:'skills'},
  {id:'ff-0003', text:'Have you ever seen a shooting star?', category:'nature'},
  {id:'ff-0004', text:'Do you make your bed most mornings?', category:'habits'},
  {id:'ff-0005', text:'Have you ever been on a boat at night?', category:'experiences'},
  {id:'ff-0006', text:'Do you put ketchup on eggs?', category:'tastes'},
  {id:'ff-0007', text:'Can you touch your toes without bending your knees?', category:'skills'},
  {id:'ff-0008', text:'Have you ever slept in a tent?', category:'experiences'},
  {id:'ff-0009', text:'Do you know how to change a tire?', category:'skills'},
  {id:'ff-0010', text:'Have you ever caught a fish?', category:'nature'},
  {id:'ff-0011', text:'Do you eat the crusts on your sandwich?', category:'tastes'},
  {id:'ff-0012', text:'Have you ever been in a school play?', category:'childhood'},
  {id:'ff-0013', text:'Can you name every planet in order?', category:'skills'},
  {id:'ff-0014', text:'Do you sing when nobody else is home?', category:'habits'},
  {id:'ff-0015', text:'Have you ever seen snow fall?', category:'nature'},
  {id:'ff-0016', text:'Do you have a favourite mug you always reach for?', category:'home'},
  {id:'ff-0017', text:'Have you ever been on a plane by yourself?', category:'travel'},
  {id:'ff-0018', text:'Can you ride a bike?', category:'skills'},
  {id:'ff-0019', text:'Do you like the smell of rain on hot pavement?', category:'tastes'},
  {id:'ff-0020', text:'Have you ever grown something you then ate?', category:'nature'},
  {id:'ff-0021', text:'Do you talk to animals when you meet them?', category:'habits'},
  {id:'ff-0022', text:'Have you ever slept through an alarm and been late?', category:'habits'},
  {id:'ff-0023', text:'Can you play a musical instrument?', category:'skills'},
  {id:'ff-0024', text:'Do you eat pizza with your hands?', category:'tastes'},
  {id:'ff-0025', text:'Have you ever seen the ocean in person?', category:'travel'},
  {id:'ff-0026', text:'Did you have a nickname as a kid?', category:'childhood'},
  {id:'ff-0027', text:'Do you fold your socks together in pairs?', category:'home'},
  {id:'ff-0028', text:'Have you ever climbed a tree?', category:'childhood'},
  {id:'ff-0029', text:'Can you do a cartwheel?', category:'skills'},
  {id:'ff-0030', text:'Do you read the last page of a book first?', category:'habits'},
  {id:'ff-0031', text:'Have you ever been camping in the rain?', category:'experiences'},
  {id:'ff-0032', text:'Do you like olives?', category:'tastes'},
  {id:'ff-0033', text:'Have you ever met someone famous?', category:'experiences'},
  {id:'ff-0034', text:'Can you tie a proper knot?', category:'skills'},
  {id:'ff-0035', text:'Do you keep plants alive successfully?', category:'home'},
  {id:'ff-0036', text:'Have you ever seen a rainbow end to end?', category:'nature'},
  {id:'ff-0037', text:'Did you ever bury a treasure as a kid?', category:'childhood'},
  {id:'ff-0038', text:'Do you drink your tea or coffee plain?', category:'tastes'},
  {id:'ff-0039', text:'Have you ever driven somewhere and forgotten the drive?', category:'habits'},
  {id:'ff-0040', text:'Can you swim in deep water comfortably?', category:'skills'},
  {id:'ff-0041', text:'Do you sleep with a window open?', category:'home'},
  {id:'ff-0042', text:'Have you ever been to a country where you spoke none of the language?', category:'travel'},
  {id:'ff-0043', text:'Do you eat cereal for dinner sometimes?', category:'tastes'},
  {id:'ff-0044', text:'Have you ever built a snowman?', category:'childhood'},
  {id:'ff-0045', text:'Can you touch your nose with your tongue?', category:'skills'},
  {id:'ff-0046', text:'Do you name your houseplants?', category:'home'},
  {id:'ff-0047', text:'Have you ever watched a sunrise all the way through?', category:'nature'},
  {id:'ff-0048', text:'Did you have a lucky object as a child?', category:'childhood'},
  {id:'ff-0049', text:'Do you eat the ice cream cone or leave it?', category:'tastes'},
  {id:'ff-0050', text:'Have you ever been lost somewhere unfamiliar?', category:'travel'},
  {id:'ff-0051', text:'Can you juggle three things at once?', category:'skills'},
  {id:'ff-0052', text:'Do you make lists for things you already did?', category:'habits'},
  {id:'ff-0053', text:'Have you ever seen a wild deer?', category:'nature'},
  {id:'ff-0054', text:'Do you keep old birthday cards?', category:'home'},
  {id:'ff-0055', text:'Have you ever sung in front of a crowd?', category:'experiences'},
  {id:'ff-0056', text:'Can you read a paper map?', category:'skills'},
  {id:'ff-0057', text:'Do you like the smell of a bookshop?', category:'tastes'},
  {id:'ff-0058', text:'Have you ever fallen asleep in a cinema?', category:'habits'},
  {id:'ff-0059', text:'Did you collect anything seriously as a kid?', category:'childhood'},
  {id:'ff-0060', text:'Have you ever seen a bat flying at dusk?', category:'nature'},
  {id:'ff-0061', text:'Do you butter your toast all the way to the edges?', category:'tastes'},
  {id:'ff-0062', text:'Can you start a fire without a lighter?', category:'skills'},
  {id:'ff-0063', text:'Have you ever slept outside under the stars?', category:'experiences'},
  {id:'ff-0064', text:'Do you talk in your sleep according to somebody?', category:'habits'},
  {id:'ff-0065', text:'Have you ever been on a train overnight?', category:'travel'},
  {id:'ff-0066', text:'Do you always take the same seat at the table?', category:'home'},
  {id:'ff-0067', text:'Can you say the alphabet backwards?', category:'skills'},
  {id:'ff-0068', text:'Have you ever found money on the ground?', category:'experiences'},
  {id:'ff-0069', text:'Do you like pineapple on pizza?', category:'tastes'},
  {id:'ff-0070', text:'Did you ever have a treehouse or a den?', category:'childhood'},
  {id:'ff-0071', text:'Have you ever seen a volcano or a hot spring?', category:'travel'},
  {id:'ff-0072', text:'Do you save the last bite of the best thing for the end?', category:'habits'},
  {id:'ff-0073', text:'Can you knit, sew, or mend a hole?', category:'skills'},
  {id:'ff-0074', text:'Have you ever grown a sunflower taller than you?', category:'nature'},
  {id:'ff-0075', text:'Do you sort your books by colour?', category:'home'},
  {id:'ff-0076', text:'Have you ever been in a boat you had to row yourself?', category:'experiences'},
  {id:'ff-0077', text:'Do you eat the pickle that comes with the meal?', category:'tastes'},
  {id:'ff-0078', text:'Can you do a handstand?', category:'skills'},
  {id:'ff-0079', text:'Did you ever run away from home for an afternoon?', category:'childhood'},
  {id:'ff-0080', text:'Have you ever seen fog roll in over water?', category:'nature'},
  {id:'ff-0081', text:'Do you keep the shoes by the door?', category:'home'},
  {id:'ff-0082', text:'Have you ever missed a flight or a train?', category:'travel'},
  {id:'ff-0083', text:'Can you cook a meal from memory with no recipe?', category:'skills'},
  {id:'ff-0084', text:'Do you like the crunchy bits at the bottom of the pan?', category:'tastes'},
  {id:'ff-0085', text:'Have you ever been woken by an animal outside?', category:'nature'},
  {id:'ff-0086', text:'Did you learn to ride a bike before you were seven?', category:'childhood'},
  {id:'ff-0087', text:'Do you reread books you already know the ending of?', category:'habits'},
  {id:'ff-0088', text:'Have you ever stayed up all night on purpose?', category:'experiences'},
  {id:'ff-0089', text:'Can you tell north from south without a phone?', category:'skills'},
  {id:'ff-0090', text:'Do you leave a light on somewhere at night?', category:'home'},
  {id:'ff-0091', text:'Have you ever eaten something you picked wild?', category:'nature'},
  {id:'ff-0092', text:'Do you dip your biscuit in your drink?', category:'tastes'},
  {id:'ff-0093', text:'Have you ever driven more than five hours in one day?', category:'travel'},
  {id:'ff-0094', text:'Did you have a favourite tree when you were small?', category:'childhood'},
  {id:'ff-0095', text:'Can you do a magic trick?', category:'skills'},
  {id:'ff-0096', text:'Do you make the same thing for breakfast every day?', category:'habits'},
  {id:'ff-0097', text:'Have you ever seen a meteor shower on purpose?', category:'nature'},
  {id:'ff-0098', text:'Do you keep a drawer nobody else is allowed in?', category:'home'},
  {id:'ff-0099', text:'Have you ever been in a hot air balloon?', category:'experiences'},
  {id:'ff-0100', text:'Do you eat soup with bread in it?', category:'tastes'},
  {id:'ff-0101', text:'Can you skip a stone more than three times?', category:'skills'},
  {id:'ff-0102', text:'Have you ever sent a letter by post this year?', category:'habits'},
  {id:'ff-0103', text:'Did you have a pet when you were a child?', category:'childhood'},
  {id:'ff-0104', text:'Have you ever swum in a lake or a river?', category:'nature'},
  {id:'ff-0105', text:'Do you close the curtains as soon as it gets dark?', category:'home'},
  {id:'ff-0106', text:'Have you ever taken a trip completely alone?', category:'travel'},
  {id:'ff-0107', text:'Can you write neatly with your other hand?', category:'skills'},
  {id:'ff-0108', text:'Do you eat the skin on a baked potato?', category:'tastes'},
  {id:'ff-0109', text:'Have you ever been up a mountain above the clouds?', category:'travel'},
  {id:'ff-0110', text:'Do you hum without noticing you are doing it?', category:'habits'},
  {id:'ff-0111', text:'Did you ever win a prize at school?', category:'childhood'},
  {id:'ff-0112', text:'Have you ever seen an owl in the wild?', category:'nature'},
  {id:'ff-0113', text:'Can you throw and catch reliably?', category:'skills'},
  {id:'ff-0114', text:'Do you have a jar of things that have no home?', category:'home'},
  {id:'ff-0115', text:'Have you ever danced when you thought nobody could see?', category:'habits'},
  {id:'ff-0116', text:'Do you like your toast barely warm or properly dark?', category:'tastes'},
  {id:'ff-0117', text:'Have you ever been somewhere with no phone signal for a day?', category:'travel'},
  {id:'ff-0118', text:'Can you remember a poem all the way through?', category:'skills'},
  {id:'ff-0119', text:'Did you sleep with a light on as a kid?', category:'childhood'},
  {id:'ff-0120', text:'Have you ever watched a storm from a safe window and enjoyed it?', category:'nature'}
];
