/* FIREFLY FUTURES PROMPT BANK
   Every prompt is a YES or NO question about YOURSELF. The room then bets on how
   many people said yes. So a good prompt is one where nobody can guess the count.

   Regenerate or extend with this exact prompt, then hand-audit every entry:

   "Write N yes or no questions for a cozy family party game. Each one asks the
   player something about their own life that they can answer instantly and
   honestly. Rules: one sentence under 80 characters, starts with Have you,
   Do you, Can you, Did you, or Would you. General audience, safe for a
   grandparent and an eight year old in the same room. NOTHING about money,
   income, appearance, weight, health, bodies, romance, relationships, politics,
   religion, alcohol, or anything embarrassing to admit out loud. Nothing that
   could out a private thing about a person. No brand names. No dash characters
   of any kind. Favour questions where you genuinely cannot predict how many
   people would say yes, because the guessing is the game. Output a JS array of
   objects with fields id, text, category. Categories: experiences, skills,
   habits, tastes, childhood, home, travel, nature."

   AUDIT RULE: read every prompt out loud and ask whether the shyest person at
   the table would be happy to answer it in front of everyone. If not, cut it.

   ⚖ STANDING DECISION (WHACKBOX_PLAN flag, resolved 2026-08-08): the "spicy or
   slightly dangerous" prompt tier described in the original pitch is CUT. It is
   not toggled off, it is not written, it does not exist in this file. We are a
   general audience studio. Do not add it later without the Director saying so.

   Bank at 2026-08-08: 284 entries. */
window.FIREFLY_BANK = [
  {id:'ff-0001', text:"Have you ever ridden a horse?", category:"experiences"},
  {id:'ff-0002', text:"Can you whistle?", category:"skills"},
  {id:'ff-0003', text:"Have you ever seen a shooting star?", category:"nature"},
  {id:'ff-0004', text:"Do you make your bed most mornings?", category:"habits"},
  {id:'ff-0005', text:"Have you ever been on a boat at night?", category:"experiences"},
  {id:'ff-0006', text:"Do you put ketchup on eggs?", category:"tastes"},
  {id:'ff-0007', text:"Can you touch your toes without bending your knees?", category:"skills"},
  {id:'ff-0008', text:"Have you ever slept in a tent?", category:"experiences"},
  {id:'ff-0009', text:"Do you know how to change a tire?", category:"skills"},
  {id:'ff-0010', text:"Have you ever caught a fish?", category:"nature"},
  {id:'ff-0011', text:"Do you eat the crusts on your sandwich?", category:"tastes"},
  {id:'ff-0012', text:"Have you ever been in a school play?", category:"childhood"},
  {id:'ff-0013', text:"Can you name every planet in order?", category:"skills"},
  {id:'ff-0014', text:"Do you sing when nobody else is home?", category:"habits"},
  {id:'ff-0015', text:"Have you ever seen snow fall?", category:"nature"},
  {id:'ff-0016', text:"Do you have a favourite mug you always reach for?", category:"home"},
  {id:'ff-0017', text:"Have you ever been on a plane by yourself?", category:"travel"},
  {id:'ff-0018', text:"Can you ride a bike?", category:"skills"},
  {id:'ff-0019', text:"Do you like the smell of rain on hot pavement?", category:"tastes"},
  {id:'ff-0020', text:"Have you ever grown something you then ate?", category:"nature"},
  {id:'ff-0021', text:"Do you talk to animals when you meet them?", category:"habits"},
  {id:'ff-0022', text:"Have you ever slept through an alarm and been late?", category:"habits"},
  {id:'ff-0023', text:"Can you play a musical instrument?", category:"skills"},
  {id:'ff-0024', text:"Do you eat pizza with your hands?", category:"tastes"},
  {id:'ff-0025', text:"Have you ever seen the ocean in person?", category:"travel"},
  {id:'ff-0026', text:"Did you have a nickname as a kid?", category:"childhood"},
  {id:'ff-0027', text:"Do you fold your socks together in pairs?", category:"home"},
  {id:'ff-0028', text:"Have you ever climbed a tree?", category:"childhood"},
  {id:'ff-0029', text:"Can you do a cartwheel?", category:"skills"},
  {id:'ff-0030', text:"Do you read the last page of a book first?", category:"habits"},
  {id:'ff-0031', text:"Have you ever been camping in the rain?", category:"experiences"},
  {id:'ff-0032', text:"Do you like olives?", category:"tastes"},
  {id:'ff-0033', text:"Have you ever met someone famous?", category:"experiences"},
  {id:'ff-0034', text:"Can you tie a proper knot?", category:"skills"},
  {id:'ff-0035', text:"Do you keep plants alive successfully?", category:"home"},
  {id:'ff-0036', text:"Have you ever seen a rainbow end to end?", category:"nature"},
  {id:'ff-0037', text:"Did you ever bury a treasure as a kid?", category:"childhood"},
  {id:'ff-0038', text:"Do you drink your tea or coffee plain?", category:"tastes"},
  {id:'ff-0039', text:"Have you ever driven somewhere and forgotten the drive?", category:"habits"},
  {id:'ff-0040', text:"Can you swim in deep water comfortably?", category:"skills"},
  {id:'ff-0041', text:"Do you sleep with a window open?", category:"home"},
  {id:'ff-0042', text:"Have you ever been to a country where you spoke none of the language?", category:"travel"},
  {id:'ff-0043', text:"Do you eat cereal for dinner sometimes?", category:"tastes"},
  {id:'ff-0044', text:"Have you ever built a snowman?", category:"childhood"},
  {id:'ff-0045', text:"Can you touch your nose with your tongue?", category:"skills"},
  {id:'ff-0046', text:"Do you name your houseplants?", category:"home"},
  {id:'ff-0047', text:"Have you ever watched a sunrise all the way through?", category:"nature"},
  {id:'ff-0048', text:"Did you have a lucky object as a child?", category:"childhood"},
  {id:'ff-0049', text:"Do you eat the ice cream cone or leave it?", category:"tastes"},
  {id:'ff-0050', text:"Have you ever been lost somewhere unfamiliar?", category:"travel"},
  {id:'ff-0051', text:"Can you juggle three things at once?", category:"skills"},
  {id:'ff-0052', text:"Do you make lists for things you already did?", category:"habits"},
  {id:'ff-0053', text:"Have you ever seen a wild deer?", category:"nature"},
  {id:'ff-0054', text:"Do you keep old birthday cards?", category:"home"},
  {id:'ff-0055', text:"Have you ever sung in front of a crowd?", category:"experiences"},
  {id:'ff-0056', text:"Can you read a paper map?", category:"skills"},
  {id:'ff-0057', text:"Do you like the smell of a bookshop?", category:"tastes"},
  {id:'ff-0058', text:"Have you ever fallen asleep in a cinema?", category:"habits"},
  {id:'ff-0059', text:"Did you collect anything seriously as a kid?", category:"childhood"},
  {id:'ff-0060', text:"Have you ever seen a bat flying at dusk?", category:"nature"},
  {id:'ff-0061', text:"Do you butter your toast all the way to the edges?", category:"tastes"},
  {id:'ff-0062', text:"Can you start a fire without a lighter?", category:"skills"},
  {id:'ff-0063', text:"Have you ever slept outside under the stars?", category:"experiences"},
  {id:'ff-0064', text:"Do you talk in your sleep according to somebody?", category:"habits"},
  {id:'ff-0065', text:"Have you ever been on a train overnight?", category:"travel"},
  {id:'ff-0066', text:"Do you always take the same seat at the table?", category:"home"},
  {id:'ff-0067', text:"Can you say the alphabet backwards?", category:"skills"},
  {id:'ff-0068', text:"Have you ever found money on the ground?", category:"experiences"},
  {id:'ff-0069', text:"Do you like pineapple on pizza?", category:"tastes"},
  {id:'ff-0070', text:"Did you ever have a treehouse or a den?", category:"childhood"},
  {id:'ff-0071', text:"Have you ever seen a volcano or a hot spring?", category:"travel"},
  {id:'ff-0072', text:"Do you save the last bite of the best thing for the end?", category:"habits"},
  {id:'ff-0073', text:"Can you knit, sew, or mend a hole?", category:"skills"},
  {id:'ff-0074', text:"Have you ever grown a sunflower taller than you?", category:"nature"},
  {id:'ff-0075', text:"Do you sort your books by colour?", category:"home"},
  {id:'ff-0076', text:"Have you ever been in a boat you had to row yourself?", category:"experiences"},
  {id:'ff-0077', text:"Do you eat the pickle that comes with the meal?", category:"tastes"},
  {id:'ff-0078', text:"Can you do a handstand?", category:"skills"},
  {id:'ff-0079', text:"Did you ever run away from home for an afternoon?", category:"childhood"},
  {id:'ff-0080', text:"Have you ever seen fog roll in over water?", category:"nature"},
  {id:'ff-0081', text:"Do you keep the shoes by the door?", category:"home"},
  {id:'ff-0082', text:"Have you ever missed a flight or a train?", category:"travel"},
  {id:'ff-0083', text:"Can you cook a meal from memory with no recipe?", category:"skills"},
  {id:'ff-0084', text:"Do you like the crunchy bits at the bottom of the pan?", category:"tastes"},
  {id:'ff-0085', text:"Have you ever been woken by an animal outside?", category:"nature"},
  {id:'ff-0086', text:"Did you learn to ride a bike before you were seven?", category:"childhood"},
  {id:'ff-0087', text:"Do you reread books you already know the ending of?", category:"habits"},
  {id:'ff-0088', text:"Have you ever stayed up all night on purpose?", category:"experiences"},
  {id:'ff-0089', text:"Can you tell north from south without a phone?", category:"skills"},
  {id:'ff-0090', text:"Do you leave a light on somewhere at night?", category:"home"},
  {id:'ff-0091', text:"Have you ever eaten something you picked wild?", category:"nature"},
  {id:'ff-0092', text:"Do you dip your biscuit in your drink?", category:"tastes"},
  {id:'ff-0093', text:"Have you ever driven more than five hours in one day?", category:"travel"},
  {id:'ff-0094', text:"Did you have a favourite tree when you were small?", category:"childhood"},
  {id:'ff-0095', text:"Can you do a magic trick?", category:"skills"},
  {id:'ff-0096', text:"Do you make the same thing for breakfast every day?", category:"habits"},
  {id:'ff-0097', text:"Have you ever seen a meteor shower on purpose?", category:"nature"},
  {id:'ff-0098', text:"Do you keep a drawer nobody else is allowed in?", category:"home"},
  {id:'ff-0099', text:"Have you ever been in a hot air balloon?", category:"experiences"},
  {id:'ff-0100', text:"Do you eat soup with bread in it?", category:"tastes"},
  {id:'ff-0101', text:"Can you skip a stone more than three times?", category:"skills"},
  {id:'ff-0102', text:"Have you ever sent a letter by post this year?", category:"habits"},
  {id:'ff-0103', text:"Did you have a pet when you were a child?", category:"childhood"},
  {id:'ff-0104', text:"Have you ever swum in a lake or a river?", category:"nature"},
  {id:'ff-0105', text:"Do you close the curtains as soon as it gets dark?", category:"home"},
  {id:'ff-0106', text:"Have you ever taken a trip completely alone?", category:"travel"},
  {id:'ff-0107', text:"Can you write neatly with your other hand?", category:"skills"},
  {id:'ff-0108', text:"Do you eat the skin on a baked potato?", category:"tastes"},
  {id:'ff-0109', text:"Have you ever been up a mountain above the clouds?", category:"travel"},
  {id:'ff-0110', text:"Do you hum without noticing you are doing it?", category:"habits"},
  {id:'ff-0111', text:"Did you ever win a prize at school?", category:"childhood"},
  {id:'ff-0112', text:"Have you ever seen an owl in the wild?", category:"nature"},
  {id:'ff-0113', text:"Can you throw and catch reliably?", category:"skills"},
  {id:'ff-0114', text:"Do you have a jar of things that have no home?", category:"home"},
  {id:'ff-0115', text:"Have you ever danced when you thought nobody could see?", category:"habits"},
  {id:'ff-0116', text:"Do you like your toast barely warm or properly dark?", category:"tastes"},
  {id:'ff-0117', text:"Have you ever been somewhere with no phone signal for a day?", category:"travel"},
  {id:'ff-0118', text:"Can you remember a poem all the way through?", category:"skills"},
  {id:'ff-0119', text:"Did you sleep with a light on as a kid?", category:"childhood"},
  {id:'ff-0120', text:"Have you ever watched a storm from a safe window and enjoyed it?", category:"nature"},
  {id:'ff-0121', text:"Have you ever ridden on the back of a motorbike?", category:"experiences"},
  {id:'ff-0122', text:"Have you ever been backstage at a theatre?", category:"experiences"},
  {id:'ff-0123', text:"Have you ever been on television or the radio?", category:"experiences"},
  {id:'ff-0124', text:"Have you ever won a raffle or a lucky draw?", category:"experiences"},
  {id:'ff-0125', text:"Have you ever been in a parade or a carnival?", category:"experiences"},
  {id:'ff-0126', text:"Have you ever slept in a hammock all night?", category:"experiences"},
  {id:'ff-0127', text:"Have you ever milked a cow or a goat?", category:"experiences"},
  {id:'ff-0128', text:"Would you take a ride in a small plane if somebody invited you?", category:"experiences"},
  {id:'ff-0129', text:"Can you make bread from scratch?", category:"skills"},
  {id:'ff-0130', text:"Can you crack an egg with one hand?", category:"skills"},
  {id:'ff-0131', text:"Can you use chopsticks without thinking about it?", category:"skills"},
  {id:'ff-0132', text:"Can you drive a car with a manual gearbox?", category:"skills"},
  {id:'ff-0133', text:"Can you fold a paper plane that flies straight?", category:"skills"},
  {id:'ff-0134', text:"Can you ice skate without holding on to anything?", category:"skills"},
  {id:'ff-0135', text:"Can you say a whole sentence in another language?", category:"skills"},
  {id:'ff-0136', text:"Have you ever cooked a meal over a campfire?", category:"skills"},
  {id:'ff-0137', text:"Have you ever fixed something everybody said was finished?", category:"skills"},
  {id:'ff-0138', text:"Can you fall asleep in a car while somebody else drives?", category:"habits"},
  {id:'ff-0139', text:"Did you ever keep a diary for more than a month?", category:"habits"},
  {id:'ff-0140', text:"Do you take the stairs when there is a lift right there?", category:"habits"},
  {id:'ff-0141', text:"Do you finish every book you start?", category:"habits"},
  {id:'ff-0142', text:"Did you ever write a story just for yourself?", category:"childhood"},
  {id:'ff-0143', text:"Did you ever take something apart to see how it worked?", category:"childhood"},
  {id:'ff-0144', text:"Did you ever write to a pen friend you had never met?", category:"childhood"},
  {id:'ff-0145', text:"Did you ever walk to school without a grown up?", category:"childhood"},
  {id:'ff-0146', text:"Have you ever painted a whole room by yourself?", category:"home"},
  {id:'ff-0147', text:"Have you ever put furniture together without the instructions?", category:"home"},
  {id:'ff-0148', text:"Have you ever knocked on a neighbour's door to borrow something?", category:"home"},
  {id:'ff-0149', text:"Do you know how to reset the fuse box where you live?", category:"home"},
  {id:'ff-0150', text:"Have you ever slept in an airport or a station?", category:"travel"},
  {id:'ff-0151', text:"Have you ever been on a ferry?", category:"travel"},
  {id:'ff-0152', text:"Have you ever driven on the other side of the road?", category:"travel"},
  {id:'ff-0153', text:"Have you ever visited a building older than a thousand years?", category:"travel"},
  {id:'ff-0154', text:"Have you ever been inside a cave?", category:"travel"},
  {id:'ff-0155', text:"Have you ever flown a kite until the string ran out?", category:"nature"},
  {id:'ff-0156', text:"Have you ever seen a whale or a dolphin in the wild?", category:"nature"},
  {id:'ff-0157', text:"Have you ever fed a bird straight from your hand?", category:"nature"},
  {id:'ff-0158', text:"Have you ever held a snake or a lizard?", category:"nature"},
  {id:'ff-0159', text:"Have you ever watched a caterpillar turn into a butterfly?", category:"nature"},
  {id:'ff-0160', text:"Would you hold a spider in your hand?", category:"nature"},
  {id:'ff-0161', text:"Have you ever tried a fruit you could not name?", category:"tastes"},
  {id:'ff-0162', text:"Have you ever eaten a meal outdoors in the dark?", category:"tastes"},
  {id:'ff-0163', text:"Do you like food that is properly spicy?", category:"tastes"},
  {id:'ff-0164', text:"Can you fold a paper aeroplane that actually flies straight?", category:"skills"},
  {id:'ff-0165', text:"Can you shuffle a deck of cards and bridge them back together?", category:"skills"},
  {id:'ff-0166', text:"Can you write your name so it reads correctly in a mirror?", category:"skills"},
  {id:'ff-0167', text:"Can you clap a rhythm back after hearing it only once?", category:"skills"},
  {id:'ff-0168', text:"Can you snap your fingers with both hands?", category:"skills"},
  {id:'ff-0169', text:"Can you make an animal noise good enough to fool somebody?", category:"skills"},
  {id:'ff-0170', text:"Can you keep a straight face while people try to make you laugh?", category:"skills"},
  {id:'ff-0171', text:"Can you tell a joke without giving away the ending too early?", category:"skills"},
  {id:'ff-0172', text:"Can you say a tongue twister three times without tripping up?", category:"skills"},
  {id:'ff-0173', text:"Can you roll your Rs?", category:"skills"},
  {id:'ff-0174', text:"Can you count to ten in a language you do not really speak?", category:"skills"},
  {id:'ff-0175', text:"Can you read music well enough to follow along?", category:"skills"},
  {id:'ff-0176', text:"Can you sing a harmony under the tune somebody else is singing?", category:"skills"},
  {id:'ff-0178', text:"Can you flip something in a pan without using a spatula?", category:"skills"},
  {id:'ff-0179', text:"Can you peel an apple in one long unbroken strip?", category:"skills"},
  {id:'ff-0180', text:"Can you eat a whole meal with chopsticks?", category:"skills"},
  {id:'ff-0181', text:"Can you pour a drink right to the brim without spilling it?", category:"skills"},
  {id:'ff-0182', text:"Can you fold a paper map back the way it came?", category:"skills"},
  {id:'ff-0183', text:"Can you thread a needle on the first try?", category:"skills"},
  {id:'ff-0184', text:"Can you tie a bow behind your back without looking?", category:"skills"},
  {id:'ff-0185', text:"Can you build a house of cards two levels high?", category:"skills"},
  {id:'ff-0186', text:"Can you keep a ball up with your feet three times in a row?", category:"skills"},
  {id:'ff-0187', text:"Can you pat your head and circle your other hand at the same time?", category:"skills"},
  {id:'ff-0188', text:"Can you pick something up using only your feet?", category:"skills"},
  {id:'ff-0189', text:"Can you spin a pen right around your thumb?", category:"skills"},
  {id:'ff-0190', text:"Can you type a whole message without looking at the keys?", category:"skills"},
  {id:'ff-0191', text:"Can you write in joined up handwriting?", category:"skills"},
  {id:'ff-0192', text:"Can you solve a twisting cube puzzle?", category:"skills"},
  {id:'ff-0193', text:"Can you recite your times tables up to twelve without pausing?", category:"skills"},
  {id:'ff-0194', text:"Can you name a bird just from its song?", category:"nature"},
  {id:'ff-0195', text:"Can you name a tree from a single leaf?", category:"nature"},
  {id:'ff-0196', text:"Can you make a daisy chain that holds together?", category:"nature"},
  {id:'ff-0197', text:"Can you whistle through a blade of grass?", category:"nature"},
  {id:'ff-0198', text:"Can you fold a fitted sheet into a neat square?", category:"home"},
  {id:'ff-0199', text:"Can you wrap a present with corners that look neat?", category:"home"},
  {id:'ff-0200', text:"Can you iron a shirt without leaving new creases in it?", category:"home"},
  {id:'ff-0201', text:"Can you fold a paper fortune teller from memory?", category:"childhood"},
  {id:'ff-0202', text:"Can you make a paper snowflake with folds and scissors?", category:"childhood"},
  {id:'ff-0203', text:"Can you tell if fruit is ripe just by touching it?", category:"tastes"},
  {id:'ff-0204', text:"Can you drive a car with a manual gearstick?", category:"travel"},
  {id:'ff-0205', text:"Can you reverse into a tight parking space in one go?", category:"travel"},
  {id:'ff-0206', text:"Can you put up a tent on your own?", category:"experiences"},
  {id:'ff-0207', text:"Do you check the fridge again hoping something new is in there?", category:"habits"},
  {id:'ff-0208', text:"Do you talk to yourself while you hunt for your keys?", category:"habits"},
  {id:'ff-0209', text:"Do you rehearse a phone call in your head before you make it?", category:"habits"},
  {id:'ff-0210', text:"Do you hold your breath when you go through a tunnel?", category:"habits"},
  {id:'ff-0211', text:"Do you knock on wood after you say something hopeful?", category:"habits"},
  {id:'ff-0212', text:"Do you fold a page corner instead of using a bookmark?", category:"habits"},
  {id:'ff-0213', text:"Do you check the door is locked twice before bed?", category:"habits"},
  {id:'ff-0214', text:"Do you make a hot drink and then forget to drink it?", category:"habits"},
  {id:'ff-0215', text:"Do you read every instruction before you start?", category:"habits"},
  {id:'ff-0216', text:"Do you plan tomorrow in your head as you fall asleep?", category:"habits"},
  {id:'ff-0217', text:"Do you stir a drink that does not need stirring?", category:"habits"},
  {id:'ff-0218', text:"Do you say thank you out loud to a machine?", category:"habits"},
  {id:'ff-0219', text:"Do you draw the same doodle whenever you pick up a pen?", category:"habits"},
  {id:'ff-0220', text:"Do you count steps or tiles without meaning to?", category:"habits"},
  {id:'ff-0221', text:"Do you always put your left shoe on first?", category:"habits"},
  {id:'ff-0222', text:"Have you ever rewritten a list just to make it neater?", category:"habits"},
  {id:'ff-0223', text:"Would you turn back for a forgotten umbrella?", category:"habits"},
  {id:'ff-0224', text:"Would you rewind a song to hear one bit again?", category:"habits"},
  {id:'ff-0225', text:"Do you keep a bag full of other bags somewhere?", category:"home"},
  {id:'ff-0226', text:"Do you wash the dishes in the same order every time?", category:"home"},
  {id:'ff-0227', text:"Do you keep a drawer of cables you will never use again?", category:"home"},
  {id:'ff-0228', text:"Do you set a clock a few minutes fast on purpose?", category:"home"},
  {id:'ff-0229', text:"Do you save gift bags and ribbon to use again?", category:"home"},
  {id:'ff-0230', text:"Do you smell the milk even when you know it is fresh?", category:"home"},
  {id:'ff-0231', text:"Do you water the plants on the same day every week?", category:"home"},
  {id:'ff-0232', text:"Do you own a notebook you have never written in?", category:"home"},
  {id:'ff-0233', text:"Do you hide the good scissors from everybody else?", category:"home"},
  {id:'ff-0234', text:"Do you leave the radio on for an empty house?", category:"home"},
  {id:'ff-0235', text:"Do you keep a glass of water beside the bed at night?", category:"home"},
  {id:'ff-0236', text:"Do you keep a torch in the same place so you can find it fast?", category:"home"},
  {id:'ff-0237', text:"Do you eat standing at the counter when you are alone?", category:"home"},
  {id:'ff-0238', text:"Can you tell the kettle is nearly boiled just by the sound?", category:"skills"},
  {id:'ff-0239', text:"Can you tell who is coming by the sound of their footsteps?", category:"skills"},
  {id:'ff-0240', text:"Can you wake at the right time without setting an alarm?", category:"skills"},
  {id:'ff-0241', text:"Do you eat the toppings off before the rest?", category:"tastes"},
  {id:'ff-0242', text:"Do you put salt on before you taste the food?", category:"tastes"},
  {id:'ff-0243', text:"Did you ever keep a diary you never showed anybody?", category:"childhood"},
  {id:'ff-0244', text:"Did you ever practise your signature over and over?", category:"childhood"},
  {id:'ff-0245', text:"Do you check the sky for the moon most nights?", category:"nature"},
  {id:'ff-0246', text:"Can you pack a bag for a trip in under ten minutes?", category:"travel"},
  {id:'ff-0247', text:"Do you like coriander in your food?", category:"tastes"},
  {id:'ff-0248', text:"Do you like liquorice sweets?", category:"tastes"},
  {id:'ff-0249', text:"Do you like coconut in a dessert?", category:"tastes"},
  {id:'ff-0250', text:"Do you eat mushrooms happily?", category:"tastes"},
  {id:'ff-0251', text:"Do you eat Brussels sprouts happily?", category:"tastes"},
  {id:'ff-0252', text:"Do you like a banana that still has green on it?", category:"tastes"},
  {id:'ff-0253', text:"Do you like mint and chocolate together?", category:"tastes"},
  {id:'ff-0254', text:"Do you eat strong blue cheese happily?", category:"tastes"},
  {id:'ff-0255', text:"Do you like custard?", category:"tastes"},
  {id:'ff-0256', text:"Do you eat tomatoes raw?", category:"tastes"},
  {id:'ff-0257', text:"Do you like the texture of jelly?", category:"tastes"},
  {id:'ff-0258', text:"Do you drink fizzy drinks after they have gone flat?", category:"tastes"},
  {id:'ff-0259', text:"Do you like the smell of coffee more than the taste?", category:"tastes"},
  {id:'ff-0260', text:"Would you try a food with no idea what is in it?", category:"tastes"},
  {id:'ff-0262', text:"Do you drink the milk left in the cereal bowl?", category:"habits"},
  {id:'ff-0263', text:"Do you eat cold leftovers straight from the fridge?", category:"habits"},
  {id:'ff-0264', text:"Do you eat the frosting before the cake?", category:"habits"},
  {id:'ff-0265', text:"Do you eat the thing you like least on the plate first?", category:"habits"},
  {id:'ff-0266', text:"Do you eat the whole apple including the core?", category:"habits"},
  {id:'ff-0267', text:"Do you put pepper on nearly everything?", category:"habits"},
  {id:'ff-0268', text:"Would you eat a biscuit that fell on the kitchen floor?", category:"habits"},
  {id:'ff-0269', text:"Would you eat the same dinner every night to save deciding?", category:"habits"},
  {id:'ff-0270', text:"Can you eat comfortably with chopsticks?", category:"skills"},
  {id:'ff-0271', text:"Can you tell butter from margarine by taste alone?", category:"skills"},
  {id:'ff-0272', text:"Can you eat something very spicy without reaching for water?", category:"skills"},
  {id:'ff-0273', text:"Can you tell a herb apart by smell with your eyes closed?", category:"skills"},
  {id:'ff-0274', text:"Did you hide a food you disliked under something at dinner?", category:"childhood"},
  {id:'ff-0275', text:"Did you like a food as a child that you cannot stand now?", category:"childhood"},
  {id:'ff-0276', text:"Did you have a food you would only eat one certain way?", category:"childhood"},
  {id:'ff-0277', text:"Did you ever taste snow on purpose as a child?", category:"childhood"},
  {id:'ff-0278', text:"Do you keep the bread in the fridge?", category:"home"},
  {id:'ff-0279', text:"Do you cook with music or the radio on?", category:"home"},
  {id:'ff-0280', text:"Do you eat dinner at the table most nights?", category:"home"},
  {id:'ff-0281', text:"Do you like a scented candle in the room?", category:"home"},
  {id:'ff-0282', text:"Have you ever eaten seaweed?", category:"experiences"},
  {id:'ff-0283', text:"Have you ever made bread from scratch?", category:"experiences"},
  {id:'ff-0284', text:"Have you ever cooked a meal over an open fire?", category:"experiences"},
  {id:'ff-0285', text:"Do you like the smell of the sea at low tide?", category:"nature"},
  {id:'ff-0286', text:"Do you like the smell of a freshly turned garden bed?", category:"nature"}
];
