"""Steam achievement icons + the Steamworks table, generated from the game's own
ACH list so the names, the descriptions and the API names cannot drift by hand.

  python3 capsules/achievements.py        -> capsules/out/achievements/<API>.png (64x64, earned)
                                             capsules/out/achievements/<API>_locked.png (64x64, grey)
                                             ACHIEVEMENTS.md (the paste sheet, in Valve's field order)

Valve: 64x64, JPG or PNG, one earned and one unearned per achievement. The badge
art is transparent and oddly proportioned, so each icon is the art fitted into
a dark rounded plate with a thin brass rim: readable at 64px on Steam's dark UI,
and the locked one is the same plate greyed so the pair reads as a pair.
API name rule (mirrors steamApi() in the game): ACH_ + id.upper().
"""
import re, json, os, sys
from PIL import Image, ImageDraw, ImageOps

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.join(HERE, '..', '..', '..', 'satellites', 'stream-hop')
OUT = os.path.join(HERE, 'out', 'achievements')
os.makedirs(OUT, exist_ok=True)
html = open(os.path.join(GAME, 'index.html'), encoding='utf-8').read()

def grab_array(name):
    m = re.search(r'var ' + name + r'=\[(.*?)\n\];', html, re.S)
    assert m, name + ' not found in the game'
    rows = []
    for line in m.group(1).split('\n'):
        d = dict(re.findall(r"(\w+):\s*'((?:[^'\\]|\\.)*)'", line))
        if 'id' in d: rows.append(d)
    return rows

ACH = grab_array('ACH')
SEASONS = grab_array('SEASONS')
for s in SEASONS:
    ACH.append({'id': 'ssn_' + s['id'], 'name': s['name'], 'art': s['art'],
                'desc': 'Cross 20 rows during ' + s['name'] + '.', 'season': s['when']})
assert len(ACH) == 26, 'expected 26 badges (21 + 5 seasonal), parsed %d' % len(ACH)

# hidden on Steam: the two that are secrets in the game too (the description gives the trick away)
HIDDEN = {'secrets'}

def plate(size=64, locked=False):
    S = size * 4
    im = Image.new('RGBA', (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    rim = (200, 168, 75, 255) if not locked else (110, 110, 104, 255)
    fill = (13, 16, 12, 255) if not locked else (26, 27, 26, 255)
    d.rounded_rectangle([0, 0, S - 1, S - 1], radius=S // 5, fill=rim)
    d.rounded_rectangle([S//32, S//32, S - 1 - S//32, S - 1 - S//32], radius=S // 5 - S//32, fill=fill)
    return im

def icon(art_path, locked):
    S = 256
    base = plate(64, locked)
    art = Image.open(art_path).convert('RGBA')
    art = ImageOps.contain(art, (int(S * 0.78), int(S * 0.78)), Image.LANCZOS)
    if locked:
        g = ImageOps.grayscale(art).point(lambda v: int(v * 0.55 + 40))
        art = Image.merge('RGBA', (g, g, g, art.split()[3].point(lambda a: int(a * 0.85))))
    x = (S - art.width) // 2; y = (S - art.height) // 2
    base.alpha_composite(art, (x, y))
    return base.resize((64, 64), Image.LANCZOS)

rows = []
for a in ACH:
    api = 'ACH_' + a['id'].upper()
    art = os.path.join(GAME, 'assets', a['art'] + '.png')
    assert os.path.exists(art), art
    icon(art, False).save(os.path.join(OUT, api + '.png'))
    icon(art, True).save(os.path.join(OUT, api + '_locked.png'))
    rows.append((api, a['name'], a['desc'], 'yes' if a['id'] in HIDDEN else 'no', a['art']))

md = ['# Jumping Jimothy — Steam achievements (generated, do not edit by hand)',
      '',
      'Generated by `python3 capsules/achievements.py` from the game\'s `ACH` + `SEASONS` tables.',
      'Icons: `capsules/out/achievements/<API>.png` (earned) and `<API>_locked.png` (not yet), 64x64 PNG.',
      '',
      '## Steamworks: where to click',
      '',
      '1. https://partner.steamgames.com/apps/achievements/5043360 (Stats & Achievements → Achievements).',
      '2. **New Achievement**, once per row below. API Name must match EXACTLY (the game sends that string).',
      '3. Display Name, Description, Hidden as in the table. Upload the two icons per row.',
      '4. **Save**, then the **Publish** tab → **Prepare for Publishing** → **Publish to Steam**.',
      '   Achievements are live only after Publish; before that every unlock call quietly fails.',
      '5. Then upload the achievements build (revision 3 zip) and test one unlock from your own',
      '   Steam library: take the first hop, "Silly Little Guy" should pop in the overlay.',
      '',
      '| # | API Name | Display Name | Description | Hidden | Icon (earned / locked) |',
      '|---|---|---|---|---|---|']
for i, (api, name, desc, hidden, art) in enumerate(rows, 1):
    md.append('| %d | `%s` | %s | %s | %s | `%s.png` / `%s_locked.png` |' % (i, api, name, desc, hidden, api, api))
md += ['', 'Total: %d achievements (21 core + 5 seasonal). Seasonal ones stay visible on purpose: they are the reason to come back.' % len(rows), '']
open(os.path.join(HERE, '..', 'ACHIEVEMENTS.md'), 'w').write('\n'.join(md))
json.dump([r[0] for r in rows], open(os.path.join(OUT, 'api_names.json'), 'w'))
print('wrote %d achievements, %d icons, ACHIEVEMENTS.md' % (len(rows), len(rows) * 2))
