// ═══ LUCID WINDS — Bee's Pollen Sort ═══
// Color-sort puzzle themed as a bee sorting pollen into vials.
// Scope locked 2026-04-23: standard tubes (no hex grid), standard pour rules,
// focus on polish + a real level progression + free undo/hint.
// The director parked the advanced ideas (hex grid, wing-beat budget,
// queen's-chamber meta, viscosity, shake-the-hive) for a possible v2 —
// see memory: project_pollen_sort_parked_ideas.md.
(function(){
'use strict';
var G=window._G;
var _e=G.e,_play=G.play,_playWin=G.playWin,_setDiff=G.setDiff,ms=G.ms,mm=G.mm,mc=G.mc,sm=G.sm,_sr=G.sr;

// ── Pollen palette — botanical, warm, distinct at small sizes ──
// Ordered so the first N colors of any level always include the most
// distinct hues.
var POLLEN=[
  {name:'Marigold',hex:'#F4B233'},
  {name:'Lavender',hex:'#9A85C4'},
  {name:'Rose',    hex:'#E47489'},
  {name:'Sage',    hex:'#7AB356'},
  {name:'Amber',   hex:'#D26B3A'},
  {name:'Cornflower',hex:'#5A82C2'},
  {name:'Clover',  hex:'#4A7C35'},
  {name:'Berry',   hex:'#8E3C5E'},
  {name:'Sunstalk',hex:'#E8DC78'},
  {name:'Indigo',  hex:'#3D4C8A'}
];

// ── State ────────────────────────────────────────────────────────────────
// CAP is read by _buildLevels at module-init time, so it MUST be assigned
// before LEVELS is built. Previously CAP was declared below the LEVELS
// assignment — hoisting made CAP=undefined during build, solvedState's
// fill loop ran zero times, and every level shipped as 4 empty tubes.
var CAP=4;
var tubes=[];
var levelIdx=0;
var sel=-1;
var moves=0;
var won=false;
var history=[];
var startTs=0,solvedTs=0,timerId=null;
var pan=null,tubesEl=null;

// ── Level bank ────────────────────────────────────────────────────────────
// 60 levels, ramping: 3 colors / 5 tubes → 8 colors / 11 tubes.
// Generated by random walk from solved state (single-unit pours so every
// state is reachable, and thus solvable, via real multi-unit gameplay).
// tubes: array of arrays of color indices (0-based into POLLEN).
var LEVELS=_buildLevels();

function _buildLevels(){
  // Deterministic seeded RNG — Mulberry32.
  var seed=0x5EED1;
  function rand(){
    seed|=0;seed=(seed+0x6D2B79F5)|0;
    var t=Math.imul(seed^seed>>>15,1|seed);
    t=t+Math.imul(t^t>>>7,61|t)^t;
    return((t^t>>>14)>>>0)/4294967296;
  }
  function randInt(n){return Math.floor(rand()*n);}

  function solvedState(numColors){
    var t=[];
    for(var c=0;c<numColors;c++){
      var col=[];for(var k=0;k<CAP;k++)col.push(c);
      t.push(col);
    }
    // Two empty tubes — the standard genre count.
    t.push([]);t.push([]);
    return t;
  }
  function cloneTubes(t){return t.map(function(c){return c.slice();});}
  function legalPour(t,from,to){
    if(from===to)return false;
    var src=t[from],dst=t[to];
    if(!src.length)return false;
    if(dst.length>=CAP)return false;
    if(dst.length&&dst[dst.length-1]!==src[src.length-1])return false;
    return true;
  }
  // Single-unit pour — used only by the scramble. The in-game pour rule still
  // moves all contiguous top-of-color units; we scramble one unit at a time
  // so that a full-tube-to-empty move doesn't trivially keep the state sorted.
  // Single-unit moves are a subset of the legal multi-unit moves, so every
  // state the scramble reaches is reachable (and thus solvable) via real play.
  function pourOne(t,from,to){
    t[to].push(t[from].pop());
  }
  function isSolved(t){
    return t.every(function(col){
      return col.length===0||(col.length===CAP&&col.every(function(c){return c===col[0];}));
    });
  }
  function scramble(numColors,numMoves){
    var t=solvedState(numColors);
    var last=-1;
    for(var i=0;i<numMoves;i++){
      var candidates=[];
      for(var a=0;a<t.length;a++){
        for(var b=0;b<t.length;b++){
          if(a===b)continue;
          if(legalPour(t,a,b)){
            // Don't immediately reverse the previous single-unit move.
            if(last!==-1&&a===lastTo&&b===lastFrom)continue;
            candidates.push({from:a,to:b});
          }
        }
      }
      if(!candidates.length)break;
      var pick=candidates[randInt(candidates.length)];
      pourOne(t,pick.from,pick.to);
      lastFrom=pick.from;lastTo=pick.to;last=i;
    }
    return t;
  }
  var lastFrom=-1,lastTo=-1;

  var levels=[];
  // Difficulty spec (colors, extraEmpty, scrambleDepth, optimal cap)
  var SPEC=[
    // 3 colors × 6 levels — tutorial
    [3,2,8,'easy'],[3,2,10,'easy'],[3,2,12,'easy'],
    [3,2,14,'easy'],[3,2,16,'easy'],[3,2,18,'easy'],
    // 4 colors × 8 levels
    [4,2,14,'easy'],[4,2,17,'easy'],[4,2,20,'easy'],[4,2,23,'easy'],
    [4,2,26,'easy'],[4,2,28,'medium'],[4,2,30,'medium'],[4,2,32,'medium'],
    // 5 colors × 10 levels
    [5,2,22,'medium'],[5,2,25,'medium'],[5,2,28,'medium'],[5,2,31,'medium'],
    [5,2,34,'medium'],[5,2,37,'medium'],[5,2,40,'medium'],[5,2,42,'medium'],
    [5,2,44,'medium'],[5,2,46,'medium'],
    // 6 colors × 10 levels
    [6,2,30,'medium'],[6,2,34,'medium'],[6,2,38,'hard'],[6,2,42,'hard'],
    [6,2,46,'hard'],[6,2,50,'hard'],[6,2,54,'hard'],[6,2,58,'hard'],
    [6,2,62,'hard'],[6,2,66,'hard'],
    // 7 colors × 14 levels
    [7,2,40,'hard'],[7,2,44,'hard'],[7,2,48,'hard'],[7,2,52,'hard'],
    [7,2,56,'hard'],[7,2,60,'hard'],[7,2,64,'hard'],[7,2,68,'hard'],
    [7,2,72,'hard'],[7,2,76,'hard'],[7,2,80,'hard'],[7,2,84,'hard'],
    [7,2,88,'hard'],[7,2,92,'hard'],
    // 8 colors × 12 levels — expert
    [8,2,60,'expert'],[8,2,66,'expert'],[8,2,72,'expert'],[8,2,78,'expert'],
    [8,2,84,'expert'],[8,2,90,'expert'],[8,2,96,'expert'],[8,2,102,'expert'],
    [8,2,108,'expert'],[8,2,114,'expert'],[8,2,120,'expert'],[8,2,126,'expert']
  ];
  for(var li=0;li<SPEC.length;li++){
    var spec=SPEC[li];
    var numColors=spec[0],extra=spec[1],depth=spec[2],diff=spec[3];
    var t=scramble(numColors,depth);
    // Sanity: reject any level that accidentally scrambled back to solved.
    if(isSolved(t)){numColors--;t=scramble(numColors,depth);}
    levels.push({
      n:li+1,
      numColors:numColors,
      extraEmpty:extra,
      difficulty:diff,
      tubes:t
    });
  }
  return levels;
}

// ── Styles ────────────────────────────────────────────────────────────────
(function injectStyle(){
  if(document.getElementById('ps-style'))return;
  var s=document.createElement('style');s.id='ps-style';
  s.textContent=[
    '@keyframes psFade{0%{opacity:0;transform:translateY(8px)}100%{opacity:1;transform:translateY(0)}}',
    '@keyframes psPop{0%{transform:scale(0.3);opacity:0}55%{transform:scale(1.15);opacity:1}100%{transform:scale(1);opacity:1}}',
    '@keyframes psPourDrop{0%{transform:translateY(-18px);opacity:0}50%{opacity:1}100%{transform:translateY(0);opacity:1}}',
    '@keyframes psBeeHover{0%,100%{transform:translateY(0) rotate(-3deg)}50%{transform:translateY(-4px) rotate(3deg)}}',
    '@keyframes psWobble{0%,100%{transform:translateY(-6px)}50%{transform:translateY(-8px) rotate(1deg)}}',
    '#PSpan{max-width:min(96vw,520px);margin:0 auto;padding:10px;user-select:none;-webkit-user-select:none;box-sizing:border-box;position:relative;animation:psFade .4s ease}',
    '.PStubes{display:flex;gap:clamp(6px,2vw,10px);justify-content:center;align-items:flex-end;flex-wrap:wrap;padding:14px 6px;min-height:180px;position:relative}',
    '.PStube{position:relative;width:clamp(38px,10vw,46px);min-height:clamp(130px,34vw,150px);border-radius:0 0 12px 12px;border:2px solid rgba(220,180,120,0.35);border-top:1.5px dashed rgba(220,180,120,0.25);display:flex;flex-direction:column-reverse;align-items:center;padding:3px;cursor:pointer;-webkit-tap-highlight-color:transparent;background:linear-gradient(180deg,rgba(26,31,23,0.15) 0%,rgba(26,31,23,0.55) 100%);box-shadow:inset 0 -8px 12px rgba(0,0,0,0.28),inset 2px 0 4px rgba(255,220,160,0.06);transition:transform .22s cubic-bezier(.25,.46,.45,.94),box-shadow .22s ease}',
    '.PStube.sel{border-color:#c8a84b;box-shadow:inset 0 -8px 12px rgba(0,0,0,0.3),0 0 16px rgba(200,168,75,0.35);animation:psWobble 1.6s ease-in-out infinite}',
    '.PStube.done{border-color:rgba(122,179,86,0.7);box-shadow:inset 0 -10px 14px rgba(0,0,0,0.3),0 0 14px rgba(122,179,86,0.28)}',
    '.PSpol{width:calc(100% - 2px);height:clamp(22px,6vw,26px);border-radius:3px;margin-bottom:1px;position:relative;box-shadow:inset 0 1px 0 rgba(255,255,255,0.18),inset 0 -1px 0 rgba(0,0,0,0.25)}',
    '.PSpol.dropped{animation:psPourDrop .32s cubic-bezier(.5,0,.3,1)}',
    '.PSbee{position:absolute;top:-34px;left:50%;transform:translateX(-50%);font-size:1.6rem;pointer-events:none;transition:left .35s cubic-bezier(.3,1.2,.4,1);filter:drop-shadow(0 2px 3px rgba(0,0,0,0.45));animation:psBeeHover 1.4s ease-in-out infinite}',
    '.PSctrl{display:flex;gap:8px;align-items:center;justify-content:space-between;padding:8px 4px 2px;flex-wrap:wrap}',
    '.PSinfo{display:flex;gap:10px;align-items:center;font-family:Georgia,serif;font-size:0.72rem;color:rgba(232,220,200,0.85);flex-wrap:wrap}',
    '.PSinfo strong{color:#c8a84b;font-weight:700}',
    '.PSbtn-row{display:flex;gap:6px;flex-wrap:wrap}',
    '.PSb{min-height:34px;padding:5px 12px;font-size:.68rem;font-family:Georgia,serif;font-weight:700;border-radius:6px;cursor:pointer;background:rgba(26,31,23,0.7);border:1.5px solid rgba(220,180,120,0.4);color:#e8dcc8;transition:all .15s}',
    '.PSb:active{background:rgba(200,168,75,0.2);transform:scale(.96)}',
    '.PSb.gold{border-color:#c8a84b;color:#c8a84b;background:linear-gradient(180deg,rgba(200,168,75,0.18),rgba(160,130,50,0.22))}',
    '.PSb.pulse{animation:psPop 1.1s ease-in-out infinite}',
    '.PSb[disabled]{opacity:.35;pointer-events:none}',
    '.PSlvl{font-family:Georgia,serif;font-style:italic;font-size:0.68rem;color:rgba(232,220,200,0.75);letter-spacing:0.04em}',
    '.PSlvl strong{color:#c8a84b;font-style:normal}'
  ].join('');
  document.head.appendChild(s);
})();

// ── Persistence ──────────────────────────────────────────────────────────
function loadProgress(){try{return parseInt(localStorage.getItem('lw_pollensort_max')||'0',10)||0;}catch(e){return 0;}}
function saveProgress(n){try{localStorage.setItem('lw_pollensort_max',String(n));}catch(e){}}

// ── Core rules ──────────────────────────────────────────────────────────
function isSolved(){
  return tubes.every(function(col){
    return col.length===0||(col.length===CAP&&col.every(function(c){return c===col[0];}));
  });
}
function isTubeDone(col){
  return col.length===CAP&&col.every(function(c){return c===col[0];});
}
function canPour(from,to){
  if(from===to)return false;
  var src=tubes[from],dst=tubes[to];
  if(!src.length)return false;
  if(dst.length>=CAP)return false;
  if(dst.length&&dst[dst.length-1]!==src[src.length-1])return false;
  return true;
}
function cloneTubes(){return tubes.map(function(c){return c.slice();});}

// How many units will pour from from → to right now
function pourCount(from,to){
  var src=tubes[from],dst=tubes[to];
  if(!src.length)return 0;
  var color=src[src.length-1];
  var n=0;
  while(src.length-1-n>=0&&src[src.length-1-n]===color&&dst.length+n<CAP)n++;
  return n;
}
function doPour(from,to){
  var snap=cloneTubes();
  var n=pourCount(from,to);
  if(!n)return false;
  var color=tubes[from][tubes[from].length-1];
  for(var i=0;i<n;i++){tubes[from].pop();tubes[to].push(color);}
  history.push(snap);
  moves++;
  _play('tap');
  return true;
}

// ── Rendering ───────────────────────────────────────────────────────────
function renderTubes(animatePour){
  if(!tubesEl)return;
  tubesEl.innerHTML='';
  for(var i=0;i<tubes.length;i++){
    (function(ti){
      var col=tubes[ti];
      var tEl=document.createElement('div');
      tEl.className='PStube'+(ti===sel?' sel':'')+(isTubeDone(col)?' done':'');
      tEl.setAttribute('data-t',ti);
      tEl.onclick=function(){onTubeTap(ti);};
      for(var k=0;k<col.length;k++){
        var pol=document.createElement('div');
        pol.className='PSpol';
        // Animate only the newly-added unit(s) from the most recent pour
        if(animatePour&&animatePour.to===ti&&k>=col.length-animatePour.count)pol.className+=' dropped';
        pol.style.background=POLLEN[col[k]].hex;
        pol.style.animationDelay=((col.length-1-k)*40)+'ms';
        tEl.appendChild(pol);
      }
      tubesEl.appendChild(tEl);
      if(ti===sel){
        var bee=document.createElement('div');
        bee.className='PSbee';bee.textContent='🐝';
        tEl.appendChild(bee);
      }
    })(i);
  }
}

function updateStatus(){
  var m=document.getElementById('PSm');if(m)m.textContent=moves;
  var ub=document.getElementById('PSu');if(ub)ub.disabled=!history.length||won;
  var lvlEl=document.getElementById('PSlvl');if(lvlEl){
    var L=LEVELS[levelIdx];
    lvlEl.innerHTML='<strong>Level '+(levelIdx+1)+'/'+LEVELS.length+'</strong> · '+L.numColors+' colors · '+L.difficulty;
  }
  var pb=document.getElementById('PSprev');if(pb)pb.disabled=(levelIdx<=0);
  var nb=document.getElementById('PSnext');if(nb){
    var prog=loadProgress();
    nb.disabled=(levelIdx>=LEVELS.length-1)||(levelIdx>=prog&&!won);
  }
  // Stuck-detector: after many moves without reducing disorder, pulse reset.
  var reset=document.getElementById('PSr');
  if(reset){
    if(moves>0&&moves%15===0&&!won&&!isSolved())reset.classList.add('pulse');
    else reset.classList.remove('pulse');
  }
}
function fmtTime(secs){var m=Math.floor(secs/60),s=secs%60;return m+':'+(s<10?'0':'')+s;}
function tickTimer(){
  if(won||!startTs)return;
  var secs=Math.max(0,Math.round((Date.now()-startTs)/1000));
  var t=document.getElementById('PSt');if(t)t.textContent=fmtTime(secs);
}

// ── Interaction ─────────────────────────────────────────────────────────
function onTubeTap(ti){
  if(won)return;
  if(sel===-1){
    if(tubes[ti].length===0)return;
    sel=ti;renderTubes();return;
  }
  if(sel===ti){sel=-1;renderTubes();return;}
  if(!canPour(sel,ti)){
    // Invalid pour — switch selection to the new tube if it has something.
    sel=tubes[ti].length?ti:-1;renderTubes();return;
  }
  var from=sel,to=ti;
  var n=pourCount(from,to);
  doPour(from,to);
  sel=-1;
  renderTubes({to:to,count:n});
  updateStatus();
  if(isSolved())handleWin();
}

function undoMove(){
  if(!history.length||won)return;
  tubes=history.pop();
  moves=Math.max(0,moves-1);
  sel=-1;
  _play('tap');
  renderTubes();updateStatus();
}

function resetLevel(){
  if(won)return;
  loadLevel(levelIdx,true);
}

function handleWin(){
  won=true;solvedTs=Date.now();
  if(timerId){clearInterval(timerId);timerId=null;}
  _e('game_win');if(_playWin)_playWin();_sr('colorsort',{w:true,s:moves,lvl:levelIdx+1});
  var prog=loadProgress();
  if(levelIdx+1>prog)saveProgress(levelIdx+1);
  setTimeout(victoryOverlay,450);
}

// ── Victory overlay (id='PSwin', same cleanup pattern as Root Rush) ─────
var _winTimer=null;
function _cleanupVictory(){
  if(_winTimer){clearTimeout(_winTimer);_winTimer=null;}
  var ov=document.getElementById('PSwin');
  if(ov&&ov.parentNode)ov.parentNode.removeChild(ov);
}
(function installExitWatcher(){
  if(!document.body||!window.MutationObserver)return;
  var mo=new MutationObserver(function(){
    if(!document.body.classList.contains('game-active'))_cleanupVictory();
  });
  mo.observe(document.body,{attributes:true,attributeFilter:['class']});
})();

function victoryOverlay(){
  var secs=Math.max(1,Math.round((solvedTs-startTs)/1000));
  var timeStr=fmtTime(secs);
  var L=LEVELS[levelIdx];
  // Rating — 3★ = under 1.35x expected-ish, 2★ = under 1.8x, 1★ = solved.
  var par=Math.max(6,Math.round(L.numColors*3));
  var stars=moves<=par?3:(moves<=Math.round(par*1.4)?2:1);
  var starRow='<div style="display:flex;gap:10px;margin:12px 0;">';
  for(var si=0;si<3;si++){
    var lit=si<stars;
    starRow+='<div style="font-size:2.4rem;line-height:1;filter:drop-shadow(0 0 '+(lit?'16px rgba(255,220,112,0.8)':'4px rgba(0,0,0,0.5)')+');color:'+(lit?'#ffdc70':'rgba(110,100,80,0.5)')+';animation:psPop 0.6s cubic-bezier(.18,1.4,.3,1) '+(si*140)+'ms both;">★</div>';
  }
  starRow+='</div>';
  var next=levelIdx<LEVELS.length-1?'<button onclick="this.parentElement.parentElement.remove();_PSnext()" style="min-height:46px;padding:10px 22px;font-family:Georgia,serif;font-weight:700;font-size:0.85rem;background:linear-gradient(180deg,rgba(200,168,75,0.35),rgba(160,120,50,0.45));border:2px solid #c8a84b;color:#f5ebd0;border-radius:8px;letter-spacing:0.05em;cursor:pointer;margin-right:8px;">Next Level →</button>':'<div style="font-family:Georgia,serif;font-style:italic;color:#c8a84b;font-size:0.9rem;margin-right:8px;">Last level complete</div>';
  var ov=document.createElement('div');
  ov.id='PSwin';
  ov.style.cssText='position:fixed;inset:0;z-index:9999;background:radial-gradient(ellipse at 50% 40%,rgba(200,168,75,0.32) 0%,rgba(13,16,12,0.94) 70%);display:flex;flex-direction:column;align-items:center;justify-content:center;padding:2rem;animation:psFade .3s ease;font-family:Georgia,serif;';
  ov.innerHTML=
    '<div style="font-size:4.2rem;line-height:1;margin-bottom:6px;filter:drop-shadow(0 0 20px rgba(200,168,75,0.85));animation:psPop .7s cubic-bezier(.18,1.4,.3,1);">🐝</div>'+
    starRow+
    '<div style="font-size:2rem;font-weight:700;color:#c8a84b;letter-spacing:0.08em;text-shadow:0 0 18px rgba(200,168,75,0.7);animation:psPop .7s cubic-bezier(.18,1.4,.3,1);">POLLEN SORTED</div>'+
    '<div style="font-family:Georgia,serif;font-style:italic;font-size:0.82rem;color:#e8dcc8;margin-top:8px;">Level '+(levelIdx+1)+' · '+L.numColors+' colors</div>'+
    '<div style="display:flex;gap:14px;margin-top:14px;font-family:DM Mono,monospace;font-size:0.7rem;color:#e8dcc8;">'+
      '<div><span style="color:rgba(232,220,200,0.55);">Moves</span> <strong style="color:#c8a84b;">'+moves+'</strong></div>'+
      '<div><span style="color:rgba(232,220,200,0.55);">Time</span> <strong style="color:#7ab356;">'+timeStr+'</strong></div>'+
    '</div>'+
    '<div style="display:flex;gap:8px;margin-top:22px;">'+
      next+
      '<button onclick="this.parentElement.parentElement.remove();_PSreset()" style="min-height:46px;padding:10px 20px;font-family:Georgia,serif;font-weight:600;font-size:0.75rem;background:rgba(26,31,23,0.7);border:1.5px solid rgba(220,180,120,0.4);color:#e8dcc8;border-radius:8px;cursor:pointer;">↻ Replay</button>'+
    '</div>';
  ov.onclick=function(ev){if(ev.target===ov)ov.remove();};
  document.body.appendChild(ov);
}

// ── Lifecycle ───────────────────────────────────────────────────────────
function loadLevel(idx,keepTimer){
  _cleanupVictory();
  levelIdx=idx;
  var L=LEVELS[idx];
  tubes=L.tubes.map(function(c){return c.slice();});
  moves=0;history=[];won=false;sel=-1;
  startTs=Date.now();solvedTs=0;
  if(!keepTimer){
    if(timerId)clearInterval(timerId);
    timerId=setInterval(tickTimer,500);
  }
  _setDiff(L.difficulty||'easy');
  renderBoard();
}

function renderBoard(){
  if(!pan)return;
  pan.innerHTML='';
  tubesEl=document.createElement('div');tubesEl.className='PStubes';tubesEl.id='PStubes';
  pan.appendChild(tubesEl);
  var ctrl=document.createElement('div');ctrl.className='PSctrl';
  ctrl.innerHTML=
    '<div class="PSinfo">'+
      '<span>Moves: <strong id="PSm">0</strong></span>'+
      '<span>⏱ <strong id="PSt">0:00</strong></span>'+
    '</div>'+
    '<div class="PSbtn-row">'+
      '<button class="PSb" id="PSu" onclick="_PSundo()" disabled>↶ Undo</button>'+
      '<button class="PSb" id="PSr" onclick="_PSreset()">↻ Reset</button>'+
    '</div>';
  pan.appendChild(ctrl);
  var lvlRow=document.createElement('div');
  lvlRow.style.cssText='display:flex;justify-content:space-between;align-items:center;padding:6px 4px 0;gap:8px;flex-wrap:wrap;';
  lvlRow.innerHTML=
    '<div class="PSlvl" id="PSlvl"></div>'+
    '<div class="PSbtn-row">'+
      '<button class="PSb" id="PSprev" onclick="_PSprev()">‹ Prev</button>'+
      '<button class="PSb gold" id="PSnext" onclick="_PSnext()">Next ›</button>'+
    '</div>';
  pan.appendChild(lvlRow);
  renderTubes();
  updateStatus();
}

function GPS(a){
  _cleanupVictory();
  ms(a,'Bee’s Pollen Sort');mm(a);
  pan=document.createElement('div');pan.id='PSpan';a.appendChild(pan);
  mc(a);
  var start=Math.min(loadProgress(),LEVELS.length-1);
  loadLevel(start,false);
}

window._PSundo=function(){undoMove();};
window._PSreset=function(){resetLevel();};
window._PSprev=function(){if(levelIdx>0){if(timerId)clearInterval(timerId);loadLevel(levelIdx-1,false);}};
window._PSnext=function(){if(levelIdx<LEVELS.length-1){if(timerId)clearInterval(timerId);loadLevel(levelIdx+1,false);}};

window._gameFns=window._gameFns||{};
window._gameFns.colorsort=GPS;
})();
