// ═══ LUCID WINDS — Vine Words (Boggle-style word finder) ═══
(function(){
'use strict';



window._gameFns=window._gameFns||{};
window._gameFns.vinewords=function VW(a){
  // Compact English 3-6 letter word list (~600 words) for validation.
  var WORDS=('THE,AND,ARE,FOR,NOT,BUT,YOU,ALL,CAN,HER,WAS,ONE,OUR,OUT,DAY,GET,HAS,HIM,HIS,HOW,'+
    'MAN,NEW,NOW,OLD,SEE,TWO,WAY,WHO,BOY,DID,ITS,LET,PUT,SAY,SHE,TOO,USE,DAD,MOM,ANT,ARM,ART,ASK,ATE,BAD,BAG,BAT,BED,BEE,BEG,BIG,BIT,BOX,BUG,BUS,BUY,CAP,CAR,CAT,COW,CRY,CUP,CUT,'+
    'DIG,DOG,DRY,EAR,EAT,EGG,END,EYE,FAN,FAR,FAT,FEW,FIN,FIT,FIX,FLY,FOG,FUN,GAS,GOT,GUN,GYM,HAM,HAT,HAY,HEN,HIT,HOP,HOT,HUG,ICE,INK,JAM,JOB,JOG,JOY,KEY,KID,LAB,LAP,LAW,LEG,LET,LID,LIE,LIP,'+
    'LOG,LOW,MAD,MAP,MAT,MEN,MET,MIX,MUD,NAP,NET,NUT,OAK,OFF,OIL,OWL,OWN,PAN,PEN,PET,PIE,PIG,PIN,POT,RAN,RAT,RED,RIB,RIM,ROW,RUB,RUG,RUN,SAD,SAT,SEA,SET,SIP,SIR,SIT,SIX,SKI,SKY,SON,SUN,TAN,'+
    'TAP,TAR,TAX,TEA,TEN,TIE,TIN,TIP,TON,TOP,TOY,TRY,TUB,VAN,WAR,WAS,WAX,WEB,WET,WIN,YES,YET,YOU,ZIP,ZOO,'+
    'ABLE,ACID,ACT,ACE,ACRE,AERO,AIDE,AIRY,AJAR,AKIN,ALBA,ALOE,ALPS,ALSO,AMID,AMUS,APEX,ARCH,AREA,ARMY,AUNT,AUTO,AVID,AWAY,AWES,AXES,AXIS,AXLE,BABE,BABY,BACK,BADE,BAIT,BAKE,BALD,BALE,BALL,BAND,'+
    'BANE,BANG,BANK,BARB,BARD,BARE,BARK,BARN,BASE,BASH,BASS,BATH,BEAD,BEAK,BEAM,BEAN,BEAR,BEAT,BEEF,BEEN,BELL,BELT,BEND,BENT,BEST,BIAS,BIDE,BIKE,BILL,BIND,BIRD,BITE,BLED,BLEW,BLOB,BLOC,BLOT,'+
    'BLOW,BLUE,BLUR,BOAR,BOAT,BODY,BOIL,BOLD,BOLT,BOMB,BOND,BONE,BONY,BOOK,BOOM,BOON,BOOR,BOOT,BORE,BORN,BOSS,BOTH,BOUT,BOWL,BRAN,BRAS,BRAT,BRAY,BRED,BREW,BRIM,BROW,BUCK,BUDS,BUFF,BULB,BULK,'+
    'BULL,BUMP,BUNK,BURN,BURY,BUSH,BUSY,BYTE,CAFE,CAGE,CAKE,CALF,CALL,CALM,CAME,CAMP,CANE,CAPE,CARD,CARE,CARP,CART,CASE,CASH,CAST,CAVE,CEDE,CELL,CENT,CHAP,CHAR,CHAT,CHEW,CHIN,CHIP,CHOP,CHUB,'+
    'CITE,CITY,CLAD,CLAM,CLAN,CLAP,CLAW,CLAY,CLEF,CLIP,CLOD,CLOG,CLOT,CLOY,CLUB,CLUE,COAL,COAT,COAX,CODE,COIL,COIN,COKE,COLD,COLT,COMB,COME,CONE,CONS,COOK,COOL,COPE,COPY,CORD,CORE,CORK,CORN,'+
    'COST,COTS,COUP,COVE,CRAB,CRAG,CRAM,CRAP,CRAW,CREW,CRIB,CROP,CROW,CUBE,CUED,CUFF,CULT,CURB,CURD,CURE,CURL,CURT,CUSP,CYST,DAFT,DAIS,DALE,DAME,DAMP,DANK,DARE,DARK,DART,DASH,DATA,DATE,DAUB,'+
    'DAZE,DEAD,DEAF,DEAL,DEAN,DEAR,DEBT,DECK,DEED,DEEM,DEEP,DEER,DELI,DELL,DELT,DEMO,DENS,DENT,DESK,DIAL,DICE,DIED,DIET,DIME,DINE,DINT,DIRE,DIRT,DISC,DISH,DIVE,DOCK,DOES,DOLE,DOLL,DOME,DONE,'+
    'DOOR,DOPE,DOSE,DOTE,DOUR,DOVE,DOWN,DOZE,DRAB,DRAG,DRAM,DRAW,DREW,DRIP,DROP,DRUG,DRUM,DUAL,DUCK,DUCT,DUDE,DUEL,DUET,DUKE,DULL,DULY,DUMP,DUNE,DUNK,DUOS,DUPE,DUSK,DUST,DUTY,DYED,DYER,DYES,'+
    'EACH,EARN,EARS,EASE,EAST,EASY,EATS,EBBS,ECHO,EDDY,EDEN,EDGE,EDGY,EDIT,EELS,EGGS,EGOS,EIRE,ELFS,ELKS,ELMS,ELSE,EMIR,EMIT,ENDS,EONS,EPIC,ERAS,ERGO,EROS,ERRS,EURO,EVEN,EVER,EVIL,EWES,EXAM,'+
    'EXIT,EYED,EYES,FACE,FACT,FADE,FAIL,FAIN,FAIR,FAKE,FALL,FAME,FARE,FARM,FAST,FATE,FAWN,FEAR,FEAT,FEED,FEEL,FELL,FELT,FEND,FERN,FERS,FESS,FETA,FEUD,FIAT,FIEF,FIFE,FILE,FILL,FILM,FIND,FINE,'+
    'FIRE,FIRM,FISH,FIST,FITS,FIVE,FLAG,FLAP,FLAT,FLAW,FLAX,FLED,FLEE,FLEW,FLEX,FLIP,FLIT,FLOE,FLOG,FLOP,FLOW,FLUB,FLUE,FLUX,FOAL,FOAM,FOCI,FOES,FOGY,FOIL,FOLD,FOLK,FOND,FONT,FOOD,FOOL,FOOT,'+
    'FORD,FORE,FORK,FORM,FORT,FOUL,FOUR,FOWL,FRAY,FREE,FROG,FROM,FUEL,FULL,FUME,FUND,FUNK,FURL,FURS,FURY,FUSE,FUSS,FUZZ,GAFF,GAGE,GAIN,GAIT,GALA,GALE,GALL,GAME,GANG,GAPE,GAPS,GARB,GATE,GAVE,'+
    'GAWK,GAZE,GEAR,GEES,GEMS,GENE,GENT,GERM,GETS,GIBE,GIFT,GILD,GILL,GILT,GINS,GIRD,GIRL,GIST,GIVE,GLAD,GLEN,GLIB,GLOB,GLOW,GLUE,GLUM,GLUT,GNAT,GOAD,GOAL,GOAT,GODS,GOES,GOLD,GOLF,GONE,GONG,'+
    'GOOD,GOOF,GOOP,GORE,GORY,GOSH,GOUT,GOWN,GRAB,GRAD,GRAM,GRAY,GREW,GREY,GRID,GRIM,GRIN,GRIP,GRIT,GROG,GROW,GRUB,GULF,GULL,GULP,GUMS,GUNK,GURU,GUSH,GUST,GUTS,HACK,HAIR,HALE,HALF,HALL,HALO,'+
    'HALT,HAND,HANG,HARD,HARE,HARK,HARM,HARP,HASH,HATE,HAUL,HAVE,HAWK,HAZE,HAZY,HEAD,HEAL,HEAP,HEAR,HEAT,HEED,HEEL,HELD,HELL,HELM,HELP,HEMP,HENS,HERB,HERD,HERE,HERO,HERS,HEWN,HIDE,HIGH,HIKE,'+
    'HILL,HILT,HIND,HINT,HIRE,HITS,HIVE,HOAR,HOAX,HOBO,HOCK,HOES,HOLD,HOLE,HOLY,HOME,HONE,HOOD,HOOF,HOOK,HOOP,HOOT,HOPE,HORN,HOSE,HOST,HOUR,HOWL,HUBS,HUES,HUFF,HUGE,HULA,HULK,HULL,HUMP,HUMS,'+
    'HUNG,HUNK,HUNT,HURL,HURT,HUSH,HUSK,HYMN,ICED,ICES,ICKY,IDEA,IDLE,IDLY,IDOL,IGLOO,INCH,INTO,IONS,IOTA,IRIS,IRON,ITCH,ITEM,IVES,IVORY,JABS,JACK,JADE,JAIL,JARS,JAVA,JAWS,JAZZ,JEEP,JEER,JELL,'+
    'JERK,JEST,JETS,JIBE,JIFF,JIGS,JILT,JINX,JOBS,JOCK,JOEY,JOGS,JOIN,JOKE,JOLT,JOTS,JOWL,JUDO,JUGS,JUMP,JUNK,JURY,JUST,KALE,KAYO,KEEL,KEEN,KEEP,KEGS,KEPT,KEYS,KICK,KILL,KILN,KILO,KILT,KIND,KING,'+
    'KINK,KISS,KITE,KITH,KITS,KIWI,KNEE,KNEW,KNIT,KNOB,KNOT,KNOW,KUDO,LACE,LACK,LADE,LADS,LADY,LAGS,LAID,LAIR,LAKE,LAMB,LAME,LAMP,LAND,LANE,LAPS,LARK,LASH,LAST,LATE,LAUD,LAVA,LAWN,LAWS,LAYS,LAZY,'+
    'LEAD,LEAF,LEAK,LEAN,LEAP,LEAS,LED,LEES,LEFT,LEGS,LEND,LENS,LENT,LESS,LETS,LEVY,LEWD,LIAR,LICE,LICK,LIDS,LIED,LIES,LIEU,LIFE,LIFT,LIKE,LILY,LIMB,LIME,LIMP,LINE,LINK,LINT,LION,LIPS,LIRA,LISP,'+
    'LIST,LITE,LIVE,LOAD,LOAF,LOAM,LOAN,LOBE,LOCK,LODE,LOFT,LOGO,LOGS,LOIN,LOLL,LONE,LONG,LOOK,LOOM,LOON,LOOP,LOOS,LOOT,LORD,LORE,LOSE,LOSS,LOST,LOTS,LOUD,LOVE,LOWS,LUCK,LULL,LUMP,LUNG,LURE,'+
    'LURK,LUSH,LUST,LUTE,LYNX,LYRE,MACE,MADE,MAGI,MAID,MAIL,MAIN,MAKE,MALE,MALL,MALT,MAMA,MANE,MANS,MANY,MAPS,MARE,MARK,MARS,MART,MASH,MASK,MASS,MAST,MATH,MATS,MAUL,MAZE,MEAD,MEAL,MEAN,MEAT,'+
    'MEEK,MEET,MELD,MELT,MEMO,MEND,MENU,MEOW,MERE,MESH,MESS,METE,MEWS,MICE,MIEN,MIFF,MILD,MILE,MILK,MILL,MIME,MIND,MINE,MINI,MINK,MINT,MIRE,MISO,MISS,MIST,MITE,MITT,MOAN,MOAT,MOBS,MOCK,MODE,'+
    'MOIL,MOLD,MOLE,MOLT,MOMS,MONK,MOOD,MOON,MOOR,MOOS,MOOT,MOPE,MOPS,MORE,MOSS,MOST,MOTE,MOTH,MOVE,MOWN,MUCH,MUCK,MUFF,MULE,MULL,MUSE,MUSH,MUSK,MUSS,MUST,MUTE,MYTH,NAGS,NAIL,NAME,NAPE,NAPS,'+
    'NARY,NAVE,NAVY,NEAR,NEAT,NECK,NEED,NEON,NERD,NESS,NEST,NEWS,NEXT,NICE,NICK,NIGH,NINE,NIPS,NODE,NODS,NOEL,NOEL,NONE,NOOK,NOON,NOPE,NORM,NOSE,NOSY,NOTE,NOUN,NOVA,NOWS,NUDE,NUMB,NUNS,NUTS,'+
    'OAFS,OAKS,OARS,OATH,OATS,OBEY,OBOE,ODDS,ODES,ODOR,OFFS,OGLE,OGRE,OHMS,OILS,OILY,OINK,OKAY,OKRA,OLDS,OMEN,OMIT,ONCE,ONES,ONLY,ONTO,OOZE,OOZY,OPAL,OPEN,OPTS,OPUS,ORAL,ORBS,ORCA,ORES,ORGY,'+
    'OURS,OUST,OUTS,OVAL,OVEN,OVER,OWED,OWES,OWLS,OWNS,PACE,PACK,PACT,PAGE,PAID,PAIL,PAIN,PAIR,PALE,PALL,PALM,PANG,PANS,PANT,PAPA,PARD,PARE,PARK,PART,PASS,PAST,PATE,PATH,PATS,PAVE,PAWN,PAWS,'+
    'PEAK,PEAL,PEAR,PEAS,PECK,PEDS,PEEK,PEEL,PEEN,PEEP,PEER,PELT,PEND,PENS,PENT,PEPS,PERK,PERT,PESO,PEST,PEWS,PICA,PICK,PIED,PIER,PIES,PIGS,PIKE,PILE,PILL,PIMP,PINE,PING,PINK,PINS,PINT,PIPE,'+
    'PITA,PITH,PITS,PITY,PLAN,PLAY,PLEA,PLED,PLOD,PLOP,PLOT,PLOW,PLOY,PLUG,PLUM,PLUS,POEM,POET,POGO,POKE,POLE,POLL,POLO,POMP,POND,PONY,POOL,POOP,POOR,POPE,POPS,PORE,PORK,PORT,POSE,POSH,POST,'+
    'POUT,PRAY,PREP,PREY,PRIG,PRIM,PROD,PROM,PROP,PROS,PROW,PSIS,PUBS,PUCK,PUFF,PUGS,PUKE,PULL,PULP,PUMA,PUMP,PUNK,PUNS,PUNT,PUNY,PUPA,PUPS,PURE,PURL,PURR,PUSH,PUTS,PUTT,PYRE,QUAD,QUAY,QUIP,'+
    'QUIT,QUIZ,RACE,RACK,RAFT,RAGE,RAGS,RAID,RAIL,RAIN,RAKE,RAMP,RAMS,RAND,RANG,RANK,RANT,RAPE,RAPS,RAPT,RARE,RASH,RASP,RATE,RATS,RAVE,RAYS,RAZE,READ,REAL,REAM,REAP,REAR,REDO,REDS,REED,REEF,'+
    'REEK,REEL,REIN,RELY,RENT,REST,RICE,RICH,RIDE,RIFE,RIFF,RIFT,RIGS,RIME,RIMS,RIND,RING,RINK,RIOT,RIPE,RIPS,RISE,RISK,RITE,RIVE,ROAD,ROAM,ROAR,ROBE,ROBS,ROCK,RODE,RODS,ROIL,ROLE,ROLL,ROME,'+
    'ROOF,ROOK,ROOM,ROOT,ROPE,ROSE,ROSY,ROTE,ROTS,ROUT,ROVE,ROWS,RUBS,RUBY,RUDE,RUFF,RUGS,RUIN,RULE,RUMP,RUNE,RUNG,RUNS,RUNT,RUSE,RUSH,RUSK,RUST,RUTS,SACK,SACS,SAFE,SAGA,SAGE,SAGS,SAID,SAIL,'+
    'SAKE,SAKI,SALE,SALT,SAME,SAND,SANE,SANG,SANK,SAPS,SARI,SASH,SAT,SAUR,SAVE,SAWN,SAWS,SAYS,SCAB,SCAD,SCAM,SCAN,SCAR,SCAT,SCOW,SCUD,SCUM,SEAL,SEAM,SEAR,SEAS,SEAT,SECT,SEED,SEEK,SEEM,SEEN,'+
    'SEEP,SEER,SEES,SELF,SELL,SEND,SENT,SERF,SETS,SEW,SEWN,SHAG,SHAH,SHAM,SHE,SHED,SHIM,SHIN,SHIP,SHOD,SHOE,SHOO,SHOP,SHOT,SHOW,SHUN,SHUT,SICK,SIDE,SIFT,SIGH,SIGN,SILK,SILL,SILO,SILT,SIMP,SINE,'+
    'SING,SINK,SINS,SIPS,SIRE,SITE,SITS,SIZE,SKEW,SKID,SKIM,SKIN,SKIP,SKIS,SKIT,SLAB,SLAG,SLAM,SLAP,SLAT,SLAY,SLED,SLEW,SLID,SLIM,SLIP,SLIT,SLOB,SLOE,SLOG,SLOP,SLOT,SLOW,SLUG,SLUM,SLUR,SMOG,'+
    'SMUG,SMUT,SNAG,SNAP,SNIP,SNIT,SNOB,SNOT,SNOW,SNUB,SNUG,SOAK,SOAP,SOAR,SOBS,SOCK,SODA,SODS,SOFA,SOFT,SOIL,SOLD,SOLE,SOLO,SOME,SONG,SONS,SOON,SOOT,SOPS,SORE,SORT,SOS,SOUL,SOUP,SOUR,SOWN,'+
    'SOWS,SPAN,SPAR,SPAS,SPAT,SPAY,SPEC,SPED,SPEW,SPIN,SPIT,SPOT,SPRY,SPUD,SPUN,SPUR,STAB,STAG,STAR,STAY,STEM,STEP,STEW,STIR,STOP,STUB,STUD,STUN,STYE,SUBS,SUCH,SUCK,SUDS,SUED,SUES,SUET,SUIT,'+
    'SULK,SUMS,SUNG,SUNK,SUNS,SURE,SURF,SWAB,SWAG,SWAM,SWAN,SWAP,SWAT,SWAY,SWIG,SWIM,SWOP,SWUM,TABS,TACK,TACT,TAIL,TAKE,TALE,TALK,TALL,TAME,TAMP,TANK,TANS,TAPE,TAPS,TARE,TARP,TART,TASK,TAUT,'+
    'TAXI,TEAK,TEAL,TEAM,TEAR,TEAS,TECH,TEEM,TEEN,TELL,TEND,TENS,TENT,TERM,TERN,TEST,TEXT,THAN,THAT,THAW,THEE,THEM,THEN,THEY,THIN,THIS,THOU,THUD,THUG,TICK,TIDE,TIDY,TIED,TIER,TIES,TIFF,TIKE,'+
    'TILE,TILL,TILT,TIME,TINE,TINS,TINT,TINY,TIPI,TIPS,TIRE,TOAD,TOED,TOES,TOFU,TOGA,TOIL,TOLD,TOLE,TOLL,TOMB,TOME,TONE,TONG,TONS,TOOK,TOOL,TOOT,TOPS,TORE,TORN,TORT,TOSS,TOTE,TOTS,TOUR,TOUT,'+
    'TOWN,TOWS,TOYS,TRAD,TRAM,TRAP,TRAY,TREE,TREK,TRIM,TRIO,TRIP,TROD,TROT,TROY,TRUE,TUBA,TUBE,TUBS,TUCK,TUFT,TUGS,TUNA,TUNE,TUNS,TURD,TURF,TURN,TUSK,TUTU,TWAS,TWIG,TWIN,TWIT,TYKE,TYPE,TYPO,'+
    'UGLY,UMPS,UNDO,UNIT,UNTO,UPON,UPPED,URGE,URNS,USED,USER,USES,VAIN,VALE,VAMP,VANE,VANS,VARY,VASE,VAST,VATS,VEAL,VEER,VEIL,VEIN,VEND,VENT,VERB,VERY,VEST,VETO,VETS,VEXT,VIAL,VIBE,VICE,VIED,'+
    'VIES,VIEW,VILE,VIM,VINE,VISA,VISE,VOID,VOLE,VOTE,VOWS,VROW,WADE,WADS,WAFT,WAGE,WAGS,WAIF,WAIL,WAIT,WAKE,WALE,WALK,WALL,WAND,WANE,WANT,WARD,WARE,WARM,WARN,WARP,WARS,WART,WARY,WASH,WASP,'+
    'WATT,WAVE,WAVY,WAXY,WEAK,WEAN,WEAR,WEBS,WEDS,WEED,WEEK,WEEP,WEES,WEFT,WEIR,WELD,WELL,WELT,WEND,WENT,WEPT,WERE,WEST,WETS,WHAM,WHAT,WHEN,WHET,WHEW,WHEY,WHIG,WHIM,WHIP,WHIR,WHIT,WHIZ,WHO,'+
    'WHOA,WHOM,WHOP,WICK,WIDE,WIFE,WIGS,WILD,WILE,WILL,WILT,WILY,WIMP,WIND,WINE,WING,WINK,WINS,WINY,WIPE,WIRE,WIRY,WISE,WISH,WITH,WITS,WOES,WOKE,WOLF,WOMB,WON,WONT,WOOD,WOOF,WOOL,WORD,WORE,'+
    'WORK,WORM,WORN,WRAP,WRIT,YANK,YARD,YARN,YAWL,YAWN,YAWS,YEAH,YEAR,YEAS,YEGG,YELL,YEN,YENS,YEPS,YETI,YOGA,YOKE,YOLK,YORE,YOU,YOUR,YOWL,YULE,YUMS,ZANY,ZAPS,ZEAL,ZEBU,ZERO,ZEST,ZINC,ZING,'+
    'ZIPS,ZITS,ZOOM,ZOOS').split(',');
  var DICT={};for(var wi=0;wi<WORDS.length;wi++){var w=WORDS[wi];if(w.length>=3)DICT[w]=1;}

  var LETTER_POOL='EEEEEEEEEEEEEAAAAAAAAAIIIIIIIIOOOOOOOOTTTTTTTTTNNNNNNNSSSSSSSRRRRRRRHHHHHLLLLLDDDDCCCGGMMMBBPPFFWWYYKV';

  var grid=[],path=[],foundSet={},foundList=[],score=0,timeLeft=120,timerId=0,playing=false;

  ms(a,'<span style="color:var(--gold)">Score: <span id="VWs">0</span></span> · <span id="VWt">2:00</span>');
  mm(a);
  var pan=document.createElement('div');pan.id='VWpan';
  pan.style.cssText='max-width:420px;margin:0 auto;padding:8px;user-select:none;-webkit-user-select:none;touch-action:none;';
  a.appendChild(pan);
  mc(a).innerHTML='<button class="gb" onclick="_VWN()">🌱 NEW</button>';

  function newGrid(){
    grid=[];
    for(var r=0;r<4;r++){
      var row=[];
      for(var c=0;c<4;c++)row.push(LETTER_POOL.charAt(Math.floor(Math.random()*LETTER_POOL.length)));
      grid.push(row);
    }
  }

  function adjacent(p1,p2){
    return Math.abs(p1[0]-p2[0])<=1&&Math.abs(p1[1]-p2[1])<=1&&!(p1[0]===p2[0]&&p1[1]===p2[1]);
  }

  function pathWord(){
    var s='';for(var i=0;i<path.length;i++)s+=grid[path[i][0]][path[i][1]];return s;
  }

  function submitWord(){
    var w=pathWord();
    if(w.length>=3&&DICT[w]&&!foundSet[w]){
      foundSet[w]=1;foundList.unshift(w);
      var pts=w.length<=3?1:w.length===4?2:w.length===5?4:w.length===6?8:w.length===7?15:25;
      score+=pts;
      _e('progress');
      if(foundList.length%5===0)_e('milestone');
      sm('+'+pts+' '+w);
    } else if(w.length>=3) {
      sm(foundSet[w]?'Already found':'Not a word');
    }
    path=[];render();
  }

  function onCell(r,c){
    if(!playing)return;
    var cell=[r,c];
    // Tap within path: if last, submit; if in path, ignore; else if adjacent to last, add
    if(path.length===0){path.push(cell);render();return;}
    var last=path[path.length-1];
    if(last[0]===r&&last[1]===c){submitWord();return;}
    // In path?
    for(var i=0;i<path.length;i++)if(path[i][0]===r&&path[i][1]===c){path=path.slice(0,i+1);render();return;}
    if(adjacent(last,cell)){path.push(cell);render();}
    else{path=[cell];render();}
  }

  function tick(){
    timeLeft--;
    var t=document.getElementById('VWt');
    if(t)t.textContent=Math.floor(timeLeft/60)+':'+(timeLeft%60<10?'0':'')+(timeLeft%60);
    if(timeLeft<=0){endGame();}
  }

  function endGame(){
    if(!playing)return;
    playing=false;
    if(timerId)clearInterval(timerId);
    var won=score>=30;
    if(won){_e('game_win');_playWin();}else{_e('game_loss');_play('lose');}
    sm('Time! Score: '+score+' · '+foundList.length+' words');
    _sr('vinewords',{w:won,s:score});
    render();
  }

  function render(){
    var h='';
    h+='<div style="text-align:center;font-family:DM Mono,monospace;font-size:1rem;color:var(--cream);min-height:22px;margin:6px 0;">'+pathWord()+'</div>';
    h+='<div style="display:flex;flex-direction:column;gap:4px;align-items:center;">';
    for(var r=0;r<4;r++){
      h+='<div style="display:flex;gap:4px;">';
      for(var c=0;c<4;c++){
        var inPath=false;for(var k=0;k<path.length;k++)if(path[k][0]===r&&path[k][1]===c){inPath=true;break;}
        var bg=inPath?'rgba(122,179,86,0.4)':'rgba(26,31,23,0.5)';
        var bc=inPath?'#7ab356':'rgba(122,179,86,0.2)';
        h+='<div onclick="_VWC('+r+','+c+')" style="width:64px;height:64px;background:'+bg+';border:2px solid '+bc+';border-radius:10px;display:flex;align-items:center;justify-content:center;font-family:Bebas Neue,sans-serif;font-size:1.8rem;color:var(--cream);cursor:pointer;">'+grid[r][c]+'</div>';
      }
      h+='</div>';
    }
    h+='</div>';
    h+='<div style="margin-top:10px;padding:8px;background:rgba(26,31,23,0.4);border-radius:8px;max-height:90px;overflow-y:auto;font-size:0.7rem;color:var(--cream);">';
    h+='<div style="font-family:Bebas Neue,sans-serif;color:var(--gold);margin-bottom:4px;">FOUND: '+foundList.length+'</div>';
    h+=foundList.slice(0,30).join(' · ');
    h+='</div>';
    pan.innerHTML=h;
    var s=document.getElementById('VWs');if(s)s.textContent=score;
  }

  window._VWC=function(r,c){onCell(r,c);};
  window._VWN=function(){
    if(timerId)clearInterval(timerId);
    newGrid();path=[];foundSet={};foundList=[];score=0;timeLeft=120;playing=true;
    render();
    timerId=setInterval(tick,1000);
  };

  _VWN();
};
})();
