/* LIFTING FOG QUESTION BANK

   Each entry is a thing speaking about itself in four clues, ordered from
   cryptic to obvious. The fog lifts one clue at a time and the answer is worth
   less each time it does.

   ⭐ FORMAT RULE THAT PREVENTS THE OBVIOUS BUG: options[0] is ALWAYS the correct
   answer. The game shuffles the four options before showing them, so an author
   can never mismatch an answer to an index and a reviewer can audit a line by
   reading it left to right.

   Regenerate or extend with this exact prompt, then hand-audit every entry:

   "Write N progressive clue questions for a cozy family quiz. Each is one
   THING (an animal, a place, an object, a food, a natural event) speaking in
   the first person about itself, in four clues ordered from cryptic to
   obvious. Clue 1 should be genuinely hard and slightly poetic, and should
   NOT be guessable by most people. Clue 4 should be so obvious that everyone
   gets it. Clues 2 and 3 step evenly between them. Rules: each clue is one
   sentence under 95 characters, true, checkable against a mainstream
   encyclopedia, general audience, no politics, no religion, no bodies, no
   violence, no brand names, NO DASH CHARACTERS OF ANY KIND. Also give three
   wrong options that are plausible for the first clue but clearly wrong by
   the last one. A wrong option that is still arguably correct at clue 4 is a
   broken question. Output a JS array of objects with fields id, options
   (array of 4 strings where the FIRST is correct), clues (array of 4 strings),
   category. Categories: animals, space, food, history, science, world, words,
   plants."

   AUDIT RULE: read clue 4 and check that exactly one option satisfies it. Then
   read clue 1 and check that it does not simply give the answer away.

   Bank at 2026-08-08: 76 entries. */
window.LIFTINGFOG_BANK = [
  {id:'lf-0001', category:"animals",
   options:["Octopus","Sea star","Jellyfish","Lobster"],
   clues:["I have been opening jars in laboratories far longer than you have.",
          "My blood runs blue and it takes three hearts to push it around.",
          "I can change my colour and my skin texture in about a second.",
          "I have eight arms, and every one of them is covered in suckers."]},
  {id:'lf-0002', category:"food",
   options:["Honey","Maple syrup","Molasses","Olive oil"],
   clues:["Sealed jars of me have been found in old tombs and were still edible.",
          "I am made by thousands of workers who never meet the person who eats me.",
          "My flavour changes completely depending on which flowers were nearby.",
          "Bees make me, and it takes a whole hive a season to fill one jar."]},
  {id:'lf-0003', category:"world",
   options:["Iceland","Norway","Greenland","Scotland"],
   clues:["My name promises cold and my neighbour with the greener name is far colder.",
          "I sit on a seam where two of the world plates are pulling apart.",
          "Almost all of my heat and power comes up out of the ground for free.",
          "My capital is Reykjavik and I am an island in the North Atlantic."]},
  {id:'lf-0004', category:"plants",
   options:["Bamboo","Sugar cane","Willow","Palm"],
   clues:["I am a grass, though almost everyone who meets me calls me a tree.",
          "Some of my kind can add most of a foot to their height in a single day.",
          "People build scaffolding, floors and whole houses out of me.",
          "Pandas eat almost nothing but me."]},
  {id:'lf-0005', category:"animals",
   options:["Emperor penguin","Puffin","Albatross","Arctic tern"],
   clues:["I raise my child through the darkest and coldest weeks on the planet.",
          "I balance my egg on my feet and cover it with a fold of warm skin.",
          "The fathers huddle together for months without eating a thing.",
          "I am the largest penguin, and I live in Antarctica."]},
  {id:'lf-0006', category:"science",
   options:["Rainbow","Aurora","Sundog","Lightning"],
   clues:["You can never reach me, and two people never see quite the same one of me.",
          "I am always exactly opposite the sun from where you are standing.",
          "I am really a full circle, but the ground hides most of me.",
          "I appear as coloured bands in the sky after rain."]},
  {id:'lf-0007', category:"history",
   options:["The printing press","The telescope","The compass","Paper money"],
   clues:["I made it possible for an idea to outrun the person who had it.",
          "Before me, a book cost about as much as a small farm.",
          "Gutenberg built a famous version of me in the 1400s.",
          "I print words onto paper using movable metal letters."]},
  {id:'lf-0008', category:"space",
   options:["The Moon","Mars","Venus","Mercury"],
   clues:["I am slowly moving away from you, a few centimetres every year.",
          "You have only ever seen one of my sides from where you live.",
          "My pull is what drags your oceans up the beach twice a day.",
          "I am the bright round thing in your night sky, and people have walked on me."]},
  {id:'lf-0009', category:"animals",
   options:["Chameleon","Gecko","Iguana","Anole"],
   clues:["My colour is a mood before it is ever a hiding place.",
          "My two eyes can look at two completely different things at once.",
          "My tongue can be longer than the rest of my body and it fires like a spring.",
          "I am the lizard famous for changing colour, and my tail curls in a spiral."]},
  {id:'lf-0010', category:"world",
   options:["The Sahara","The Gobi","The Kalahari","The Atacama"],
   clues:["I am roughly the size of a large country you could name, and I am growing.",
          "Snow has fallen on my northern edge more than once in living memory.",
          "Caravans crossed me with salt and gold for well over a thousand years.",
          "I am the great hot desert that covers northern Africa."]},
  {id:'lf-0011', category:"science",
   options:["Salt","Sugar","Sand","Chalk"],
   clues:["Wars were fought over me and workers were once paid in me.",
          "I am the only rock that people eat on purpose.",
          "I am two elements that are each dangerous alone and harmless together.",
          "You keep me in a shaker next to the pepper."]},
  {id:'lf-0012', category:"animals",
   options:["Owl","Hawk","Raven","Bat"],
   clues:["I can hear a heartbeat under snow from across a field.",
          "My feathers have soft combed edges so that my flight makes no sound.",
          "I cannot move my eyes in their sockets, so I turn my whole head instead.",
          "I hunt at night and people say I go hoo."]},
  {id:'lf-0013', category:"plants",
   options:["Mushroom","Moss","Fern","Lichen"],
   clues:["I am closer to you on the tree of life than I am to the plants around me.",
          "The part you see is only the fruit, and the real body is a web underground.",
          "One of my kind in Oregon is among the largest living things on earth.",
          "You slice me into pans, and I grow with a cap on a stalk."]},
  {id:'lf-0014', category:"world",
   options:["Venice","Amsterdam","Stockholm","Bruges"],
   clues:["I was built on wooden posts driven into soft mud, and I am still standing on them.",
          "I have no cars at all, and my rubbish and my post arrive by water.",
          "I am spread across more than a hundred small islands joined by bridges.",
          "I am the Italian city of canals, and my boats are called gondolas."]},
  {id:'lf-0015', category:"science",
   options:["Ice","Glass","Wax","Quartz"],
   clues:["I am one of the very few things that grows lighter when I turn solid.",
          "That single strange habit is why life can survive in a frozen lake.",
          "I float on the liquid I came from, which almost nothing else does.",
          "You put me in a drink to make it cold."]},
  {id:'lf-0016', category:"words",
   options:["The alphabet","A dictionary","Braille","Shorthand"],
   clues:["I came from merchants who needed to count faster than they could carve.",
          "My name is simply the first two of my own letters said one after the other.",
          "Almost every one of my versions puts A near the front.",
          "A, B, C, and twenty three more of me."]},
  {id:'lf-0017', category:"animals",
   options:["Camel","Llama","Donkey","Yak"],
   clues:["What I carry on my back is not water, and everybody thinks it is.",
          "I have two rows of lashes and I can close my nostrils in a storm.",
          "I can drink a bathtub of water in about ten minutes when I find it.",
          "I am the desert animal with one or two humps."]},
  {id:'lf-0018', category:"world",
   options:["Mount Everest","K2","Mont Blanc","Kilimanjaro"],
   clues:["I am still growing, though only about as fast as your fingernails.",
          "My summit rock was once the floor of a warm shallow sea.",
          "The air at my top holds about a third of the oxygen you are breathing now.",
          "I am the highest mountain on earth, sitting on the border of Nepal and Tibet."]},
  {id:'lf-0019', category:"food",
   options:["Bread","Cheese","Yoghurt","Vinegar"],
   clues:["I am one of the oldest prepared foods, older than farming in some places.",
          "A living culture of mine can be kept alive and shared for generations.",
          "I am made of little more than flour, water, salt and time.",
          "You slice me and put me in the toaster."]},
  {id:'lf-0020', category:"space",
   options:["Saturn","Jupiter","Uranus","Neptune"],
   clues:["I am light enough that I would float if you could find a bath big enough.",
          "My most famous feature is mostly ice, and it is thinner than you imagine.",
          "I have dozens of moons, and one of them has lakes of liquid methane.",
          "I am the planet with the big bright rings around me."]},
  {id:'lf-0021', category:"animals",
   options:["Blue whale","Elephant","Giant squid","Manatee"],
   clues:["My song is so low that most of it slips under the floor of your hearing.",
          "My tongue alone weighs about as much as a whole elephant.",
          "I strain tiny shrimp called krill through the fringed plates in my mouth.",
          "I am the largest animal that has ever lived, and I swim in the ocean."]},
  {id:'lf-0022', category:"animals",
   options:["Giraffe","Ostrich","Moose","Horse"],
   clues:["I have the same number of bones in my neck as a mouse does.",
          "I sleep only a few minutes at a time, and I do it standing up.",
          "My tongue is dark blue and about half a metre long.",
          "I am the tallest animal on land, with a very long neck and a patched coat."]},
  {id:'lf-0023', category:"animals",
   options:["Platypus","Beaver","Otter","Frog"],
   clues:["I hunt with my eyes closed, reading faint sparks of electricity in the mud.",
          "I am a mammal, and yet I lay eggs.",
          "The first scientists who saw me were sure I was a hoax stitched together.",
          "I have a bill like a duck, a flat tail, and I live in Australian rivers."]},
  {id:'lf-0024', category:"animals",
   options:["Axolotl","Newt","Tadpole","Frog"],
   clues:["I stay a child my whole life and never trade my pond for dry land.",
          "The only wild home I have left is a set of canals near Mexico City.",
          "Laboratories study me because I can grow a whole leg back exactly as it was.",
          "I am the pale pink Mexican amphibian with frilly gills, kept in home tanks."]},
  {id:'lf-0025', category:"animals",
   options:["Tardigrade","Amoeba","Dust mite","Plankton"],
   clues:["I have been outside a spacecraft in open space and carried on afterwards.",
          "Boiling, freezing and years of drought are all things I simply wait out.",
          "I am about half a millimetre long and I walk on eight stubby legs.",
          "People call me the water bear, and you need a microscope to see me."]},
  {id:'lf-0026', category:"animals",
   options:["Kangaroo","Rabbit","Ostrich","Deer"],
   clues:["The faster I hop the less energy it costs me, which is a rare bargain.",
          "I cannot walk backwards, and my tail works like a fifth limb.",
          "I carry my young in a pouch at the front of me for months.",
          "I am the big hopping animal of Australia, and my baby is called a joey."]},
  {id:'lf-0027', category:"animals",
   options:["Sloth","Koala","Anteater","Panda"],
   clues:["Tiny green plants grow in my coat, so I match the leaves without trying.",
          "One meal can take me most of a month to digest.",
          "I climb down from my tree only about once a week.",
          "I am the famously slow rainforest animal that hangs upside down by long claws."]},
  {id:'lf-0028', category:"animals",
   options:["Hummingbird","Bumblebee","Dragonfly","Wren"],
   clues:["I remember which flowers I emptied and how long they take to refill.",
          "I can hover in one place and even fly backwards, which no other bird does.",
          "My nest is about the size of a walnut and my eggs are like small beans.",
          "I am the tiniest bird, sipping nectar with wings that blur into a hum."]},
  {id:'lf-0029', category:"animals",
   options:["Flamingo","Heron","Stork","Crane"],
   clues:["I am born grey, and it is my dinner that slowly paints me.",
          "I feed with my head upside down, sieving tiny creatures out of the water.",
          "I can stand for hours on one leg in lakes too salty for most animals.",
          "I am the tall pink wading bird that gathers in enormous flocks."]},
  {id:'lf-0030', category:"animals",
   options:["Bat","Flying squirrel","Swift","Moth"],
   clues:["I map the dark by shouting into it and listening to what comes back.",
          "My wing is a hand with very long fingers and thin skin stretched between.",
          "I am the only mammal that truly flies rather than glides.",
          "I hang upside down to rest, and I flit out of caves at dusk."]},
  {id:'lf-0031', category:"animals",
   options:["Narwhal","Walrus","Beluga","Swordfish"],
   clues:["Traders once sold my spiral as proof that unicorns were real.",
          "The spiral is really a tooth that grows out in a long straight twist.",
          "I spend the whole year in Arctic water and find gaps in the ice to breathe.",
          "I am the Arctic whale with one long tusk, called the unicorn of the sea."]},
  {id:'lf-0032', category:"animals",
   options:["Cheetah","Greyhound","Falcon","Antelope"],
   clues:["My spine bends and springs like a bow, and it flings me into the next stride.",
          "I cannot roar at all, and the sound I make is closer to a bird chirp.",
          "I go from standing still to full motorway speed in about three seconds.",
          "I am the fastest runner on land, a spotted cat of the African plains."]},
  {id:'lf-0033', category:"world",
   options:["The Great Barrier Reef","The Maldives","The Galapagos Islands","The Serengeti"],
   clues:["Tiny builders no bigger than a grain of rice have been raising me for ages.",
          "I stretch for more than two thousand kilometres along a warm eastern coast.",
          "Clownfish and sea turtles live in me, and Australia keeps me as a marine park.",
          "I am the huge coral reef off the north east coast of Australia."]},
  {id:'lf-0034', category:"world",
   options:["The Grand Canyon","Yosemite Valley","The Great Rift Valley","Monument Valley"],
   clues:["A very patient river carved me out, and it is still down there working.",
          "My walls read like a book of stone whose oldest pages are nearly two billion years old.",
          "I am about a mile deep, and visitors ride mules down the trails into me.",
          "I am the enormous canyon in Arizona, cut by the Colorado River."]},
  {id:'lf-0035', category:"world",
   options:["Niagara Falls","Victoria Falls","Angel Falls","Iguazu Falls"],
   clues:["I creep upstream a little every year by eating the rock under my own edge.",
          "Boats full of visitors in raincoats sail right up to the churn at my base.",
          "Two countries share me, and a bridge lets people walk from one side to the other.",
          "I am the famous waterfall on the border of Canada and the United States."]},
  {id:'lf-0036', category:"world",
   options:["Antarctica","Greenland","Siberia","The Arctic"],
   clues:["I am the driest continent, and most of the fresh water on earth is frozen on me.",
          "Nobody lives on me for good, and the people who work here all fly home again.",
          "My ice is over a mile thick in places, and it hides mountains and whole lakes.",
          "I am the frozen continent at the bottom of the world, where penguins live."]},
  {id:'lf-0037', category:"world",
   options:["The Amazon Rainforest","The Congo Rainforest","Borneo","The Everglades"],
   clues:["Dust blown across an entire ocean from a desert lands on me and feeds me.",
          "I make my own weather, and rivers of vapour rise off me into the sky.",
          "About one in ten of all the known kinds of animal and plant lives inside me.",
          "I am the largest rainforest in the world, and Brazil holds most of me."]},
  {id:'lf-0038', category:"world",
   options:["Japan","Indonesia","The Philippines","South Korea"],
   clues:["I am really thousands of islands, though nearly everyone lives on four of them.",
          "My trains are timed so closely that being one minute late counts as news.",
          "My tallest mountain is the volcano Fuji, and my ground shakes very often.",
          "I am the island country whose capital city is Tokyo."]},
  {id:'lf-0039', category:"world",
   options:["The Netherlands","Belgium","Denmark","Switzerland"],
   clues:["I took a good deal of my land back from the sea, and pumps keep it dry.",
          "Much of my ground sits lower than the waves just beyond my walls.",
          "I have more bicycles than people, and my fields turn to stripes of colour in spring.",
          "I am the country of tulips and windmills, and my capital is Amsterdam."]},
  {id:'lf-0040', category:"world",
   options:["Istanbul","Athens","Alexandria","Lisbon"],
   clues:["I have worn three names that people still remember, and I answer to the newest.",
          "I stand on two continents at once, with a ribbon of water between my halves.",
          "Ships pass through my middle all day along a strait called the Bosphorus.",
          "I am the largest city in Turkey, and I was once called Constantinople."]},
  {id:'lf-0041', category:"history",
   options:["The Great Wall of China","Hadrian's Wall","The Silk Road","The Grand Canal"],
   clues:["Sticky rice was stirred into my mortar, and some of it is holding to this day.",
          "I am not one long line at all, but many walls built and rebuilt over centuries.",
          "People love to say you can see me from the moon, and that has never been true.",
          "I am the long stone wall that winds across the north of China."]},
  {id:'lf-0042', category:"history",
   options:["The Eiffel Tower","Big Ben","The Empire State Building","The Statue of Liberty"],
   clues:["I was due to be taken down after twenty years, and a radio aerial saved me.",
          "I grow about fifteen centimetres taller on hot days and shrink again when it cools.",
          "I am a lattice of iron, and a team repaints me about every seven years.",
          "I am the tall iron tower that stands over the city of Paris."]},
  {id:'lf-0043', category:"history",
   options:["Machu Picchu","Petra","Angkor Wat","Chichen Itza"],
   clues:["I was built with no wheels, no iron tools and no mortar between my stones.",
          "My blocks fit so closely that a sheet of paper will not slide between them.",
          "I sit on a green ridge in the Andes, high above a river valley.",
          "I am the ancient Inca city in the mountains of Peru."]},
  {id:'lf-0044', category:"history",
   options:["The Great Pyramid of Giza","The Sphinx","Stonehenge","The Parthenon"],
   clues:["I once wore a smooth white casing that shone in the sun, and it is mostly gone.",
          "My four sides line up with north, south, east and west almost exactly.",
          "For about four thousand years nothing that people built stood taller than me.",
          "I am the largest of the stone pyramids that stand near Cairo in Egypt."]},
  {id:'lf-0045', category:"history",
   options:["Umbrella","Raincoat","Sun hat","Folding fan"],
   clues:["My name comes from an old word for shade, and rain was never the point.",
          "For thousands of years I was carried mainly to keep the sun off someone.",
          "A man in London was laughed at in the street for carrying me in the rain.",
          "You open me above you when it rains, and a gust can turn me inside out."]},
  {id:'lf-0046', category:"science",
   options:["Microwave oven","Toaster","Electric kettle","Air fryer"],
   clues:["I was found by accident in the 1940s by an engineer working on radar.",
          "The first food anyone aimed me at on purpose was popcorn.",
          "I shake the water inside food so quickly that the food heats itself.",
          "I sit on the kitchen counter, I have a turntable inside, and I go ping."]},
  {id:'lf-0047', category:"science",
   options:["Pencil","Chalk","Crayon","Charcoal"],
   clues:["The grey stuff in my middle was first dug from one valley in England.",
          "Shepherds used that same grey stone to mark their sheep before I existed.",
          "There has never been any lead in me, whatever people call my middle.",
          "You sharpen me, and there is often a little eraser on my other end."]},
  {id:'lf-0048', category:"history",
   options:["Traffic light","Street lamp","Stop sign","Post box"],
   clues:["The first of me stood in London in 1868, before cars filled the streets.",
          "A person had to stand beside me and work me by hand with a lever.",
          "My middle colour was added later, to give everyone a moment to get ready.",
          "I hang above the road, and red means stop while green means go."]},
  {id:'lf-0049', category:"history",
   options:["Jigsaw puzzle","Globe","Dominoes","Playing cards"],
   clues:["I began as a teaching tool, cut around the edges of countries on a map.",
          "A London mapmaker glued his map onto wood and sawed me apart in the 1760s.",
          "For my first hundred years I was made of wood, and only later of cardboard.",
          "I come in a box in hundreds of pieces and you build the picture on the lid."]},
  {id:'lf-0050', category:"history",
   options:["Tin can","Glass jar","Barrel","Cardboard box"],
   clues:["I kept food safe for nearly fifty years before a tool existed to open me.",
          "Early instructions printed on me suggested a hammer and a chisel.",
          "Explorers and sailors carried me so their food would last a whole voyage.",
          "You keep soup and beans in me in the cupboard, and I am made of metal."]},
  {id:'lf-0051', category:"history",
   options:["Bicycle","Kick scooter","Wheelbarrow","Roller skates"],
   clues:["My first version in 1817 had no pedals at all and you pushed yourself along.",
          "For a while my front wheel was enormous and my back wheel was tiny.",
          "Adding a chain to my back wheel is what finally made me safe to ride.",
          "I have two wheels, handlebars and pedals, and you ring my little bell."]},
  {id:'lf-0052', category:"words",
   options:["Denim","Corduroy","Linen","Velvet"],
   clues:["My name is really a French town name that English speakers wore down.",
          "The word for my most famous trousers comes from the Italian city of Genoa.",
          "Only one set of my threads is dyed blue, which is why I fade so pale.",
          "Almost everybody owns a pair of blue jeans made of me."]},
  {id:'lf-0053', category:"food",
   options:["Ketchup","Mustard","Mayonnaise","Soy sauce"],
   clues:["I began in Asia as a salty sauce made from fish, with no tomato in me.",
          "English cooks made me from mushrooms and walnuts for over a hundred years.",
          "Tomatoes only joined me in America in the early 1800s and then took over.",
          "You squeeze me from a bottle onto fries, and I am red, thick and sweet."]},
  {id:'lf-0054', category:"food",
   options:["Chocolate","Coffee","Vanilla","Tea"],
   clues:["My pods grow straight out of the trunk of the tree, not from the branches.",
          "For most of my long history I was a bitter frothy drink and never a bar.",
          "My beans must be fermented and then roasted before I taste like anything.",
          "I come in a bar of squares, I am sweet and brown, and I melt in a pocket."]},
  {id:'lf-0055', category:"plants",
   options:["Carrot","Potato","Beetroot","Parsnip"],
   clues:["For most of my history I was purple or yellow, and orange came much later.",
          "Dutch growers made my orange kind common about four hundred years ago.",
          "The part you eat is a root, and my leafy tops open into white lace flowers.",
          "I am the long orange root that goes in a stew, and rabbits love me."]},
  {id:'lf-0056', category:"plants",
   options:["Vanilla","Cinnamon","Saffron","Almond"],
   clues:["Away from my home country almost none of me forms without a helping hand.",
          "I am the pod of a climbing orchid, and a boy on an island found the trick.",
          "My name comes from a Spanish word meaning little pod, and I grow long.",
          "I am the flavour of plain white ice cream."]},
  {id:'lf-0057', category:"science",
   options:["Lightning","Thunder","Hail","Wind"],
   clues:["I heat the air I pass through to about five times hotter than the surface of the sun.",
          "The bang you hear afterwards is just the air clapping shut behind me.",
          "Somewhere on earth I flash dozens of times every single second.",
          "I am the bright flash in a storm, and thunder is the sound I make."]},
  {id:'lf-0058', category:"space",
   options:["Aurora","Comet","Meteor shower","Moonlight"],
   clues:["I appear when a wind from the sun crashes into the very top of your air.",
          "Oxygen high above gives me my green, and I glow best near the poles.",
          "I hang as rippling curtains of light across a clear winter night sky.",
          "People in the far north call me the Northern Lights."]},
  {id:'lf-0059', category:"science",
   options:["Hurricane","Tornado","Blizzard","Sandstorm"],
   clues:["I am handed a name from a list months before I even exist.",
          "I can only be born over warm ocean water, and I fade once I cross land.",
          "At my very centre there is a circle of calm sky called the eye.",
          "I am the giant spinning storm that comes off the warm ocean and gets a name."]},
  {id:'lf-0060', category:"science",
   options:["Snowflake","Hailstone","Frost","Raindrop"],
   clues:["I begin to grow around a speck of dust far too small for you to see.",
          "The way my water freezes gives me six sides every single time.",
          "No two of me have ever been found to match, though nobody has checked them all.",
          "I am one tiny crystal of snow that lands on your glove in winter."]},
  {id:'lf-0061', category:"science",
   options:["Volcano","Geyser","Earthquake","Hot spring"],
   clues:["I build a mountain out of the very thing that tears me open.",
          "Most of me is hidden, running in long chains along the floor of the sea.",
          "Melted rock rises from deep below and pours out of my top as lava.",
          "I am the mountain that erupts with lava, ash and smoke."]},
  {id:'lf-0062', category:"science",
   options:["Tide","Wave","Ocean current","Whirlpool"],
   clues:["I am the sea keeping time with something far out in space.",
          "Twice a day I climb the beach and twice a day I slide back down.",
          "In the Bay of Fundy I move the water up and down by over fifteen metres.",
          "I am the daily rise and fall of the sea, pulled along by the moon."]},
  {id:'lf-0063', category:"science",
   options:["Diamond","Ruby","Emerald","Pearl"],
   clues:["I am made of the same single element as the soft grey stuff inside a pencil.",
          "Great pressure deep underground squeezed me together a very long time ago.",
          "Nothing in nature can scratch me except another one of me.",
          "I am the clear sparkling gemstone, the hardest one there is."]},
  {id:'lf-0064', category:"world",
   options:["The Pacific Ocean","The Atlantic Ocean","The Indian Ocean","The Arctic Ocean"],
   clues:["My deepest trench could swallow the tallest mountain with a mile to spare.",
          "A ring of volcanoes traces my edge, and people call it the Ring of Fire.",
          "I am wider than the moon and I cover about a third of the planet.",
          "I am the largest ocean, lying between Asia and the Americas."]},
  {id:'lf-0065', category:"space",
   options:["Meteor","Comet","Satellite","Planet"],
   clues:["I am often no bigger than a grain of sand, and I never reach the ground.",
          "I glow because the air in front of me is squashed and heated as I rush in.",
          "Every August a whole shower of us seems to pour out of one patch of sky.",
          "People call me a shooting star and make a wish when I streak past."]},
  {id:'lf-0066', category:"world",
   options:["Glacier","Iceberg","Avalanche","Frozen lake"],
   clues:["I am a river so slow that you could watch me all day and see nothing move.",
          "I grind valleys into the shape of a letter U and leave heaps of rubble behind.",
          "Snow piled up for centuries packed me into ice so dense that it looks blue.",
          "I am the huge sheet of ice that creeps slowly down a mountain valley."]},
  {id:'lf-0067', category:"plants",
   options:["Peanut","Almond","Walnut","Pecan"],
   clues:["I am not a nut at all, and I am a closer cousin of peas and beans.",
          "When my flowers fade, the stalks bend down and push themselves into the soil.",
          "My crop finishes ripening completely underground, so the whole plant is pulled up.",
          "I come two to a wrinkly shell, and I am the classic butter for a sandwich."]},
  {id:'lf-0068', category:"food",
   options:["Coffee","Tea","Chicory","Barley"],
   clues:["What you grind is the seed of my small red fruit, which looks a lot like a cherry.",
          "Ethiopia is my homeland, and a legend credits a goat herder with noticing me.",
          "I am picked and shipped while still green, and I only turn brown in a hot drum.",
          "I am the dark drink people brew from ground beans in the morning."]},
  {id:'lf-0069', category:"food",
   options:["Cashew","Almond","Pistachio","Hazelnut"],
   clues:["I hang from the bottom of a bright fruit, growing outside it instead of within.",
          "My shell holds an oil so fierce that nobody ever sells me still inside it.",
          "I curl like a small comma, and there is only ever one of me in a shell.",
          "I am the creamy nut curved like a crescent moon, popular in a stir fry."]},
  {id:'lf-0070', category:"food",
   options:["Tea","Coffee","Mint","Chamomile"],
   clues:["I am an evergreen bush that would grow into a tree if pickers ever let me.",
          "The finest picking takes only my bud and the two leaves just below it.",
          "Black, green and white are not different plants but different ways of treating me.",
          "I am the drink that comes as black or green in a little bag, taken with milk in Britain."]},
  {id:'lf-0071', category:"plants",
   options:["Pineapple","Coconut","Banana","Mango"],
   clues:["I take almost two years to grow, and my plant makes just one of me.",
          "I grow low to the ground on a spiky plant, and never in a tree.",
          "I am really dozens of small fruits fused together, which is why my skin is tiled.",
          "I am the golden tropical fruit with a spiky skin and a crown of leaves."]},
  {id:'lf-0072', category:"food",
   options:["Potato","Carrot","Turnip","Parsnip"],
   clues:["I came out of the Andes and reached Europe in the 1500s.",
          "Peru still grows thousands of my varieties, in colours no shop near you sells.",
          "I am not a root but a swollen stem, which is why I grow eyes and can sprout.",
          "Ireland is famous for growing me, and I turn into mash, chips and crisps."]},
  {id:'lf-0073', category:"plants",
   options:["Cinnamon","Nutmeg","Clove","Ginger"],
   clues:["I am neither seed nor leaf but the inner bark of a small evergreen tree.",
          "Sri Lanka has been my most famous home for many hundreds of years.",
          "My bark curls into tight quills as it dries, and those are the sticks you buy.",
          "I am the warm brown spice dusted on toast and swirled into buns."]},
  {id:'lf-0074', category:"food",
   options:["Maple syrup","Honey","Molasses","Caramel"],
   clues:["I begin as a clear watery sap that tastes barely sweet at all.",
          "It takes about forty buckets of that sap to boil down into one of me.",
          "I only run when the nights freeze and the days thaw, so my season is short.",
          "Canada makes most of me, and I am poured warm over pancakes."]},
  {id:'lf-0075', category:"food",
   options:["Cranberry","Blueberry","Raspberry","Strawberry"],
   clues:["Farmers flood my fields with water when it is time to gather me.",
          "I float, because there are four little pockets of air inside me.",
          "I grow on low trailing vines in sandy bogs, mostly in North America.",
          "I am the small tart red berry served as a sauce beside the holiday turkey."]},
  {id:'lf-0076', category:"food",
   options:["Corn","Wheat","Rice","Barley"],
   clues:["My wild ancestor was a scruffy Mexican grass with only a few hard seeds.",
          "Every silky thread at my top leads to one seed, and each needs its own pollen.",
          "I cannot scatter my own seeds any more, so I depend on people to plant me.",
          "I grow on a cob wrapped in green leaves, and I pop when heated in a pan."]}
];
