/* LIFTING FOG QUESTION BANK

   Each entry is a thing speaking about itself in four clues, ordered from
   cryptic to obvious. The fog lifts one clue at a time and the answer is worth
   less each time it does.

   ⭐ FORMAT RULE THAT PREVENTS THE OBVIOUS BUG: options[0] is ALWAYS the correct
   answer. The game shuffles the four options before showing them, so an author
   can never mismatch an answer to an index and a reviewer can audit a line by
   reading it left to right.

   Regenerate or extend with this exact prompt, then hand-audit every entry:

   "Write N progressive clue questions for a cozy family quiz. Each is one
   THING (an animal, a place, an object, a food, a natural event) speaking in
   the first person about itself, in four clues ordered from cryptic to
   obvious. Clue 1 should be genuinely hard and slightly poetic, and should
   NOT be guessable by most people. Clue 4 should be so obvious that everyone
   gets it. Clues 2 and 3 step evenly between them. Rules: each clue is one
   sentence under 95 characters, true, checkable against a mainstream
   encyclopedia, general audience, no politics, no religion, no bodies, no
   violence, no brand names, NO DASH CHARACTERS OF ANY KIND. Also give three
   wrong options that are plausible for the first clue but clearly wrong by
   the last one. A wrong option that is still arguably correct at clue 4 is a
   broken question. Output a JS array of objects with fields id, options
   (array of 4 strings where the FIRST is correct), clues (array of 4 strings),
   category. Categories: animals, space, food, history, science, world, words,
   plants."

   AUDIT RULE: read clue 4 and check that exactly one option satisfies it. Then
   read clue 1 and check that it does not simply give the answer away.

   Bank at 2026-08-08: 140 entries. */
window.LIFTINGFOG_BANK = [
  {id:'lf-0001', category:"animals",
   options:["Octopus","Sea star","Jellyfish","Lobster"],
   clues:["I have been opening jars in laboratories far longer than you have.",
          "My blood runs blue and it takes three hearts to push it around.",
          "I can change my colour and my skin texture in about a second.",
          "I have eight arms, and every one of them is covered in suckers."]},
  {id:'lf-0002', category:"food",
   options:["Honey","Maple syrup","Molasses","Olive oil"],
   clues:["Sealed jars of me have been found in old tombs and were still edible.",
          "I am made by thousands of workers who never meet the person who eats me.",
          "My flavour changes completely depending on which flowers were nearby.",
          "Bees make me, and it takes a whole hive a season to fill one jar."]},
  {id:'lf-0003', category:"world",
   options:["Iceland","Norway","Greenland","Scotland"],
   clues:["My name promises cold and my neighbour with the greener name is far colder.",
          "I sit on a seam where two of the world plates are pulling apart.",
          "Almost all of my heat and power comes up out of the ground for free.",
          "My capital is Reykjavik and I am an island in the North Atlantic."]},
  {id:'lf-0004', category:"plants",
   options:["Bamboo","Sugar cane","Willow","Palm"],
   clues:["I am a grass, though almost everyone who meets me calls me a tree.",
          "Some of my kind can add most of a foot to their height in a single day.",
          "People build scaffolding, floors and whole houses out of me.",
          "Pandas eat almost nothing but me."]},
  {id:'lf-0005', category:"animals",
   options:["Emperor penguin","Puffin","Albatross","Arctic tern"],
   clues:["I raise my child through the darkest and coldest weeks on the planet.",
          "I balance my egg on my feet and cover it with a fold of warm skin.",
          "The fathers huddle together for months without eating a thing.",
          "I am the largest penguin, and I live in Antarctica."]},
  {id:'lf-0006', category:"science",
   options:["Rainbow","Aurora","Sundog","Lightning"],
   clues:["You can never reach me, and two people never see quite the same one of me.",
          "I am always exactly opposite the sun from where you are standing.",
          "I am really a full circle, but the ground hides most of me.",
          "I appear as coloured bands in the sky after rain."]},
  {id:'lf-0007', category:"history",
   options:["The printing press","The telescope","The compass","Paper money"],
   clues:["I made it possible for an idea to outrun the person who had it.",
          "Before me, a book cost about as much as a small farm.",
          "Gutenberg built a famous version of me in the 1400s.",
          "I print words onto paper using movable metal letters."]},
  {id:'lf-0008', category:"space",
   options:["The Moon","Mars","Venus","Mercury"],
   clues:["I am slowly moving away from you, a few centimetres every year.",
          "You have only ever seen one of my sides from where you live.",
          "My pull is what drags your oceans up the beach twice a day.",
          "I am the bright round thing in your night sky, and people have walked on me."]},
  {id:'lf-0009', category:"animals",
   options:["Chameleon","Gecko","Iguana","Anole"],
   clues:["My colour is a mood before it is ever a hiding place.",
          "My two eyes can look at two completely different things at once.",
          "My tongue can be longer than the rest of my body and it fires like a spring.",
          "I am the lizard famous for changing colour, and my tail curls in a spiral."]},
  {id:'lf-0010', category:"world",
   options:["The Sahara","The Gobi","The Kalahari","The Atacama"],
   clues:["I am roughly the size of a large country you could name, and I am growing.",
          "Snow has fallen on my northern edge more than once in living memory.",
          "Caravans crossed me with salt and gold for well over a thousand years.",
          "I am the great hot desert that covers northern Africa."]},
  {id:'lf-0011', category:"science",
   options:["Salt","Sugar","Sand","Chalk"],
   clues:["Wars were fought over me and workers were once paid in me.",
          "I am the only rock that people eat on purpose.",
          "I am two elements that are each dangerous alone and harmless together.",
          "You keep me in a shaker next to the pepper."]},
  {id:'lf-0012', category:"animals",
   options:["Owl","Hawk","Raven","Bat"],
   clues:["I can hear a heartbeat under snow from across a field.",
          "My feathers have soft combed edges so that my flight makes no sound.",
          "I cannot move my eyes in their sockets, so I turn my whole head instead.",
          "I hunt at night and people say I go hoo."]},
  {id:'lf-0013', category:"plants",
   options:["Mushroom","Moss","Fern","Lichen"],
   clues:["I am closer to you on the tree of life than I am to the plants around me.",
          "The part you see is only the fruit, and the real body is a web underground.",
          "One of my kind in Oregon is among the largest living things on earth.",
          "You slice me into pans, and I grow with a cap on a stalk."]},
  {id:'lf-0014', category:"world",
   options:["Venice","Amsterdam","Stockholm","Bruges"],
   clues:["I was built on wooden posts driven into soft mud, and I am still standing on them.",
          "I have no cars at all, and my rubbish and my post arrive by water.",
          "I am spread across more than a hundred small islands joined by bridges.",
          "I am the Italian city of canals, and my boats are called gondolas."]},
  {id:'lf-0015', category:"science",
   options:["Ice","Glass","Wax","Quartz"],
   clues:["I am one of the very few things that grows lighter when I turn solid.",
          "That single strange habit is why life can survive in a frozen lake.",
          "I float on the liquid I came from, which almost nothing else does.",
          "You put me in a drink to make it cold."]},
  {id:'lf-0016', category:"words",
   options:["The alphabet","A dictionary","Braille","Shorthand"],
   clues:["I came from merchants who needed to count faster than they could carve.",
          "My name is simply the first two of my own letters said one after the other.",
          "Almost every one of my versions puts A near the front.",
          "A, B, C, and twenty three more of me."]},
  {id:'lf-0017', category:"animals",
   options:["Camel","Llama","Donkey","Yak"],
   clues:["What I carry on my back is not water, and everybody thinks it is.",
          "I have two rows of lashes and I can close my nostrils in a storm.",
          "I can drink a bathtub of water in about ten minutes when I find it.",
          "I am the desert animal with one or two humps."]},
  {id:'lf-0018', category:"world",
   options:["Mount Everest","K2","Mont Blanc","Kilimanjaro"],
   clues:["I am still growing, though only about as fast as your fingernails.",
          "My summit rock was once the floor of a warm shallow sea.",
          "The air at my top holds about a third of the oxygen you are breathing now.",
          "I am the highest mountain on earth, sitting on the border of Nepal and Tibet."]},
  {id:'lf-0019', category:"food",
   options:["Bread","Cheese","Yoghurt","Vinegar"],
   clues:["I am one of the oldest prepared foods, older than farming in some places.",
          "A living culture of mine can be kept alive and shared for generations.",
          "I am made of little more than flour, water, salt and time.",
          "You slice me and put me in the toaster."]},
  {id:'lf-0020', category:"space",
   options:["Saturn","Jupiter","Uranus","Neptune"],
   clues:["I am light enough that I would float if you could find a bath big enough.",
          "My most famous feature is mostly ice, and it is thinner than you imagine.",
          "I have dozens of moons, and one of them has lakes of liquid methane.",
          "I am the planet with the big bright rings around me."]},
  {id:'lf-0021', category:"animals",
   options:["Blue whale","Elephant","Giant squid","Manatee"],
   clues:["My song is so low that most of it slips under the floor of your hearing.",
          "My tongue alone weighs about as much as a whole elephant.",
          "I strain tiny shrimp called krill through the fringed plates in my mouth.",
          "I am the largest animal that has ever lived, and I swim in the ocean."]},
  {id:'lf-0022', category:"animals",
   options:["Giraffe","Ostrich","Moose","Horse"],
   clues:["I have the same number of bones in my neck as a mouse does.",
          "I sleep only a few minutes at a time, and I do it standing up.",
          "My tongue is dark blue and about half a metre long.",
          "I am the tallest animal on land, with a very long neck and a patched coat."]},
  {id:'lf-0023', category:"animals",
   options:["Platypus","Beaver","Otter","Frog"],
   clues:["I hunt with my eyes closed, reading faint sparks of electricity in the mud.",
          "I am a mammal, and yet I lay eggs.",
          "The first scientists who saw me were sure I was a hoax stitched together.",
          "I have a bill like a duck, a flat tail, and I live in Australian rivers."]},
  {id:'lf-0024', category:"animals",
   options:["Axolotl","Newt","Tadpole","Frog"],
   clues:["I stay a child my whole life and never trade my pond for dry land.",
          "The only wild home I have left is a set of canals near Mexico City.",
          "Laboratories study me because I can grow a whole leg back exactly as it was.",
          "I am the pale pink Mexican amphibian with frilly gills, kept in home tanks."]},
  {id:'lf-0025', category:"animals",
   options:["Tardigrade","Amoeba","Dust mite","Plankton"],
   clues:["I have been outside a spacecraft in open space and carried on afterwards.",
          "Boiling, freezing and years of drought are all things I simply wait out.",
          "I am about half a millimetre long and I walk on eight stubby legs.",
          "People call me the water bear, and you need a microscope to see me."]},
  {id:'lf-0026', category:"animals",
   options:["Kangaroo","Rabbit","Ostrich","Deer"],
   clues:["The faster I hop the less energy it costs me, which is a rare bargain.",
          "I cannot walk backwards, and my tail works like a fifth limb.",
          "I carry my young in a pouch at the front of me for months.",
          "I am the big hopping animal of Australia, and my baby is called a joey."]},
  {id:'lf-0027', category:"animals",
   options:["Sloth","Koala","Anteater","Panda"],
   clues:["Tiny green plants grow in my coat, so I match the leaves without trying.",
          "One meal can take me most of a month to digest.",
          "I climb down from my tree only about once a week.",
          "I am the famously slow rainforest animal that hangs upside down by long claws."]},
  {id:'lf-0028', category:"animals",
   options:["Hummingbird","Bumblebee","Dragonfly","Wren"],
   clues:["I remember which flowers I emptied and how long they take to refill.",
          "I can hover in one place and even fly backwards, which no other bird does.",
          "My nest is about the size of a walnut and my eggs are like small beans.",
          "I am the tiniest bird, sipping nectar with wings that blur into a hum."]},
  {id:'lf-0029', category:"animals",
   options:["Flamingo","Heron","Stork","Crane"],
   clues:["I am born grey, and it is my dinner that slowly paints me.",
          "I feed with my head upside down, sieving tiny creatures out of the water.",
          "I can stand for hours on one leg in lakes too salty for most animals.",
          "I am the tall pink wading bird that gathers in enormous flocks."]},
  {id:'lf-0030', category:"animals",
   options:["Bat","Flying squirrel","Swift","Moth"],
   clues:["I map the dark by shouting into it and listening to what comes back.",
          "My wing is a hand with very long fingers and thin skin stretched between.",
          "I am the only mammal that truly flies rather than glides.",
          "I hang upside down to rest, and I flit out of caves at dusk."]},
  {id:'lf-0031', category:"animals",
   options:["Narwhal","Walrus","Beluga","Swordfish"],
   clues:["Traders once sold my spiral as proof that unicorns were real.",
          "The spiral is really a tooth that grows out in a long straight twist.",
          "I spend the whole year in Arctic water and find gaps in the ice to breathe.",
          "I am the Arctic whale with one long tusk, called the unicorn of the sea."]},
  {id:'lf-0032', category:"animals",
   options:["Cheetah","Greyhound","Falcon","Antelope"],
   clues:["My spine bends and springs like a bow, and it flings me into the next stride.",
          "I cannot roar at all, and the sound I make is closer to a bird chirp.",
          "I go from standing still to full motorway speed in about three seconds.",
          "I am the fastest runner on land, a spotted cat of the African plains."]},
  {id:'lf-0033', category:"world",
   options:["The Great Barrier Reef","The Maldives","The Galapagos Islands","The Serengeti"],
   clues:["Tiny builders no bigger than a grain of rice have been raising me for ages.",
          "I stretch for more than two thousand kilometres along a warm eastern coast.",
          "Clownfish and sea turtles live in me, and Australia keeps me as a marine park.",
          "I am the huge coral reef off the north east coast of Australia."]},
  {id:'lf-0034', category:"world",
   options:["The Grand Canyon","Yosemite Valley","The Great Rift Valley","Monument Valley"],
   clues:["A very patient river carved me out, and it is still down there working.",
          "My walls read like a book of stone whose oldest pages are nearly two billion years old.",
          "I am about a mile deep, and visitors ride mules down the trails into me.",
          "I am the enormous canyon in Arizona, cut by the Colorado River."]},
  {id:'lf-0035', category:"world",
   options:["Niagara Falls","Victoria Falls","Angel Falls","Iguazu Falls"],
   clues:["I creep upstream a little every year by eating the rock under my own edge.",
          "Boats full of visitors in raincoats sail right up to the churn at my base.",
          "Two countries share me, and a bridge lets people walk from one side to the other.",
          "I am the famous waterfall on the border of Canada and the United States."]},
  {id:'lf-0036', category:"world",
   options:["Antarctica","Greenland","Siberia","The Arctic"],
   clues:["I am the driest continent, and most of the fresh water on earth is frozen on me.",
          "Nobody lives on me for good, and the people who work here all fly home again.",
          "My ice is over a mile thick in places, and it hides mountains and whole lakes.",
          "I am the frozen continent at the bottom of the world, where penguins live."]},
  {id:'lf-0037', category:"world",
   options:["The Amazon Rainforest","The Congo Rainforest","Borneo","The Everglades"],
   clues:["Dust blown across an entire ocean from a desert lands on me and feeds me.",
          "I make my own weather, and rivers of vapour rise off me into the sky.",
          "About one in ten of all the known kinds of animal and plant lives inside me.",
          "I am the largest rainforest in the world, and Brazil holds most of me."]},
  {id:'lf-0038', category:"world",
   options:["Japan","Indonesia","The Philippines","South Korea"],
   clues:["I am really thousands of islands, though nearly everyone lives on four of them.",
          "My trains are timed so closely that being one minute late counts as news.",
          "My tallest mountain is the volcano Fuji, and my ground shakes very often.",
          "I am the island country whose capital city is Tokyo."]},
  {id:'lf-0039', category:"world",
   options:["The Netherlands","Belgium","Denmark","Switzerland"],
   clues:["I took a good deal of my land back from the sea, and pumps keep it dry.",
          "Much of my ground sits lower than the waves just beyond my walls.",
          "I have more bicycles than people, and my fields turn to stripes of colour in spring.",
          "I am the country of tulips and windmills, and my capital is Amsterdam."]},
  {id:'lf-0040', category:"world",
   options:["Istanbul","Athens","Alexandria","Lisbon"],
   clues:["I have worn three names that people still remember, and I answer to the newest.",
          "I stand on two continents at once, with a ribbon of water between my halves.",
          "Ships pass through my middle all day along a strait called the Bosphorus.",
          "I am the largest city in Turkey, and I was once called Constantinople."]},
  {id:'lf-0041', category:"history",
   options:["The Great Wall of China","Hadrian's Wall","The Silk Road","The Grand Canal"],
   clues:["Sticky rice was stirred into my mortar, and some of it is holding to this day.",
          "I am not one long line at all, but many walls built and rebuilt over centuries.",
          "People love to say you can see me from the moon, and that has never been true.",
          "I am the long stone wall that winds across the north of China."]},
  {id:'lf-0042', category:"history",
   options:["The Eiffel Tower","Big Ben","The Empire State Building","The Statue of Liberty"],
   clues:["I was due to be taken down after twenty years, and a radio aerial saved me.",
          "I grow about fifteen centimetres taller on hot days and shrink again when it cools.",
          "I am a lattice of iron, and a team repaints me about every seven years.",
          "I am the tall iron tower that stands over the city of Paris."]},
  {id:'lf-0043', category:"history",
   options:["Machu Picchu","Petra","Angkor Wat","Chichen Itza"],
   clues:["I was built with no wheels, no iron tools and no mortar between my stones.",
          "My blocks fit so closely that a sheet of paper will not slide between them.",
          "I sit on a green ridge in the Andes, high above a river valley.",
          "I am the ancient Inca city in the mountains of Peru."]},
  {id:'lf-0044', category:"history",
   options:["The Great Pyramid of Giza","The Sphinx","Stonehenge","The Parthenon"],
   clues:["I once wore a smooth white casing that shone in the sun, and it is mostly gone.",
          "My four sides line up with north, south, east and west almost exactly.",
          "For about four thousand years nothing that people built stood taller than me.",
          "I am the largest of the stone pyramids that stand near Cairo in Egypt."]},
  {id:'lf-0045', category:"history",
   options:["Umbrella","Raincoat","Sun hat","Folding fan"],
   clues:["My name comes from an old word for shade, and rain was never the point.",
          "For thousands of years I was carried mainly to keep the sun off someone.",
          "A man in London was laughed at in the street for carrying me in the rain.",
          "You open me above you when it rains, and a gust can turn me inside out."]},
  {id:'lf-0046', category:"science",
   options:["Microwave oven","Toaster","Electric kettle","Air fryer"],
   clues:["I was found by accident in the 1940s by an engineer working on radar.",
          "The first food anyone aimed me at on purpose was popcorn.",
          "I shake the water inside food so quickly that the food heats itself.",
          "I sit on the kitchen counter, I have a turntable inside, and I go ping."]},
  {id:'lf-0047', category:"science",
   options:["Pencil","Chalk","Crayon","Charcoal"],
   clues:["The grey stuff in my middle was first dug from one valley in England.",
          "Shepherds used that same grey stone to mark their sheep before I existed.",
          "There has never been any lead in me, whatever people call my middle.",
          "You sharpen me, and there is often a little eraser on my other end."]},
  {id:'lf-0048', category:"history",
   options:["Traffic light","Street lamp","Stop sign","Post box"],
   clues:["The first of me stood in London in 1868, before cars filled the streets.",
          "A person had to stand beside me and work me by hand with a lever.",
          "My middle colour was added later, to give everyone a moment to get ready.",
          "I hang above the road, and red means stop while green means go."]},
  {id:'lf-0049', category:"history",
   options:["Jigsaw puzzle","Globe","Dominoes","Playing cards"],
   clues:["I began as a teaching tool, cut around the edges of countries on a map.",
          "A London mapmaker glued his map onto wood and sawed me apart in the 1760s.",
          "For my first hundred years I was made of wood, and only later of cardboard.",
          "I come in a box in hundreds of pieces and you build the picture on the lid."]},
  {id:'lf-0050', category:"history",
   options:["Tin can","Glass jar","Barrel","Cardboard box"],
   clues:["I kept food safe for nearly fifty years before a tool existed to open me.",
          "Early instructions printed on me suggested a hammer and a chisel.",
          "Explorers and sailors carried me so their food would last a whole voyage.",
          "You keep soup and beans in me in the cupboard, and I am made of metal."]},
  {id:'lf-0051', category:"history",
   options:["Bicycle","Kick scooter","Wheelbarrow","Roller skates"],
   clues:["My first version in 1817 had no pedals at all and you pushed yourself along.",
          "For a while my front wheel was enormous and my back wheel was tiny.",
          "Adding a chain to my back wheel is what finally made me safe to ride.",
          "I have two wheels, handlebars and pedals, and you ring my little bell."]},
  {id:'lf-0052', category:"words",
   options:["Denim","Corduroy","Linen","Velvet"],
   clues:["My name is really a French town name that English speakers wore down.",
          "The word for my most famous trousers comes from the Italian city of Genoa.",
          "Only one set of my threads is dyed blue, which is why I fade so pale.",
          "Almost everybody owns a pair of blue jeans made of me."]},
  {id:'lf-0053', category:"food",
   options:["Ketchup","Mustard","Mayonnaise","Soy sauce"],
   clues:["I began in Asia as a salty sauce made from fish, with no tomato in me.",
          "English cooks made me from mushrooms and walnuts for over a hundred years.",
          "Tomatoes only joined me in America in the early 1800s and then took over.",
          "You squeeze me from a bottle onto fries, and I am red, thick and sweet."]},
  {id:'lf-0054', category:"food",
   options:["Chocolate","Coffee","Vanilla","Tea"],
   clues:["My pods grow straight out of the trunk of the tree, not from the branches.",
          "For most of my long history I was a bitter frothy drink and never a bar.",
          "My beans must be fermented and then roasted before I taste like anything.",
          "I come in a bar of squares, I am sweet and brown, and I melt in a pocket."]},
  {id:'lf-0055', category:"plants",
   options:["Carrot","Potato","Beetroot","Parsnip"],
   clues:["For most of my history I was purple or yellow, and orange came much later.",
          "Dutch growers made my orange kind common about four hundred years ago.",
          "The part you eat is a root, and my leafy tops open into white lace flowers.",
          "I am the long orange root that goes in a stew, and rabbits love me."]},
  {id:'lf-0056', category:"plants",
   options:["Vanilla","Cinnamon","Saffron","Almond"],
   clues:["Away from my home country almost none of me forms without a helping hand.",
          "I am the pod of a climbing orchid, and a boy on an island found the trick.",
          "My name comes from a Spanish word meaning little pod, and I grow long.",
          "I am the flavour of plain white ice cream."]},
  {id:'lf-0057', category:"science",
   options:["Lightning","Thunder","Hail","Wind"],
   clues:["I heat the air I pass through to about five times hotter than the surface of the sun.",
          "The bang you hear afterwards is just the air clapping shut behind me.",
          "Somewhere on earth I flash dozens of times every single second.",
          "I am the bright flash in a storm, and thunder is the sound I make."]},
  {id:'lf-0058', category:"space",
   options:["Aurora","Comet","Meteor shower","Moonlight"],
   clues:["I appear when a wind from the sun crashes into the very top of your air.",
          "Oxygen high above gives me my green, and I glow best near the poles.",
          "I hang as rippling curtains of light across a clear winter night sky.",
          "People in the far north call me the Northern Lights."]},
  {id:'lf-0059', category:"science",
   options:["Hurricane","Tornado","Blizzard","Sandstorm"],
   clues:["I am handed a name from a list months before I even exist.",
          "I can only be born over warm ocean water, and I fade once I cross land.",
          "At my very centre there is a circle of calm sky called the eye.",
          "I am the giant spinning storm that comes off the warm ocean and gets a name."]},
  {id:'lf-0060', category:"science",
   options:["Snowflake","Hailstone","Frost","Raindrop"],
   clues:["I begin to grow around a speck of dust far too small for you to see.",
          "The way my water freezes gives me six sides every single time.",
          "No two of me have ever been found to match, though nobody has checked them all.",
          "I am one tiny crystal of snow that lands on your glove in winter."]},
  {id:'lf-0061', category:"science",
   options:["Volcano","Geyser","Earthquake","Hot spring"],
   clues:["I build a mountain out of the very thing that tears me open.",
          "Most of me is hidden, running in long chains along the floor of the sea.",
          "Melted rock rises from deep below and pours out of my top as lava.",
          "I am the mountain that erupts with lava, ash and smoke."]},
  {id:'lf-0062', category:"science",
   options:["Tide","Wave","Ocean current","Whirlpool"],
   clues:["I am the sea keeping time with something far out in space.",
          "Twice a day I climb the beach and twice a day I slide back down.",
          "In the Bay of Fundy I move the water up and down by over fifteen metres.",
          "I am the daily rise and fall of the sea, pulled along by the moon."]},
  {id:'lf-0063', category:"science",
   options:["Diamond","Ruby","Emerald","Pearl"],
   clues:["I am made of the same single element as the soft grey stuff inside a pencil.",
          "Great pressure deep underground squeezed me together a very long time ago.",
          "Nothing in nature can scratch me except another one of me.",
          "I am the clear sparkling gemstone, the hardest one there is."]},
  {id:'lf-0064', category:"world",
   options:["The Pacific Ocean","The Atlantic Ocean","The Indian Ocean","The Arctic Ocean"],
   clues:["My deepest trench could swallow the tallest mountain with a mile to spare.",
          "A ring of volcanoes traces my edge, and people call it the Ring of Fire.",
          "I am wider than the moon and I cover about a third of the planet.",
          "I am the largest ocean, lying between Asia and the Americas."]},
  {id:'lf-0065', category:"space",
   options:["Meteor","Comet","Satellite","Planet"],
   clues:["I am often no bigger than a grain of sand, and I never reach the ground.",
          "I glow because the air in front of me is squashed and heated as I rush in.",
          "Every August a whole shower of us seems to pour out of one patch of sky.",
          "People call me a shooting star and make a wish when I streak past."]},
  {id:'lf-0066', category:"world",
   options:["Glacier","Iceberg","Avalanche","Frozen lake"],
   clues:["I am a river so slow that you could watch me all day and see nothing move.",
          "I grind valleys into the shape of a letter U and leave heaps of rubble behind.",
          "Snow piled up for centuries packed me into ice so dense that it looks blue.",
          "I am the huge sheet of ice that creeps slowly down a mountain valley."]},
  {id:'lf-0067', category:"plants",
   options:["Peanut","Almond","Walnut","Pecan"],
   clues:["I am not a nut at all, and I am a closer cousin of peas and beans.",
          "When my flowers fade, the stalks bend down and push themselves into the soil.",
          "My crop finishes ripening completely underground, so the whole plant is pulled up.",
          "I come two to a wrinkly shell, and I am the classic butter for a sandwich."]},
  {id:'lf-0068', category:"food",
   options:["Coffee","Tea","Chicory","Barley"],
   clues:["What you grind is the seed of my small red fruit, which looks a lot like a cherry.",
          "Ethiopia is my homeland, and a legend credits a goat herder with noticing me.",
          "I am picked and shipped while still green, and I only turn brown in a hot drum.",
          "I am the dark drink people brew from ground beans in the morning."]},
  {id:'lf-0069', category:"food",
   options:["Cashew","Almond","Pistachio","Hazelnut"],
   clues:["I hang from the bottom of a bright fruit, growing outside it instead of within.",
          "My shell holds an oil so fierce that nobody ever sells me still inside it.",
          "I curl like a small comma, and there is only ever one of me in a shell.",
          "I am the creamy nut curved like a crescent moon, popular in a stir fry."]},
  {id:'lf-0070', category:"food",
   options:["Tea","Coffee","Mint","Chamomile"],
   clues:["I am an evergreen bush that would grow into a tree if pickers ever let me.",
          "The finest picking takes only my bud and the two leaves just below it.",
          "Black, green and white are not different plants but different ways of treating me.",
          "I am the drink that comes as black or green in a little bag, taken with milk in Britain."]},
  {id:'lf-0071', category:"plants",
   options:["Pineapple","Coconut","Banana","Mango"],
   clues:["I take almost two years to grow, and my plant makes just one of me.",
          "I grow low to the ground on a spiky plant, and never in a tree.",
          "I am really dozens of small fruits fused together, which is why my skin is tiled.",
          "I am the golden tropical fruit with a spiky skin and a crown of leaves."]},
  {id:'lf-0072', category:"food",
   options:["Potato","Carrot","Turnip","Parsnip"],
   clues:["I came out of the Andes and reached Europe in the 1500s.",
          "Peru still grows thousands of my varieties, in colours no shop near you sells.",
          "I am not a root but a swollen stem, which is why I grow eyes and can sprout.",
          "Ireland is famous for growing me, and I turn into mash, chips and crisps."]},
  {id:'lf-0073', category:"plants",
   options:["Cinnamon","Nutmeg","Clove","Ginger"],
   clues:["I am neither seed nor leaf but the inner bark of a small evergreen tree.",
          "Sri Lanka has been my most famous home for many hundreds of years.",
          "My bark curls into tight quills as it dries, and those are the sticks you buy.",
          "I am the warm brown spice dusted on toast and swirled into buns."]},
  {id:'lf-0074', category:"food",
   options:["Maple syrup","Honey","Molasses","Caramel"],
   clues:["I begin as a clear watery sap that tastes barely sweet at all.",
          "It takes about forty buckets of that sap to boil down into one of me.",
          "I only run when the nights freeze and the days thaw, so my season is short.",
          "Canada makes most of me, and I am poured warm over pancakes."]},
  {id:'lf-0075', category:"food",
   options:["Cranberry","Blueberry","Raspberry","Strawberry"],
   clues:["Farmers flood my fields with water when it is time to gather me.",
          "I float, because there are four little pockets of air inside me.",
          "I grow on low trailing vines in sandy bogs, mostly in North America.",
          "I am the small tart red berry served as a sauce beside the holiday turkey."]},
  {id:'lf-0076', category:"food",
   options:["Corn","Wheat","Rice","Barley"],
   clues:["My wild ancestor was a scruffy Mexican grass with only a few hard seeds.",
          "Every silky thread at my top leads to one seed, and each needs its own pollen.",
          "I cannot scatter my own seeds any more, so I depend on people to plant me.",
          "I grow on a cob wrapped in green leaves, and I pop when heated in a pan."]},
  {id:'lf-0077', category:"animals",
   options:["Monarch butterfly","Honeybee","Moth","Ladybird"],
   clues:["The trip home in spring takes three or four generations of my family to finish.",
          "Millions of us cover the same few fir trees in one Mexican forest every winter.",
          "My caterpillars will eat the leaves of one plant only, and that plant is milkweed.",
          "I am the big orange butterfly with black veins that everybody knows."]},
  {id:'lf-0078', category:"animals",
   options:["Dragonfly","Butterfly","Wasp","Beetle"],
   clues:["I spend years underwater as a hunter before I ever see the sky.",
          "I can beat each of my four wings on its own, so I fly sideways and even backwards.",
          "My eyes wrap almost the whole way round my head, so very little escapes me.",
          "I am the long thin insect with four clear wings that darts over the pond in summer."]},
  {id:'lf-0079', category:"animals",
   options:["Ant","Termite","Wasp","Beetle"],
   clues:["Some of my sisters hang from the ceiling all their lives as living jars of syrup.",
          "I leave a scent trail behind me so the rest of the nest can follow me to the food.",
          "My whole nest is one queen and her daughters, and it can number in the millions.",
          "I march in a line across the kitchen floor towards a dropped crumb."]},
  {id:'lf-0080', category:"animals",
   options:["Earthworm","Caterpillar","Millipede","Centipede"],
   clues:["A famous naturalist gave me the last book he ever wrote, after forty years of watching.",
          "I have no eyes at all, and yet I feel light on my skin and hurry away from it.",
          "I swallow soil, pass it through myself and leave little curls of it on the lawn.",
          "I am the long pink wriggler that gardeners are glad to find in the soil."]},
  {id:'lf-0081', category:"animals",
   options:["Jellyfish","Sea anemone","Squid","Sea sponge"],
   clues:["One kind of me can wind back to a younger form and begin its life all over again.",
          "I have no brain, no bones and no heart, and my kind has drifted here for ages.",
          "I am about ninety five parts water in a hundred, so I all but vanish on the sand.",
          "I drift through the sea like a clear bell trailing long tentacles behind me."]},
  {id:'lf-0082', category:"animals",
   options:["Seahorse","Shrimp","Clownfish","Pufferfish"],
   clues:["I hold tight to a stem all night so the current cannot carry me off while I rest.",
          "I am a fish, and yet I have no scales and I swim upright instead of flat.",
          "In my family it is the father who carries the eggs in a pouch until they hatch.",
          "I am the little sea creature shaped like a horse's head, tail curled round seaweed."]},
  {id:'lf-0083', category:"animals",
   options:["Horseshoe crab","Hermit crab","Lobster","Sea turtle"],
   clues:["I was crawling up these beaches long before the first dinosaur ever appeared.",
          "I am no crab at all, and my nearest relatives are the spiders and the scorpions.",
          "On the big spring tides I come ashore in great crowds to lay eggs in the sand.",
          "I am the sea creature shaped like a helmet, with a long stiff spike for a tail."]},
  {id:'lf-0084', category:"animals",
   options:["Firefly","Moth","Cricket","Mayfly"],
   clues:["I make light with almost no heat, which no lamp in your house can manage.",
          "Each of my kinds blinks its own pattern, like a code flickering over the grass.",
          "I am a beetle, and my young glow quietly in the grass long before they can fly.",
          "Children catch me in jars on summer nights and call me a lightning bug."]},
  {id:'lf-0085', category:"animals",
   options:["Cicada","Cricket","Grasshopper","Locust"],
   clues:["Some of my families count out thirteen or seventeen years before they come up.",
          "I spend all of those years underground, drinking sap from the roots of trees.",
          "I am among the loudest insects alive, and a chorus of us can drown out a mower.",
          "I am the loud summer insect that leaves an empty brown shell on the tree bark."]},
  {id:'lf-0086', category:"animals",
   options:["Starfish","Sea urchin","Sea anemone","Sea cucumber"],
   clues:["There is a small eye at the tip of every one of my arms.",
          "I have no brain and no blood, and I walk on hundreds of tiny feet run by water.",
          "Lose an arm and I grow it back, and in some of my kind that arm grows a new me.",
          "I am the five armed creature you find in a rock pool, often orange or purple."]},
  {id:'lf-0087', category:"animals",
   options:["Woodlouse","Beetle","Earwig","Ant"],
   clues:["I am a relative of the crab that came out onto the land and never went back.",
          "I still breathe through gills, so I have to stay somewhere damp or I dry out.",
          "I chew up dead leaves and old wood and hand the garden back its soil.",
          "I am the small grey creature under the flowerpot that rolls into a ball."]},
  {id:'lf-0088', category:"animals",
   options:["Spider","Silkworm","Scorpion","Cricket"],
   clues:["My thread leaves me as a liquid and turns solid only as I draw it out.",
          "For its weight my line is tougher than steel, and I often eat it to spin a new one.",
          "I have eight legs, so whatever anybody calls me I am no insect.",
          "I spin a round web in the corner of the shed and wait in the middle of it."]},
  {id:'lf-0089', category:"history",
   options:["Statue of Liberty","The Angel of the North","The Little Mermaid statue","The Colossus of Rhodes"],
   clues:["I arrived at my home in more than three hundred pieces packed inside wooden crates.",
          "I began the colour of shiny new copper, and the weather slowly turned me green.",
          "I was a gift from France, and my inner frame was designed by Gustave Eiffel.",
          "I stand on an island in New York Harbour, holding a torch above my spiked crown."]},
  {id:'lf-0090', category:"world",
   options:["The Golden Gate Bridge","The Brooklyn Bridge","The Sydney Harbour Bridge","Tower Bridge"],
   clues:["My famous colour started life as nothing more than a coat of primer.",
          "A crew of painters works on me all year round, touching up where the salt air bites.",
          "My two towers hold cables spun from wire that would circle the earth three times.",
          "I am the orange suspension bridge at the mouth of San Francisco Bay."]},
  {id:'lf-0091', category:"history",
   options:["Stonehenge","The Ring of Brodgar","The Carnac stones","Newgrange"],
   clues:["My earliest ring was a circle of dug pits, centuries older than my great stones.",
          "My smaller stones came from hills in Wales, a very long way from where I stand.",
          "On the longest day of the year the sun rises in line with my main avenue.",
          "I am the ring of huge standing stones on a plain in southern England."]},
  {id:'lf-0092', category:"history",
   options:["The Empire State Building","The Flatiron Building","The Space Needle","The Gateway Arch"],
   clues:["I went up in about four hundred days, and in a good week I gained four floors.",
          "My spire was meant to be a mooring mast for airships, and that plan never worked.",
          "My top floors change colour at night to mark holidays and big events.",
          "I am the New York skyscraper a giant ape climbs in an old black and white film."]},
  {id:'lf-0093', category:"world",
   options:["The Hoover Dam","The Three Gorges Dam","The Aswan High Dam","The Grand Coulee Dam"],
   clues:["My concrete would have taken a century to cool, so chilled pipes were laid inside me.",
          "The water I hold back forms one of the largest lakes ever made by people.",
          "I curve upstream, so the harder the water pushes the tighter I grip the canyon walls.",
          "I am the huge concrete dam on the Colorado River between Nevada and Arizona."]},
  {id:'lf-0094', category:"world",
   options:["The Panama Canal","The Suez Canal","The Erie Canal","The Corinth Canal"],
   clues:["Ships do not sail through me so much as climb me, and then climb back down again.",
          "A lake made by damming a river forms the long middle stretch of my route.",
          "I cut about thirteen thousand kilometres off a voyage around South America.",
          "I am the canal cut across Panama that joins the Atlantic to the Pacific."]},
  {id:'lf-0095', category:"history",
   options:["The Colosseum","The Pantheon","The Parthenon","The Arena of Nimes"],
   clues:["A cloth roof was hauled over my crowd by sailors who knew how to work the ropes.",
          "Under my floor ran a maze of tunnels with wooden lifts worked by hand.",
          "Fifty thousand people could leave me quickly through eighty numbered arches.",
          "I am the great oval stone arena standing in the middle of Rome."]},
  {id:'lf-0096', category:"history",
   options:["The Great Sphinx","The Colossi of Memnon","The Easter Island statues","The Lion of Lucerne"],
   clues:["I was carved out of one ridge of soft rock, and the quarry left behind is my yard.",
          "Sand buried me up to my shoulders for centuries, which is why so much of me survives.",
          "I have the body of a lion and a human face, and I look east towards the sunrise.",
          "I am the giant stone lion with a human head that sits beside the pyramids at Giza."]},
  {id:'lf-0097', category:"world",
   options:["The Taj Mahal","The Red Fort","The Amber Fort","The Gateway of India"],
   clues:["My four corner towers lean very slightly outward, and that was done on purpose.",
          "I look pink at dawn, white at midday and pale gold under a full moon.",
          "I am white marble, perfectly symmetrical, with a long still pool laid out before me.",
          "I am the famous white domed monument at Agra in northern India."]},
  {id:'lf-0098', category:"history",
   options:["Fork","Spoon","Knife","Tongs"],
   clues:["I came west from Byzantium to Italy and was mocked as a vanity for hundreds of years.",
          "My earliest table version had only two straight points, so food rolled off me.",
          "A gentle curve and four points were added later so I could scoop as well as spear.",
          "I sit to the left of the plate and you twirl spaghetti round me."]},
  {id:'lf-0099', category:"history",
   options:["Pressure cooker","Kettle","Slow cooker","Steamer"],
   clues:["I was built in a laboratory in 1679, and the man who built me later drew a steam engine.",
          "By trapping steam inside, I push my contents well above the normal boiling point.",
          "That extra heat is why beans that want two hours are ready in twenty minutes.",
          "I lock my lid tight, hiss on the stove, and cook a stew in a fraction of the usual time."]},
  {id:'lf-0100', category:"science",
   options:["Vacuum flask","Cool box","Lunch box","Kettle"],
   clues:["A Scottish chemist built me to hold gases so cold that they had turned to liquid.",
          "My trick is nothing at all, an empty gap between two walls that heat cannot cross.",
          "My inner wall is silvered like a mirror so warmth is bounced back where it came from.",
          "I am the flask that keeps soup hot until lunchtime and cold drinks cold all day."]},
  {id:'lf-0101', category:"science",
   options:["Aluminium foil","Cling film","Baking paper","Greaseproof paper"],
   clues:["What I am made of was once rarer in pure form than gold, though the ground is full of it.",
          "Only cheap electricity freed it from its rock, and after that I could be rolled out thin.",
          "One of my faces is shiny and one is dull, purely because I am rolled two sheets at a time.",
          "You tear me off a roll to wrap leftovers, and I crumple into a silver ball."]},
  {id:'lf-0102', category:"science",
   options:["Sponge","Tea towel","Oven glove","Chopping board"],
   clues:["The first of my kind were gathered off the sea floor, and every one had been alive.",
          "Divers off Greece and Florida harvested me for centuries before factories made me from foam.",
          "The holes all through me are the whole point, because they hold many times my weight in water.",
          "You squeeze me out at the sink and wipe the plates with me."]},
  {id:'lf-0103', category:"science",
   options:["Nonstick pan","Cast iron pan","Copper pan","Clay pot"],
   clues:["In 1938 a chemist opened a gas cylinder, found it empty, and scraped out a white powder.",
          "A French engineer put that powder on his fishing tackle years before it ever met a pan.",
          "The same stuff coats pipes and the tape that seals them, because almost nothing sticks to it.",
          "An egg slides straight off me, and you are told never to scrape me with a metal fork."]},
  {id:'lf-0104', category:"history",
   options:["Dishwasher","Washing machine","Sink","Kettle"],
   clues:["An American woman patented me in 1886, and hotels bought me long before homes did.",
          "She showed me at the great Chicago fair of 1893 and carried off its top award.",
          "She built me because washing up by hand kept chipping her good china.",
          "You stack the plates in my racks, drop in a tablet, and I spray them clean with hot water."]},
  {id:'lf-0105', category:"history",
   options:["Coffee filter","Tea bag","Paper napkin","Cake case"],
   clues:["In 1908 a woman in Dresden punched holes in a brass pot and tore up a school blotter.",
          "She was tired of grit in the cup, so she took out a patent on my paper the same year.",
          "I am folded into a cone, and hot water drips through me while the grounds stay behind.",
          "You spoon ground beans into me in the machine, and the dark drink drips into the jug."]},
  {id:'lf-0106', category:"world",
   options:["Chopsticks","Tongs","Skewers","Toothpicks"],
   clues:["I began at the cooking fire as a pair of twigs for reaching into a very hot pot.",
          "Food was cut small in the kitchen instead of at the table, which is why I was enough.",
          "About a fifth of the people on earth pick up their dinner with me every day.",
          "I am the pair of slim sticks you hold in one hand to eat rice and noodles."]},
  {id:'lf-0107', category:"history",
   options:["Mortar and pestle","Rolling pin","Sieve","Blender"],
   clues:["I am older than farming, and I was grinding wild seeds long before anyone planted one.",
          "Cooks and painters both leaned on me, because grinding is grinding whatever you are making.",
          "I come as two pieces, a heavy stone bowl and a stubby stone tool that fits your hand.",
          "You crush garlic and spices in my bowl by pounding and grinding them."]},
  {id:'lf-0108', category:"space",
   options:["Jupiter","Saturn","Neptune","Uranus"],
   clues:["Four little specks circling me showed people that not everything goes round the earth.",
          "A storm broader than the whole earth has been spinning on my face for centuries.",
          "I am a giant ball of gas with no surface, and I turn right round in about ten hours.",
          "I am the largest planet in the solar system, and I have a Great Red Spot."]},
  {id:'lf-0109', category:"space",
   options:["Mars","Venus","Mercury","Jupiter"],
   clues:["Two small lumpy moons circle me, and the nearer one creeps closer every year.",
          "The tallest volcano known anywhere stands on me, more than twice the height of Everest.",
          "Robots named Curiosity and Perseverance have driven across my dusty ground.",
          "I am the red planet, fourth from the sun and the next one out from earth."]},
  {id:'lf-0110', category:"space",
   options:["Venus","Mercury","Mars","Jupiter"],
   clues:["My day lasts longer than my year, and I spin the opposite way to my neighbours.",
          "Thick yellow clouds hide my ground so well that radar was needed to map it.",
          "I am the hottest planet of all, hot enough to melt lead on my surface.",
          "I am the second planet from the sun, and the brightest one in your evening sky."]},
  {id:'lf-0111', category:"space",
   options:["Neptune","Uranus","Saturn","Jupiter"],
   clues:["Sums worked out on paper found me before any telescope was pointed my way.",
          "The fastest winds ever measured anywhere in the solar system blow across me.",
          "I take about one hundred and sixty five years to travel once round the sun.",
          "I am the deep blue planet, the eighth and farthest one from the sun."]},
  {id:'lf-0112', category:"space",
   options:["Halley's Comet","Comet Hale Bopp","The Perseid meteor shower","The Andromeda Galaxy"],
   clues:["An astronomer worked out that three visits in old records had all been me.",
          "I am stitched into a famous embroidery of 1066, with people below pointing up at me.",
          "I come back into view about every seventy six years, and I am due again in 2061.",
          "I am the most famous comet of all, and I carry the name of Edmond Halley."]},
  {id:'lf-0113', category:"space",
   options:["The Sun","Sirius","Betelgeuse","Jupiter"],
   clues:["I lose about four million tonnes of myself every second and hardly notice.",
          "I turn hydrogen into helium in my middle, and that is where all my heat comes from.",
          "My light takes a little over eight minutes to cross the gap and reach you.",
          "I am the star at the centre of the solar system, and I light up your day."]},
  {id:'lf-0114', category:"space",
   options:["The Milky Way","The Andromeda Galaxy","The Orion Nebula","The Big Dipper"],
   clues:["You will never see all of me, because you are standing inside me.",
          "My name comes from a Latin phrase that means road of milk.",
          "I am a great spiral of hundreds of billions of stars, and the sun is only one.",
          "I am the pale band of light across a dark sky, the galaxy that holds your sun."]},
  {id:'lf-0115', category:"space",
   options:["The International Space Station","The Hubble Space Telescope","A weather satellite","A high flying aeroplane"],
   clues:["I have not had a single empty night since the year 2000.",
          "My crew see sixteen sunrises and sixteen sunsets in every twenty four hours.",
          "Many countries built me in pieces, and every piece was bolted on in orbit.",
          "I am the crewed space station circling earth, and you can watch me pass overhead."]},
  {id:'lf-0116', category:"space",
   options:["A total solar eclipse","A lunar eclipse","A new moon","A meteor shower"],
   clues:["I happen only because two very different circles look the same size from where you stand.",
          "While I last the birds go quiet, the air cools, and bright stars come out at midday.",
          "I sweep a narrow shadow across the ground, and you must stand in it to see me.",
          "I am what happens when the moon covers the sun completely and the day goes dark."]},
  {id:'lf-0117', category:"space",
   options:["Titan","Europa","Ganymede","Io"],
   clues:["Rain falls on me, rivers run and lakes fill, and not one drop of it is water.",
          "I am the only moon anywhere with a thick atmosphere, and mine is thicker than yours.",
          "A probe called Huygens parachuted down and landed on my orange surface in 2005.",
          "I am the largest moon of Saturn, and I am wider than the planet Mercury."]},
  {id:'lf-0118', category:"space",
   options:["Pluto","Ceres","Eris","Neptune"],
   clues:["A girl of eleven in Oxford suggested the name I was given in 1930.",
          "My path is so slanted and stretched that for twenty years I came nearer than Neptune.",
          "A craft called New Horizons flew past me in 2015 and found a huge pale heart shape.",
          "I was counted as the ninth planet until 2006, when I became a dwarf planet."]},
  {id:'lf-0119', category:"plants",
   options:["Sunflower","Dahlia","Marigold","Daisy"],
   clues:["My seeds are packed in two sets of spirals that count out a famous number pattern.",
          "My young head swings from east to west each day and turns back again at night.",
          "Whole fields of me are grown so that oil can be pressed from my striped seeds.",
          "I am the tall yellow flower with a big brown middle, and my seeds are a snack."]},
  {id:'lf-0120', category:"plants",
   options:["Oak","Birch","Maple","Chestnut"],
   clues:["More kinds of insect live on me than on any other tree in Britain.",
          "Jays and squirrels bury my seeds and forget enough of them to plant new woods.",
          "My leaves have wavy lobed edges, and my timber built ships and great hall roofs.",
          "My seed is called an acorn and it sits in a little cup."]},
  {id:'lf-0121', category:"plants",
   options:["Dandelion","Daisy","Clover","Buttercup"],
   clues:["I can set seed with no pollen at all, so a whole meadow of me may be one family.",
          "My name comes from French words meaning tooth of a lion, after my jagged leaves.",
          "My bright yellow head closes and reopens as a silver globe of tiny parachutes.",
          "Children blow my grey seed clock to tell the time, and I pop up in every lawn."]},
  {id:'lf-0122', category:"plants",
   options:["Venus flytrap","Pitcher plant","Sundew","Cactus"],
   clues:["A hair inside me must be brushed twice within half a minute before I will move.",
          "Every wild one of me grows in one small patch of boggy ground in the Carolinas.",
          "The soil where I live is so poor that I take my nitrogen from insects instead.",
          "My two hinged leaves have spiky edges and snap shut on a fly in a blink."]},
  {id:'lf-0123', category:"plants",
   options:["Tulip","Daffodil","Hyacinth","Snowdrop"],
   clues:["I came to the Low Countries from the mountains of Central Asia and Turkey.",
          "My name is thought to come from an old word for a turban, after my cup shape.",
          "I am planted as a bulb in autumn and sleep in the cold ground until spring.",
          "Dutch fields grow me in bright stripes, and my flower is a smooth cup of six petals."]},
  {id:'lf-0124', category:"plants",
   options:["Baobab","Acacia","Banyan","Joshua tree"],
   clues:["I can hold thousands of litres of water inside my trunk to last out a dry season.",
          "People say I look planted upside down, with my roots waving about in the air.",
          "Hollow ones of me have served as shelters and even as tiny shops in Africa.",
          "I am the huge African tree with a fat barrel trunk and short bare branches on top."]},
  {id:'lf-0125', category:"science",
   options:["Yeast","Mould","Pollen","Algae"],
   clues:["I was the first living thing with a cell nucleus to have my whole gene map written out.",
          "I am a fungus made of a single cell, and billions of me fit on one spoon.",
          "I feed on sugar and give off a gas, which is exactly what makes dough rise.",
          "Bakers stir me into bread dough to make it puff up, and I come in little packets."]},
  {id:'lf-0126', category:"food",
   options:["Truffle","Ginger","Turnip","Chestnut"],
   clues:["I never break the surface, so I depend on animals digging me up to spread me about.",
          "I live tangled in the roots of oak and hazel trees, and I trade food with them.",
          "Chefs shave me in paper thin slivers over pasta and eggs for my strong smell.",
          "I am the lumpy fungus that grows underground, and dogs are trained to sniff me out."]},
  {id:'lf-0127', category:"food",
   options:["Rice","Wheat","Oats","Millet"],
   clues:["More than half the people on earth eat me at very nearly every meal.",
          "I am the one major grain that is happy to grow with my feet in standing water.",
          "Terraces cut into Asian hillsides hold the shallow ponds where I am planted.",
          "I am the small white grain boiled in a pot and served with curry and stir fries."]},
  {id:'lf-0128', category:"food",
   options:["Banana","Mango","Papaya","Coconut"],
   clues:["The plant I grow on is a giant herb whose trunk is only tightly rolled leaves.",
          "Nearly every one of me sold is a clone taken as a cutting, with no seeds inside.",
          "I grow in big hands that point upward, and my plant is cut down after one crop.",
          "I am the long yellow fruit you peel, and cartoon monkeys are always drawn with me."]},
  {id:'lf-0129', category:"history",
   options:["Piano","Harpsichord","Clavichord","Xylophone"],
   clues:["A Florentine maker built me around 1700 to solve one stubborn keyboard problem.",
          "Inside me, felt covered hammers strike more than two hundred tightly stretched strings.",
          "My full name means soft and loud, because how hard you press decides which you get.",
          "I have 88 black and white keys, and I often stand against the wall of a room."]},
  {id:'lf-0130', category:"history",
   options:["Violin","Trumpet","Harp","Banjo"],
   clues:["The town of Cremona in Italy produced the most treasured of me over three centuries ago.",
          "My bow is strung with horsehair, and rosin makes it sticky enough to grip my strings.",
          "I have four strings and no frets, so your finger alone decides where the note falls.",
          "I am the small wooden instrument you tuck under your chin and play with a bow."]},
  {id:'lf-0131', category:"world",
   options:["Bagpipes","Accordion","Harmonica","Flute"],
   clues:["I have only one volume, which is loud, and no player has ever made me whisper.",
          "I store air in a bag under the arm, so my sound never pauses for a breath.",
          "One of my pipes carries the tune while the others hum one long steady note.",
          "I am the loud Scottish instrument played by a piper in a kilt at a parade."]},
  {id:'lf-0132', category:"science",
   options:["Theremin","Synthesizer","Accordion","Harmonica"],
   clues:["A Russian scientist stumbled on me while building a device that senses things nearby.",
          "One upright aerial on me sets the pitch and a looped one sets how loud I am.",
          "Old films borrowed my wavering voice whenever something strange drifted onto the screen.",
          "You play me by waving your hands in the air beside me, never touching me at all."]},
  {id:'lf-0133', category:"world",
   options:["Steel drum","Xylophone","Marimba","Gong"],
   clues:["Carnival bands on a Caribbean island built me out of something thrown away.",
          "My whole playing face is hammered into dents, and every dent sounds a different note.",
          "I started life as an empty oil barrel before hammers turned me into an instrument.",
          "I am the shiny metal drum from Trinidad, played with two rubber tipped sticks."]},
  {id:'lf-0134', category:"world",
   options:["Didgeridoo","Trombone","Bassoon","Tuba"],
   clues:["Termites hollowed me out long before any person thought to pick me up.",
          "Players breathe in while still blowing out, so my note can run on for minutes.",
          "I am a long hollow wooden tube with no holes, no keys and no strings at all.",
          "I am the Aboriginal Australian instrument that makes a long low droning buzz."]},
  {id:'lf-0135', category:"history",
   options:["Harmonica","Kazoo","Recorder","Whistle"],
   clues:["I was the first musical instrument played in space, carried up in secret in 1965.",
          "Rows of thin metal reeds inside me quiver as your breath rushes past them.",
          "I give one note when you breathe out and a different one when you breathe in.",
          "I am the small metal instrument with a row of holes, also called a mouth organ."]},
  {id:'lf-0136', category:"history",
   options:["Flute","Clarinet","Oboe","Trumpet"],
   clues:["The oldest instruments ever dug up are versions of me, made forty thousand years ago.",
          "My note appears when your breath splits on a sharp edge, and I carry no reed at all.",
          "I am counted with the woodwinds even though I am usually made of silvery metal.",
          "I am the slim instrument you hold out sideways and blow across, not into."]},
  {id:'lf-0137', category:"world",
   options:["Ukulele","Banjo","Mandolin","Guitar"],
   clues:["Sailors from Portugal carried my little ancestor to a chain of islands in 1879.",
          "My name in the island language is usually said to mean jumping flea.",
          "I have four soft nylon strings and I fit easily into a backpack.",
          "I am the tiny four string guitar from Hawaii, strummed on the beach."]},
  {id:'lf-0138', category:"science",
   options:["Echo","Thunder","Whisper","Wind"],
   clues:["I am always late, always fainter, and I never say anything of my own.",
          "Sound covers about a third of a kilometre each second, so my delay measures distance.",
          "A cliff face or an empty hall throws the sound straight back to whoever made it.",
          "Shout hello across a valley and I answer you with hello a moment later."]},
  {id:'lf-0139', category:"science",
   options:["Metronome","Tuning fork","Stopwatch","Music stand"],
   clues:["I hold no tune of my own, yet a practice room feels unfinished without me.",
          "A weight slides up and down my swinging arm, and moving it changes my speed.",
          "Composers print a number at the top of the page to say how fast to set me.",
          "I am the little pyramid that sits on the piano and ticks to keep your time."]},
  {id:'lf-0140', category:"history",
   options:["Saxophone","Clarinet","Trumpet","Trombone"],
   clues:["A Belgian maker gave me his own family name in the 1840s.",
          "I am built of brass and yet I am counted among the woodwinds.",
          "A single reed on my mouthpiece buzzes when you blow, exactly as a clarinet does.",
          "I am the curved golden horn with an upturned bell, famous in jazz bands."]}
];
