/* MOTHLIGHT FACT BANK
   Regenerate or extend with this exact prompt, then hand-audit every entry:

   "Write N true-or-false facts for a family party quiz. Rules: each fact is
   one complete sentence under 110 characters, checkable against a mainstream
   encyclopedia, general audience, no politics, no religion, no bodies, no
   violence, no brand names, no dash characters of any kind. Aim for half
   true and half false, and make several facts things people confidently get
   wrong. For each, output: the sentence, true or false, and a short source
   name (one recognizable reference). Output as a JS array of objects with
   fields id, text, answer, source, category. Categories: animals, space,
   food, history, science, world, words, plants."

   AUDIT RULE: a fact nobody verified does not ship. Check each answer field
   against the named source before committing.
   Bank at 2026-08-08: 659 entries. Grown overnight by a generate then
   adversarially fact check pipeline; every entry a checker could not confirm
   was thrown away rather than softened. */
window.MOTHLIGHT_BANK = [
  {id:'ml-0001', text:"A group of moths can be called an eclipse.", answer:true,  source:"Merriam-Webster", category:"animals"},
  {id:'ml-0002', text:"Sealed honey can stay good to eat for thousands of years.", answer:true,  source:"Smithsonian", category:"food"},
  {id:'ml-0003', text:"Bananas grow on trees.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0004', text:"The Eiffel Tower is a little taller in summer than in winter.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0005', text:"Goldfish can only remember things for three seconds.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0006', text:"An octopus has three hearts.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0007', text:"Lightning never strikes the same place twice.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0008', text:"Venus is the hottest planet in our solar system.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0009', text:"Humans and giraffes have the same number of neck bones.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0010', text:"Bats are blind.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0011', text:"A day on Venus is longer than a year on Venus.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0012', text:"The Great Wall of China is easily visible from the Moon.", answer:false, source:"NASA", category:"world"},
  {id:'ml-0013', text:"Strawberries wear their seeds on the outside.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0014', text:"Peanuts are a kind of nut.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0015', text:"A cucumber is a fruit.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0016', text:"Sound travels faster in water than in air.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0017', text:"Humans use only ten percent of their brains.", answer:false, source:"Scientific American", category:"science"},
  {id:'ml-0018', text:"Hot water can freeze faster than cold water in some conditions.", answer:true,  source:"Scientific American", category:"science"},
  {id:'ml-0019', text:"Camels store water in their humps.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0020', text:"A shrimp's heart is in its head.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0021', text:"Sunflowers always face the sun, even at night.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0022', text:"Wombats have cube shaped droppings.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0023', text:"Mount Everest is the closest point on Earth to space.", answer:false, source:"NASA", category:"world"},
  {id:'ml-0024', text:"Scotland's national animal is the unicorn.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0025', text:"Bulls charge because the color red makes them angry.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0026', text:"Sea otters sometimes hold hands while they sleep.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0027', text:"An ostrich hides by burying its head in the sand.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0028', text:"Hot lightning bolts are about five times hotter than the surface of the sun.", answer:true,  source:"NOAA", category:"science"},
  {id:'ml-0029', text:"Dogs can only see in black and white.", answer:false, source:"American Kennel Club", category:"animals"},
  {id:'ml-0030', text:"A blue whale's heart is about the size of a small car.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0031', text:"Glass is a slow moving liquid.", answer:false, source:"Scientific American", category:"science"},
  {id:'ml-0032', text:"Kangaroos cannot easily hop backwards.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0033', text:"Chameleons change color mainly to match their background.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0034', text:"There are more trees on Earth than stars in the Milky Way.", answer:true,  source:"Nature", category:"plants"},
  {id:'ml-0035', text:"You lose most of your body heat through your head.", answer:false, source:"Scientific American", category:"science"},
  {id:'ml-0036', text:"Octopuses have blue blood.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0037', text:"Mice love cheese more than any other food.", answer:false, source:"BBC Science Focus", category:"animals"},
  {id:'ml-0038', text:"Hippos produce a reddish fluid that works like sunscreen.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0039', text:"Toads give you warts if you touch them.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0040', text:"The Sahara is the largest hot desert in the world.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0041', text:"Antarctica is the largest desert on Earth.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0042', text:"Sharks must stop swimming to sleep.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0043', text:"Sharks as a group are older than the rings of Saturn may be.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0044', text:"Water conducts electricity when perfectly pure.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0045', text:"Cows have best friends and get stressed when separated.", answer:true,  source:"BBC Science Focus", category:"animals"},
  {id:'ml-0046', text:"The tongue has separate zones for sweet, salty, sour and bitter.", answer:false, source:"Scientific American", category:"science"},
  {id:'ml-0047', text:"Butterflies can taste with their feet.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0048', text:"Penguins live at the North Pole.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0049', text:"A snail can sleep for about three years at a stretch.", answer:true,  source:"BBC Science Focus", category:"animals"},
  {id:'ml-0050', text:"Coffee beans are beans.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0051', text:"Pineapples take about two years to grow one fruit.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0052', text:"Tomatoes were once widely feared as poisonous in Europe.", answer:true,  source:"Smithsonian", category:"food"},
  {id:'ml-0053', text:"Carrots were originally mostly purple.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0054', text:"Eating carrots gives you night vision.", answer:false, source:"Smithsonian", category:"food"},
  {id:'ml-0055', text:"White chocolate contains no cocoa solids.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0056', text:"Adding salt makes water boil at a lower temperature.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0057', text:"Apples float because they are about one quarter air.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0058', text:"Swallowed chewing gum stays in your stomach for seven years.", answer:false, source:"Mayo Clinic", category:"food"},
  {id:'ml-0059', text:"Cashews grow attached to the bottom of a fruit called a cashew apple.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0060', text:"Ketchup was once sold as a medicine in the United States.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0061', text:"The Moon has a permanently dark side that never sees the sun.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0062', text:"Jupiter is the fastest spinning planet in our solar system.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0063', text:"A year on Mercury lasts only 88 Earth days.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0064', text:"The sun is yellow.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0065', text:"Saturn would float in a big enough bathtub of water.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0066', text:"There is a permanent hexagon shaped storm on Saturn.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0067', text:"Mars appears red because of rust on its surface.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0068', text:"The asteroid belt is so crowded that spacecraft must dodge rocks.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0069', text:"Footprints left on the Moon could last for millions of years.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0070', text:"Sound carries wonderfully through the vacuum of space.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0071', text:"Neutron stars can spin hundreds of times per second.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0072', text:"The Moon causes the ocean tides.", answer:true,  source:"NOAA", category:"space"},
  {id:'ml-0073', text:"Mercury is the hottest planet because it is closest to the sun.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0074', text:"Olympus Mons on Mars is the tallest volcano in the solar system.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0075', text:"A comet's tail always points away from the sun.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0076', text:"The Roman Colosseum could reportedly be flooded for mock sea battles.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0077', text:"Napoleon was unusually short for a Frenchman of his time.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0078', text:"Oxford University is older than the Aztec Empire.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0079', text:"Vikings wore horned helmets into battle.", answer:false, source:"Smithsonian", category:"history"},
  {id:'ml-0080', text:"Cleopatra lived closer in time to the Moon landing than to the Great Pyramid.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0081', text:"The shortest war on record lasted less than an hour.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0082', text:"Medieval people believed the Earth was flat.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0083', text:"Woolly mammoths were still alive while the pyramids were being built.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0084', text:"The Hundred Years War lasted exactly one hundred years.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0085', text:"Ancient Romans used urine as a laundry cleaner.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0086', text:"The Leaning Tower of Pisa began leaning while it was still being built.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0087', text:"Albert Einstein failed math at school.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0088', text:"The first computer programmer is widely considered to be a woman.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0089', text:"The Statue of Liberty was a gift from France.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0090', text:"Salem's convicted witches were burned at the stake.", answer:false, source:"Smithsonian", category:"history"},
  {id:'ml-0091', text:"Australia is wider than the Moon.", answer:true,  source:"NASA", category:"world"},
  {id:'ml-0092', text:"Africa is the continent with the most countries.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0093', text:"The Amazon is agreed by everyone to be the longest river on Earth.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0094', text:"Canada has more lakes than the rest of the world combined.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0095', text:"Russia spans eleven time zones.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0096', text:"The capital of Australia is Sydney.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0097', text:"Istanbul sits on two continents at once.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0098', text:"The Dead Sea is actually a lake.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0099', text:"Iceland is mostly covered in ice.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0100', text:"The Pacific Ocean is larger than all the land on Earth combined.", answer:true,  source:"NOAA", category:"world"},
  {id:'ml-0101', text:"More people live in Tokyo than in all of Canada.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0102', text:"The Nile flows from south to north.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0103', text:"Mount Kilimanjaro is in South America.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0104', text:"There is a town in Norway where the sun does not set for weeks in summer.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0105', text:"The Netherlands is the world's biggest exporter of tulips.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0106', text:"Venice is built on about 120 small islands.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0107', text:"The Great Barrier Reef is the largest living structure on Earth.", answer:true,  source:"National Geographic", category:"world"},
  {id:'ml-0108', text:"All deserts are hot.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0109', text:"The little word set has one of the longest entries in the dictionary.", answer:true,  source:"Oxford English Dictionary", category:"words"},
  {id:'ml-0110', text:"The word queue sounds exactly the same with its last four letters removed.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0111', text:"A pangram is a sentence that uses every letter of the alphabet.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0112', text:"The opposite of nocturnal is infernal.", answer:false, source:"Merriam-Webster", category:"words"},
  {id:'ml-0113', text:"A group of crows can be called a murder.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0114', text:"A baby rabbit is called a cub.", answer:false, source:"Merriam-Webster", category:"words"},
  {id:'ml-0115', text:"The dot over a lowercase i has a name: the tittle.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0116', text:"A word that reads the same forwards and backwards is a pantomime.", answer:false, source:"Merriam-Webster", category:"words"},
  {id:'ml-0117', text:"The fear of long words has an ironically long scientific style name.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0118', text:"A baby goat is called a kid.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0119', text:"The plural of octopus can correctly be octopuses.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0120', text:"A group of owls can be called a parliament.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0121', text:"Buttercups are safe to eat in salads.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0122', text:"Bamboo can grow more than half a meter in a single day.", answer:true,  source:"Guinness World Records", category:"plants"},
  {id:'ml-0123', text:"A sunflower head is actually hundreds of tiny flowers.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0124', text:"Trees get most of their mass from the soil they grow in.", answer:false, source:"Scientific American", category:"plants"},
  {id:'ml-0125', text:"Some trees can send nutrients to their neighbors through root networks.", answer:true,  source:"Nature", category:"plants"},
  {id:'ml-0126', text:"Cacti store water mainly in their spines.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0127', text:"The largest single flower in the world can be about a meter across.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0128', text:"Grass is a flowering plant.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0129', text:"Venus flytraps count the touches before they snap shut.", answer:true,  source:"Nature", category:"plants"},
  {id:'ml-0130', text:"Mushrooms are plants.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0131', text:"An oak tree can drop thousands of acorns in a single autumn.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0132', text:"Moss only ever grows on the north side of trees.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0133', text:"Some seeds need fire to sprout.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0134', text:"A tomato is legally a vegetable in the United States for tariff purposes.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0135', text:"Broccoli, kale and cabbage are all the same species of plant.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0136', text:"Rice is grown underwater because it cannot survive in dry soil.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0137', text:"Vanilla flavoring comes from a kind of orchid.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0138', text:"A pumpkin is a berry to a botanist.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0139', text:"Four leaf clovers do not exist in nature.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0140', text:"The oldest known living tree is thousands of years old.", answer:true,  source:"Guinness World Records", category:"plants"},
  {id:'ml-0141', text:"Your fingernails keep growing for weeks after you die.", answer:false, source:"BBC Science Focus", category:"science"},
  {id:'ml-0142', text:"Bones are about five times stronger than steel of the same weight.", answer:true,  source:"BBC Science Focus", category:"science"},
  {id:'ml-0143', text:"Cracking your knuckles causes arthritis.", answer:false, source:"Harvard Health", category:"science"},
  {id:'ml-0144', text:"You are a little taller in the morning than at night.", answer:true,  source:"BBC Science Focus", category:"science"},
  {id:'ml-0145', text:"Humans have exactly five senses.", answer:false, source:"Scientific American", category:"science"},
  {id:'ml-0146', text:"Hair and fingernails are made of the same protein.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0147', text:"Reading in dim light permanently damages your eyes.", answer:false, source:"Harvard Health", category:"science"},
  {id:'ml-0148', text:"Your stomach gets a new lining every few days.", answer:true,  source:"BBC Science Focus", category:"science"},
  {id:'ml-0149', text:"Shaving makes hair grow back thicker.", answer:false, source:"Mayo Clinic", category:"science"},
  {id:'ml-0150', text:"The human body contains enough iron to make a small nail.", answer:true,  source:"BBC Science Focus", category:"science"},
  {id:'ml-0151', text:"Rainbows are full circles when seen from high enough up.", answer:true,  source:"NOAA", category:"science"},
  {id:'ml-0152', text:"Thunder is the sound of clouds crashing into each other.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0153', text:"No two snowflakes have ever been proven identical.", answer:true,  source:"NOAA", category:"science"},
  {id:'ml-0154', text:"A rainbow at night is impossible.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0155', text:"Raindrops are shaped like teardrops as they fall.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0156', text:"Hurricanes spin in opposite directions north and south of the equator.", answer:true,  source:"NOAA", category:"science"},
  {id:'ml-0157', text:"It can be too cold to snow heavily.", answer:true,  source:"NOAA", category:"science"},
  {id:'ml-0158', text:"Deserts never get snow.", answer:false, source:"NOAA", category:"world"},
  {id:'ml-0159', text:"A single bolt of lightning could toast a hundred thousand slices of bread.", answer:true,  source:"BBC Science Focus", category:"science"},
  {id:'ml-0160', text:"Wind is caused by the Earth spinning under the air.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0161', text:"Honeybees tell each other where flowers are by dancing.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0162', text:"A bee visits about fifty to a hundred flowers in one trip.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0163', text:"Wasps can make honey just like bees.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0164', text:"Ants never sleep.", answer:false, source:"BBC Science Focus", category:"animals"},
  {id:'ml-0165', text:"Some ants farm aphids the way people farm cattle.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0166', text:"Dragonflies are among the most successful hunters in the animal kingdom.", answer:true,  source:"BBC Science Focus", category:"animals"},
  {id:'ml-0167', text:"Fireflies make light with almost no heat.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0168', text:"A ladybug's spots tell you its age in years.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0169', text:"Crickets chirp faster in warmer weather.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0170', text:"Spiders are insects.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0171', text:"A moth's feathery antennae can smell a mate from miles away.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0172', text:"Earthworms have five heart like organs.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0173', text:"Butterflies live for only one day.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0174', text:"Snails have thousands of tiny teeth.", answer:true,  source:"BBC Science Focus", category:"animals"},
  {id:'ml-0175', text:"Daddy longlegs are the most venomous spiders but cannot bite humans.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0176', text:"Cats spend roughly two thirds of their lives asleep.", answer:true,  source:"BBC Science Focus", category:"animals"},
  {id:'ml-0177', text:"A cat's purr always means it is happy.", answer:false, source:"BBC Science Focus", category:"animals"},
  {id:'ml-0178', text:"Adult cats mostly meow at humans, not at other cats.", answer:true,  source:"BBC Science Focus", category:"animals"},
  {id:'ml-0179', text:"Dogs sweat mainly through their tongues.", answer:false, source:"American Kennel Club", category:"animals"},
  {id:'ml-0180', text:"A dog's nose print is unique, a bit like a fingerprint.", answer:true,  source:"American Kennel Club", category:"animals"},
  {id:'ml-0181', text:"Goats have rectangular pupils.", answer:true,  source:"BBC Science Focus", category:"animals"},
  {id:'ml-0182', text:"Owls can turn their heads in a complete circle.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0183', text:"Flamingos are pink because of what they eat.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0184', text:"A duck's quack does not echo.", answer:false, source:"BBC Science Focus", category:"animals"},
  {id:'ml-0185', text:"Crows can recognize and remember individual human faces.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0186', text:"Hummingbirds are the only birds that can fly backwards.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0187', text:"Touching a baby bird makes its mother abandon it.", answer:false, source:"Audubon", category:"animals"},
  {id:'ml-0188', text:"Some birds nap while flying.", answer:true,  source:"Nature", category:"animals"},
  {id:'ml-0189', text:"Penguins propose to each other with pebbles.", answer:false, source:"Audubon", category:"animals"},
  {id:'ml-0190', text:"An albatross can glide for hours barely flapping its wings.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0191', text:"Elephants are the only mammals that cannot jump.", answer:false, source:"BBC Science Focus", category:"animals"},
  {id:'ml-0192', text:"Elephants can hear storms rumbling from far away through their feet.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0193', text:"A rhino's horn is made of hair like keratin, not bone.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0194', text:"Giraffes sleep standing up for eight hours a night.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0195', text:"Polar bear skin is black under all that white fur.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0196', text:"Sloths can hold their breath longer than dolphins.", answer:true,  source:"BBC Science Focus", category:"animals"},
  {id:'ml-0197', text:"Beavers eat fish they catch in their dams.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0198', text:"Squirrels help plant thousands of trees by forgetting where they buried acorns.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0199', text:"Porcupines can shoot their quills at attackers.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0200', text:"A raccoon's front paws become more sensitive underwater.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0201', text:"Bread rises because yeast releases carbon dioxide.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0202', text:"Popcorn pops because of a tiny drop of water inside each kernel.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0203', text:"Lemons float and limes sink.", answer:true,  source:"BBC Science Focus", category:"food"},
  {id:'ml-0204', text:"Adding oil to pasta water keeps the noodles from sticking together.", answer:false, source:"BBC Science Focus", category:"food"},
  {id:'ml-0205', text:"A watermelon is over ninety percent water.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0206', text:"Spicy heat from chili is a taste detected by the tongue's taste buds.", answer:false, source:"Scientific American", category:"food"},
  {id:'ml-0207', text:"Onions make you cry because they release a gas that stings your eyes.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0208', text:"Brown eggs are more nutritious than white eggs.", answer:false, source:"Mayo Clinic", category:"food"},
  {id:'ml-0209', text:"Wasabi served outside Japan is usually dyed horseradish.", answer:true,  source:"BBC", category:"food"},
  {id:'ml-0210', text:"Microwaves cook food from the inside out.", answer:false, source:"BBC Science Focus", category:"food"},
  {id:'ml-0211', text:"Pound cake is named for a recipe using a pound each of four ingredients.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0212', text:"Almonds are seeds, not true nuts.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0213', text:"Searing meat seals in all of its juices.", answer:false, source:"BBC Science Focus", category:"food"},
  {id:'ml-0214', text:"Maple syrup starts as a nearly flavorless watery sap.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0215', text:"Raw cookie dough is risky mostly because of the flour, not just the egg.", answer:true,  source:"FDA", category:"food"},
  {id:'ml-0216', text:"The fortune cookie was invented in ancient China.", answer:false, source:"Smithsonian", category:"food"},
  {id:'ml-0217', text:"Pearls dissolve in vinegar.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0218', text:"Bubble wrap was first invented as wallpaper.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0219', text:"The microwave oven was inspired by a melted chocolate bar in a pocket.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0220', text:"Velcro was inspired by burrs sticking to a dog's fur.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0221', text:"The first parachute jump happened before the first airplane flew.", answer:true,  source:"Guinness World Records", category:"history"},
  {id:'ml-0222', text:"Umbrellas were invented in London to deal with the rain.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0223', text:"The first alarm clock could only ring at four in the morning.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0224', text:"Chess was invented in Russia.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0225', text:"The ice cream cone became popular at a World's Fair.", answer:true,  source:"Smithsonian", category:"food"},
  {id:'ml-0226', text:"Roller skates made their debut by crashing through a ballroom mirror.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0227', text:"The zipper took decades to become a common part of clothing.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0228', text:"Paper was invented in ancient Egypt.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0229', text:"A jiffy is a real unit of time in physics.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0230', text:"An inchworm is exactly one inch long.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0231', text:"Hot air balloons flew passengers before the invention of the bicycle.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0232', text:"The Wright brothers' first flight was shorter than a jumbo jet's wingspan.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0233', text:"Goldfish turn pale if kept in the dark.", answer:true,  source:"BBC Science Focus", category:"animals"},
  {id:'ml-0234', text:"Toilets flush in opposite directions north and south of the equator.", answer:false, source:"Scientific American", category:"science"},
  {id:'ml-0235', text:"A bolt of lightning is thinner than most people imagine, only a few centimeters.", answer:true,  source:"NOAA", category:"science"},
  {id:'ml-0236', text:"Bananas are naturally a little radioactive.", answer:true,  source:"BBC Science Focus", category:"food"},
  {id:'ml-0237', text:"Sugar makes children hyperactive.", answer:false, source:"Mayo Clinic", category:"food"},
  {id:'ml-0238', text:"You can see the curvature of the Earth from a passenger plane window.", answer:false, source:"Scientific American", category:"science"},
  {id:'ml-0239', text:"Wait an hour after eating before swimming or you will get dangerous cramps.", answer:false, source:"Mayo Clinic", category:"science"},
  {id:'ml-0240', text:"The tea bag was popularized by accident when samples were dunked whole.", answer:true,  source:"BBC", category:"history"},
  {id:'ml-0241', text:"Koala fingerprints are so much like human ones that they can be confused under a microscope.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0242', text:"Rabbits are rodents, just like mice and squirrels.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0243', text:"Hippos are more closely related to whales than they are to horses.", answer:true,  source:"Smithsonian", category:"animals"},
  {id:'ml-0244', text:"Hyenas belong to the dog family.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0245', text:"Female reindeer grow antlers, which makes them unusual among deer.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0246', text:"A lizard that regrows its tail grows a new set of tail bones inside it.", answer:false, source:"Smithsonian", category:"animals"},
  {id:'ml-0247', text:"Despite the long argument about it, the giant panda really is a bear.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0248', text:"Venomous and poisonous are two words for exactly the same thing.", answer:false, source:"Merriam-Webster", category:"animals"},
  {id:'ml-0249', text:"Algae grows in the fur of wild sloths and gives them a greenish tinge.", answer:true,  source:"Smithsonian", category:"animals"},
  {id:'ml-0250', text:"Snakes feel slimy to the touch.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0251', text:"Newborn kangaroos are only about the size of a jellybean.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0252', text:"Every snake in the world hatches out of an egg.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0253', text:"Komodo dragons have produced healthy young with no male involved.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0254', text:"Wolves howl at the full moon.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0255', text:"Crocodiles cannot stick their tongues out.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0256', text:"A cobra sways in its basket because it enjoys the charmer's music.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0257', text:"Not a single turtle or tortoise alive today has teeth.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0258', text:"Bears sleep so deeply all winter that nothing can wake them until spring.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0259', text:"Because a turtle shell is part of the skeleton, no turtle can crawl out of it.", answer:true,  source:"Smithsonian", category:"animals"},
  {id:'ml-0260', text:"Any armadillo can curl itself into a tight ball for protection.", answer:false, source:"Smithsonian", category:"animals"},
  {id:'ml-0261', text:"Snakes have no eyelids, so they sleep with their eyes open.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0262', text:"One dog year is always exactly seven human years.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0263', text:"Whether alligator eggs become male or female depends on how warm the nest is.", answer:true,  source:"Smithsonian", category:"animals"},
  {id:'ml-0264', text:"Cats always land on their feet, whatever the fall.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0265', text:"The saltwater crocodile is the largest living reptile on Earth.", answer:true,  source:"Guinness World Records", category:"animals"},
  {id:'ml-0266', text:"Elephants are terrified of mice.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0267', text:"The okapi, striped like a zebra, is the giraffe's closest living relative.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0268', text:"A saucer of cow milk is good for a grown cat.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0269', text:"Most wolf packs are simply a family group led by the two parents.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0270', text:"Cold blooded animals such as lizards have blood that is always cold.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0271', text:"Pigs roll in mud to cool off because they can barely sweat.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0272', text:"Rattlesnakes gain one new rattle segment for every year of life.", answer:false, source:"Smithsonian", category:"animals"},
  {id:'ml-0273', text:"In a hunting dive the peregrine falcon is the fastest animal on the planet.", answer:true,  source:"Guinness World Records", category:"animals"},
  {id:'ml-0274', text:"Every spider builds a web to catch its food.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0275', text:"An ostrich lays the largest egg of any bird alive today.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0276', text:"A centipede always has exactly one hundred legs.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0277', text:"Arctic terns fly from the Arctic to Antarctica and back every year.", answer:true,  source:"Audubon", category:"animals"},
  {id:'ml-0278', text:"Crickets make their chirping sound by rubbing their back legs together.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0279', text:"Modern birds are the surviving branch of the dinosaur family tree.", answer:true,  source:"Smithsonian", category:"animals"},
  {id:'ml-0280', text:"Fireflies belong to the fly family.", answer:false, source:"Smithsonian", category:"animals"},
  {id:'ml-0281', text:"That fierce eagle screech in movies is usually a hawk call on the soundtrack.", answer:true,  source:"Audubon", category:"animals"},
  {id:'ml-0282', text:"Adult clothes moths are the ones nibbling holes in a wool sweater.", answer:false, source:"Smithsonian", category:"animals"},
  {id:'ml-0283', text:"Many monarch butterflies travel thousands of miles to the same Mexican forests each winter.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0284', text:"Scientists still cannot explain how a bumblebee manages to fly.", answer:false, source:"National Geographic", category:"animals"},
  {id:'ml-0285', text:"Some cicadas spend seventeen years underground before they climb up to sing.", answer:true,  source:"Smithsonian", category:"animals"},
  {id:'ml-0286', text:"Geese fly in a V mainly so the leader can keep an eye on the whole flock.", answer:false, source:"Audubon", category:"animals"},
  {id:'ml-0287', text:"The dust that rubs off a butterfly wing is really thousands of tiny scales.", answer:true,  source:"Smithsonian", category:"animals"},
  {id:'ml-0288', text:"Owls cannot see a thing in daylight.", answer:false, source:"Audubon", category:"animals"},
  {id:'ml-0289', text:"A honeybee has five eyes, two large ones and three small ones on top of its head.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0290', text:"Tiny hummingbirds ride on the backs of geese to cross long distances.", answer:false, source:"Audubon", category:"animals"},
  {id:'ml-0291', text:"Some dung beetles keep rolling in a straight line by steering off the Milky Way.", answer:true,  source:"National Geographic", category:"animals"},
  {id:'ml-0292', text:"Uncooked rice thrown at weddings is harmful to the birds that eat it.", answer:false, source:"Audubon", category:"animals"},
  {id:'ml-0293', text:"Most spiders look at the world through eight eyes.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0294', text:"Coral is a slow growing underwater plant.", answer:false, source:"NOAA", category:"animals"},
  {id:'ml-0295', text:"Horseshoe crabs are closer relatives of spiders than of crabs.", answer:true,  source:"Smithsonian", category:"animals"},
  {id:'ml-0296', text:"A whale's spout is seawater that it swallowed and then blasts back out.", answer:false, source:"NOAA", category:"animals"},
  {id:'ml-0297', text:"Among seahorses it is the father who carries the eggs in a pouch until the young emerge.", answer:true,  source:"NOAA", category:"animals"},
  {id:'ml-0298', text:"Sea turtles pull their heads inside their shells when they feel threatened.", answer:false, source:"NOAA", category:"animals"},
  {id:'ml-0299', text:"The whale shark is the biggest fish in the ocean and it feeds mostly on plankton.", answer:true,  source:"NOAA", category:"animals"},
  {id:'ml-0300', text:"Honeybees are native to North America.", answer:false, source:"Smithsonian", category:"animals"},
  {id:'ml-0301', text:"Despite the name, the electric eel is not a true eel.", answer:true,  source:"Britannica", category:"animals"},
  {id:'ml-0302', text:"Locusts and grasshoppers are two completely unrelated insects.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0303', text:"Killer whales are really the largest members of the dolphin family.", answer:true,  source:"NOAA", category:"animals"},
  {id:'ml-0304', text:"Like other fish, sharks have a skeleton made of bone.", answer:false, source:"NOAA", category:"animals"},
  {id:'ml-0305', text:"A manatee's closest living relatives include the elephant.", answer:true,  source:"NOAA", category:"animals"},
  {id:'ml-0306', text:"Termites are simply a pale kind of ant.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0307', text:"The largest eyes ever measured on any animal belong to a deep sea squid.", answer:true,  source:"Smithsonian", category:"animals"},
  {id:'ml-0308', text:"Barnacles are close relatives of clams and oysters.", answer:false, source:"Britannica", category:"animals"},
  {id:'ml-0309', text:"Saturn has more confirmed moons than Jupiter.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0310', text:"Every planet in the solar system has at least one moon.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0311', text:"More than 99 percent of all the mass in the solar system sits inside the Sun.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0312', text:"Saturn is the only planet in our solar system with rings.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0313', text:"Neptune's place in the sky was predicted with mathematics before anyone found it.", answer:true,  source:"Britannica", category:"space"},
  {id:'ml-0314', text:"Phases of the Moon happen when Earth's shadow falls across it.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0315', text:"Pluto has not finished a single lap around the Sun since its discovery in 1930.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0316', text:"Seasons happen because Earth's orbit carries it closer to and further from the Sun.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0317', text:"Ganymede, a moon of Jupiter, is bigger than the planet Mercury.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0318', text:"The asteroid belt is the shattered wreckage of a planet that blew apart.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0319', text:"Titan is the only moon known to have a thick atmosphere.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0320', text:"One day the Sun will explode as a supernova.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0321', text:"Earth passes closest to the Sun in early January.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0322', text:"Jupiter came very close to igniting and becoming a second sun.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0323', text:"The Sun's outer atmosphere is far hotter than the bright surface we see.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0324', text:"There is no gravity at all on the Moon.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0325', text:"Uranus is tipped so far over that it rolls around the Sun almost on its side.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0326', text:"At its closest approach Mars looks as large as the full Moon in our sky.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0327', text:"Venus spins in the opposite direction to almost every other planet.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0328', text:"A solar eclipse happens every month at the new moon.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0329', text:"Earth's Moon is wider than the dwarf planet Pluto.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0330', text:"Sunspots are holes in the surface of the Sun.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0331', text:"Winds on Neptune blow faster than on any other planet.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0332', text:"Heat from the Sun comes from burning fuel the way a campfire burns wood.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0333', text:"Alone among the planets, Earth is not named after a Greek or Roman god.", answer:true,  source:"Britannica", category:"space"},
  {id:'ml-0334', text:"Meteor and meteorite are two words for exactly the same thing.", answer:false, source:"Merriam-Webster", category:"space"},
  {id:'ml-0335', text:"Io, one of Jupiter's moons, is the most volcanically active world we know of.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0336', text:"Midday on the Moon comes with a bright blue sky overhead.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0337', text:"Saturn's rings are made almost entirely of water ice.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0338', text:"Comets grow their tails because they catch fire in the Sun's heat.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0339', text:"Sunsets photographed on Mars glow blue around the Sun.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0340', text:"Jupiter's Great Red Spot is a crater left by a giant impact.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0341', text:"Our Sun holds about 99.8 percent of all the mass in the solar system.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0342', text:"Astronauts float aboard the space station because there is no gravity that high up.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0343', text:"The Andromeda galaxy appears several times wider in our sky than the full Moon.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0344', text:"Polaris, the North Star, is the brightest star in the night sky.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0345', text:"Apollo crews left mirrors on the Moon that scientists still bounce lasers off today.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0346', text:"Constellations are groups of stars that sit close together out in space.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0347', text:"Alan Shepard swung a makeshift golf club on the Moon during Apollo 14.", answer:true,  source:"Smithsonian", category:"space"},
  {id:'ml-0348', text:"NASA spent millions inventing a pen for space while cosmonauts just used pencils.", answer:false, source:"Smithsonian", category:"space"},
  {id:'ml-0349', text:"On Apollo 15 a hammer and a feather were dropped together and landed at the same moment.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0350', text:"Cosmic expansion is carrying Andromeda and the Milky Way farther apart every year.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0351', text:"Voyager 1 is the most distant human made object ever sent out from Earth.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0352', text:"Of the four fundamental forces of nature, gravity is by far the strongest.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0353', text:"Both Voyager probes carry a gold plated record of music and greetings from Earth.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0354', text:"Earth has gravity because the planet spins on its axis.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0355', text:"Crews aboard the International Space Station see about 16 sunrises every day.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0356', text:"John Glenn was the first American to fly into space.", answer:false, source:"Smithsonian", category:"space"},
  {id:'ml-0357', text:"Each year the Moon drifts roughly four centimeters farther away from Earth.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0358', text:"Red stars burn hotter than blue stars.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0359', text:"Valentina Tereshkova became the first woman to fly in space in 1963.", answer:true,  source:"Britannica", category:"space"},
  {id:'ml-0360', text:"Swapping our Sun for a black hole of the same mass would pull Earth straight in.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0361', text:"A supermassive black hole sits at the center of our galaxy.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0362', text:"Ever since the Big Bang the expansion of the universe has been slowing down.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0363', text:"Astronomers released the first image of a black hole's shadow in 2019.", answer:true,  source:"Britannica", category:"space"},
  {id:'ml-0364', text:"The Space Shuttle carried astronauts to the Moon and back many times.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0365', text:"It takes our Sun more than 200 million years to circle the galaxy once.", answer:true,  source:"Britannica", category:"space"},
  {id:'ml-0366', text:"Our solar system sits right at the center of the Milky Way.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0367', text:"Stars twinkle in the night sky while planets usually shine with a steadier light.", answer:true,  source:"Britannica", category:"space"},
  {id:'ml-0368', text:"A flag left standing on the Moon ripples in a light lunar breeze.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0369', text:"Proxima Centauri, the nearest star to our Sun, sits about four light years away.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0370', text:"A meteorite is scorching hot to the touch the moment it lands.", answer:false, source:"Smithsonian", category:"space"},
  {id:'ml-0371', text:"Sputnik 1 became the first artificial satellite when it launched in 1957.", answer:true,  source:"Britannica", category:"space"},
  {id:'ml-0372', text:"Galaxies are spread so far apart that they never collide with one another.", answer:false, source:"NASA", category:"space"},
  {id:'ml-0373', text:"Unlike Hubble, the James Webb Space Telescope orbits the Sun rather than the Earth.", answer:true,  source:"NASA", category:"space"},
  {id:'ml-0374', text:"Stars shine because they are burning fuel much like a campfire does.", answer:false, source:"Britannica", category:"space"},
  {id:'ml-0375', text:"Nutmeg and mace are two different spices taken from the same fruit.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0376', text:"Potatoes were first grown in Ireland and travelled from there to the rest of the world.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0377', text:"Black, white and green peppercorns all come from the same vine.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0378', text:"Long before anyone crossed the ocean, tomatoes grew wild all over Italy.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0379', text:"Cacao pods grow straight out of the trunk and thick branches of the tree.", answer:true,  source:"Kew Gardens", category:"food"},
  {id:'ml-0380', text:"Kiwifruit is a plant native to New Zealand.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0381', text:"After a peanut flower fades, its stalk pushes into the soil and the pod ripens underground.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0382', text:"Madagascar is the original home of the vanilla plant.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0383', text:"Ginger is an underground stem rather than a root.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0384', text:"Black tea and green tea come from two different plants.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0385', text:"Fig flowers bloom hidden inside the fruit instead of out in the open.", answer:true,  source:"Kew Gardens", category:"food"},
  {id:'ml-0386', text:"Green olives and black olives grow on separate trees.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0387', text:"A coconut is not a nut but a drupe, the same kind of fruit as a peach.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0388', text:"Cinnamon is ground from the dried roots of a small shrub.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0389', text:"Brazil nuts grow packed inside a heavy woody pod like segments in an orange.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0390', text:"Saffron is gathered from the seeds of a wild grass.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0391', text:"Apple trees are grafted because a seed from a good apple rarely grows the same fruit.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0392', text:"Cranberries grow underwater in flooded ponds.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0393', text:"Apples, pears and strawberries all belong to the rose family.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0394', text:"Almond trees are closer relatives of walnut trees than of peach trees.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0395', text:"Corn was bred by early farmers from a wild Mexican grass called teosinte.", answer:true,  source:"Smithsonian", category:"food"},
  {id:'ml-0396', text:"Chili peppers and black pepper come from plants in the same family.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0397', text:"Sweet potatoes and potatoes sit in completely different plant families.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0398', text:"The fruit we call an orange took its name from the color orange.", answer:false, source:"Oxford English Dictionary", category:"food"},
  {id:'ml-0399', text:"Buckwheat is not a wheat at all and is closer kin to rhubarb.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0400', text:"Welsh rarebit is a slow cooked rabbit dish from Wales.", answer:false, source:"Merriam-Webster", category:"food"},
  {id:'ml-0401', text:"Despite the name, a Jerusalem artichoke is a sunflower tuber from North America.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0402', text:"Most of the world's sugar is made from beets rather than cane.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0403', text:"English speakers named the pineapple for its likeness to a pine cone.", answer:true,  source:"Oxford English Dictionary", category:"food"},
  {id:'ml-0404', text:"Chocolate was first enjoyed as a solid sweet bar rather than as a drink.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0405', text:"Nutmeg and mace are two different spices that come from the same fruit.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0406', text:"Marco Polo brought pasta home to Italy after tasting noodles in China.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0407', text:"Allspice is a single dried berry and not a blend of several spices.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0408', text:"Caesar salad was named after Julius Caesar.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0409', text:"Black, white and green peppercorns all come from one plant.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0410', text:"Barbecue comes from an old French phrase meaning from beard to tail.", answer:false, source:"Merriam-Webster", category:"food"},
  {id:'ml-0411', text:"Cloves are flower buds that get picked and dried before they open.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0412', text:"The seeds are the hottest part of a chili pepper.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0413', text:"Vanilla orchids grown for their pods are pollinated by hand, one flower at a time.", answer:true,  source:"Kew Gardens", category:"food"},
  {id:'ml-0415', text:"Chocolate was a drink for centuries before anyone pressed it into a bar.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0416', text:"Ginger and turmeric belong to completely unrelated plant families.", answer:false, source:"Kew Gardens", category:"food"},
  {id:'ml-0417', text:"Most brown sugar in shops is white sugar with molasses added back in.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0418', text:"Instant coffee is just coffee beans ground into a very fine powder.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0419', text:"Baking powder is mostly baking soda mixed with a dry acid.", answer:true,  source:"Merriam-Webster", category:"food"},
  {id:'ml-0420', text:"Swiss style cheese gets its holes from air trapped during pressing.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0421', text:"Marshmallow sweets were first made from the root of a plant called marsh mallow.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0422', text:"Food heated in a microwave comes out slightly radioactive.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0423', text:"Fresh pineapple keeps a gelatin dessert from setting because of an enzyme in the fruit.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0424', text:"Cilantro and coriander come from two different plants.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0425', text:"Tonic water glows under ultraviolet light because of the quinine in it.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0426', text:"Wild rice is ordinary rice that has been left unpolished.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0427', text:"Bananas give off a gas that ripens other fruit sitting next to them.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0428', text:"Buckwheat is a variety of wheat grown for its darker flour.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0429', text:"Potatoes are swollen underground stems rather than roots.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0430', text:"Ice cream is churned so tightly that it holds almost no air.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0431', text:"Danes know the pastry we call a Danish by a name meaning Viennese bread.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0432', text:"Anything dropped on the floor stays clean if you pick it up within five seconds.", answer:false, source:"Smithsonian", category:"food"},
  {id:'ml-0433', text:"Sushi is a word for seasoned rice rather than for raw fish.", answer:true,  source:"Merriam-Webster", category:"food"},
  {id:'ml-0434', text:"Deep orange yolks are a sign that an egg is fresher than one with a pale yolk.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0435', text:"One shot of espresso carries less caffeine than a full mug of drip coffee.", answer:true,  source:"Britannica", category:"food"},
  {id:'ml-0436', text:"Cinnamon is scraped from the roots of the cinnamon tree.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0437', text:"Work on Stonehenge began before the Great Pyramid of Giza was built.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0438', text:"A bar of chocolate contains no caffeine at all.", answer:false, source:"Britannica", category:"food"},
  {id:'ml-0439', text:"Ancient Greek marble statues were once painted in bright colors.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0440', text:"Vast armies of slaves built the pyramids of Egypt.", answer:false, source:"Smithsonian", category:"history"},
  {id:'ml-0441', text:"Roman builders warmed rooms by running hot air through spaces beneath the floor.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0442', text:"Roman soldiers were handed their wages in salt.", answer:false, source:"Merriam-Webster", category:"history"},
  {id:'ml-0443', text:"Rome's Pantheon still holds the record for the largest unreinforced concrete dome.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0444', text:"A marathon race was one of the events at the ancient Olympic Games.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0445', text:"Winners at the ancient Olympics were crowned with a wreath of wild olive.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0446', text:"Marco Polo brought the first noodles back to Italy from China.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0447', text:"Sumerian scribes pressed their writing into soft clay tablets with a cut reed.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0448', text:"Cleopatra came from a long line of native Egyptian rulers.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0449', text:"Counting by sixties in ancient Mesopotamia is why an hour still has sixty minutes.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0450', text:"The Colossus of Rhodes stood astride the harbor with ships passing underneath.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0451', text:"A Greek device called the Antikythera mechanism used bronze gears to track the sky.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0452', text:"Roman numerals include a symbol for zero.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0453', text:"Hero of Alexandria described a toy that spun on jets of steam nearly two thousand years ago.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0454', text:"The Great Wall of China is one unbroken wall running from end to end.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0455', text:"Inca officials kept their records on knotted cords called quipu.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0456', text:"Each Egyptian hieroglyph stands for a whole word rather than a sound.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0457', text:"Farmers digging a well in China uncovered the buried Terracotta Army.", answer:true,  source:"National Geographic", category:"history"},
  {id:'ml-0458', text:"European sailors invented the magnetic compass during the Middle Ages.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0459', text:"The Great Pyramid is lined up with true north to within a fraction of a degree.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0460', text:"The Iron Age came before the Bronze Age.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0461', text:"Cities of the ancient Indus Valley had planned street grids and covered drains.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0462', text:"Troy was never located by archaeologists and is treated as pure legend.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0463', text:"Norse sailors reached North America roughly five centuries before Columbus sailed.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0464', text:"Egyptians invented the wheel in order to move the stones for the pyramids.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0465', text:"Bronze, the metal that named an age, is copper mixed with tin.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0466', text:"Powerful pumps pushed water uphill through the aqueducts of ancient Rome.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0467', text:"Babylonian clay tablets show the Pythagorean rule long before Pythagoras was born.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0468', text:"Hadrian's Wall runs right along today's border between England and Scotland.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0469', text:"Our word plumber goes back to the Latin word for lead, the metal Romans piped water through.", answer:true,  source:"Merriam-Webster", category:"history"},
  {id:'ml-0470', text:"Silk was first made in ancient India.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0471', text:"Sticky notes came from an adhesive so weak that nobody could think of a use for it for years.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0472', text:"The Maya people vanished completely and left no descendants behind.", answer:false, source:"National Geographic", category:"history"},
  {id:'ml-0473', text:"Pencils have never contained lead, only graphite mixed with clay.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0474', text:"The flush toilet was invented by an English plumber named Thomas Crapper.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0475', text:"Before rubber erasers arrived, people rubbed out pencil marks with crumbs of bread.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0476', text:"Thomas Edison invented the very first electric light bulb.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0477', text:"Jigsaw puzzles began as maps cut into pieces to teach children geography.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0478', text:"James Watt invented the very first steam engine.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0479', text:"Escalators were shown off to the public as an amusement ride at Coney Island.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0480', text:"The first practical gasoline automobile was built in the United States.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0481', text:"Air conditioning was invented to steady paper at a printing plant, not to cool people down.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0482', text:"An apple fell on Isaac Newton's head and that is how he came up with gravity.", answer:false, source:"Royal Society", category:"history"},
  {id:'ml-0483', text:"Early powered vacuum cleaners were horse drawn and waited in the street while hoses ran through windows.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0484', text:"Charles Lindbergh made the first nonstop flight across the Atlantic.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0485', text:"A woman named Josephine Cochrane invented the first practical dishwasher in the 1880s.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0486', text:"Golf got its name as a short way of writing gentlemen only, ladies forbidden.", answer:false, source:"Merriam-Webster", category:"history"},
  {id:'ml-0487', text:"Anders Celsius first set his temperature scale with zero at boiling and one hundred at freezing.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0488', text:"SOS was chosen because it stands for save our ship.", answer:false, source:"Merriam-Webster", category:"history"},
  {id:'ml-0489', text:"Wood was the shell of the very first computer mouse, built in the 1960s.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0490', text:"Tulips grew wild in the Netherlands long before they were known anywhere else.", answer:false, source:"Kew Gardens", category:"history"},
  {id:'ml-0491', text:"Ships once carried blocks of ice cut from New England ponds all the way to India.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0492', text:"Germany is where the piano was invented around the year 1700.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0493', text:"Standard time zones were adopted mostly because railways needed timetables that agreed.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0494', text:"Coffee plants were first found growing wild in Brazil.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0495', text:"Suitcases with wheels did not catch on until the 1970s, after people had walked on the Moon.", answer:true,  source:"Smithsonian", category:"history"},
  {id:'ml-0496', text:"For centuries chocolate was eaten as a solid bar before anyone thought to make it a drink.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0497', text:"In English the fruit came first and the color orange was later named after it.", answer:true,  source:"Oxford English Dictionary", category:"history"},
  {id:'ml-0498', text:"Potatoes were first grown as a crop in Ireland.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0499', text:"Riders of the earliest bicycles had no pedals and simply pushed along the ground with their feet.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0500', text:"Arabic numerals got their name because they were invented in Arabia.", answer:false, source:"Britannica", category:"history"},
  {id:'ml-0501', text:"Paris only meant to keep the Eiffel Tower for twenty years before taking it down.", answer:true,  source:"Britannica", category:"history"},
  {id:'ml-0502', text:"Old signs reading ye olde were meant to be said with a yee sound at the start.", answer:false, source:"Oxford English Dictionary", category:"history"},
  {id:'ml-0503', text:"Helium was found in sunlight years before anyone found it here on Earth.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0504', text:"Sliced bread was on shop shelves before anyone invented the pop up toaster.", answer:false, source:"Smithsonian", category:"history"},
  {id:'ml-0505', text:"Oxygen turns into a pale blue liquid once it gets cold enough.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0506', text:"Diamonds are formed from coal squeezed deep underground.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0507', text:"Gallium is a solid metal that melts at about thirty degrees Celsius.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0508', text:"Gold is the best conductor of electricity of any metal.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0509', text:"Liquid water reaches its densest point a few degrees above freezing.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0510', text:"Blue stars burn cooler than red stars.", answer:false, source:"NASA", category:"science"},
  {id:'ml-0511', text:"Metal feels colder than wood at the same temperature because it pulls heat away faster.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0512', text:"The white cloud rising from a boiling kettle is water in its gas form.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0513', text:"Stainless steel resists rust because of a thin invisible layer of chromium oxide.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0514', text:"Water boils at exactly one hundred degrees Celsius everywhere on Earth.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0515', text:"Tungsten has the highest melting point of any metal.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0516', text:"Baking soda and vinegar fizz because the mixture gives off oxygen.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0517', text:"In the 1800s aluminum was treated as more precious than gold.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0518', text:"Among all substances, only water expands as it freezes.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0519', text:"Celsius and Fahrenheit thermometers read the same number at minus forty degrees.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0520', text:"Every metal sinks in water.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0521', text:"Diamond conducts heat better than copper does.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0522', text:"Of all the elements, helium is the lightest.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0523', text:"Table salt is built from two elements that are dangerous on their own.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0524', text:"A rainbow contains exactly seven colors and no more.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0525', text:"Sound travels faster through warm air than through cold air.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0526', text:"Noise cancelling headphones work by playing the same noise back louder.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0527', text:"Mixing red, green and blue light in equal amounts makes white light.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0528', text:"Snow looks white because ice is naturally a white material.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0529', text:"Krakatoa's 1883 eruption was heard thousands of kilometers away.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0530', text:"A candle flame in orbit makes the same teardrop shape it makes on Earth.", answer:false, source:"NASA", category:"science"},
  {id:'ml-0531', text:"Every year the Atlantic Ocean grows a few centimeters wider as the plates beneath it drift apart.", answer:true,  source:"USGS", category:"science"},
  {id:'ml-0532', text:"With no air in the way, a heavy ball falls faster than a light one.", answer:false, source:"NASA", category:"science"},
  {id:'ml-0533', text:"Rock at the very summit of Mount Everest holds fossils of creatures that lived in an ancient sea.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0534', text:"Diamonds are simply lumps of coal that got squeezed hard enough underground.", answer:false, source:"USGS", category:"science"},
  {id:'ml-0535', text:"A tsunami crossing deep ocean can pass under a ship almost unnoticed.", answer:true,  source:"NOAA", category:"science"},
  {id:'ml-0536', text:"California will eventually break off and slide into the Pacific Ocean.", answer:false, source:"USGS", category:"science"},
  {id:'ml-0537', text:"Most volcanic activity on Earth happens underwater along the long ridges of the sea floor.", answer:true,  source:"USGS", category:"science"},
  {id:'ml-0538', text:"Opening the windows during a tornado equalizes the pressure and saves the house.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0539', text:"Pumice is a volcanic rock so full of bubbles that it floats on water.", answer:true,  source:"USGS", category:"science"},
  {id:'ml-0540', text:"Tornadoes steer clear of big cities because tall buildings break them apart.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0541', text:"Many lava flows move slowly enough that a person can simply walk away from them.", answer:true,  source:"USGS", category:"science"},
  {id:'ml-0542', text:"Rubber tires are the reason a car is a safe place to sit during a thunderstorm.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0543', text:"Ash clouds above an erupting volcano can crackle with their own lightning.", answer:true,  source:"USGS", category:"science"},
  {id:'ml-0544', text:"Earthquakes are more likely on hot still days, which is why people say earthquake weather.", answer:false, source:"USGS", category:"science"},
  {id:'ml-0545', text:"Earth's magnetic poles have swapped places many times over the planet's long history.", answer:true,  source:"USGS", category:"science"},
  {id:'ml-0546', text:"Icebergs are simply large chunks of frozen seawater.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0547', text:"Petrichor is the name for that earthy smell the air takes on after rain.", answer:true,  source:"Oxford English Dictionary", category:"science"},
  {id:'ml-0548', text:"The North Pole sits on solid land, the way the South Pole does.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0549', text:"Rain that evaporates before it ever reaches the ground is called virga.", answer:true,  source:"Met Office", category:"science"},
  {id:'ml-0550', text:"Hurricanes, typhoons and cyclones are three different kinds of storm.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0551', text:"Lightning can reach the ground more than ten miles from the storm cloud that made it.", answer:true,  source:"NOAA", category:"science"},
  {id:'ml-0552', text:"The sea looks blue because it reflects the color of the sky above it.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0553', text:"Around five thousand years ago much of the Sahara was grassland dotted with lakes.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0554', text:"Red sky in the morning is an old promise of a calm and sunny day ahead.", answer:false, source:"Met Office", category:"science"},
  {id:'ml-0555', text:"Rubies and sapphires are the same mineral showing up in different colors.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0556', text:"One second between the flash and the thunder means the storm is one mile away.", answer:false, source:"NOAA", category:"science"},
  {id:'ml-0557', text:"Snow high in the mountains can look pink because tiny algae are growing in it.", answer:true,  source:"National Geographic", category:"science"},
  {id:'ml-0558', text:"Lightning cannot happen during a snowstorm.", answer:false, source:"Met Office", category:"science"},
  {id:'ml-0559', text:"Challenger Deep in the Pacific lies almost eleven kilometers below the surface.", answer:true,  source:"NOAA", category:"science"},
  {id:'ml-0560', text:"Stalactites are the ones that grow upward from the floor of a cave.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0561', text:"Going up one whole step on the earthquake magnitude scale means about thirty two times the energy.", answer:true,  source:"USGS", category:"science"},
  {id:'ml-0562', text:"Old Faithful in Yellowstone erupts exactly once an hour, on the hour.", answer:false, source:"USGS", category:"science"},
  {id:'ml-0563', text:"The Mediterranean Sea dried out almost completely in the distant geological past.", answer:true,  source:"Britannica", category:"science"},
  {id:'ml-0564', text:"Antarctica is far too cold and icy to have any active volcanoes.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0565', text:"France spans more time zones than any other country thanks to its overseas territories.", answer:true,  source:"Guinness World Records", category:"world"},
  {id:'ml-0566', text:"Measured from base to peak, Mount Everest is the tallest mountain on Earth.", answer:false, source:"Britannica", category:"science"},
  {id:'ml-0567', text:"Reno in Nevada sits farther west than Los Angeles.", answer:true,  source:"USGS", category:"world"},
  {id:'ml-0568', text:"Monaco is the smallest country in the world.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0569', text:"Saudi Arabia has no permanent rivers anywhere within its borders.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0570', text:"Rio de Janeiro is the capital of Brazil.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0571', text:"Sudan has more ancient pyramids standing on its land than Egypt does.", answer:true,  source:"Smithsonian", category:"world"},
  {id:'ml-0572', text:"Mount Everest sits entirely inside Nepal.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0573', text:"No bridge crosses the main channel of the Amazon River.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0574', text:"The Alps are the highest mountains anywhere outside Asia.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0575', text:"Nepal flies the only national flag in the world that is not a rectangle.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0576', text:"No mountain range on land runs longer than the Rockies.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0577', text:"Lake Baikal in Siberia holds roughly a fifth of the world's unfrozen fresh surface water.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0578', text:"Of all the rivers in the United States, the Mississippi is the longest.", answer:false, source:"USGS", category:"world"},
  {id:'ml-0579', text:"China stretches across five geographic time zones but keeps one official time.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0580', text:"Nowhere on Earth is there a canyon deeper than the Grand Canyon.", answer:false, source:"National Geographic", category:"world"},
  {id:'ml-0581', text:"The Golden Gate Bridge is painted a deep orange rather than gold.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0582', text:"Big Ben is the name of the clock tower beside the River Thames.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0583', text:"The Danube passes through more countries than any other river on Earth.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0584', text:"Ships cross the Suez Canal by climbing a staircase of locks.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0585', text:"New York City lies farther south than Rome.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0586', text:"Every time zone in the world is a whole number of hours away from London.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0587', text:"The shortest scheduled flight in the world hops between two Scottish islands in under two minutes.", answer:true,  source:"Guinness World Records", category:"world"},
  {id:'ml-0588', text:"Zero degrees longitude runs straight through Paris.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0589', text:"Only two countries on Earth are surrounded entirely by other landlocked countries.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0590', text:"You would travel south from the equator to reach the Tropic of Cancer.", answer:false, source:"National Geographic", category:"world"},
  {id:'ml-0591', text:"The Congo River crosses the equator twice on its way to the sea.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0592', text:"Like Antarctica, the Arctic is a continent buried under a thick sheet of ice.", answer:false, source:"National Geographic", category:"world"},
  {id:'ml-0593', text:"Mount Everest takes its name from a British surveyor.", answer:true,  source:"Britannica", category:"world"},
  {id:'ml-0594', text:"Death Valley is the lowest point on dry land anywhere in the world.", answer:false, source:"USGS", category:"world"},
  {id:'ml-0595', text:"The word robot came to English from a Czech play about artificial workers.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0596', text:"Roughly twenty percent of the oxygen we breathe comes from the Amazon rainforest.", answer:false, source:"National Geographic", category:"world"},
  {id:'ml-0597', text:"Alphabet is simply the names of the first two Greek letters stuck together.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0598', text:"Cape Town stands at the southern tip of Africa.", answer:false, source:"Britannica", category:"world"},
  {id:'ml-0599', text:"Icelandic still uses a letter called thorn that English dropped long ago.", answer:true,  source:"Britannica", category:"words"},
  {id:'ml-0600', text:"Kangaroo comes from an Aboriginal phrase meaning I do not understand you.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0601', text:"Korea's alphabet was designed on purpose in the 1400s instead of growing slowly.", answer:true,  source:"Britannica", category:"words"},
  {id:'ml-0602', text:"Posh began as shorthand for port out starboard home on old sea voyages.", answer:false, source:"Oxford English Dictionary", category:"words"},
  {id:'ml-0603', text:"Louis Braille worked out his system of raised dots while still a teenager.", answer:true,  source:"Britannica", category:"words"},
  {id:'ml-0604', text:"News got its name from the letters for north, east, west and south.", answer:false, source:"Merriam-Webster", category:"words"},
  {id:'ml-0605', text:"Sequoyah built a complete writing system for Cherokee without being able to read English.", answer:true,  source:"Britannica", category:"words"},
  {id:'ml-0606', text:"Tip is short for to insure promptness.", answer:false, source:"Merriam-Webster", category:"words"},
  {id:'ml-0607', text:"More people speak Mandarin Chinese as a first language than any other.", answer:true,  source:"Britannica", category:"words"},
  {id:'ml-0608', text:"The distress call SOS was chosen because it stands for save our souls.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0609', text:"In old shop signs the Y of Ye Olde stands for a lost letter pronounced th.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0610', text:"Butterfly started life as flutterby before people muddled the sounds.", answer:false, source:"Oxford English Dictionary", category:"words"},
  {id:'ml-0611', text:"Scribes added that silent b in doubt to echo the Latin word behind it.", answer:true,  source:"Oxford English Dictionary", category:"words"},
  {id:'ml-0612', text:"Those islands called the Canaries were named after the little yellow birds.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0613', text:"An apron used to be a napron until the n drifted over to the word before it.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0614', text:"Inuit languages have hundreds of completely separate root words for snow.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0615', text:"Denim is named after a city in France and jeans after a city in Italy.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0616', text:"Emoji comes straight from the English word emotion.", answer:false, source:"Merriam-Webster", category:"words"},
  {id:'ml-0617', text:"Boondocks came into English from a Tagalog word meaning mountain.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0618', text:"Big Ben is the official name of the clock tower beside the Thames.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0619', text:"Chicago takes its name from an Indigenous word for a wild onion plant.", answer:true,  source:"Britannica", category:"words"},
  {id:'ml-0620', text:"Etymology is the branch of science that studies insects.", answer:false, source:"Merriam-Webster", category:"words"},
  {id:'ml-0621', text:"Singapore comes from Sanskrit words meaning lion city.", answer:true,  source:"Britannica", category:"words"},
  {id:'ml-0622', text:"Shakespeare wrote his plays in Old English.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0623', text:"Mount Everest is named after a British surveyor.", answer:true,  source:"Britannica", category:"words"},
  {id:'ml-0624', text:"Deaf people everywhere share one universal sign language.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0625', text:"That bird we call a turkey was named after the country, not the other way round.", answer:true,  source:"Merriam-Webster", category:"words"},
  {id:'ml-0626', text:"Egyptian hieroglyphs were pure pictures with no signs for sounds.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0627', text:"Sahara means desert in Arabic, so saying Sahara Desert says desert twice.", answer:true,  source:"Britannica", category:"words"},
  {id:'ml-0628', text:"The letter J is one of the oldest letters in the English alphabet.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0629', text:"Fungi are more closely related to animals than to plants.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0630', text:"Greenland earned its name from the lush green meadows the first settlers found.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0631', text:"Lichens growing on rocks and bark are a partnership between a fungus and algae.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0632', text:"The Cyrillic alphabet was invented in Russia.", answer:false, source:"Britannica", category:"words"},
  {id:'ml-0633', text:"Some fungi glow in the dark with a faint greenish light.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0634', text:"The Amazon rainforest supplies twenty percent of the oxygen we breathe.", answer:false, source:"National Geographic", category:"plants"},
  {id:'ml-0635', text:"Green tea and black tea come from the leaves of the same plant.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0636', text:"Plants only give off oxygen and never take any in.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0637', text:"Chocolate starts as seeds inside pods that grow straight from the trunk of a cacao tree.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0638', text:"Pitcher plants and other carnivorous plants get all of their food from insects.", answer:false, source:"Kew Gardens", category:"plants"},
  {id:'ml-0639', text:"Cinnamon is the dried inner bark of a tree.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0640', text:"Tulips are native to the Netherlands.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0641', text:"Saffron is made from three thin threads found inside each crocus flower.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0642', text:"Kiwifruit is native to New Zealand.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0643', text:"Cranberry growers flood their fields at harvest so the fruit floats to the top.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0644', text:"Sweet potatoes are simply a sweeter variety of the ordinary potato.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0645', text:"Peanut plants push their flower stalks down into the soil so the pods ripen underground.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0646', text:"Bamboo is a type of tree.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0647', text:"Corn, wheat and rice all belong to the grass family.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0648', text:"Potatoes are the roots of the potato plant.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0649', text:"Flowering plants arrived on Earth long after the first dinosaurs did.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0650', text:"Ferns spread by scattering tiny seeds from the undersides of their leaves.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0651', text:"Water climbs to the top of a tall tree with no pump, drawn up as the leaves lose moisture.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0652', text:"Toadstool is the scientific term for one particular family of fungi.", answer:false, source:"Merriam-Webster", category:"plants"},
  {id:'ml-0653', text:"Clover and bean plants keep bacteria in their roots that pull nitrogen out of the air.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0654', text:"Mushrooms can only grow in total darkness.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0655', text:"Each silky thread on an ear of corn leads to one kernel.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0656', text:"Pine trees produce small flowers before their cones appear.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0657', text:"A date palm was grown from a seed that was roughly two thousand years old.", answer:true,  source:"National Geographic", category:"plants"},
  {id:'ml-0658', text:"Every flower produces nectar for its pollinators.", answer:false, source:"Britannica", category:"plants"},
  {id:'ml-0659', text:"Autumn yellows and oranges sit in the leaf all summer, hidden by green chlorophyll.", answer:true,  source:"Britannica", category:"plants"},
  {id:'ml-0660', text:"Evergreen trees keep the very same needles for their entire lives.", answer:false, source:"Britannica", category:"plants"}
];
