/* MOTHLIGHT FACT BANK
   Regenerate or extend with this exact prompt, then hand-audit every entry:

   "Write N true-or-false facts for a family party quiz. Rules: each fact is
   one complete sentence under 110 characters, checkable against a mainstream
   encyclopedia, general audience, no politics, no religion, no bodies, no
   violence, no brand names, no dash characters of any kind. Aim for half
   true and half false, and make several facts things people confidently get
   wrong. For each, output: the sentence, true or false, and a short source
   name (one recognizable reference). Output as a JS array of objects with
   fields id, text, answer, source, category. Categories: animals, space,
   food, history, science, world, words, plants."

   AUDIT RULE: a fact nobody verified does not ship. Check each answer field
   against the named source before committing.
   Launch bank 2026-08-07: 240 entries, 120 true / 120 false. */
window.MOTHLIGHT_BANK = [
  {id:'ml-0001', text:"A group of moths can be called an eclipse.", answer:true,  source:'Merriam-Webster', category:'animals'},
  {id:'ml-0002', text:"Sealed honey can stay good to eat for thousands of years.", answer:true,  source:'Smithsonian', category:'food'},
  {id:'ml-0003', text:"Bananas grow on trees.", answer:false, source:'Britannica', category:'plants'},
  {id:'ml-0004', text:"The Eiffel Tower is a little taller in summer than in winter.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0005', text:"Goldfish can only remember things for three seconds.", answer:false, source:'National Geographic', category:'animals'},
  {id:'ml-0006', text:"An octopus has three hearts.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0007', text:"Lightning never strikes the same place twice.", answer:false, source:'NOAA', category:'science'},
  {id:'ml-0008', text:"Venus is the hottest planet in our solar system.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0009', text:"Humans and giraffes have the same number of neck bones.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0010', text:"Bats are blind.", answer:false, source:'National Geographic', category:'animals'},
  {id:'ml-0011', text:"A day on Venus is longer than a year on Venus.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0012', text:"The Great Wall of China is easily visible from the Moon.", answer:false, source:'NASA', category:'world'},
  {id:'ml-0013', text:"Strawberries wear their seeds on the outside.", answer:true,  source:'Britannica', category:'plants'},
  {id:'ml-0014', text:"Peanuts are a kind of nut.", answer:false, source:'Britannica', category:'food'},
  {id:'ml-0015', text:"A cucumber is a fruit.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0016', text:"Sound travels faster in water than in air.", answer:true,  source:'Britannica', category:'science'},
  {id:'ml-0017', text:"Humans use only ten percent of their brains.", answer:false, source:'Scientific American', category:'science'},
  {id:'ml-0018', text:"Hot water can freeze faster than cold water in some conditions.", answer:true,  source:'Scientific American', category:'science'},
  {id:'ml-0019', text:"Camels store water in their humps.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0020', text:"A shrimp's heart is in its head.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0021', text:"Sunflowers always face the sun, even at night.", answer:false, source:'Britannica', category:'plants'},
  {id:'ml-0022', text:"Wombats have cube shaped droppings.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0023', text:"Mount Everest is the closest point on Earth to space.", answer:false, source:'NASA', category:'world'},
  {id:'ml-0024', text:"Scotland's national animal is the unicorn.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0025', text:"Bulls charge because the color red makes them angry.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0026', text:"Sea otters sometimes hold hands while they sleep.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0027', text:"An ostrich hides by burying its head in the sand.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0028', text:"Hot lightning bolts are about five times hotter than the surface of the sun.", answer:true,  source:'NOAA', category:'science'},
  {id:'ml-0029', text:"Dogs can only see in black and white.", answer:false, source:'American Kennel Club', category:'animals'},
  {id:'ml-0030', text:"A blue whale's heart is about the size of a small car.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0031', text:"Glass is a slow moving liquid.", answer:false, source:'Scientific American', category:'science'},
  {id:'ml-0032', text:"Kangaroos cannot easily hop backwards.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0033', text:"Chameleons change color mainly to match their background.", answer:false, source:'National Geographic', category:'animals'},
  {id:'ml-0034', text:"There are more trees on Earth than stars in the Milky Way.", answer:true,  source:'Nature', category:'plants'},
  {id:'ml-0035', text:"You lose most of your body heat through your head.", answer:false, source:'Scientific American', category:'science'},
  {id:'ml-0036', text:"Octopuses have blue blood.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0037', text:"Mice love cheese more than any other food.", answer:false, source:'BBC Science Focus', category:'animals'},
  {id:'ml-0038', text:"Hippos produce a reddish fluid that works like sunscreen.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0039', text:"Toads give you warts if you touch them.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0040', text:"The Sahara is the largest hot desert in the world.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0041', text:"Antarctica is the largest desert on Earth.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0042', text:"Sharks must stop swimming to sleep.", answer:false, source:'National Geographic', category:'animals'},
  {id:'ml-0043', text:"Sharks as a group are older than the rings of Saturn may be.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0044', text:"Water conducts electricity when perfectly pure.", answer:false, source:'Britannica', category:'science'},
  {id:'ml-0045', text:"Cows have best friends and get stressed when separated.", answer:true,  source:'BBC Science Focus', category:'animals'},
  {id:'ml-0046', text:"The tongue has separate zones for sweet, salty, sour and bitter.", answer:false, source:'Scientific American', category:'science'},
  {id:'ml-0047', text:"Butterflies can taste with their feet.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0048', text:"Penguins live at the North Pole.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0049', text:"A snail can sleep for about three years at a stretch.", answer:true,  source:'BBC Science Focus', category:'animals'},
  {id:'ml-0050', text:"Coffee beans are beans.", answer:false, source:'Britannica', category:'food'},
  {id:'ml-0051', text:"Pineapples take about two years to grow one fruit.", answer:true,  source:'Britannica', category:'plants'},
  {id:'ml-0052', text:"Tomatoes were once widely feared as poisonous in Europe.", answer:true,  source:'Smithsonian', category:'food'},
  {id:'ml-0053', text:"Carrots were originally mostly purple.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0054', text:"Eating carrots gives you night vision.", answer:false, source:'Smithsonian', category:'food'},
  {id:'ml-0055', text:"White chocolate contains no cocoa solids.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0056', text:"Adding salt makes water boil at a lower temperature.", answer:false, source:'Britannica', category:'science'},
  {id:'ml-0057', text:"Apples float because they are about one quarter air.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0058', text:"Swallowed chewing gum stays in your stomach for seven years.", answer:false, source:'Mayo Clinic', category:'food'},
  {id:'ml-0059', text:"Cashews grow attached to the bottom of a fruit called a cashew apple.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0060', text:"Ketchup was once sold as a medicine in the United States.", answer:true,  source:'Smithsonian', category:'history'},
  {id:'ml-0061', text:"The Moon has a permanently dark side that never sees the sun.", answer:false, source:'NASA', category:'space'},
  {id:'ml-0062', text:"Jupiter is the fastest spinning planet in our solar system.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0063', text:"A year on Mercury lasts only 88 Earth days.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0064', text:"The sun is yellow.", answer:false, source:'NASA', category:'space'},
  {id:'ml-0065', text:"Saturn would float in a big enough bathtub of water.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0066', text:"There is a permanent hexagon shaped storm on Saturn.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0067', text:"Mars appears red because of rust on its surface.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0068', text:"The asteroid belt is so crowded that spacecraft must dodge rocks.", answer:false, source:'NASA', category:'space'},
  {id:'ml-0069', text:"Footprints left on the Moon could last for millions of years.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0070', text:"Sound carries wonderfully through the vacuum of space.", answer:false, source:'NASA', category:'space'},
  {id:'ml-0071', text:"Neutron stars can spin hundreds of times per second.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0072', text:"The Moon causes the ocean tides.", answer:true,  source:'NOAA', category:'space'},
  {id:'ml-0073', text:"Mercury is the hottest planet because it is closest to the sun.", answer:false, source:'NASA', category:'space'},
  {id:'ml-0074', text:"Olympus Mons on Mars is the tallest volcano in the solar system.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0075', text:"A comet's tail always points away from the sun.", answer:true,  source:'NASA', category:'space'},
  {id:'ml-0076', text:"The Roman Colosseum could reportedly be flooded for mock sea battles.", answer:true,  source:'Britannica', category:'history'},
  {id:'ml-0077', text:"Napoleon was unusually short for a Frenchman of his time.", answer:false, source:'Britannica', category:'history'},
  {id:'ml-0078', text:"Oxford University is older than the Aztec Empire.", answer:true,  source:'Britannica', category:'history'},
  {id:'ml-0079', text:"Vikings wore horned helmets into battle.", answer:false, source:'Smithsonian', category:'history'},
  {id:'ml-0080', text:"Cleopatra lived closer in time to the Moon landing than to the Great Pyramid.", answer:true,  source:'Britannica', category:'history'},
  {id:'ml-0081', text:"The shortest war on record lasted less than an hour.", answer:true,  source:'Britannica', category:'history'},
  {id:'ml-0082', text:"Medieval people believed the Earth was flat.", answer:false, source:'Britannica', category:'history'},
  {id:'ml-0083', text:"Woolly mammoths were still alive while the pyramids were being built.", answer:true,  source:'Smithsonian', category:'history'},
  {id:'ml-0084', text:"The Hundred Years War lasted exactly one hundred years.", answer:false, source:'Britannica', category:'history'},
  {id:'ml-0085', text:"Ancient Romans used urine as a laundry cleaner.", answer:true,  source:'Smithsonian', category:'history'},
  {id:'ml-0086', text:"The Leaning Tower of Pisa began leaning while it was still being built.", answer:true,  source:'Britannica', category:'history'},
  {id:'ml-0087', text:"Albert Einstein failed math at school.", answer:false, source:'Britannica', category:'history'},
  {id:'ml-0088', text:"The first computer programmer is widely considered to be a woman.", answer:true,  source:'Britannica', category:'history'},
  {id:'ml-0089', text:"The Statue of Liberty was a gift from France.", answer:true,  source:'Britannica', category:'history'},
  {id:'ml-0090', text:"Salem's convicted witches were burned at the stake.", answer:false, source:'Smithsonian', category:'history'},
  {id:'ml-0091', text:"Australia is wider than the Moon.", answer:true,  source:'NASA', category:'world'},
  {id:'ml-0092', text:"Africa is the continent with the most countries.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0093', text:"The Amazon is agreed by everyone to be the longest river on Earth.", answer:false, source:'Britannica', category:'world'},
  {id:'ml-0094', text:"Canada has more lakes than the rest of the world combined.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0095', text:"Russia spans eleven time zones.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0096', text:"The capital of Australia is Sydney.", answer:false, source:'Britannica', category:'world'},
  {id:'ml-0097', text:"Istanbul sits on two continents at once.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0098', text:"The Dead Sea is actually a lake.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0099', text:"Iceland is mostly covered in ice.", answer:false, source:'Britannica', category:'world'},
  {id:'ml-0100', text:"The Pacific Ocean is larger than all the land on Earth combined.", answer:true,  source:'NOAA', category:'world'},
  {id:'ml-0101', text:"More people live in Tokyo than in all of Canada.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0102', text:"The Nile flows from south to north.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0103', text:"Mount Kilimanjaro is in South America.", answer:false, source:'Britannica', category:'world'},
  {id:'ml-0104', text:"There is a town in Norway where the sun does not set for weeks in summer.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0105', text:"The Netherlands is the world's biggest exporter of tulips.", answer:true,  source:'Britannica', category:'plants'},
  {id:'ml-0106', text:"Venice is built on about 120 small islands.", answer:true,  source:'Britannica', category:'world'},
  {id:'ml-0107', text:"The Great Barrier Reef is the largest living structure on Earth.", answer:true,  source:'National Geographic', category:'world'},
  {id:'ml-0108', text:"All deserts are hot.", answer:false, source:'Britannica', category:'world'},
  {id:'ml-0109', text:"The little word set has one of the longest entries in the dictionary.", answer:true,  source:'Oxford English Dictionary', category:'words'},
  {id:'ml-0110', text:"The word queue sounds exactly the same with its last four letters removed.", answer:true,  source:'Merriam-Webster', category:'words'},
  {id:'ml-0111', text:"A pangram is a sentence that uses every letter of the alphabet.", answer:true,  source:'Merriam-Webster', category:'words'},
  {id:'ml-0112', text:"The opposite of nocturnal is infernal.", answer:false, source:'Merriam-Webster', category:'words'},
  {id:'ml-0113', text:"A group of crows can be called a murder.", answer:true,  source:'Merriam-Webster', category:'words'},
  {id:'ml-0114', text:"A baby rabbit is called a cub.", answer:false, source:'Merriam-Webster', category:'words'},
  {id:'ml-0115', text:"The dot over a lowercase i has a name: the tittle.", answer:true,  source:'Merriam-Webster', category:'words'},
  {id:'ml-0116', text:"A word that reads the same forwards and backwards is a pantomime.", answer:false, source:'Merriam-Webster', category:'words'},
  {id:'ml-0117', text:"The fear of long words has an ironically long scientific style name.", answer:true,  source:'Merriam-Webster', category:'words'},
  {id:'ml-0118', text:"A baby goat is called a kid.", answer:true,  source:'Merriam-Webster', category:'words'},
  {id:'ml-0119', text:"The plural of octopus can correctly be octopuses.", answer:true,  source:'Merriam-Webster', category:'words'},
  {id:'ml-0120', text:"A group of owls can be called a parliament.", answer:true,  source:'Merriam-Webster', category:'words'},
  {id:'ml-0121', text:"Buttercups are safe to eat in salads.", answer:false, source:'Britannica', category:'plants'},
  {id:'ml-0122', text:"Bamboo can grow more than half a meter in a single day.", answer:true,  source:'Guinness World Records', category:'plants'},
  {id:'ml-0123', text:"A sunflower head is actually hundreds of tiny flowers.", answer:true,  source:'Britannica', category:'plants'},
  {id:'ml-0124', text:"Trees get most of their mass from the soil they grow in.", answer:false, source:'Scientific American', category:'plants'},
  {id:'ml-0125', text:"Some trees can send nutrients to their neighbors through root networks.", answer:true,  source:'Nature', category:'plants'},
  {id:'ml-0126', text:"Cacti store water mainly in their spines.", answer:false, source:'Britannica', category:'plants'},
  {id:'ml-0127', text:"The largest single flower in the world can be about a meter across.", answer:true,  source:'Britannica', category:'plants'},
  {id:'ml-0128', text:"Grass is a flowering plant.", answer:true,  source:'Britannica', category:'plants'},
  {id:'ml-0129', text:"Venus flytraps count the touches before they snap shut.", answer:true,  source:'Nature', category:'plants'},
  {id:'ml-0130', text:"Mushrooms are plants.", answer:false, source:'Britannica', category:'plants'},
  {id:'ml-0131', text:"An oak tree can drop thousands of acorns in a single autumn.", answer:true,  source:'Britannica', category:'plants'},
  {id:'ml-0132', text:"Moss only ever grows on the north side of trees.", answer:false, source:'Britannica', category:'plants'},
  {id:'ml-0133', text:"Some seeds need fire to sprout.", answer:true,  source:'Britannica', category:'plants'},
  {id:'ml-0134', text:"A tomato is legally a vegetable in the United States for tariff purposes.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0135', text:"Broccoli, kale and cabbage are all the same species of plant.", answer:true,  source:'Britannica', category:'plants'},
  {id:'ml-0136', text:"Rice is grown underwater because it cannot survive in dry soil.", answer:false, source:'Britannica', category:'plants'},
  {id:'ml-0137', text:"Vanilla flavoring comes from a kind of orchid.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0138', text:"A pumpkin is a berry to a botanist.", answer:true,  source:'Britannica', category:'plants'},
  {id:'ml-0139', text:"Four leaf clovers do not exist in nature.", answer:false, source:'Britannica', category:'plants'},
  {id:'ml-0140', text:"The oldest known living tree is thousands of years old.", answer:true,  source:'Guinness World Records', category:'plants'},
  {id:'ml-0141', text:"Your fingernails keep growing for weeks after you die.", answer:false, source:'BBC Science Focus', category:'science'},
  {id:'ml-0142', text:"Bones are about five times stronger than steel of the same weight.", answer:true,  source:'BBC Science Focus', category:'science'},
  {id:'ml-0143', text:"Cracking your knuckles causes arthritis.", answer:false, source:'Harvard Health', category:'science'},
  {id:'ml-0144', text:"You are a little taller in the morning than at night.", answer:true,  source:'BBC Science Focus', category:'science'},
  {id:'ml-0145', text:"Humans have exactly five senses.", answer:false, source:'Scientific American', category:'science'},
  {id:'ml-0146', text:"Hair and fingernails are made of the same protein.", answer:true,  source:'Britannica', category:'science'},
  {id:'ml-0147', text:"Reading in dim light permanently damages your eyes.", answer:false, source:'Harvard Health', category:'science'},
  {id:'ml-0148', text:"Your stomach gets a new lining every few days.", answer:true,  source:'BBC Science Focus', category:'science'},
  {id:'ml-0149', text:"Shaving makes hair grow back thicker.", answer:false, source:'Mayo Clinic', category:'science'},
  {id:'ml-0150', text:"The human body contains enough iron to make a small nail.", answer:true,  source:'BBC Science Focus', category:'science'},
  {id:'ml-0151', text:"Rainbows are full circles when seen from high enough up.", answer:true,  source:'NOAA', category:'science'},
  {id:'ml-0152', text:"Thunder is the sound of clouds crashing into each other.", answer:false, source:'NOAA', category:'science'},
  {id:'ml-0153', text:"No two snowflakes have ever been proven identical.", answer:true,  source:'NOAA', category:'science'},
  {id:'ml-0154', text:"A rainbow at night is impossible.", answer:false, source:'NOAA', category:'science'},
  {id:'ml-0155', text:"Raindrops are shaped like teardrops as they fall.", answer:false, source:'NOAA', category:'science'},
  {id:'ml-0156', text:"Hurricanes spin in opposite directions north and south of the equator.", answer:true,  source:'NOAA', category:'science'},
  {id:'ml-0157', text:"It can be too cold to snow heavily.", answer:true,  source:'NOAA', category:'science'},
  {id:'ml-0158', text:"Deserts never get snow.", answer:false, source:'NOAA', category:'world'},
  {id:'ml-0159', text:"A single bolt of lightning could toast a hundred thousand slices of bread.", answer:true,  source:'BBC Science Focus', category:'science'},
  {id:'ml-0160', text:"Wind is caused by the Earth spinning under the air.", answer:false, source:'NOAA', category:'science'},
  {id:'ml-0161', text:"Honeybees tell each other where flowers are by dancing.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0162', text:"A bee visits about fifty to a hundred flowers in one trip.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0163', text:"Wasps can make honey just like bees.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0164', text:"Ants never sleep.", answer:false, source:'BBC Science Focus', category:'animals'},
  {id:'ml-0165', text:"Some ants farm aphids the way people farm cattle.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0166', text:"Dragonflies are among the most successful hunters in the animal kingdom.", answer:true,  source:'BBC Science Focus', category:'animals'},
  {id:'ml-0167', text:"Fireflies make light with almost no heat.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0168', text:"A ladybug's spots tell you its age in years.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0169', text:"Crickets chirp faster in warmer weather.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0170', text:"Spiders are insects.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0171', text:"A moth's feathery antennae can smell a mate from miles away.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0172', text:"Earthworms have five heart like organs.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0173', text:"Butterflies live for only one day.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0174', text:"Snails have thousands of tiny teeth.", answer:true,  source:'BBC Science Focus', category:'animals'},
  {id:'ml-0175', text:"Daddy longlegs are the most venomous spiders but cannot bite humans.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0176', text:"Cats spend roughly two thirds of their lives asleep.", answer:true,  source:'BBC Science Focus', category:'animals'},
  {id:'ml-0177', text:"A cat's purr always means it is happy.", answer:false, source:'BBC Science Focus', category:'animals'},
  {id:'ml-0178', text:"Adult cats mostly meow at humans, not at other cats.", answer:true,  source:'BBC Science Focus', category:'animals'},
  {id:'ml-0179', text:"Dogs sweat mainly through their tongues.", answer:false, source:'American Kennel Club', category:'animals'},
  {id:'ml-0180', text:"A dog's nose print is unique, a bit like a fingerprint.", answer:true,  source:'American Kennel Club', category:'animals'},
  {id:'ml-0181', text:"Goats have rectangular pupils.", answer:true,  source:'BBC Science Focus', category:'animals'},
  {id:'ml-0182', text:"Owls can turn their heads in a complete circle.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0183', text:"Flamingos are pink because of what they eat.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0184', text:"A duck's quack does not echo.", answer:false, source:'BBC Science Focus', category:'animals'},
  {id:'ml-0185', text:"Crows can recognize and remember individual human faces.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0186', text:"Hummingbirds are the only birds that can fly backwards.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0187', text:"Touching a baby bird makes its mother abandon it.", answer:false, source:'Audubon', category:'animals'},
  {id:'ml-0188', text:"Some birds nap while flying.", answer:true,  source:'Nature', category:'animals'},
  {id:'ml-0189', text:"Penguins propose to each other with pebbles.", answer:false, source:'Audubon', category:'animals'},
  {id:'ml-0190', text:"An albatross can glide for hours barely flapping its wings.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0191', text:"Elephants are the only mammals that cannot jump.", answer:false, source:'BBC Science Focus', category:'animals'},
  {id:'ml-0192', text:"Elephants can hear storms rumbling from far away through their feet.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0193', text:"A rhino's horn is made of hair like keratin, not bone.", answer:true,  source:'Britannica', category:'animals'},
  {id:'ml-0194', text:"Giraffes sleep standing up for eight hours a night.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0195', text:"Polar bear skin is black under all that white fur.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0196', text:"Sloths can hold their breath longer than dolphins.", answer:true,  source:'BBC Science Focus', category:'animals'},
  {id:'ml-0197', text:"Beavers eat fish they catch in their dams.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0198', text:"Squirrels help plant thousands of trees by forgetting where they buried acorns.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0199', text:"Porcupines can shoot their quills at attackers.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0200', text:"A raccoon's front paws become more sensitive underwater.", answer:true,  source:'National Geographic', category:'animals'},
  {id:'ml-0201', text:"Bread rises because yeast releases carbon dioxide.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0202', text:"Popcorn pops because of a tiny drop of water inside each kernel.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0203', text:"Lemons float and limes sink.", answer:true,  source:'BBC Science Focus', category:'food'},
  {id:'ml-0204', text:"Adding oil to pasta water keeps the noodles from sticking together.", answer:false, source:'BBC Science Focus', category:'food'},
  {id:'ml-0205', text:"A watermelon is over ninety percent water.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0206', text:"Spicy heat from chili is a taste detected by the tongue's taste buds.", answer:false, source:'Scientific American', category:'food'},
  {id:'ml-0207', text:"Onions make you cry because they release a gas that stings your eyes.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0208', text:"Brown eggs are more nutritious than white eggs.", answer:false, source:'Mayo Clinic', category:'food'},
  {id:'ml-0209', text:"Wasabi served outside Japan is usually dyed horseradish.", answer:true,  source:'BBC', category:'food'},
  {id:'ml-0210', text:"Microwaves cook food from the inside out.", answer:false, source:'BBC Science Focus', category:'food'},
  {id:'ml-0211', text:"Pound cake is named for a recipe using a pound each of four ingredients.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0212', text:"Almonds are seeds, not true nuts.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0213', text:"Searing meat seals in all of its juices.", answer:false, source:'BBC Science Focus', category:'food'},
  {id:'ml-0214', text:"Maple syrup starts as a nearly flavorless watery sap.", answer:true,  source:'Britannica', category:'food'},
  {id:'ml-0215', text:"Raw cookie dough is risky mostly because of the flour, not just the egg.", answer:true,  source:'FDA', category:'food'},
  {id:'ml-0216', text:"The fortune cookie was invented in ancient China.", answer:false, source:'Smithsonian', category:'food'},
  {id:'ml-0217', text:"Pearls dissolve in vinegar.", answer:true,  source:'Britannica', category:'science'},
  {id:'ml-0218', text:"Bubble wrap was first invented as wallpaper.", answer:true,  source:'Smithsonian', category:'history'},
  {id:'ml-0219', text:"The microwave oven was inspired by a melted chocolate bar in a pocket.", answer:true,  source:'Smithsonian', category:'history'},
  {id:'ml-0220', text:"Velcro was inspired by burrs sticking to a dog's fur.", answer:true,  source:'Smithsonian', category:'history'},
  {id:'ml-0221', text:"The first parachute jump happened before the first airplane flew.", answer:true,  source:'Guinness World Records', category:'history'},
  {id:'ml-0222', text:"Umbrellas were invented in London to deal with the rain.", answer:false, source:'Britannica', category:'history'},
  {id:'ml-0223', text:"The first alarm clock could only ring at four in the morning.", answer:true,  source:'Smithsonian', category:'history'},
  {id:'ml-0224', text:"Chess was invented in Russia.", answer:false, source:'Britannica', category:'history'},
  {id:'ml-0225', text:"The ice cream cone became popular at a World's Fair.", answer:true,  source:'Smithsonian', category:'food'},
  {id:'ml-0226', text:"Roller skates made their debut by crashing through a ballroom mirror.", answer:true,  source:'Smithsonian', category:'history'},
  {id:'ml-0227', text:"The zipper took decades to become a common part of clothing.", answer:true,  source:'Smithsonian', category:'history'},
  {id:'ml-0228', text:"Paper was invented in ancient Egypt.", answer:false, source:'Britannica', category:'history'},
  {id:'ml-0229', text:"A jiffy is a real unit of time in physics.", answer:true,  source:'Britannica', category:'science'},
  {id:'ml-0230', text:"An inchworm is exactly one inch long.", answer:false, source:'Britannica', category:'animals'},
  {id:'ml-0231', text:"Hot air balloons flew passengers before the invention of the bicycle.", answer:true,  source:'Britannica', category:'history'},
  {id:'ml-0232', text:"The Wright brothers' first flight was shorter than a jumbo jet's wingspan.", answer:true,  source:'Smithsonian', category:'history'},
  {id:'ml-0233', text:"Goldfish turn pale if kept in the dark.", answer:true,  source:'BBC Science Focus', category:'animals'},
  {id:'ml-0234', text:"Toilets flush in opposite directions north and south of the equator.", answer:false, source:'Scientific American', category:'science'},
  {id:'ml-0235', text:"A bolt of lightning is thinner than most people imagine, only a few centimeters.", answer:true,  source:'NOAA', category:'science'},
  {id:'ml-0236', text:"Bananas are naturally a little radioactive.", answer:true,  source:'BBC Science Focus', category:'food'},
  {id:'ml-0237', text:"Sugar makes children hyperactive.", answer:false, source:'Mayo Clinic', category:'food'},
  {id:'ml-0238', text:"You can see the curvature of the Earth from a passenger plane window.", answer:false, source:'Scientific American', category:'science'},
  {id:'ml-0239', text:"Wait an hour after eating before swimming or you will get dangerous cramps.", answer:false, source:'Mayo Clinic', category:'science'},
  {id:'ml-0240', text:"The tea bag was popularized by accident when samples were dunked whole.", answer:true,  source:'BBC', category:'history'}
];
