/* SAME SOIL PAIR BANK

   One player is the subject. They pick which of two things is more them. The
   rest of the room predicts what they picked. The subject's own answer is the
   only authority, so nobody can ever be told they are wrong about themselves.

   ⚖ THE ART DECISION, RECORDED. WHACKBOX_PLAN specs this title with roughly 720
   small illustrations, and the art pipeline is the critical path. So v1 ships
   with AUTHORED WORD PAIRS instead: two or three words a side, large on the TV,
   which is readable at ten feet and costs nothing. Illustrations are an upgrade
   that drops straight into the same bank as an `art` field per side. Shipping
   the words first means the game exists while the art is drawn, and it means
   the pairs get playtested before anybody paints 720 of anything.

   Regenerate or extend with this exact prompt, then hand-audit every entry:

   "Write N either or pairs for a cozy family party game where players guess
   which one somebody prefers. Each side is one to three words under 22
   characters. The two sides must be genuinely balanced, so a room would split
   on them. General audience, safe for a grandparent and an eight year old.
   NOTHING about money, appearance, weight, health, bodies, romance,
   relationships, politics, religion or alcohol, and nothing where one answer
   makes a person look bad. No brand names. No dash characters of any kind.
   Output a JS array of objects with fields id, a, b, category. Categories:
   places, food, weather, animals, time, comfort, adventure, senses."

   AUDIT RULE: for each pair ask whether either side could embarrass the person
   who picks it. If yes, cut it. This game only works because answering is safe.

   Bank at 2026-08-08: 206 pairs. Round one hand written, round two generated
   then adversarially audited for taste and for whether a room would actually split. */
window.SAMESOIL_BANK = [
  {id:'ss-0001', a:"Mountains", b:"The sea", category:"places"},
  {id:'ss-0002', a:"Sunrise", b:"Sunset", category:"time"},
  {id:'ss-0003', a:"Tea", b:"Coffee", category:"food"},
  {id:'ss-0004', a:"Cats", b:"Dogs", category:"animals"},
  {id:'ss-0005', a:"Rain on a roof", b:"Wind in trees", category:"senses"},
  {id:'ss-0006', a:"Sweet", b:"Salty", category:"food"},
  {id:'ss-0007', a:"A big city", b:"A small village", category:"places"},
  {id:'ss-0008', a:"Summer", b:"Winter", category:"weather"},
  {id:'ss-0009', a:"A window seat", b:"An aisle seat", category:"adventure"},
  {id:'ss-0010', a:"Early bird", b:"Night owl", category:"time"},
  {id:'ss-0011', a:"Books", b:"Films", category:"comfort"},
  {id:'ss-0012', a:"A long bath", b:"A quick shower", category:"comfort"},
  {id:'ss-0013', a:"Forest", b:"Desert", category:"places"},
  {id:'ss-0014', a:"Pancakes", b:"Toast", category:"food"},
  {id:'ss-0015', a:"Snow", b:"Sunshine", category:"weather"},
  {id:'ss-0016', a:"Horses", b:"Birds", category:"animals"},
  {id:'ss-0017', a:"A map", b:"Wander and see", category:"adventure"},
  {id:'ss-0018', a:"Popcorn", b:"Chocolate", category:"food"},
  {id:'ss-0019', a:"Crackling fire", b:"Ocean waves", category:"senses"},
  {id:'ss-0020', a:"Camping", b:"A cosy inn", category:"adventure"},
  {id:'ss-0021', a:"Autumn leaves", b:"Spring blossom", category:"weather"},
  {id:'ss-0022', a:"Handwritten", b:"Typed", category:"comfort"},
  {id:'ss-0023', a:"A river", b:"A lake", category:"places"},
  {id:'ss-0024', a:"Crunchy", b:"Soft", category:"food"},
  {id:'ss-0025', a:"Owls", b:"Foxes", category:"animals"},
  {id:'ss-0026', a:"Morning quiet", b:"Evening quiet", category:"time"},
  {id:'ss-0027', a:"A big table", b:"A small table", category:"comfort"},
  {id:'ss-0028', a:"Soup", b:"Salad", category:"food"},
  {id:'ss-0029', a:"Fog", b:"Frost", category:"weather"},
  {id:'ss-0030', a:"A train", b:"A boat", category:"adventure"},
  {id:'ss-0031', a:"Lemon", b:"Lime", category:"food"},
  {id:'ss-0032', a:"Stars", b:"Clouds", category:"senses"},
  {id:'ss-0033', a:"A garden", b:"A balcony", category:"places"},
  {id:'ss-0034', a:"Butter", b:"Jam", category:"food"},
  {id:'ss-0035', a:"Bees", b:"Butterflies", category:"animals"},
  {id:'ss-0036', a:"Plan it all", b:"Decide that day", category:"adventure"},
  {id:'ss-0037', a:"Thick socks", b:"Bare feet", category:"comfort"},
  {id:'ss-0038', a:"A long walk", b:"A long nap", category:"time"},
  {id:'ss-0039', a:"Cinnamon", b:"Vanilla", category:"senses"},
  {id:'ss-0040', a:"An old house", b:"A new house", category:"places"},
  {id:'ss-0041', a:"Peaches", b:"Berries", category:"food"},
  {id:'ss-0042', a:"Thunder", b:"Stillness", category:"weather"},
  {id:'ss-0043', a:"Turtles", b:"Otters", category:"animals"},
  {id:'ss-0044', a:"The front row", b:"The back row", category:"comfort"},
  {id:'ss-0045', a:"Bread", b:"Rice", category:"food"},
  {id:'ss-0046', a:"A hammock", b:"An armchair", category:"comfort"},
  {id:'ss-0047', a:"A cave", b:"A treehouse", category:"adventure"},
  {id:'ss-0048', a:"Mint", b:"Ginger", category:"senses"},
  {id:'ss-0049', a:"A lighthouse", b:"A windmill", category:"places"},
  {id:'ss-0050', a:"Noodles", b:"Dumplings", category:"food"},
  {id:'ss-0051', a:"Puddles", b:"Dry paths", category:"weather"},
  {id:'ss-0052', a:"Elephants", b:"Whales", category:"animals"},
  {id:'ss-0053', a:"One big trip", b:"Many small trips", category:"adventure"},
  {id:'ss-0054', a:"Wooden spoons", b:"Metal spoons", category:"comfort"},
  {id:'ss-0055', a:"Apples", b:"Oranges", category:"food"},
  {id:'ss-0056', a:"A full moon", b:"No moon at all", category:"senses"},
  {id:'ss-0057', a:"A meadow", b:"A cliff top", category:"places"},
  {id:'ss-0058', a:"Porridge", b:"Cereal", category:"food"},
  {id:'ss-0059', a:"A breeze", b:"Perfect stillness", category:"weather"},
  {id:'ss-0060', a:"Frogs", b:"Squirrels", category:"animals"},
  {id:'ss-0061', a:"Take the stairs", b:"Take the lift", category:"time"},
  {id:'ss-0062', a:"A quilt", b:"A blanket", category:"comfort"},
  {id:'ss-0063', a:"Olives", b:"Pickles", category:"food"},
  {id:'ss-0064', a:"Pine", b:"Sea air", category:"senses"},
  {id:'ss-0065', a:"An island", b:"A valley", category:"places"},
  {id:'ss-0066', a:"Cake", b:"Pie", category:"food"},
  {id:'ss-0067', a:"Grey skies", b:"Bright glare", category:"weather"},
  {id:'ss-0068', a:"Deer", b:"Rabbits", category:"animals"},
  {id:'ss-0069', a:"Arrive early", b:"Arrive just in time", category:"time"},
  {id:'ss-0070', a:"A window open", b:"A window shut", category:"comfort"},
  {id:'ss-0071', a:"Garlic", b:"Chilli", category:"food"},
  {id:'ss-0072', a:"Church bells", b:"Birdsong", category:"senses"},
  {id:'ss-0073', a:"A market", b:"A quiet shop", category:"places"},
  {id:'ss-0074', a:"Mushrooms", b:"Peppers", category:"food"},
  {id:'ss-0075', a:"A misty morning", b:"A crisp afternoon", category:"weather"},
  {id:'ss-0076', a:"Hedgehogs", b:"Badgers", category:"animals"},
  {id:'ss-0077', a:"Finish it today", b:"Sleep on it", category:"time"},
  {id:'ss-0078', a:"A stone floor", b:"A wooden floor", category:"comfort"},
  {id:'ss-0079', a:"Honey", b:"Maple syrup", category:"food"},
  {id:'ss-0080', a:"Distant thunder", b:"A close cricket", category:"senses"},
  {id:'ss-0081', a:"A canal", b:"A coastline", category:"places"},
  {id:'ss-0082', a:"Roast potatoes", b:"Chips", category:"food"},
  {id:'ss-0083', a:"A hot day", b:"A cool day", category:"weather"},
  {id:'ss-0084', a:"Herons", b:"Kingfishers", category:"animals"},
  {id:'ss-0085', a:"Front of the bus", b:"Back of the bus", category:"time"},
  {id:'ss-0086', a:"A candle", b:"A lamp", category:"comfort"},
  {id:'ss-0087', a:"Strawberries", b:"Cherries", category:"food"},
  {id:'ss-0088', a:"Fresh laundry", b:"Fresh bread", category:"senses"},
  {id:'ss-0089', a:"A hill fort", b:"A harbour", category:"places"},
  {id:'ss-0090', a:"Cheese", b:"Chocolate", category:"food"},
  {id:'ss-0091', a:"First snow", b:"Last warm day", category:"weather"},
  {id:'ss-0092', a:"Moths", b:"Dragonflies", category:"animals"},
  {id:'ss-0093', a:"Do it now", b:"Save it for later", category:"time"},
  {id:'ss-0094', a:"A big mug", b:"A small cup", category:"comfort"},
  {id:'ss-0095', a:"A stone path", b:"A grass path", category:"places"},
  {id:'ss-0096', a:"A long story", b:"A short one", category:"comfort"},
  {id:'ss-0097', a:"Barely warm toast", b:"Properly dark toast", category:"food"},
  {id:'ss-0098', a:"Eat the cone", b:"Leave the cone", category:"food"},
  {id:'ss-0099', a:"A waterfall", b:"A hot spring", category:"places"},
  {id:'ss-0100', a:"A pine wood", b:"An apple orchard", category:"places"},
  {id:'ss-0101', a:"Sand dunes", b:"Rock pools", category:"places"},
  {id:'ss-0102', a:"A hedge maze", b:"A wildflower field", category:"places"},
  {id:'ss-0103', a:"A log cabin", b:"A stone cottage", category:"places"},
  {id:'ss-0104', a:"A city park", b:"A wild wood", category:"places"},
  {id:'ss-0105', a:"A quiet library", b:"A busy cafe", category:"places"},
  {id:'ss-0106', a:"Big open sky", b:"Tall close trees", category:"senses"},
  {id:'ss-0107', a:"A snowy peak", b:"A green hill", category:"places"},
  {id:'ss-0108', a:"A castle keep", b:"A walled garden", category:"places"},
  {id:'ss-0109', a:"A city rooftop", b:"A quiet courtyard", category:"places"},
  {id:'ss-0110', a:"A country lane", b:"A coast road", category:"adventure"},
  {id:'ss-0111', a:"A rope bridge", b:"Stepping stones", category:"adventure"},
  {id:'ss-0112', a:"A balloon ride", b:"A canoe trip", category:"adventure"},
  {id:'ss-0113', a:"A mountain pass", b:"A river crossing", category:"adventure"},
  {id:'ss-0114', a:"Dark starry hills", b:"Bright city lights", category:"senses"},
  {id:'ss-0115', a:"A picnic table", b:"A campfire", category:"comfort"},
  {id:'ss-0116', a:"Ketchup", b:"Mustard", category:"food"},
  {id:'ss-0117', a:"Jam then cream", b:"Cream then jam", category:"food"},
  {id:'ss-0118', a:"Cut in triangles", b:"Cut in squares", category:"food"},
  {id:'ss-0119', a:"Follow the recipe", b:"Make it up", category:"food"},
  {id:'ss-0120', a:"Fizzy water", b:"Still water", category:"food"},
  {id:'ss-0121', a:"A starter", b:"A pudding", category:"food"},
  {id:'ss-0122', a:"Cheese on toast", b:"Beans on toast", category:"food"},
  {id:'ss-0123', a:"Scrambled eggs", b:"Boiled eggs", category:"food"},
  {id:'ss-0124', a:"In a cone", b:"In a bowl", category:"food"},
  {id:'ss-0125', a:"Sauce on top", b:"Sauce on side", category:"food"},
  {id:'ss-0126', a:"Best bit first", b:"Best bit last", category:"time"},
  {id:'ss-0127', a:"A picnic", b:"The kitchen table", category:"places"},
  {id:'ss-0128', a:"A hot lunch", b:"A cold lunch", category:"food"},
  {id:'ss-0129', a:"Waffles", b:"French toast", category:"food"},
  {id:'ss-0130', a:"With ice", b:"No ice", category:"food"},
  {id:'ss-0131', a:"Through a straw", b:"From the glass", category:"comfort"},
  {id:'ss-0132', a:"Lightly toasted", b:"Well toasted", category:"food"},
  {id:'ss-0133', a:"Custard", b:"Cream", category:"food"},
  {id:'ss-0134', a:"The usual", b:"Something new", category:"adventure"},
  {id:'ss-0135', a:"A barbecue", b:"A roast dinner", category:"food"},
  {id:'ss-0136', a:"Marshmallows on", b:"Just the cocoa", category:"comfort"},
  {id:'ss-0137', a:"A big breakfast", b:"A big dinner", category:"time"},
  {id:'ss-0138', a:"Breakfast in bed", b:"At the table", category:"comfort"},
  {id:'ss-0139', a:"A long meal", b:"A quick meal", category:"time"},
  {id:'ss-0140', a:"Curtains open", b:"Curtains closed", category:"comfort"},
  {id:'ss-0141', a:"Kitchen music", b:"Quiet kitchen", category:"senses"},
  {id:'ss-0142', a:"Line dried", b:"Machine dried", category:"comfort"},
  {id:'ss-0143', a:"At the table", b:"On a tray", category:"comfort"},
  {id:'ss-0144', a:"Lights low", b:"Lights bright", category:"senses"},
  {id:'ss-0145', a:"Same mug always", b:"A different mug", category:"comfort"},
  {id:'ss-0146', a:"Follow the recipe", b:"Cook by feel", category:"food"},
  {id:'ss-0147', a:"Leftovers cold", b:"Leftovers warmed", category:"food"},
  {id:'ss-0148', a:"Milk in first", b:"Tea in first", category:"food"},
  {id:'ss-0149', a:"A busy house", b:"A quiet house", category:"senses"},
  {id:'ss-0150', a:"A tea towel", b:"The drying rack", category:"comfort"},
  {id:'ss-0151', a:"The kitchen", b:"The living room", category:"places"},
  {id:'ss-0152', a:"A wall calendar", b:"A pocket notebook", category:"time"},
  {id:'ss-0153', a:"A jigsaw", b:"Playing cards", category:"comfort"},
  {id:'ss-0154', a:"By the window", b:"By the fire", category:"comfort"},
  {id:'ss-0155', a:"Your usual seat", b:"Wherever is free", category:"comfort"},
  {id:'ss-0156', a:"Dark toast", b:"Pale toast", category:"food"},
  {id:'ss-0157', a:"Take an umbrella", b:"Trust the sky", category:"weather"},
  {id:'ss-0158', a:"Hot water bottle", b:"A warm drink", category:"comfort"},
  {id:'ss-0159', a:"Weekend at home", b:"Weekend out", category:"adventure"},
  {id:'ss-0160', a:"Big fluffy clouds", b:"Clear blue sky", category:"weather"},
  {id:'ss-0161', a:"An umbrella", b:"A raincoat", category:"weather"},
  {id:'ss-0162', a:"Deep snow", b:"Falling snow", category:"weather"},
  {id:'ss-0163', a:"A kite day", b:"A picnic day", category:"weather"},
  {id:'ss-0164', a:"Watch the storm", b:"Curl up inside", category:"weather"},
  {id:'ss-0165', a:"Soft drizzle", b:"Sudden downpour", category:"weather"},
  {id:'ss-0166', a:"Penguins", b:"Polar bears", category:"animals"},
  {id:'ss-0167', a:"Goats", b:"Sheep", category:"animals"},
  {id:'ss-0168', a:"Foals", b:"Lambs", category:"animals"},
  {id:'ss-0169', a:"Crabs", b:"Starfish", category:"animals"},
  {id:'ss-0170', a:"Ducks", b:"Swans", category:"animals"},
  {id:'ss-0171', a:"Chipmunks", b:"Meerkats", category:"animals"},
  {id:'ss-0172', a:"Tigers", b:"Pandas", category:"animals"},
  {id:'ss-0173', a:"A bluebell wood", b:"A sand dune", category:"places"},
  {id:'ss-0174', a:"An orchard", b:"A wildflower field", category:"places"},
  {id:'ss-0175', a:"A frosty window", b:"A steamy window", category:"senses"},
  {id:'ss-0176', a:"Northern lights", b:"A meteor shower", category:"senses"},
  {id:'ss-0177', a:"Cut grass", b:"Fallen leaves", category:"senses"},
  {id:'ss-0178', a:"Jumping in leaves", b:"Making a snowman", category:"adventure"},
  {id:'ss-0179', a:"Rock pooling", b:"Berry picking", category:"adventure"},
  {id:'ss-0180', a:"Birdwatching", b:"Stargazing", category:"adventure"},
  {id:'ss-0181', a:"Climbing a hill", b:"Following a stream", category:"adventure"},
  {id:'ss-0182', a:"A sun hat", b:"A woolly hat", category:"comfort"},
  {id:'ss-0183', a:"All at once", b:"Bit by bit", category:"time"},
  {id:'ss-0184', a:"Five more minutes", b:"Up at once", category:"time"},
  {id:'ss-0185', a:"A busy hour", b:"An empty hour", category:"time"},
  {id:'ss-0186', a:"Ten small jobs", b:"One big job", category:"time"},
  {id:'ss-0187', a:"Make a list", b:"Remember it", category:"time"},
  {id:'ss-0188', a:"No spoilers", b:"Tell me now", category:"comfort"},
  {id:'ss-0189', a:"A favourite again", b:"Something brand new", category:"comfort"},
  {id:'ss-0190', a:"Watch them all", b:"One a week", category:"comfort"},
  {id:'ss-0191', a:"Loud music", b:"A quiet room", category:"comfort"},
  {id:'ss-0192', a:"Talk it through", b:"Think it through", category:"comfort"},
  {id:'ss-0193', a:"Draw something", b:"Write something", category:"comfort"},
  {id:'ss-0194', a:"Potter about", b:"Sit and think", category:"comfort"},
  {id:'ss-0195', a:"Read the manual", b:"Press the buttons", category:"adventure"},
  {id:'ss-0196', a:"The scenic route", b:"The quickest route", category:"adventure"},
  {id:'ss-0197', a:"Lead the way", b:"Follow along", category:"adventure"},
  {id:'ss-0198', a:"Ask a friend", b:"Look it up", category:"adventure"},
  {id:'ss-0199', a:"Follow the recipe", b:"Guess the amounts", category:"food"},
  {id:'ss-0200', a:"A big batch", b:"Just tonight", category:"food"},
  {id:'ss-0201', a:"At the table", b:"On the sofa", category:"food"},
  {id:'ss-0202', a:"A gallery", b:"A workshop", category:"places"},
  {id:'ss-0203', a:"Watch the birds", b:"Watch the fish", category:"animals"},
  {id:'ss-0204', a:"Bring a coat", b:"Risk it", category:"weather"},
  {id:'ss-0205', a:"Photograph it", b:"Just look", category:"senses"},
  {id:'ss-0206', a:"Hum along", b:"Listen quietly", category:"senses"}
];
