/* FIRST FROST TRIVIA BANK

   Ordinary multiple choice trivia. In this game the trivia is the BACKDROP and
   the Frost console is the headline, so these questions are built to be fair and
   quick to read rather than fiendish. A question nobody can answer is not a
   knockout, it is a stalemate.

   ⭐ FORMAT RULE: options[0] is ALWAYS the correct answer. The game shuffles the
   options before showing them, so an author can never mismatch an answer to an
   index and a reviewer can audit a line by reading it left to right.

   Regenerate or extend with this exact prompt, then hand-audit every entry:

   "Write N multiple choice trivia questions for a family party knockout game.
   Rules: the question is one sentence under 95 characters. Four options, each
   under 30 characters. The first option must be the correct one. The three
   wrong options must be plainly wrong to somebody who knows the answer, and
   plausible to somebody who does not. General audience, no politics, no
   religion, no bodies, no violence, no brand names, NO DASH CHARACTERS OF ANY
   KIND. Difficulty should sit where roughly half a room of adults would get it
   right. Include a short recognizable source name. Output a JS array of objects
   with fields id, q, options, category, source. Categories: animals, space,
   food, history, science, world, words, plants."

   AUDIT RULE: check every answer against its named source before committing,
   and check that no wrong option is also defensible.

   Bank at 2026-08-08: 307 entries. */
window.FIRSTFROST_BANK = [
  {id:'ff-t001', q:"Which planet has the shortest day in our solar system?", options:["Jupiter","Mercury","Mars","Neptune"], category:"space", source:"NASA"},
  {id:'ff-t002', q:"What is the largest living structure on earth?", options:["The Great Barrier Reef","The Amazon rainforest","A giant sequoia","The Sahara"], category:"nature", source:"Britannica"},
  {id:'ff-t003', q:"Which of these is a fruit in botanical terms?", options:["Cucumber","Celery","Rhubarb","Lettuce"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t004', q:"How many strings does a standard violin have?", options:["Four","Six","Five","Eight"], category:"world", source:"Britannica"},
  {id:'ff-t005', q:"Which ocean is the deepest?", options:["Pacific","Atlantic","Indian","Arctic"], category:"world", source:"NOAA"},
  {id:'ff-t006', q:"What do you call a group of crows?", options:["A murder","A parliament","A gaggle","A pride"], category:"words", source:"Merriam-Webster"},
  {id:'ff-t007', q:"Which metal is liquid at room temperature?", options:["Mercury","Aluminium","Zinc","Nickel"], category:"science", source:"Royal Society"},
  {id:'ff-t008', q:"Roughly how long does light take to travel from the Sun to earth?", options:["Eight minutes","Eight seconds","Eight hours","Eight days"], category:"space", source:"NASA"},
  {id:'ff-t009', q:"Which country has the most time zones?", options:["France","Russia","The United States","China"], category:"world", source:"Britannica"},
  {id:'ff-t010', q:"What is the hardest natural substance on earth?", options:["Diamond","Quartz","Steel","Granite"], category:"science", source:"USGS"},
  {id:'ff-t011', q:"Which animal has the longest recorded lifespan?", options:["Ocean quahog clam","Galapagos tortoise","Blue whale","Elephant"], category:"animals", source:"National Geographic"},
  {id:'ff-t012', q:"What is the main ingredient in traditional hummus?", options:["Chickpeas","Lentils","White beans","Peas"], category:"food", source:"Britannica"},
  {id:'ff-t013', q:"Which of these instruments has the lowest range?", options:["Tuba","Trumpet","Clarinet","Flute"], category:"world", source:"Britannica"},
  {id:'ff-t014', q:"What is the largest desert on earth by area?", options:["Antarctica","The Sahara","The Gobi","The Arabian"], category:"world", source:"Britannica"},
  {id:'ff-t015', q:"Which gas makes up most of the air you are breathing?", options:["Nitrogen","Oxygen","Carbon dioxide","Argon"], category:"science", source:"NOAA"},
  {id:'ff-t016', q:"How many keys does a standard full size piano have?", options:["Eighty eight","Sixty one","Seventy six","One hundred"], category:"world", source:"Britannica"},
  {id:'ff-t017', q:"Which bird can fly backwards?", options:["Hummingbird","Swift","Kingfisher","Wren"], category:"animals", source:"Audubon"},
  {id:'ff-t018', q:"What was the first food eaten in space?", options:["Apple sauce","A sandwich","Chocolate","Dried beef"], category:"space", source:"NASA"},
  {id:'ff-t019', q:"Which sea has no coastline at all?", options:["The Sargasso Sea","The Coral Sea","The Baltic Sea","The Bering Sea"], category:"world", source:"NOAA"},
  {id:'ff-t020', q:"How many bones are in an adult giraffe neck?", options:["Seven","Twelve","Twenty","Thirty two"], category:"animals", source:"Britannica"},
  {id:'ff-t021', q:"Which of these was invented first?", options:["The fax machine","The telephone","The radio","The lightbulb"], category:"history", source:"Smithsonian"},
  {id:'ff-t022', q:"What colour is a polar bear skin under its fur?", options:["Black","White","Pink","Grey"], category:"animals", source:"National Geographic"},
  {id:'ff-t023', q:"Which spice comes from a crocus flower?", options:["Saffron","Turmeric","Paprika","Cumin"], category:"food", source:"Kew Gardens"},
  {id:'ff-t024', q:"What is the tallest type of grass?", options:["Bamboo","Sugar cane","Pampas grass","Rye"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t025', q:"Which planet spins on its side compared with the others?", options:["Uranus","Saturn","Venus","Mars"], category:"space", source:"NASA"},
  {id:'ff-t026', q:"What does a philatelist collect?", options:["Stamps","Coins","Butterflies","Maps"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t027', q:"Which is the only continent with no active volcanoes?", options:["Australia","Europe","Africa","South America"], category:"world", source:"USGS"},
  {id:'ff-t028', q:"How many hearts does an earthworm have?", options:["Five","One","Two","None"], category:"animals", source:"Britannica"},
  {id:'ff-t029', q:"What is dry ice made of?", options:["Carbon dioxide","Water","Nitrogen","Ammonia"], category:"science", source:"Royal Society"},
  {id:'ff-t030', q:"Which country gave the world the sandwich name?", options:["England","France","Germany","Italy"], category:"food", source:"Britannica"},
  {id:'ff-t031', q:"What is the study of fungi called?", options:["Mycology","Botany","Entomology","Geology"], category:"words", source:"Merriam-Webster"},
  {id:'ff-t032', q:"Which is the smallest country in the world by area?", options:["Vatican City","Monaco","San Marino","Malta"], category:"world", source:"Britannica"},
  {id:'ff-t033', q:"How long is a single day on Mars, roughly?", options:["Twenty four and a half hours","Ten hours","Forty hours","Twelve hours"], category:"space", source:"NASA"},
  {id:'ff-t034', q:"Which nut is used to make marzipan?", options:["Almond","Walnut","Hazelnut","Cashew"], category:"food", source:"Britannica"},
  {id:'ff-t035', q:"What is the loudest animal on earth?", options:["Sperm whale","Lion","Howler monkey","Elephant"], category:"animals", source:"National Geographic"},
  {id:'ff-t036', q:"Which of these is not a real cloud type?", options:["Stratofog","Cirrus","Cumulus","Nimbostratus"], category:"science", source:"Met Office"},
  {id:'ff-t037', q:"How many sides does a standard pencil usually have?", options:["Six","Four","Eight","Five"], category:"world", source:"Britannica"},
  {id:'ff-t038', q:"Which tree produces acorns?", options:["Oak","Beech","Maple","Ash"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t039', q:"What was the first item sold over the internet?", options:["A book","A record","A pizza","A watch"], category:"history", source:"Smithsonian"},
  {id:'ff-t040', q:"Which body of water is the saltiest?", options:["The Dead Sea","The Red Sea","The Mediterranean","The Caspian Sea"], category:"world", source:"Britannica"},
  {id:'ff-t041', q:"Which animal can run the fastest over land?", options:["The cheetah","The lion","The greyhound","The ostrich"], category:"animals", source:"National Geographic"},
  {id:'ff-t042', q:"What is a baby kangaroo called?", options:["A joey","A cub","A kit","A calf"], category:"animals", source:"Britannica"},
  {id:'ff-t043', q:"What is the largest animal ever known to have lived?", options:["The blue whale","The African elephant","The giant squid","The saltwater crocodile"], category:"animals", source:"National Geographic"},
  {id:'ff-t044', q:"Which is the largest species of shark?", options:["The whale shark","The great white shark","The hammerhead shark","The tiger shark"], category:"animals", source:"NOAA"},
  {id:'ff-t045', q:"Which living bird lays the largest egg?", options:["The ostrich","The emu","The albatross","The swan"], category:"animals", source:"Britannica"},
  {id:'ff-t046', q:"Which of these animals is the only mammal that can truly fly?", options:["The bat","The flying squirrel","The sugar glider","The flying fish"], category:"animals", source:"Britannica"},
  {id:'ff-t047', q:"Which sea creature has three hearts?", options:["The octopus","The clam","The jellyfish","The crab"], category:"animals", source:"NOAA"},
  {id:'ff-t048', q:"Which of these can regrow a lost arm?", options:["A starfish","A snail","A tortoise","A goldfish"], category:"animals", source:"NOAA"},
  {id:'ff-t049', q:"How many humps does a Bactrian camel have?", options:["Two","One","Three","Four"], category:"animals", source:"Britannica"},
  {id:'ff-t050', q:"Which is the largest rodent in the world?", options:["The capybara","The beaver","The porcupine","The otter"], category:"animals", source:"National Geographic"},
  {id:'ff-t051', q:"Which is the largest of the big cats?", options:["The tiger","The lion","The jaguar","The leopard"], category:"animals", source:"National Geographic"},
  {id:'ff-t052', q:"Which gentle sea mammal is nicknamed the sea cow?", options:["The manatee","The walrus","The seal","The dolphin"], category:"animals", source:"NOAA"},
  {id:'ff-t053', q:"Which bird reaches the fastest speed when it dives through the air?", options:["The peregrine falcon","The golden eagle","The swift","The albatross"], category:"animals", source:"Audubon"},
  {id:'ff-t054', q:"Which of these animals is an amphibian?", options:["A newt","A lizard","A snake","A tortoise"], category:"animals", source:"Britannica"},
  {id:'ff-t055', q:"In a honeybee hive, which bee lays nearly all of the eggs?", options:["The queen","A worker bee","A drone","A scout bee"], category:"animals", source:"Britannica"},
  {id:'ff-t056', q:"Which insects build a nest of chewed wood pulp that looks like paper?", options:["Wasps","Ants","Beetles","Moths"], category:"animals", source:"Natural History Museum"},
  {id:'ff-t057', q:"What is a group of wolves called?", options:["A pack","A pride","A herd","A shoal"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t058', q:"What is a young swan called?", options:["A cygnet","A duckling","A gosling","A fawn"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t059', q:"What do you call a scientist who studies birds?", options:["An ornithologist","A botanist","A geologist","A cartographer"], category:"words", source:"Britannica"},
  {id:'ff-t060', q:"What word describes an animal that is active at night?", options:["Nocturnal","Migratory","Aquatic","Herbivore"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t061', q:"Which is the tallest tree species in the world?", options:["The coast redwood","The giant sequoia","The Douglas fir","The English oak"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t062', q:"What does each ring inside a tree trunk usually stand for?", options:["One year of growth","One rainy day","One lost branch","One hundred leaves"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t063', q:"Which plant produces the largest single flower on earth?", options:["Rafflesia","The sunflower","The lotus","The magnolia"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t064', q:"Which tree is known for white bark that peels away in papery strips?", options:["Birch","Oak","Pine","Willow"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t065', q:"What does the Beaufort scale measure?", options:["Wind speed","Rainfall","Snow depth","Earthquakes"], category:"science", source:"Met Office"},
  {id:'ff-t066', q:"Which planet has the giant storm called the Great Red Spot?", options:["Jupiter","Saturn","Mars","Venus"], category:"space", source:"NASA"},
  {id:'ff-t067', q:"Which galaxy does earth sit in?", options:["The Milky Way","Andromeda","Orion","The Great Bear"], category:"space", source:"NASA"},
  {id:'ff-t068', q:"Which planet is the hottest in our solar system?", options:["Venus","Mercury","Mars","Jupiter"], category:"space", source:"NASA"},
  {id:'ff-t069', q:"What was the name of the first satellite sent into orbit?", options:["Sputnik 1","Explorer 1","Vanguard 1","Telstar"], category:"history", source:"Smithsonian"},
  {id:'ff-t070', q:"Who was the first person to walk on the moon?", options:["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","John Glenn"], category:"space", source:"NASA"},
  {id:'ff-t071', q:"Who was the first person to travel into space?", options:["Yuri Gagarin","Alan Shepard","John Glenn","Neil Armstrong"], category:"space", source:"Britannica"},
  {id:'ff-t072', q:"Which Apollo mission first landed people on the moon?", options:["Apollo 11","Apollo 8","Apollo 10","Apollo 13"], category:"space", source:"NASA"},
  {id:'ff-t073', q:"What does a light year measure?", options:["Distance","Time","Brightness","Speed"], category:"science", source:"Royal Observatory Greenwich"},
  {id:'ff-t074', q:"Which former ninth planet is now called a dwarf planet?", options:["Pluto","Ceres","Eris","Charon"], category:"space", source:"Britannica"},
  {id:'ff-t075', q:"The asteroid belt sits between which two planets?", options:["Mars and Jupiter","Earth and Mars","Jupiter and Saturn","Venus and earth"], category:"space", source:"NASA"},
  {id:'ff-t076', q:"What is the largest volcano in the solar system?", options:["Olympus Mons","Valles Marineris","Mauna Kea","Mount Everest"], category:"space", source:"NASA"},
  {id:'ff-t077', q:"Roughly how long does the moon take to circle earth once?", options:["About a month","About a week","About a year","About a day"], category:"space", source:"Royal Observatory Greenwich"},
  {id:'ff-t078', q:"Why do we always see the same side of the moon?", options:["It spins once each orbit","It does not spin at all","Earth holds it still","It has no far side"], category:"space", source:"NASA"},
  {id:'ff-t079', q:"What is the Sun mostly made of?", options:["Hydrogen","Iron","Oxygen","Molten rock"], category:"space", source:"NASA"},
  {id:'ff-t080', q:"What is the name of the largest moon of Saturn?", options:["Titan","Europa","Triton","Io"], category:"space", source:"NASA"},
  {id:'ff-t081', q:"What do we call a space rock once it lands on the ground?", options:["A meteorite","A meteor","A comet","A nebula"], category:"space", source:"Britannica"},
  {id:'ff-t082', q:"Which way does the tail of a comet always point?", options:["Away from the Sun","Toward the Sun","Toward earth","Straight down"], category:"space", source:"NASA"},
  {id:'ff-t083', q:"What did the Voyager probes carry that holds sounds from earth?", options:["A golden record","A stone tablet","A silver flag","A glass globe"], category:"space", source:"NASA"},
  {id:'ff-t084', q:"Which famous telescope launched in 1990 and still orbits earth?", options:["Hubble","Webb","Kepler","Chandra"], category:"space", source:"NASA"},
  {id:'ff-t085', q:"Roughly how many people have walked on the moon?", options:["Twelve","Two","Twenty four","Fifty"], category:"space", source:"NASA"},
  {id:'ff-t086', q:"Which space station has hosted crews in orbit since the year 2000?", options:["International Space Station","Mir","Skylab","Salyut 1"], category:"space", source:"ESA"},
  {id:'ff-t087', q:"What happens during a solar eclipse?", options:["The moon covers the Sun","Earth covers the Sun","The Sun covers the moon","Clouds cover the Sun"], category:"science", source:"Royal Observatory Greenwich"},
  {id:'ff-t088', q:"Who first used a telescope to see moons circling Jupiter?", options:["Galileo","Isaac Newton","Nicolaus Copernicus","Johannes Kepler"], category:"history", source:"Britannica"},
  {id:'ff-t089', q:"Which planet do the rovers Curiosity and Perseverance explore?", options:["Mars","The moon","Venus","Titan"], category:"space", source:"NASA"},
  {id:'ff-t090', q:"Which is the longest river in Africa?", options:["The Nile","The Congo","The Niger","The Zambezi"], category:"world", source:"Britannica"},
  {id:'ff-t091', q:"Which ocean lies between Africa and Australia?", options:["The Indian Ocean","The Atlantic Ocean","The Pacific Ocean","The Arctic Ocean"], category:"world", source:"NOAA"},
  {id:'ff-t092', q:"Which mountain range is the traditional divide between Europe and Asia?", options:["The Urals","The Alps","The Pyrenees","The Carpathians"], category:"world", source:"Britannica"},
  {id:'ff-t093', q:"Machu Picchu sits high in the mountains of which country?", options:["Peru","Mexico","Chile","Brazil"], category:"history", source:"UNESCO"},
  {id:'ff-t094', q:"The ancient rock city of Petra stands in which country?", options:["Jordan","Egypt","Morocco","Turkey"], category:"history", source:"UNESCO"},
  {id:'ff-t095', q:"Which is the largest island in the world?", options:["Greenland","New Guinea","Borneo","Madagascar"], category:"world", source:"Britannica"},
  {id:'ff-t096', q:"Which canal links the Atlantic and Pacific oceans?", options:["The Panama Canal","The Suez Canal","The Erie Canal","The Grand Canal"], category:"world", source:"Britannica"},
  {id:'ff-t097', q:"Which river flows through the Grand Canyon?", options:["The Colorado River","The Rio Grande","The Missouri River","The Hudson River"], category:"world", source:"National Geographic"},
  {id:'ff-t098', q:"Which city is the capital of Australia?", options:["Canberra","Sydney","Melbourne","Brisbane"], category:"world", source:"Britannica"},
  {id:'ff-t099', q:"Which country is famous for its long coastal fjords?", options:["Norway","Ireland","Portugal","Poland"], category:"world", source:"Britannica"},
  {id:'ff-t100', q:"Which of the world's oceans is the smallest?", options:["The Arctic","The Indian","The Southern","The Atlantic"], category:"world", source:"NOAA"},
  {id:'ff-t101', q:"Mount Kilimanjaro rises in which country?", options:["Tanzania","Kenya","Uganda","Ethiopia"], category:"world", source:"UNESCO"},
  {id:'ff-t102', q:"The Leaning Tower stands in which Italian city?", options:["Pisa","Milan","Naples","Turin"], category:"world", source:"UNESCO"},
  {id:'ff-t103', q:"Which two countries share the longest land border in the world?", options:["Canada and the United States","Russia and China","Chile and Argentina","India and Bangladesh"], category:"world", source:"Britannica"},
  {id:'ff-t104', q:"Which is the longest river in South America?", options:["The Amazon","The Orinoco","The Magdalena","The Rio de la Plata"], category:"world", source:"Britannica"},
  {id:'ff-t105', q:"Most of the Amazon rainforest sits inside which country?", options:["Brazil","Peru","Colombia","Venezuela"], category:"world", source:"National Geographic"},
  {id:'ff-t106', q:"Wellington is the capital city of which country?", options:["New Zealand","Australia","South Africa","Canada"], category:"world", source:"Britannica"},
  {id:'ff-t107', q:"Which lake has the largest surface area of any freshwater lake?", options:["Lake Superior","Lake Baikal","Lake Victoria","Lake Tanganyika"], category:"world", source:"NOAA"},
  {id:'ff-t108', q:"Stonehenge stands in which part of the United Kingdom?", options:["England","Scotland","Wales","Northern Ireland"], category:"history", source:"English Heritage"},
  {id:'ff-t109', q:"Which sea lies between Italy and the Balkan coast?", options:["The Adriatic Sea","The Aegean Sea","The Baltic Sea","The Caspian Sea"], category:"world", source:"Britannica"},
  {id:'ff-t110', q:"What is the tallest waterfall in the world?", options:["Angel Falls","Niagara Falls","Victoria Falls","Iguazu Falls"], category:"world", source:"National Geographic"},
  {id:'ff-t111', q:"Which city is the capital of Iceland?", options:["Reykjavik","Oslo","Helsinki","Bergen"], category:"world", source:"Britannica"},
  {id:'ff-t112', q:"Which continent has the most countries in it?", options:["Africa","Asia","Europe","South America"], category:"world", source:"Britannica"},
  {id:'ff-t113', q:"Which mountain range runs down the western side of South America?", options:["The Andes","The Rockies","The Himalayas","The Atlas Mountains"], category:"world", source:"Britannica"},
  {id:'ff-t114', q:"Which is the largest state in the United States by area?", options:["Alaska","Texas","California","Montana"], category:"world", source:"Britannica"},
  {id:'ff-t115', q:"Bubble wrap was first invented to be used as what?", options:["Textured wallpaper","Tent lining","Shoe padding","Pool floats"], category:"history", source:"Smithsonian"},
  {id:'ff-t116', q:"The microwave oven came from an accident while testing which invention?", options:["Radar","Television","The telephone","The refrigerator"], category:"science", source:"Smithsonian"},
  {id:'ff-t117', q:"What did people rub on paper to lift pencil marks before rubber erasers?", options:["Bread","Candle wax","Chalk dust","Wool cloth"], category:"history", source:"Britannica"},
  {id:'ff-t118', q:"Which frozen treat began when a boy left a drink outside on a cold night?", options:["The ice lolly","The ice cream cone","The doughnut","Candy floss"], category:"food", source:"Smithsonian"},
  {id:'ff-t119', q:"Which fastener was inspired by burrs sticking to a coat after a country walk?", options:["Hook and loop tape","The zip","The safety pin","The press stud"], category:"science", source:"Smithsonian"},
  {id:'ff-t120', q:"What were the earliest umbrellas mainly used to keep off?", options:["The sun","Rain","Snow","Wind"], category:"history", source:"Britannica"},
  {id:'ff-t121', q:"What was the first paper in ancient China mainly made from?", options:["Mulberry bark and rags","Wheat straw only","Crushed shells","Animal skins"], category:"history", source:"Britannica"},
  {id:'ff-t122', q:"What did ancient Egyptians write on long before paper reached them?", options:["Papyrus","Parchment","Birch bark","Silk"], category:"history", source:"British Museum"},
  {id:'ff-t123', q:"Which ancient region is usually credited with inventing the wheel?", options:["Mesopotamia","Ancient Egypt","Ancient Greece","Northern China"], category:"history", source:"Britannica"},
  {id:'ff-t124', q:"What colour were most carrots before orange ones became common?", options:["Purple","Bright blue","Pale pink","Deep green"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t125', q:"Which of these foods came to Europe from the Americas?", options:["The tomato","The apple","The pear","The onion"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t126', q:"What were the first tea bags made from?", options:["Silk","Paper","Cotton wool","Thin card"], category:"food", source:"Britannica"},
  {id:'ff-t127', q:"What was the first escalator shown to the public as?", options:["A fairground ride","A factory lift","A ship gangway","A hotel staircase"], category:"history", source:"Smithsonian"},
  {id:'ff-t128', q:"Which children's toy was first sold as a wallpaper cleaner?", options:["Modelling dough","The yo yo","Building blocks","The spinning top"], category:"history", source:"Smithsonian"},
  {id:'ff-t129', q:"Which food has been found still edible in jars thousands of years old?", options:["Honey","Bread","Cheese","Jam"], category:"food", source:"National Geographic"},
  {id:'ff-t130', q:"What was the earliest ketchup mainly made from?", options:["Fish","Tomatoes","Beetroot","Cabbage"], category:"food", source:"Smithsonian"},
  {id:'ff-t131', q:"How did the ancient Maya usually enjoy chocolate?", options:["As a bitter drink","As a solid bar","As a cake icing","As a sweet powder"], category:"food", source:"Smithsonian"},
  {id:'ff-t132', q:"Which continent is the coffee plant originally from?", options:["Africa","South America","Asia","Europe"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t133', q:"Where did potatoes first grow wild before farmers spread them?", options:["South America","Ireland","Eastern Europe","West Africa"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t134', q:"Which flower reached the Netherlands from Turkey and made the country famous?", options:["The tulip","The daffodil","The sunflower","The bluebell"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t135', q:"Which ancient people gave us the names of the months we still use?", options:["The Romans","The Greeks","The Egyptians","The Vikings"], category:"words", source:"Britannica"},
  {id:'ff-t136', q:"Where did the digits 0 to 9 that we write today first come from?", options:["India","Ancient Rome","Ancient Greece","Egypt"], category:"science", source:"Britannica"},
  {id:'ff-t137', q:"Which of these was invented in ancient China?", options:["The compass","The telescope","The steam engine","The barometer"], category:"history", source:"Britannica"},
  {id:'ff-t138', q:"Which Italian city gave its name to the blue cloth we call jeans?", options:["Genoa","Venice","Naples","Florence"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t139', q:"Which country holds the oldest known bowl of noodles ever found?", options:["China","Italy","Greece","Turkey"], category:"food", source:"National Geographic"},
  {id:'ff-t140', q:"Frost forms when water vapour turns straight into which state of matter?", options:["Solid","Liquid","Gas","Plasma"], category:"science", source:"Met Office"},
  {id:'ff-t141', q:"Thunder is the sound made by what?", options:["Air heated by lightning","Clouds bumping together","Rain hitting the ground","Wind snapping branches"], category:"science", source:"Met Office"},
  {id:'ff-t142', q:"Which instrument is used to measure wind speed?", options:["Anemometer","Barometer","Hygrometer","Sundial"], category:"science", source:"Met Office"},
  {id:'ff-t143', q:"A barometer measures which of these?", options:["Air pressure","Wind speed","Rainfall","Hours of sunshine"], category:"science", source:"Met Office"},
  {id:'ff-t144', q:"Counting the seconds between lightning and thunder tells you what?", options:["How far away the storm is","How strong the storm is","How long the rain lasts","Which way the wind blows"], category:"science", source:"NOAA"},
  {id:'ff-t145', q:"Seen from high above, what shape is a rainbow?", options:["A full circle","A square","A straight line","A spiral"], category:"science", source:"Met Office"},
  {id:'ff-t146', q:"Why does the sky look blue on a clear day?", options:["Air scatters blue light","It reflects the oceans","Clouds are blue inside","Sunlight is blue"], category:"science", source:"NASA"},
  {id:'ff-t147', q:"What gives the earth its seasons?", options:["Its tilted axis","Its distance from the sun","Sunspots","The pull of the moon"], category:"space", source:"NASA"},
  {id:'ff-t148', q:"Ice floats because freezing makes water do what?", options:["Expand","Shrink","Get heavier","Turn salty"], category:"science", source:"Royal Society"},
  {id:'ff-t149', q:"Water boils at a lower temperature in which place?", options:["Up a high mountain","At the seaside","Deep inside a cave","Beside a lake"], category:"science", source:"Britannica"},
  {id:'ff-t150', q:"Why is salt spread on roads before a freezing night?", options:["It lowers the freezing point","It warms the road surface","It dries out the air","It makes the ice harder"], category:"science", source:"Met Office"},
  {id:'ff-t151', q:"Hail is made inside which kind of cloud?", options:["A thunderstorm cloud","A thin wispy cloud","A low sea mist","A morning haze"], category:"science", source:"NOAA"},
  {id:'ff-t152', q:"How many points does a snowflake crystal usually have?", options:["Six","Four","Eight","Three"], category:"science", source:"Met Office"},
  {id:'ff-t153', q:"A compass needle lines up with what?", options:["The earth's magnetic field","The North Star","The prevailing wind","The midday sun"], category:"science", source:"Britannica"},
  {id:'ff-t154', q:"Steel is mostly iron mixed with a small amount of what?", options:["Carbon","Silver","Chalk","Lead"], category:"science", source:"Britannica"},
  {id:'ff-t155', q:"Bronze is copper mixed with which other metal?", options:["Tin","Zinc","Iron","Silver"], category:"history", source:"Britannica"},
  {id:'ff-t156', q:"Ordinary window glass is made mainly by melting what?", options:["Sand","Clay","Iron ore","Coal"], category:"science", source:"Britannica"},
  {id:'ff-t157', q:"The lead in a pencil is really made from which mineral?", options:["Graphite","Lead","Chalk","Quartz"], category:"science", source:"USGS"},
  {id:'ff-t158', q:"Hook and loop fasteners were inspired by which natural thing?", options:["Plant burrs","Bird feathers","Fish scales","Snail shells"], category:"plants", source:"Smithsonian"},
  {id:'ff-t159', q:"What is inside the gap between the two walls of a vacuum flask?", options:["Almost nothing at all","Warm water","Soft foam","Fine sand"], category:"science", source:"Britannica"},
  {id:'ff-t160', q:"A microwave oven heats food mainly by shaking which part of it?", options:["The water in it","The salt in it","The sugar in it","The plate"], category:"food", source:"Royal Institution"},
  {id:'ff-t161', q:"What makes bread dough rise before baking?", options:["Gas made by yeast","Salt in the flour","Cold from the fridge","Extra flour"], category:"food", source:"Britannica"},
  {id:'ff-t162', q:"Sound travels fastest through which of these?", options:["Steel","Air","Water","Empty space"], category:"science", source:"Britannica"},
  {id:'ff-t163', q:"Natural rubber starts out as a milky sap from what?", options:["A tree","A rock","A seashell","A mushroom"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t164', q:"Cotton fabric comes from which part of the plant?", options:["The seed pod","The root","The stem","The leaves"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t165', q:"Which vegetable is fermented to make sauerkraut?", options:["Cabbage","Carrot","Potato","Onion"], category:"food", source:"Britannica"},
  {id:'ff-t166', q:"Vanilla comes from the pod of which kind of plant?", options:["An orchid","A fern","A cactus","A palm"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t167', q:"Which of these fruits carries its seeds on the outside?", options:["Strawberry","Blueberry","Plum","Grape"], category:"food", source:"Britannica"},
  {id:'ff-t168', q:"What is the main ingredient in guacamole?", options:["Avocado","Cucumber","Courgette","Green pepper"], category:"food", source:"Britannica"},
  {id:'ff-t169', q:"Which grain is used to make a traditional risotto?", options:["Rice","Barley","Oats","Wheat"], category:"food", source:"Britannica"},
  {id:'ff-t170', q:"What does yeast do to bread dough?", options:["Makes it rise","Adds salt","Turns it green","Keeps it flat"], category:"food", source:"Royal Society"},
  {id:'ff-t171', q:"Which of these nuts grows underground?", options:["Peanut","Almond","Walnut","Pecan"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t172', q:"Which herb gives pesto its green colour and flavour?", options:["Basil","Parsley","Mint","Dill"], category:"food", source:"Britannica"},
  {id:'ff-t173', q:"Which part of the cinnamon tree gives us the spice?", options:["The bark","The root","The leaves","The berries"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t174', q:"A raisin is a dried version of which fruit?", options:["Grape","Plum","Apricot","Fig"], category:"food", source:"Britannica"},
  {id:'ff-t175', q:"What is tofu made from?", options:["Soybeans","Rice","Corn","Peanuts"], category:"food", source:"Britannica"},
  {id:'ff-t176', q:"Which of these vegetables grows on a trailing vine?", options:["Pumpkin","Cabbage","Broccoli","Cauliflower"], category:"plants", source:"Royal Horticultural Society"},
  {id:'ff-t177', q:"Which spice is a dried flower bud?", options:["Cloves","Nutmeg","Ginger","Black pepper"], category:"food", source:"Kew Gardens"},
  {id:'ff-t178', q:"Which of these citrus fruits is the smallest?", options:["Kumquat","Grapefruit","Orange","Lemon"], category:"food", source:"Britannica"},
  {id:'ff-t179', q:"What are capers before they are pickled?", options:["Flower buds","Small berries","Tree seeds","Tiny roots"], category:"food", source:"Britannica"},
  {id:'ff-t180', q:"What gives a chilli pepper its fiery kick?", options:["Capsaicin","Caffeine","Citric acid","Gluten"], category:"food", source:"Royal Society"},
  {id:'ff-t181', q:"Which bread is traditionally baked in a tandoor oven?", options:["Naan","Baguette","Ciabatta","Rye bread"], category:"food", source:"Britannica"},
  {id:'ff-t182', q:"What is a very young plant grown from a seed called?", options:["A seedling","A cutting","A graft","A bulb"], category:"plants", source:"Royal Horticultural Society"},
  {id:'ff-t183', q:"Which of these plants catches and eats insects?", options:["The Venus flytrap","The fern","The daisy","The ivy"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t184', q:"What is the green paste usually served beside sushi?", options:["Wasabi","Pesto","Guacamole","Mint sauce"], category:"food", source:"Britannica"},
  {id:'ff-t185', q:"Which part of the carrot plant do we normally eat?", options:["The root","The leaves","The flower","The seed pod"], category:"plants", source:"Royal Horticultural Society"},
  {id:'ff-t186', q:"In cooking, what does it mean to blanch a vegetable?", options:["Boil it briefly","Fry it in oil","Freeze it solid","Coat it in flour"], category:"food", source:"Larousse Gastronomique"},
  {id:'ff-t187', q:"Prunes are the dried form of which fruit?", options:["Plum","Apple","Peach","Cherry"], category:"food", source:"Britannica"},
  {id:'ff-t188', q:"Traditional polenta is made from which ground grain?", options:["Corn","Wheat","Rice","Oats"], category:"food", source:"Britannica"},
  {id:'ff-t189', q:"Which tree is tapped for the sap that becomes syrup?", options:["Maple","Oak","Willow","Apple"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t190', q:"Which of these animals is a marsupial?", options:["The koala","The sloth","The lemur","The meerkat"], category:"animals", source:"Britannica"},
  {id:'ff-t191', q:"Which is the largest species of penguin?", options:["The emperor penguin","The king penguin","The gentoo penguin","The little blue penguin"], category:"animals", source:"Britannica"},
  {id:'ff-t192', q:"Which of these creatures is not an insect?", options:["The spider","The ant","The beetle","The grasshopper"], category:"animals", source:"Natural History Museum"},
  {id:'ff-t193', q:"Most bats find their food in the dark mainly by using what?", options:["Echoes of their own calls","Very sharp night vision","A strong sense of smell","Warmth rising from grass"], category:"animals", source:"Britannica"},
  {id:'ff-t194', q:"What is the change from caterpillar to butterfly called?", options:["Metamorphosis","Hibernation","Pollination","Germination"], category:"animals", source:"Natural History Museum"},
  {id:'ff-t195', q:"What word describes an animal that eats both plants and other animals?", options:["Omnivore","Herbivore","Carnivore","Marsupial"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t196', q:"Which of these birds is unable to fly?", options:["The kiwi","The puffin","The pelican","The heron"], category:"animals", source:"Britannica"},
  {id:'ff-t197', q:"Which lizard is famous for changing the colour of its skin?", options:["The chameleon","The iguana","The Komodo dragon","The skink"], category:"animals", source:"Britannica"},
  {id:'ff-t198', q:"Which part of a snake picks up smells from the air?", options:["Its tongue","Its ears","Its tail","Its scales"], category:"animals", source:"Britannica"},
  {id:'ff-t199', q:"Which plant makes up almost all of a giant panda's food?", options:["Bamboo","Eucalyptus","Sugar cane","Clover"], category:"animals", source:"National Geographic"},
  {id:'ff-t200', q:"What do bees gather from flowers and turn into honey?", options:["Nectar","Sap","Dew","Rainwater"], category:"animals", source:"Britannica"},
  {id:'ff-t201', q:"Which of these trees keeps its leaves through the winter?", options:["The holly","The willow","The birch","The horse chestnut"], category:"plants", source:"Woodland Trust"},
  {id:'ff-t202', q:"Which gas do plants take in from the air to make their food?", options:["Carbon dioxide","Oxygen","Nitrogen","Helium"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t203', q:"What is the process plants use to make food from sunlight called?", options:["Photosynthesis","Pollination","Germination","Evaporation"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t204', q:"Which part of a flower makes the pollen?", options:["The stamen","The petal","The stalk","The sepal"], category:"plants", source:"Royal Horticultural Society"},
  {id:'ff-t205', q:"Which of these trees carries its seeds inside cones?", options:["The pine","The oak","The maple","The elm"], category:"plants", source:"Woodland Trust"},
  {id:'ff-t206', q:"Which of these plants spreads by spores instead of seeds?", options:["The fern","The rose","The oak","The daisy"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t207', q:"Which plant is famous for turning to follow the sun as it grows?", options:["The sunflower","The rose","The daisy","The poppy"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t208', q:"What do gardeners call a plant that lives for only one year?", options:["An annual","A perennial","A conifer","An evergreen"], category:"plants", source:"Royal Horticultural Society"},
  {id:'ff-t209', q:"Which part of a plant takes in water from the soil?", options:["The roots","The leaves","The flowers","The bark"], category:"plants", source:"Royal Horticultural Society"},
  {id:'ff-t210', q:"What is the yearly journey birds make to warmer places called?", options:["Migration","Hibernation","Pollination","Evolution"], category:"words", source:"Audubon"},
  {id:'ff-t211', q:"Which of these animals truly hibernates through the winter?", options:["The hedgehog","The fox","The deer","The rabbit"], category:"animals", source:"Wildlife Trusts"},
  {id:'ff-t212', q:"What is a young frog called before it grows its legs?", options:["A tadpole","A grub","A nymph","A fledgling"], category:"animals", source:"Britannica"},
  {id:'ff-t213', q:"Which is the heaviest land animal alive today?", options:["The African elephant","The hippopotamus","The white rhinoceros","The giraffe"], category:"animals", source:"National Geographic"},
  {id:'ff-t214', q:"Which of these mammals lays eggs?", options:["The platypus","The dolphin","The bat","The otter"], category:"animals", source:"Britannica"},
  {id:'ff-t215', q:"What is the green colouring in leaves that captures sunlight?", options:["Chlorophyll","Cellulose","Nectar","Starch"], category:"plants", source:"Kew Gardens"},
  {id:'ff-t216', q:"Which animal builds a lodge of sticks and mud in a river?", options:["The beaver","The otter","The badger","The heron"], category:"animals", source:"National Geographic"},
  {id:'ff-t217', q:"Which of these sea creatures is a mammal?", options:["The dolphin","The shark","The tuna","The squid"], category:"animals", source:"NOAA"},
  {id:'ff-t218', q:"Which of these animals belongs to the dog family?", options:["The fox","The hyena","The badger","The raccoon"], category:"animals", source:"Britannica"},
  {id:'ff-t219', q:"Which of these small animals is a mollusc?", options:["The snail","The ant","The crab","The woodlouse"], category:"animals", source:"Natural History Museum"},
  {id:'ff-t220', q:"Which mountain has the highest peak above sea level?", options:["Mount Everest","K2","Mont Blanc","Kilimanjaro"], category:"world", source:"National Geographic"},
  {id:'ff-t221', q:"Which country covers the largest land area in the world?", options:["Russia","Canada","China","Brazil"], category:"world", source:"Britannica"},
  {id:'ff-t222', q:"Which desert is known as the driest place on earth?", options:["The Atacama","The Gobi","The Kalahari","The Mojave"], category:"world", source:"National Geographic"},
  {id:'ff-t223', q:"Which ocean surrounds Antarctica?", options:["The Southern Ocean","The Indian Ocean","The Atlantic Ocean","The Arctic Ocean"], category:"world", source:"NOAA"},
  {id:'ff-t224', q:"What is the name of the deepest known place in the ocean?", options:["The Mariana Trench","The Bermuda Triangle","The Sargasso Sea","The Bay of Bengal"], category:"world", source:"NOAA"},
  {id:'ff-t225', q:"The Suez Canal links the Red Sea to which other sea?", options:["The Mediterranean","The Black Sea","The Caspian Sea","The Baltic Sea"], category:"world", source:"Britannica"},
  {id:'ff-t226', q:"What is the imaginary line at zero degrees longitude called?", options:["The prime meridian","The equator","The date line","The Arctic Circle"], category:"world", source:"Royal Observatory Greenwich"},
  {id:'ff-t227', q:"Which city is the capital of Canada?", options:["Ottawa","Toronto","Vancouver","Montreal"], category:"world", source:"Britannica"},
  {id:'ff-t228', q:"Which South American country is famously long and narrow?", options:["Chile","Peru","Ecuador","Bolivia"], category:"world", source:"Britannica"},
  {id:'ff-t229', q:"Which strait separates Spain from the north coast of Africa?", options:["The Strait of Gibraltar","The Bering Strait","The Bosphorus","The Strait of Dover"], category:"world", source:"Britannica"},
  {id:'ff-t230', q:"What do we call the place where a river flows into the sea?", options:["The mouth","The source","The bank","The bed"], category:"world", source:"Britannica"},
  {id:'ff-t231', q:"Which country is made up of more than seventeen thousand islands?", options:["Indonesia","Japan","Greece","The Philippines"], category:"world", source:"Britannica"},
  {id:'ff-t232', q:"Roughly how much of the earth's surface is covered by ocean?", options:["About seventy percent","About thirty percent","About half","About ninety percent"], category:"world", source:"NOAA"},
  {id:'ff-t233', q:"What mainly causes the ocean tides to rise and fall?", options:["The pull of the moon","Wind on the waves","Rivers flowing in","Rain out at sea"], category:"science", source:"NOAA"},
  {id:'ff-t234', q:"Which warm ocean current carries water north toward western Europe?", options:["The Gulf Stream","The Jet Stream","The Trade Winds","The Doldrums"], category:"world", source:"NOAA"},
  {id:'ff-t235', q:"Roughly how much of an iceberg sits below the water?", options:["About nine tenths","About half","About a quarter","Almost none"], category:"science", source:"USGS"},
  {id:'ff-t236', q:"Which of these best describes fog?", options:["A cloud at ground level","Smoke from warm soil","Frozen rain in the air","Fine dust from fields"], category:"science", source:"Met Office"},
  {id:'ff-t237', q:"What is the word for rain, snow and hail all taken together?", options:["Precipitation","Condensation","Evaporation","Humidity"], category:"science", source:"Met Office"},
  {id:'ff-t238', q:"Humidity is a measure of what in the air?", options:["Water vapour","Air pressure","Wind speed","Cloud height"], category:"science", source:"Met Office"},
  {id:'ff-t239', q:"What is the calm centre of a hurricane called?", options:["The eye","The core","The wall","The spine"], category:"science", source:"NOAA"},
  {id:'ff-t240', q:"Which type of cloud is the tall towering one that brings thunderstorms?", options:["Cumulonimbus","Cirrus","Stratus","Altocumulus"], category:"science", source:"Met Office"},
  {id:'ff-t241', q:"What is a monsoon?", options:["A seasonal rainy wind","A sudden sandstorm","A very high tide","A winter frost"], category:"science", source:"Met Office"},
  {id:'ff-t242', q:"What is a narrow spinning column of air that touches the ground called?", options:["A tornado","A hurricane","A monsoon","A blizzard"], category:"science", source:"NOAA"},
  {id:'ff-t243', q:"What is molten rock called once it reaches the surface?", options:["Lava","Magma","Basalt","Pumice"], category:"science", source:"USGS"},
  {id:'ff-t244', q:"Fossils are found most often in which kind of rock?", options:["Sedimentary","Igneous","Metamorphic","Volcanic glass"], category:"science", source:"Natural History Museum"},
  {id:'ff-t245', q:"The Mohs scale is used to compare what in minerals?", options:["Hardness","Weight","Age","Colour"], category:"science", source:"USGS"},
  {id:'ff-t246', q:"What is the ring of volcanoes around the edge of the Pacific called?", options:["The Ring of Fire","The Great Rift","The Gulf Stream","The Bermuda Triangle"], category:"science", source:"USGS"},
  {id:'ff-t247', q:"What are the giant moving slabs of the earth's outer shell called?", options:["Tectonic plates","Ocean currents","Lava flows","Fault lines"], category:"science", source:"USGS"},
  {id:'ff-t248', q:"In a cave, which of these hangs down from the ceiling?", options:["A stalactite","A stalagmite","A geode","A sand dune"], category:"science", source:"Britannica"},
  {id:'ff-t249', q:"What is a geyser?", options:["A jet of hot water and steam","A frozen waterfall","A deep ocean current","A desert whirlwind"], category:"science", source:"USGS"},
  {id:'ff-t250', q:"The Eiffel Tower was first built as the grand entrance to what kind of event?", options:["A world fair","An Olympic Games","A flower show","A car race"], category:"history", source:"Britannica"},
  {id:'ff-t251', q:"The green outer skin of the Statue of Liberty is made from which metal?", options:["Copper","Steel","Silver","Aluminium"], category:"world", source:"Britannica"},
  {id:'ff-t252', q:"The Great Wall of China was built mainly to serve as what?", options:["A defensive barrier","A water channel","A market road","A railway route"], category:"history", source:"Britannica"},
  {id:'ff-t253', q:"What colour is the Golden Gate Bridge painted?", options:["Orange","Gold","Silver","Sky blue"], category:"world", source:"National Geographic"},
  {id:'ff-t254', q:"The curved white roof of the Sydney Opera House is often said to look like what?", options:["Sails","Wheels","Pyramids","Beehives"], category:"world", source:"UNESCO"},
  {id:'ff-t255', q:"Which of these is the tallest building in the world today?", options:["Burj Khalifa","The Empire State Building","The Shard","Taipei 101"], category:"world", source:"Britannica"},
  {id:'ff-t256', q:"The Great Pyramid at Giza was built mainly from millions of what?", options:["Cut stone blocks","Baked mud bricks","Timber beams","Iron plates"], category:"history", source:"British Museum"},
  {id:'ff-t257', q:"The Taj Mahal in India is famous for being built from which material?", options:["White marble","Red brick","Timber","Concrete"], category:"world", source:"UNESCO"},
  {id:'ff-t258', q:"A traditional igloo is built from blocks of what?", options:["Packed snow","Clear lake ice","Frozen soil","Woven reeds"], category:"world", source:"Britannica"},
  {id:'ff-t259', q:"The Channel Tunnel links England with which country?", options:["France","Belgium","Ireland","Denmark"], category:"world", source:"Britannica"},
  {id:'ff-t260', q:"The first high speed bullet trains began running in which country?", options:["Japan","France","Germany","Italy"], category:"history", source:"Britannica"},
  {id:'ff-t261', q:"What is the London Underground railway commonly nicknamed?", options:["The Tube","The Loop","The Pipe","The Tunnels"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t262', q:"Which pair of brothers made the first powered aeroplane flight?", options:["The Wright brothers","The Montgolfier brothers","The Lumiere brothers","The Grimm brothers"], category:"history", source:"Smithsonian"},
  {id:'ff-t263', q:"A hovercraft rides along on a cushion of what?", options:["Air","Foam","Steam","Sand"], category:"science", source:"Britannica"},
  {id:'ff-t264', q:"What colour is the flight recorder known as the black box actually painted?", options:["Bright orange","Jet black","Deep blue","Silver grey"], category:"science", source:"Britannica"},
  {id:'ff-t265', q:"On a boat, which side is starboard when you face forward?", options:["The right side","The left side","The front","The back"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t266', q:"On a ship, what is the room called the galley used for?", options:["Cooking","Steering","Sleeping","Storing the anchors"], category:"words", source:"Britannica"},
  {id:'ff-t267', q:"Which invention made tall office buildings practical to use every day?", options:["The safety lift","The escalator","The revolving door","The fire escape"], category:"history", source:"Smithsonian"},
  {id:'ff-t268', q:"In a stone arch, what is the keystone?", options:["The wedge at the very top","The block at the base","A stone in the floor","A carved name plate"], category:"words", source:"Britannica"},
  {id:'ff-t269', q:"Concrete is made by mixing water and stony aggregate with what?", options:["Cement","Salt","Chalk dust","Wood pulp"], category:"science", source:"Britannica"},
  {id:'ff-t270', q:"An ordinary building brick is made by shaping and baking what?", options:["Clay","Gravel","Crushed glass","Plaster"], category:"science", source:"Britannica"},
  {id:'ff-t271', q:"What does a builder check with a plumb line?", options:["That a wall is upright","How heavy a stone is","How wide a room is","How dry the paint is"], category:"science", source:"Britannica"},
  {id:'ff-t272', q:"A ramp is an everyday example of which simple machine?", options:["The inclined plane","The pulley","The lever","The wheel and axle"], category:"science", source:"Britannica"},
  {id:'ff-t273', q:"Which invention let Europe copy books quickly from the 1400s onwards?", options:["The printing press","The typewriter","The fountain pen","The photocopier"], category:"history", source:"Britannica"},
  {id:'ff-t274', q:"Morse code spells out letters using what?", options:["Short and long signals","Colours and shapes","Numbers only","Loud and soft voices"], category:"words", source:"Britannica"},
  {id:'ff-t275', q:"On a suspension bridge, what holds the roadway up?", options:["Steel cables","Floating barrels","Timber posts","Strong magnets"], category:"science", source:"Britannica"},
  {id:'ff-t276', q:"In a hydroelectric dam, what spins the turbines?", options:["Falling water","Burning coal","Sunlight","Sea salt"], category:"science", source:"Britannica"},
  {id:'ff-t277', q:"Which clock keeps time using a steadily swinging weight?", options:["The pendulum clock","The sundial","The hourglass","The water clock"], category:"history", source:"Royal Observatory Greenwich"},
  {id:'ff-t278', q:"Popcorn pops because every kernel holds a tiny amount of what?", options:["Water","Air","Oil","Sugar"], category:"food", source:"Royal Institution"},
  {id:'ff-t279', q:"What do you call a word that reads the same forwards and backwards?", options:["A palindrome","An anagram","An acronym","A synonym"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t280', q:"What is the term for a word that imitates the sound it describes?", options:["Onomatopoeia","Alliteration","Metaphor","Rhyme"], category:"words", source:"Britannica"},
  {id:'ff-t281', q:"What do you call a comparison that uses the word like or as?", options:["A simile","A metaphor","A pun","A proverb"], category:"words", source:"Britannica"},
  {id:'ff-t282', q:"What is the repeated first sound in the phrase six silly swans called?", options:["Alliteration","Rhyme","Riddle","Verse"], category:"words", source:"Poetry Foundation"},
  {id:'ff-t283', q:"Which short poem has three lines of five, seven and five syllables?", options:["A haiku","A sonnet","A limerick","A ballad"], category:"words", source:"Poetry Foundation"},
  {id:'ff-t284', q:"How many lines does a traditional sonnet have?", options:["Fourteen","Ten","Twelve","Twenty"], category:"words", source:"Poetry Foundation"},
  {id:'ff-t285', q:"What do you call a word that means the opposite of another word?", options:["An antonym","A synonym","A homonym","An acronym"], category:"words", source:"Cambridge Dictionary"},
  {id:'ff-t286', q:"The words pair and pear are an example of what?", options:["Homophones","Antonyms","Anagrams","Acronyms"], category:"words", source:"Cambridge Dictionary"},
  {id:'ff-t287', q:"What do you call letters added to the front of a word, like un in unhappy?", options:["A prefix","A suffix","A syllable","A vowel"], category:"words", source:"Cambridge Dictionary"},
  {id:'ff-t288', q:"What is the study of where words come from called?", options:["Etymology","Entomology","Geography","Astronomy"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t289', q:"What is the word for a false name that an author writes under?", options:["A pseudonym","A homonym","An antonym","A palindrome"], category:"words", source:"Britannica"},
  {id:'ff-t290', q:"Which alphabet is used to write Russian?", options:["Cyrillic","Greek","Latin","Arabic"], category:"world", source:"Britannica"},
  {id:'ff-t291', q:"Which of these languages is written from right to left?", options:["Arabic","Spanish","Russian","Greek"], category:"world", source:"Britannica"},
  {id:'ff-t292', q:"Characters called kanji are used in writing which language?", options:["Japanese","Korean","Thai","Vietnamese"], category:"world", source:"Britannica"},
  {id:'ff-t293', q:"Which ancient writing was pressed into wet clay with a wedge tip?", options:["Cuneiform","Hieroglyphs","Braille","Cursive"], category:"history", source:"British Museum"},
  {id:'ff-t294', q:"What are the picture symbols of ancient Egyptian writing called?", options:["Hieroglyphs","Runes","Cursive","Braille"], category:"history", source:"British Museum"},
  {id:'ff-t295', q:"What is the art of beautiful decorative handwriting called?", options:["Calligraphy","Cartography","Choreography","Photography"], category:"words", source:"Britannica"},
  {id:'ff-t296', q:"Which invention by Johannes Gutenberg helped spread printed books?", options:["The printing press","The typewriter","The fountain pen","The photocopier"], category:"history", source:"Britannica"},
  {id:'ff-t297', q:"The words uppercase and lowercase first came from what?", options:["Trays of printing type","Sizes of writing paper","Colours of printing ink","Names of two printers"], category:"history", source:"Smithsonian"},
  {id:'ff-t298', q:"The word alphabet comes from the first two letters of which alphabet?", options:["Greek","Latin","Arabic","Runic"], category:"words", source:"Britannica"},
  {id:'ff-t299', q:"The English word restaurant was borrowed from which language?", options:["French","German","Dutch","Greek"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t300', q:"The word shampoo came into English from which language?", options:["Hindi","Japanese","Italian","Turkish"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t301', q:"Which language has the most native speakers in the world?", options:["Mandarin Chinese","English","Arabic","Russian"], category:"world", source:"Britannica"},
  {id:'ff-t302', q:"Which letter appears most often in written English?", options:["E","T","S","O"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t303', q:"The word brunch was made by blending which two words?", options:["Breakfast and lunch","Bread and lunch","Brew and munch","Broth and lunch"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t304', q:"What does the short form PS at the end of a letter stand for?", options:["Postscript","Please send","Point stated","Personal note"], category:"words", source:"Oxford English Dictionary"},
  {id:'ff-t305', q:"The month name September comes from the Latin word for which number?", options:["Seven","Nine","Ten","Four"], category:"words", source:"Britannica"},
  {id:'ff-t306', q:"Japan is often known as the land of the rising what?", options:["Sun","Moon","Mist","Wind"], category:"world", source:"Britannica"},
  {id:'ff-t307', q:"Which author created the detective Sherlock Holmes?", options:["Arthur Conan Doyle","Agatha Christie","Charles Dickens","Jules Verne"], category:"world", source:"Britannica"}
];
