#!/usr/bin/env node
/*
 * status.js
 *
 * Prints a live snapshot of where Litter Bug stands right now:
 *   - art bank progress (current vs target per layer)
 *   - smoke harness pass count
 *   - recent commits
 *   - asset disk usage
 *
 * Also writes the same snapshot to STATUS.md so anyone browsing the
 * repo (or you, on your phone) can see current state without running
 * Node.
 *
 * Run: `npm run status` or `node scripts/status.js`
 */
var fs = require('fs');
var path = require('path');
var { execSync } = require('child_process');
var LAYERS = require('./art-layers');

var ROOT = path.join(__dirname, '..');
var STATUS_PATH = path.join(ROOT, 'STATUS.md');

function tryExec(cmd) {
  try { return execSync(cmd, { cwd: ROOT, encoding: 'utf8' }).trim(); }
  catch (e) { return null; }
}

function progressBar(have, target, width) {
  width = width || 20;
  var pct = target === 0 ? 1 : Math.min(have / target, 1);
  var filled = Math.round(pct * width);
  var bar = '█'.repeat(filled) + '░'.repeat(width - filled);
  return bar + ' ' + have + '/' + target;
}

// ── Gather data ───────────────────────────────────────────────────────
var layerStats = Object.keys(LAYERS).map(function(name){
  var cfg = LAYERS[name];
  var jsonPath = path.join(ROOT, 'assets', cfg.dirName, cfg.catalogFile);
  var count = 0;
  if (fs.existsSync(jsonPath)) {
    try {
      var catalog = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
      count = catalog.length;
    } catch (e) {}
  }
  return {
    name: name,
    display: cfg.displayName,
    kind: cfg.kind === 'procedural' ? 'JSON' : 'PNG',
    have: count,
    target: cfg.targetSize || 0,
    needed: Math.max(0, (cfg.targetSize || 0) - count)
  };
});

// Smoke pass count
var smokeOut = tryExec('npm run smoke 2>&1 || true');
var smokeBlocks = (smokeOut || '').match(/(\d+) pass, (\d+) fail/g) || [];
var totalPass = 0, totalFail = 0;
smokeBlocks.forEach(function(b){
  var m = b.match(/(\d+) pass, (\d+) fail/);
  if (m) { totalPass += parseInt(m[1], 10); totalFail += parseInt(m[2], 10); }
});

// Recent commits
var recentCommits = tryExec('git log --oneline -10') || '(no git history)';

// Current HEAD
var headHash = tryExec('git rev-parse --short HEAD') || '(unknown)';
var headBranch = tryExec('git rev-parse --abbrev-ref HEAD') || '(unknown)';

// Asset disk usage
var assetSize = tryExec('du -sh assets/ 2>/dev/null') || 'assets/ (size unknown)';

// Timestamp
var now = new Date().toISOString();

// ── CLI output ────────────────────────────────────────────────────────
console.log('');
console.log('═══ Litter Bug status ═══');
console.log('   ' + now);
console.log('   ' + headBranch + ' @ ' + headHash);
console.log('');
console.log('── Art banks ──');
layerStats.forEach(function(s){
  var pad = function(str, n){ return (str + ' '.repeat(n)).slice(0, n); };
  console.log('  ' + pad(s.name, 10) + ' ' + pad('[' + s.kind + ']', 6) + '  ' + progressBar(s.have, s.target));
});
console.log('');
console.log('── Smoke ──');
if (smokeBlocks.length === 0) {
  console.log('  ✗ smoke did not produce parseable output');
} else {
  console.log('  ' + (totalFail === 0 ? '✓' : '✗') + ' ' + totalPass + ' pass, ' + totalFail + ' fail');
}
console.log('');
console.log('── Assets on disk ──');
console.log('  ' + assetSize);
console.log('');
console.log('── Recent commits ──');
recentCommits.split('\n').slice(0, 8).forEach(function(line){
  console.log('  ' + line);
});
console.log('');
console.log('Full roadmap: ROADMAP.md');
console.log('Auto-snapshot: STATUS.md');
console.log('');

// ── STATUS.md ─────────────────────────────────────────────────────────
var totalHave = layerStats.reduce(function(s, l){ return s + l.have; }, 0);
var totalTarget = layerStats.reduce(function(s, l){ return s + l.target; }, 0);

var lines = [];
lines.push('<!-- AUTOGENERATED by `npm run status` — do not edit by hand. -->');
lines.push('');
lines.push('# Litter Bug — STATUS');
lines.push('');
lines.push('_Snapshot generated ' + now + '_  ');
lines.push('_Branch: `' + headBranch + '` · HEAD: `' + headHash + '`_');
lines.push('');
lines.push('## Art banks');
lines.push('');
lines.push('| Layer | Kind | Have | Target | Need | Progress |');
lines.push('|---|---|---|---|---|---|');
layerStats.forEach(function(s){
  var pct = s.target ? Math.round(s.have / s.target * 100) : 0;
  lines.push('| ' + s.name
    + ' | ' + s.kind
    + ' | ' + s.have
    + ' | ' + s.target
    + ' | ' + s.needed
    + ' | ' + pct + '% |');
});
lines.push('');
lines.push('**Aggregate:** ' + totalHave + ' / ' + totalTarget
  + ' (' + (totalTarget ? Math.round(totalHave / totalTarget * 100) : 0) + '%)');
lines.push('');
lines.push('## Smoke');
lines.push('');
if (smokeBlocks.length === 0) {
  lines.push('Smoke did not produce parseable output. Run `npm run smoke` manually.');
} else {
  lines.push('**' + totalPass + ' pass, ' + totalFail + ' fail**'
    + (totalFail === 0 ? ' ✓' : ' ✗'));
}
lines.push('');
lines.push('## Assets on disk');
lines.push('');
lines.push('```');
lines.push(assetSize);
lines.push('```');
lines.push('');
lines.push('## Recent commits');
lines.push('');
lines.push('```');
recentCommits.split('\n').slice(0, 10).forEach(function(line){
  lines.push(line);
});
lines.push('```');
lines.push('');
lines.push('## What\'s next');
lines.push('');
lines.push('See `ROADMAP.md` for the full list of everything still to make.');
lines.push('');

fs.writeFileSync(STATUS_PATH, lines.join('\n') + '\n');
console.log('Wrote ' + path.relative(ROOT, STATUS_PATH) + '.');

// Also drop a lightweight JSON blob the bug-lab can fetch / future
// pages can consume. Same data, no parsing-of-markdown needed.
var jsonStatusPath = path.join(ROOT, 'assets', 'status.json');
fs.writeFileSync(jsonStatusPath, JSON.stringify({
  generated: now,
  branch: headBranch,
  head: headHash,
  smoke: { pass: totalPass, fail: totalFail },
  totals: { have: totalHave, target: totalTarget },
  layers: layerStats
}, null, 2) + '\n');
console.log('Wrote ' + path.relative(ROOT, jsonStatusPath) + '.');
