/* Bake VERIFIED playstyle facets into portal/index.html between the
   VIBES-START/END markers. Only machine-confident (firm) tags from
   portal/catalog-tags.json are baked; the DAILY list is curated here by
   hand. Regenerate tags first with `node scripts/tag_catalog.mjs`. */
import { readFileSync, writeFileSync } from 'fs';

const tags = JSON.parse(readFileSync('portal/catalog-tags.json', 'utf8'));

// hand-curated: games with a true daily hook, by display name
const DAILY = ['Jumping Jimothy', 'Word Sprout', 'Story Seeds'];

const map = {};
const add = (nm, k) => { (map[nm] = map[nm] || []).push(k); };
for (const g of tags.games || []) {
  const t = g.tags || {};
  const firm = (key, val) => t[key] && t[key].firm && t[key].value === val;
  if (firm('length', 'under 2 min')) add(g.name, 'quick');
  if (firm('brain', 'think')) add(g.name, 'think');
  if (firm('brain', 'reflex')) add(g.name, 'reflex');
  if (firm('brain', 'make')) add(g.name, 'make');
  if (t.company && t.company.firm && t.company.value !== 'alone') add(g.name, 'together');
}
for (const nm of DAILY) add(nm, 'daily');

const block = `/*VIBES-START*/
/* Verified playstyle facets. REGENERATED by \`node scripts/bake_vibes.mjs\`
   from portal/catalog-tags.json — only machine-CONFIDENT tags are baked, and
   the DAILY list is curated by hand in that script. Do not edit inline. */
var VIBES = ${JSON.stringify(map)};
/*VIBES-END*/`;

const p = 'portal/index.html';
let src = readFileSync(p, 'utf8');
const re = /\/\*VIBES-START\*\/[\s\S]*?\/\*VIBES-END\*\//;
if (!re.test(src)) { console.error('VIBES markers not found'); process.exit(1); }
src = src.replace(re, block);
writeFileSync(p, src);
const n = Object.keys(map).length;
console.log('baked vibes for ' + n + ' games:',
  ['quick','think','reflex','make','together','daily'].map(k =>
    k + '=' + Object.values(map).filter(v => v.includes(k)).length).join(' '));
