import puppeteer from 'puppeteer';
const OUT='/tmp/claude-1000/-workspaces-lucid-winds/d6e4270b-d486-419c-825e-b18f22aea7f8/scratchpad';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const b=await puppeteer.launch({args:['--no-sandbox','--mute-audio']});
const p=await b.newPage();
await p.emulate({viewport:{width:412,height:915,isMobile:true,hasTouch:true,deviceScaleFactor:2},userAgent:'Mozilla/5.0 Mobile'});
p.on('pageerror',e=>console.log('PAGEERROR:',e.message));
await p.goto('http://127.0.0.1:8777/bramblewick.html?bramblewicktest=1',{waitUntil:'networkidle2'});
await sleep(700);
console.log('start:',await p.evaluate(()=>__bw.start(1,0)));
await p.evaluate(()=>{ __bw.addWeapon('dandelion'); __bw.addWeapon('nettle');
  __bw.addCompanion('ladybug'); __bw.addCompanion('bee'); __bw.addCompanion('koala'); __bw.addCompanion('mammoth');
  __bw.swarmAt(6,'wasp'); __bw.swarmAt(4,'mite'); __bw.swarmAt(4,'spittle'); __bw.swarmAt(4,'thrip'); });
await sleep(3500);
console.log('reaction:',await p.evaluate(()=>__bw.forceReaction('spore','sap')));
await sleep(350);
console.log('fx:',JSON.stringify(await p.evaluate(()=>__bw.fxCounts())));
console.log('state:',JSON.stringify(await p.evaluate(()=>__bw.state())));
await p.screenshot({path:OUT+'/bramble-run.png'});
await sleep(2500);
console.log('fx later (webs+globs should appear):',JSON.stringify(await p.evaluate(()=>__bw.fxCounts())));
await p.evaluate(()=>__bw.levelUp());
await sleep(300);
await p.screenshot({path:OUT+'/bramble-draft.png'});
await b.close(); console.log('DONE');
