#!/usr/bin/env node
/* docs/3D-VR-AUDIT.md, GENERATED FROM docs/3d-vr-audit.json.
     node scripts/vr_audit_md.mjs

   The table and the JSON cannot disagree because the table is not written by
   hand: it is this file's only output. Rerunning it on unchanged input must
   produce a byte identical file, which is why nothing here reads the clock,
   the git state or the filesystem beyond the one input.

   ⛔ Do not hand edit docs/3D-VR-AUDIT.md. Edit the JSON and rerun. */
import { readFileSync, writeFileSync } from "fs";
import { LANES, ROUTES, EFFORTS, COMFORTS } from "./vr_audit_check.mjs";

const IN = "docs/3d-vr-audit.json";
const OUT = "docs/3D-VR-AUDIT.md";

const rows = JSON.parse(readFileSync(IN, "utf8"));

/* sort: lane, then effort, then name. The lane order is the reading order the
   handoff asks for, the bodies first and the default last. */
const LANE_ORDER = ["TABLETOP", "STANDING", "WINDOW", "NEVER-IMMERSIVE"];
const rank = (list, v) => { const i = list.indexOf(v); return i < 0 ? 99 : i; };
const sorted = rows.slice().sort((a, b) =>
  rank(LANE_ORDER, a.lane) - rank(LANE_ORDER, b.lane)
  || rank(EFFORTS, a.effort) - rank(EFFORTS, b.effort)
  || a.name.localeCompare(b.name, "en"));

/* a pipe inside a cell would split the column */
const cell = (v) => String(v == null ? "" : v).replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
const tally = (f, list) => list.map(v => `${v} **${rows.filter(r => r[f] === v).length}**`).join(" · ");

let md = "";
md += "# 3D AND VR AUDIT, ALL 187 CARDED GAMES\n\n";
md += "**Generated by `scripts/vr_audit_md.mjs` from `docs/3d-vr-audit.json`. Do not hand edit.**\n";
md += "Edit the JSON and rerun; the two cannot disagree because this table is not written by hand.\n\n";
md += "The vocabulary is section 4 of `HANDOFF-3D-VR.md` and nothing else is allowed in the\n";
md += "lane, route, effort and comfort columns. `scripts/vr_audit_check.mjs` asserts that, and\n";
md += "asserts one row per catalog row, and asserts that every row carries a `file:line` cite\n";
md += "or the word UNREAD with a reason.\n\n";
md += "⛔ **Nothing here has been run on a headset, and nothing here has been built.** This is a\n";
md += "static read of the source plus the shots in `docs/shots-vr/`. Every call in it should be\n";
md += "checked against the Quest 2 before it is believed, the same law `QUEST-COMPAT.md` carries.\n\n";
md += "## Counts\n\n";
md += "| axis | counts |\n|---|---|\n";
md += `| lane | ${tally("lane", LANE_ORDER)} |\n`;
md += `| route | ${tally("route", ROUTES)} |\n`;
md += `| effort | ${tally("effort", EFFORTS)} |\n`;
md += `| comfort | ${tally("comfort", COMFORTS)} |\n`;
md += `| kind | satellite **${rows.filter(r => r.kind === "satellite").length}** · native **${rows.filter(r => r.kind === "native").length}** |\n`;
md += `| gated | **${rows.filter(r => r.gated).length}** of ${rows.length} |\n`;
md += `| UNREAD | **${rows.filter(r => /^UNREAD\b/.test(r.cite)).length}** |\n\n`;
md += "## The table\n\n";
md += "Sorted lane, then effort, then name. `split` answers whether the simulation runs with no\n";
md += "screen, which is the property that let Ripcord put a 3D camera on an untouched game in\n";
md += "570 lines. `cite` is the one line that decided the row.\n\n";
md += "| # | game | kind | lane | route | effort | comfort | renderer | camera | area | split | input | cite | the hands | notes |\n";
md += "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n";
sorted.forEach((r, i) => {
  md += "| " + [i + 1, (r.gated ? "🔒 " : "") + r.name, r.kind, r.lane, r.route, r.effort,
    r.comfort, r.renderer, r.camera, r.area, r.split, r.input, "`" + cell(r.cite) + "`",
    r.hands, r.notes].map(cell).join(" | ") + " |\n";
});
md += "\n## By lane\n\n";
for (const lane of LANE_ORDER) {
  const g = sorted.filter(r => r.lane === lane);
  md += `### ${lane} — ${g.length}\n\n`;
  md += g.map(r => (r.gated ? "🔒 " : "") + r.name + " (" + r.effort + ", " + r.comfort + ", " + r.route + ")").join(" · ") + "\n\n";
}
md += "## By route\n\n";
for (const route of ROUTES) {
  const g = sorted.filter(r => r.route === route);
  md += `### ${route} — ${g.length}\n\n`;
  md += g.map(r => (r.gated ? "🔒 " : "") + r.name).join(" · ") + "\n\n";
}
writeFileSync(OUT, md);
console.log("wrote " + OUT + "  " + rows.length + " rows, " + md.length + " bytes");
