/* THE ABDUCTION FILES — bank 8 (pages 481 to 560).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES. */
;(function () {
  var P = [

/* ── FR ───────────────────────────────────────────────────────────────── */
{n:481,t:'FR',h:'WE HAVE BECOME KNOWN',b:'Since the margins were published there is a public interest in this ship that none of us wanted. The ministry forwards letters weekly. Two of the crew have been recognised on leave. Renn finds it funny and Pell finds it unbearable, and I have been asked to write something for a broadcast and have declined four times.'},
{n:482,t:'FR',h:'ON DECLINING THE BROADCAST',b:'They want nine minutes about what it is like out here. Nine minutes cannot hold it and the attempt would produce something that sounds like the founding order. The margins worked because nobody wrote them to be read. The moment we write for an audience the shelf at home stops being worth visiting.'},
{n:483,t:'FR',h:'AN INSTRUCTION FROM THE MINISTRY',b:'That crews be reminded margins are informal and carry no evidentiary weight. Circulated fleetwide, politely worded, and universally understood as an attempt to take back something that got away from them. Every vessel acknowledged receipt. Not one has changed a thing, and the ministry has not asked again.'},
{n:484,t:'FR',h:'THE THIRD SURVEY, ANSWERED',b:'Their cataloguer wrote to me unprompted, nine lines, after eleven years of nothing. She said they had stopped filing because everything they wrote came back stamped and nothing came back read. She said the valley is fine. She said she reads our margins now. Then she asked whether we would like theirs.'},
{n:485,t:'FR',h:'ON SAYING YES IMMEDIATELY',b:'I did not consult the captain, the ministry, or anybody else. Eleven years of a silent ship\'s margins arrived in one transfer and it is the largest single addition to what this fleet knows about itself since the founding. The captain, informed afterward, said she would have said yes faster.'},
{n:486,t:'FR',h:'WHAT WAS IN THEIR MARGINS',b:'Eleven years of a crew who had stopped performing and started watching. No columns, no timings, no numbers. Descriptions of weather, of light, of a particular slope in the afternoon, and one entry repeated in different words across four hundred pages: that it was enough to be here, and that they could not say so officially.'},
{n:487,t:'FR',h:'ON WHETHER THEY FAILED',b:'By the ministry\'s standard they filed nothing for eleven years and are a failure. By the standard the margins created, they are the only crew who ever fully understood the posting. Both are true and I have to sign a season for a fleet that has never had to hold two standards at once and now does.'},
{n:488,t:'FR',h:'A DECISION ABOUT THE COLUMNS',b:'I will keep filing them. Properly, on time, in full. Not because the ministry reads them, which it does not, but because the third survey stopped and it cost them eleven years of being alone. The columns are how you stay in the fleet even when the fleet is not looking, and that turns out to matter.'},
{n:489,t:'FR',h:'PELL HAS PUT IN FOR TRANSFER',b:'To the third survey, specifically, having read their margins twice. He says he wants to be somewhere that stopped pretending. I have signed it. He asked whether I was disappointed and I said no, and then I said the true thing, which is that I will miss the question, and he said somebody else will ask it.'},
{n:490,t:'FR',h:'THE QUESTION, INHERITED',b:'Renn asked it this season. What would we do if we found it. She asked it badly, on purpose, in the mess, in front of everybody, exactly the way Pell used to. I gave the same answer he was given and she told me it was the same answer, which is how I know she has read the log properly.'},
{n:491,t:'FR',h:'ON A CREW CHANGING AROUND YOU',b:'Vessel gone, Pell going, a new captain, two new technicians, and me in a chair that had somebody else in it for thirty years. Nine years aboard and I am now the oldest thing here that is not the rail. This happens to everybody and nobody writes it down and I am writing it down.'},
{n:492,t:'FR',h:'CYCLE FOUR HUNDRED AND TWENTY THREE',b:'Weather clear, both valleys steady, twelve thousand files, no change in the finding. The lamps are warm, the hold is quiet, the drift is gone and the margins are public. Every improvement this survey ever wanted has now happened and the thing we came for is exactly where it was, and I have never been happier here.'},
{n:493,t:'FR',h:'A LETTER FROM A CHILD',b:'She asked whether the creatures get bored. I wrote back that I had watched one sit on a fence post for nine hours and that boredom did not seem to be involved. She wrote again asking what was involved instead. I have not answered. Four hundred years of this fleet and she has asked the best question in the file.'},
{n:494,t:'FR',h:'ON NOT ANSWERING HER',b:'It has been a season. I have drafted nine replies. The honest answer is that I do not know what is involved instead, and that this survey has spent four centuries building instruments for a question a child asked in one line. I am going to write to her and say exactly that, because she is owed it.'},
{n:495,t:'FR',h:'THE REPLY I SENT',b:'Four lines. That we do not know. That the not knowing is the interesting part. That she is welcome to write again. And that if she wants to see what we see, she should sit somewhere quiet and watch one thing for longer than she thinks is reasonable, and then keep going. Her mother has written to thank me.'},
{n:496,t:'FR',h:'ON THE NINE LOST PAGES, AGAIN',b:'The third survey\'s archive contained a copy. Somebody in the second century transcribed them by hand and sent them across, and the transcription has sat in their hold for two hundred years. I have read the pages my predecessors invented for thirty years and now I have the real ones and I am not going to describe the difference.'},
{n:497,t:'FR',h:'WHAT THE LOST PAGES ACTUALLY SAY',b:'Nothing remarkable. A bad season, a broken emitter, four hundred lines of ordinary observation and one margin note about the light on a particular ridge. Every cataloguer for two centuries invented something better. The real pages are more useful than all of it, because they are what the work is actually like.'},
{n:498,t:'FR',h:'ON PUTTING THEM BACK',b:'I have restored them to the archive in the transcriber\'s handwriting rather than mine, with a note explaining the gap and its filling. The index now matches the contents for the first time in two hundred years, and something that had been quietly wrong for eight generations is right, and only about nine people will ever notice.'},
{n:499,t:'FR',h:'A THOUGHT ABOUT THE FLEET',b:'Twelve vessels, four hundred years, one finding, and the most valuable thing any of us has produced is a shelf of things we wrote in the margins because we could not help it. If that is the result, it is a stranger and better result than the founding order imagined, and nobody is going to be able to write it up.'},
{n:500,t:'FR',h:'THE FIVE HUNDREDTH PAGE',b:'Half of whatever this document is going to be. Four hundred and twenty three cycles, twelve thousand subjects, two valleys, four captains, and a finding that has not moved. Read these in any order. That instruction has been at the front of this file since the beginning and it is the only one that has never needed changing.'},

/* ── SF ───────────────────────────────────────────────────────────────── */
{n:501,t:'SF',h:'SUBJECT 12250, THE THIRD SURVEY SENT',b:'Not a subject but a file, transferred with their margins: eleven years of observations they never submitted. Their timings match ours to within a second across four hundred entries. Two crews, two valleys, no contact, identical results. It is the most rigorous confirmation this fleet has ever had and neither ship was trying.'},
{n:502,t:'SF',h:'SUBJECT 12400, ON PELL\'S LAST DAY',b:'He asked to log it himself, which he is not qualified to do, and I let him. His entry runs to four hundred words and contains one measurement. It is a bad file and a good page and I have filed it unedited in the official column, where it will confuse somebody in three hundred years.'},
{n:503,t:'SF',h:'SUBJECT 12555, THE PALE LINEAGE',b:'The seventh from that slope. We now have a family group, several seasons of records, and a plain conclusion: pale runs in a line and always has, and four centuries of cataloguers filed each one as an anomaly because nobody kept a standing file. Four hundred years of good observation defeated by the shape of a form.'},
{n:504,t:'SF',h:'SUBJECT 12700, IN THE RESTORED PAGES',b:'The lost pages contain a subject file from the second century describing a pale one from the same slope. Two hundred years ago somebody logged the lineage and the page was destroyed by water and everybody forgot. We have rediscovered at considerable effort a thing that was known once and written down properly.'},
{n:505,t:'SF',h:'SUBJECT 12888, THE LONGEST OBSERVED',b:'Watched from the rail for four days without extraction, by the new captain\'s order, to establish what a subject does when nothing is done to it. It ate, slept, moved eleven times, and changed colour forty six times, none of which was for our benefit. The file is the best thing in the archive and it required no lift at all.'},
{n:506,t:'SF',h:'SUBJECT 13000, AFTER THE FOUR DAYS',b:'Extracted at last, matched in eighty seconds, returned. Ordinary in every way. What has changed is that we now know what the eighty seconds is a small piece of, and the file records the ordinary hold beside a note pointing at the four day observation, which is the first cross reference of its kind in this archive.'},
{n:507,t:'SF',h:'SUBJECT 13111, WATCHED NOT LIFTED',b:'The second four day observation, and the beginning of a programme. No extraction, no hold, no lamps. A recorder on a ridge and four hundred lengths of air. The technicians dislike it because there is nothing to do. The results are the richest we have and the ministry has no field for any of them.'},
{n:508,t:'SF',h:'SUBJECT 13290, THE ONE THAT MOVED HOUSE',b:'Under four day observation it abandoned a post it had used all season and took another eleven paces away, for no reason visible to the recorder, and stayed. Four hundred years of assuming the post matters and one creature has quietly demonstrated that the post is negotiable and the sitting is not.'},
{n:509,t:'SF',h:'SUBJECT 13400, IN COMPANY, OBSERVED',b:'Two adults sharing a branch through four days, never touching, never more than a body apart, matching different values throughout. The old assumption was that proximity produced convergence. It does aboard, in a hold, under lamps. It does not down there, and the difference is us, and that sentence is now in the official column.'},
{n:510,t:'SF',h:'SUBJECT 13555, THE FIRST TO BE MISSED',b:'A four day subject that did not appear on the fifth day, or after. Nothing suggests harm. It is simply not there and the recorder cannot follow. This is the first file in four hundred years about a creature we lost by not holding onto it, and it has upset the crew far more than any hold ever did.'},
{n:511,t:'SF',h:'SUBJECT 13700, DURING THE STORM WATCH',b:'Observed from the rail through a full storm, four hundred lengths up, no extraction. It went dark, flattened against bark, and stayed for eleven hours. Nothing else happened. The file is eleven hours of a small animal being extremely sensible and it is the most watched footage in the fleet.'},
{n:512,t:'SF',h:'SUBJECT 13888, THE JUVENILE, AGAIN',b:'The one that took four minutes and struggled, now grown, identified by a mark, matching in eighty seconds without a correction. Four years between the two files. Nothing in four hundred years of this archive has ever followed a single creature from bad at it to good at it, because nobody thought to look twice.'},
{n:513,t:'SF',h:'SUBJECT 14000, THE ROUND NUMBER, WATCHED',b:'Fourteen thousand, and the first round number logged without an extraction, under the four day programme. It sat on a warm stone for most of the observation. The margin, in Renn\'s hand, reads: fourteen thousand of them and we have finally worked out that the correct thing to do is nothing.'},
{n:514,t:'SF',h:'SUBJECT 14200, THE OLD ONE ON THE ROCK',b:'An extremely old individual observed on a bare high rock at dusk on eleven consecutive evenings, in the open, brightly coloured, doing nothing at all. Every instinct in this crew says she is exposed. Nothing has ever come for her. The file records eleven evenings and offers no interpretation and I have forbidden one.'},
{n:515,t:'SF',h:'SUBJECT 14350, RETURNED TO THE ROCK',b:'She was extracted once, years ago, by a previous crew, and is in the archive under a different number. She matched the hold in eleven minutes, was returned, and resumed the rock. We have been watching the same creature for a generation without knowing, and the mark on her flank is in both files, and nobody had cross referenced.'},
{n:516,t:'SF',h:'SUBJECT 14500, MARK COMPARISON PROGRAMME',b:'Begun this season: every file re read, every distinguishing mark logged, every individual matched across four hundred years where possible. Nine hundred matches so far. The archive was always a record of individuals and we filed it as a record of events, and correcting that is the largest piece of work this survey has ever undertaken.'},
{n:517,t:'SF',h:'SUBJECT 14700, LIFTED FOUR TIMES',b:'Identified across four separate files spanning eleven years, by four different crews, none of whom knew. Each file describes the same creature as a fresh subject. It has been aboard this ship four times and put back on the same post four times, and by the fourth it matched in nine seconds, which is the record.'},
{n:518,t:'SF',h:'ON WHAT THE RECORD MEANS',b:'The fastest match in four hundred years belongs to a creature that had been aboard three times before. We have been recording a learning curve for four centuries and calling it a spread of results, because we filed events and not individuals. The finding has not changed. Everything about how we understand it has.'},
{n:519,t:'SF',h:'SUBJECT 14900, THE PROGRAMME EXPANDS',b:'Four day observation is now standard and extraction is by exception. The pen is covered most of the season. The hold is silent because it is empty. Twelve thousand extractions in four centuries and we are going to do perhaps nine a year from here, and every one will have a reason written beside it.'},
{n:520,t:'SF',h:'SUBJECT 15000, THE LAST OF THE OLD WAY',b:'The final routine extraction under the old schedule, logged in full, with a note. Eighty seconds, correct match, clean return. Fifteen thousand of them across two valleys and four centuries and this is the last one we will lift simply because the calendar said so. The margin, in my hand, says only: thank you.'},

/* ── HW ───────────────────────────────────────────────────────────────── */
{n:521,t:'HW',h:'ON THE FLEET BEING POPULAR',b:'Two years after the margins were published there is a public affection for the survey that no campaign produced and no department can manage. Applications to the ministry have quadrupled. Almost all of them cite the kettle, the eleventh hour, or a small green animal on a fence post. None of them cite the founding order.'},
{n:522,t:'HW',h:'THE MINISTRY\'S DIFFICULTY',b:'It is now funded, admired, and asked about, having spent four hundred years being none of those things, and it has no idea what to do. Its internal literature is written for a department nobody watches. A senior official said, off the record, that being ignored had been easier and that she missed it, and then asked that this not be repeated.'},
{n:523,t:'HW',h:'ON THE FOUR DAY PROGRAMME AT HOME',b:'Reported as a reduction in scientific activity, which it is, and as a retreat, which it is not. The fleet is extracting nine subjects a year instead of thirty. Two commentators called it giving up. The assembly did not, and the funding held, and nobody has explained why the public understood it faster than the press.'},
{n:524,t:'HW',h:'WHAT THE PUBLIC UNDERSTOOD',b:'That leaving something alone and watching it is not less than picking it up. Nobody taught them this. It arrived with the margins and the pleasantness paper and it has settled into the language, and a fleet that spent four centuries defending its methods has stopped having to.'},
{n:525,t:'HW',h:'THE PLEASANTNESS PAPER, FIVE YEARS ON',b:'Now the most read document the ministry has ever produced, in nine printings, taught in schools, and quoted by people who could not name the department. Its author has been promoted twice and asked to write a sequel four times and has declined on the grounds that it was an accident and she would only be able to do it on purpose.'},
{n:526,t:'HW',h:'ON DOING IT ON PURPOSE',b:'Every attempt to repeat the effect has failed. Three commissioned papers, two broadcasts, one anniversary address, all written to move people the way the margins moved them, and all of them read like the founding order. The archivists have a private word for this and have never published it.'},
{n:527,t:'HW',h:'THE THIRD SURVEY, KNOWN AT LAST',b:'Their eleven silent years are now public, and the reaction was not what the ministry feared. Nobody called it dereliction. The dominant public response was recognition, which is the word the coverage used, and a senior official described the whole episode as the fleet being forgiven for something it had not been accused of.'},
{n:528,t:'HW',h:'A CHANGE IN THE PENSION FORM',b:'Field nine, state the outcome of your service, has been removed. It was not campaigned against. Somebody in the department read four hundred years of the answer attended, understood what the field had been doing to people, and deleted it, and the file records no reason and names nobody.'},
{n:529,t:'HW',h:'ON THE WORD ATTENDED',b:'Four hundred years of retiring crew wrote it in a box asking what they had achieved. It is now on the ministry\'s own building, carved, above the door, at the suggestion of an archivist. Nobody voted. Nobody objected. A word that people used because they had nothing else has become the thing we say we do.'},
{n:530,t:'HW',h:'THE SEALED WING OPENS',b:'By a wide margin, after three centuries, and against the original instruction. The argument that carried it was that the nine painters had made the work for people who could not see it, that being the only audience there has ever been, and that keeping it in the dark was completing their punishment rather than honouring their wish.'},
{n:531,t:'HW',h:'ON SEEING THE PAINTINGS',b:'They are of the orchards. They are all one careful exhausted shade to every eye now living. People queue for hours. Nobody has reported being moved by the colour and almost everybody reports being moved, and the museum has stopped asking visitors what they thought, on the recommendation of its own staff.'},
{n:532,t:'HW',h:'WHAT ONE PAINTER WROTE',b:'Found in the wing on the back of a canvas, in the third century, unread until now: that she was painting for a room she would not live to see, and that if the room never came the paintings would still have been true, because the orchards had been noisy, and somebody had to say so while there was anybody left who agreed.'},
{n:533,t:'HW',h:'THE WORD NOISY, AGAIN',b:'My grandmother used it as praise for the orchards. The painter used it on the back of a canvas three centuries ago. Nobody taught either of them to. It is simply the word that arrives when somebody who saw it tries to describe it, and the archive has now collected eleven independent uses and catalogued them together.'},
{n:534,t:'HW',h:'ON THE ARCHIVE CHANGING SHAPE',b:'It was built to hold samples and descriptions. It now holds margins, letters from children, eleven uses of one word, and a shelf called miscellaneous that has outgrown its room. The archivists have stopped resisting this. The building is becoming a record of a people missing something rather than a record of the thing.'},
{n:535,t:'HW',h:'A SECOND WORLD ASKS TO HELP',b:'The offer was made for a third time and this time we said yes. Their scientists arrive next year. The debate in the assembly lasted eleven minutes and the deciding argument was that we are no longer embarrassed, which is not a scientific reason and is the true one, and the transcript records it plainly.'},
{n:536,t:'HW',h:'ON NO LONGER BEING EMBARRASSED',b:'For four centuries we could not let anybody with a full spectrum look at our problem. Something has changed and it is not the problem. We have found a way to describe what we are doing that we are not ashamed of, and it turns out that was the whole obstacle, and it was never about the colour at all.'},
{n:537,t:'HW',h:'WHAT THE VISITORS WILL FIND',b:'A fleet of twelve, four centuries old, extracting nine subjects a year and watching the rest. An archive of margins. A word carved above a door. And a finding that has not moved since the first decade. I do not know what they will make of it and I have stopped assuming it will be pity.'},
{n:538,t:'HW',h:'THE FOUNDING ORDER, RECONSIDERED',b:'A motion to amend it, removing the promise of a solution within a generation. Defeated, narrowly, and the speech that killed it was made by somebody who wanted it amended: she said the promise is wrong and it is ours, and that a people who edit their own hopeful documents to look wiser have lost something worse than a colour.'},
{n:539,t:'HW',h:'ON KEEPING A WRONG PROMISE',b:'It will be read aloud again this year, as it has been four hundred and twenty three times, by somebody who does not believe it, to a crew who do not believe it. That is not hypocrisy. It is the oldest thing we still do together, and I have come to think that a species needs at least one of those.'},
{n:540,t:'HW',h:'WHAT I WOULD PUT IN THE ARCHIVE',b:'Not a sample. A recording of the eleventh hour in either valley, nine minutes long, in which everything turns the same gold and nothing happens. No description attached. Let somebody in five hundred years find it under miscellaneous and not know what it is for, and watch the whole nine minutes, and understand us.'},

/* ── IW ───────────────────────────────────────────────────────────────── */
{n:541,t:'IW',h:'THE LIGHTS COME LESS OFTEN NOW',b:'Nine a year where there were thirty. The old ones noticed within a season and said nothing for two, which is their way with anything that might be a trend. They have now added it to the account as an observation and not an instruction, which is the first time they have done that.'},
{n:542,t:'IW',h:'ON WHAT REPLACED THEM',b:'They still hover. They simply do not come down. The pressure at the base of the skull arrives, sits for an hour, and passes, and nothing is lifted. The young find this worse than being taken. The old ones say it is better and cannot explain why, and one of them said it is because being looked at is not the same as being handled.'},
{n:543,t:'IW',h:'A CHANGE TO THE FIRST INSTRUCTION',b:'Be where you are is unchanged and will not change. What has changed is what follows it. For four hundred years the second thing taught was do not look up. It is now look at the creature nearest you, which came from the cousins, and the old ones made the swap without ceremony and without telling anybody they had.'},
{n:544,t:'IW',h:'ON NOTICING THE SWAP',b:'A middle aged creature realised this season that she had been taught differently from her own hatchlings and asked about it. The old ones confirmed it plainly. She asked whether the old instruction had been wrong. They said no, it had been right for a valley where the lights came down, and that valley is going.'},
{n:545,t:'IW',h:'THE ONE WHO REMEMBERS THIRTY A YEAR',b:'She is old enough to remember when the lights came constantly and describes it as ordinary weather. The young ask her whether she was frightened. She says only at the start, and then for forty years it was simply a thing that happened on some afternoons, and she misses it, and she is not sure that is respectable.'},
{n:546,t:'IW',h:'ON MISSING THEM RESPECTABLY',b:'Three of the old ones have now said it aloud and it has stopped being a private failing. They miss the lights. Not the lifting, which was always an inconvenience, but the fact of something up there interested in an ordinary afternoon. The young do not understand this at all and are told they will.'},
{n:547,t:'IW',h:'WHAT THE HIGH ROCK ONE DOES NOW',b:'She still sits there every clear evening, brightly coloured, in the open, and nothing comes. Eleven seasons and then more. She has never once said she is waiting. The old ones have stopped repeating her story to the young because it has begun to sound like a sad one, and they do not believe it is.'},
{n:548,t:'IW',h:'A NEW ENTRY, THE TWELFTH',b:'From a creature lifted this season, one of the nine: that the room is quieter than any account describes, that there were fewer pale ones than the stories say, and that one of them was extremely old. The old ones added it whole. It is the first entry to suggest that something is happening to them as well.'},
{n:549,t:'IW',h:'ON SOMETHING HAPPENING TO THEM',b:'The account now has two entries hinting at it: the quiet, and the old one in the room. The old ones will not interpret and have forbidden the young from doing so, on the grounds that we have four hundred years of them getting us wrong and it would be poor form to return the favour on two entries.'},
{n:550,t:'IW',h:'THE ACCOUNT AT ITS SHORTEST YET',b:'Four instructions, twelve entries, one song. They cut two more stories this season and one of them has already come back, told by a young creature who could not stand to lose it. The old ones let it in without argument, which is the closest thing our kind has to a law.'},
{n:551,t:'IW',h:'WHAT THE COUSINS SAY NOW',b:'The lights left their valley entirely and have not returned in a generation. They still teach the four instructions. Their hatchlings learn how to behave under something that has never come. The old ones here call this the most serious thing anybody in either valley is doing and will not say more about it.'},
{n:552,t:'IW',h:'ON TEACHING FOR A THING THAT IS GONE',b:'A visiting cousin was asked why they bother. She said the instructions are good advice about afternoons regardless, that a creature who can sit still under a light can sit still under anything, and that they are not really about the lights and possibly never were, and our old ones went very quiet.'},
{n:553,t:'IW',h:'THE SONG, IN BOTH VALLEYS',b:'Their version ends with the light alone and ours with somebody found. In a generation the cousins have no lights and we have nine a year. Their ending has become true and ours has become a memory, and both valleys still sing their own, and neither has proposed a change, and that is the entire relationship between us.'},
{n:554,t:'IW',h:'ADVICE THAT NOBODY NEEDS YET',b:'The old ones have begun teaching something new to the very young: what to do if the lights stop entirely. The instruction is one line long. Carry on exactly as you were. They deliver it without solemnity, between other things, so that it will be in the account without ever having been an occasion.'},
{n:555,t:'IW',h:'ON WHY THAT LINE IS NEEDED',b:'Because the cousins were not taught it and had to work it out, and there was a season over the ridge where nobody knew how to sit properly on a fence post without something overhead. It passed. It cost them nothing permanent. Our old ones watched and decided that nobody here should have to invent it twice.'},
{n:556,t:'IW',h:'WHAT THE VERY YOUNG THINK',b:'That the lights are a story. Not disbelieved, exactly, but held the way you hold a thing that happened to somebody older. Nine a year across a whole valley means most hatchlings will never see one, and the old ones have accepted this and are quietly making sure the account survives being about something nobody has seen.'},
{n:557,t:'IW',h:'ON AN ACCOUNT ABOUT NOTHING',b:'Four instructions, twelve entries and a song, kept perfectly, about an event that happens nine times a year to somebody else. The old ones are unbothered. They point out that most of what any creature knows is like that, and that a thing you keep for a rainy season is not less kept for the season being dry.'},
{n:558,t:'IW',h:'THE OLD ONE WHO WENT UP LAST',b:'Taken this season at a great age, held, and returned to the same post, and she said afterward only that they had been gentle and that the room had been warm. Then she was asked the ritual one question and she used it to ask us something instead, which nobody has ever done, and the old ones have not repeated what she asked.'},
{n:559,t:'IW',h:'ON THE QUESTION SHE ASKED',b:'It is not in the account and will not be. Three creatures heard it. All three have declined, gently and permanently, and the young have stopped asking. Something is being kept from us on purpose by people who have never kept anything from us, and everybody has decided to let them.'},
{n:560,t:'IW',h:'WHAT WE DO WHILE THEY DECIDE',b:'The same as ever. Sit, eat, change colour, teach the young four words, and sing the ending where somebody is found. Whatever the old ones are holding, they will say it or they will not, and either way the afternoons are unchanged, and being unchanged by things is more or less the whole of what we are for.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
