/* THE ABDUCTION FILES — bank 1 (pages 1 to 60).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES. */
;(function () {
  var P = [

/* ── the opening frame: what this is, from four angles ─────────────────── */
{n:1,t:'FR',h:'FIRST ENTRY, AGAIN',b:'They have given me the log again because nobody else wants it. Very well. Cycle four hundred and eleven of the survey. Weather over the target valley is clear. The lift is calibrated. Morale is described in the manual as sufficient. I am to record everything, in order, without opinion. I have already failed at one of those three and it is not yet midday.'},
{n:2,t:'HW',h:'THE COLOUR DROUGHT',b:'It began with a shade of green nobody could name afterward. Then a blue went, and then the warm end of the spectrum thinned like broth. We are told it is not a sickness, because a sickness would be something we could argue with. Our world is not dying. It is simply becoming easier to describe, and we are running out of words we want to use.'},
{n:3,t:'SF',h:'SUBJECT 0001, HELD SIX MINUTES',b:'Green, small, entirely unbothered. Taken from a fence post at dusk. Aboard, it climbed the observation rail, considered the grey wall of the hold, and turned a polite approximation of grey. The whole crew went quiet. Cataloguer Renn wept, which is not in any procedure. Returned to the same fence post, where it resumed being green without comment.'},
{n:4,t:'IW',h:'WHAT THE OLD ONES SAY ABOUT LIGHTS',b:'The old ones say the lights are lonely. They say a light that meant you harm would not hover so politely, and would not put you back. They say if you must be lifted, go limp and be dull, because the lights are collecting brightness and there is no reason to give them yours. Then they say: but do not be too dull, or they will worry.'},

/* ── FR: the work, the mishaps, the doubt ─────────────────────────────── */
{n:5,t:'FR',h:'ON THE PROPER USE OF THE LIFT',b:'The lift is a specimen instrument. It is not, whatever the crew calls it, a beam. Calling it a beam encourages the sort of behaviour we saw in cycle three hundred and eight, when Ensign Pell tried to lift a bicycle. The bicycle came apart. The report on the bicycle is longer than the report on the first contact, and I have read both twice.'},
{n:6,t:'FR',h:'A NOTE ON THE HOLD LIGHTING',b:'I have requested warmer lamps in the hold nine times. The subjects match whatever we give them, so grey lamps teach us that a creature can be grey, which we knew. Requisitions replied that warm lamps are a comfort item. I wrote back that the entire mission is a comfort item. Requisitions has stopped replying, which I am counting as progress.'},
{n:7,t:'FR',h:'THE HOVER IS THE HARD PART',b:'Recruits imagine the difficulty is finding them. It is not. They are everywhere, sitting in plain view, being the exact colour of the thing they are sitting on. The difficulty is holding station over a valley for an hour without wobbling, while below you something the size of your hand quietly wins.'},
{n:8,t:'FR',h:'WHY WE DO NOT USE NETS',b:'A net catches the animal and loses the answer. Whatever they do, they do it while calm, and a netted creature is not calm. So we hover, and we wait, and we lift them gently, and they arrive aboard mildly inconvenienced. Then they turn the colour of our floor and we learn nothing, gently.'},
{n:9,t:'FR',h:'INVENTORY, PARTIAL',b:'One lift, functioning. Two spare emitters, one of which hums. Four hundred and eleven cycles of logs, of which perhaps nine contain anything. A crew of six, down from thirty. One kettle, contested. And a locked cabinet of colour samples from home, which we are permitted to open on the anniversary and which nobody has asked to open in some time.'},
{n:10,t:'FR',h:'THE QUESTION PELL ASKED',b:'Pell asked what happens if we find it. If a subject shows us the trick and we learn it and take it home. I said the drought ends. Pell asked what we would do then, given that the entire fleet, the whole four hundred years, is this. I put down the log and we watched the valley for a while and neither of us said anything useful.'},
{n:11,t:'FR',h:'CORRECTION TO A PREVIOUS ENTRY',b:'In cycle four hundred and two I recorded that a subject had failed to change colour under observation. I was wrong. It had changed to the exact shade of the observation glass, which is why I could not see it. I found it later by its eyes. I have amended the record. I have not amended my confidence.'},
{n:12,t:'FR',h:'THE ANNIVERSARY',b:'Four hundred years today. There was a small ceremony in the hold. The captain read the founding order, which promises a solution within a generation. Nobody laughed, which was kind of us. Afterward Renn put a green sample on the wall for an hour and we all found reasons to walk past it.'},
{n:13,t:'FR',h:'ON BEING SEEN',b:'A subject looked at me today. Not near me. At me, one eye, the way you look at a thing you have already decided about. I recorded no change in its colour, which is itself the observation: it did not think it needed to hide from me. I have been thinking about that for six hours and I do not like where it goes.'},
{n:14,t:'FR',h:'PROCEDURE FOR A WET LIFT',b:'If the subject is on water, do not lift the water. This seems obvious. It was not obvious in cycle two hundred and nine, and the hold smelled of pond for a season. Wait for it to reach a bank. They always reach a bank. They are in no hurry, which is one of the many advantages they hold over us.'},
{n:15,t:'FR',h:'MORALE, AS REQUIRED BY THE FORM',b:'The form asks me to rate morale from one to nine. I have written five for two hundred cycles. Today I wrote five again and then sat looking at it. Five is not a feeling. Five is what you write so that nobody visits. I am leaving it at five.'},

/* ── SF: the creatures, one page each ─────────────────────────────────── */
{n:16,t:'SF',h:'SUBJECT 0044, THE ONE THAT ATE FIRST',b:'Taken from a warm stone. Before it would consent to be observed it ate nine crickets, unhurried, in front of six scientists who had been waiting four hundred years. Then it slept. Then it matched the stone we had brought aboard for it, which we had not told it was from home. Renn has requested a transfer.'},
{n:17,t:'SF',h:'SUBJECT 0090, THE STILL ONE',b:'Held eleven minutes and never moved once. Not a limb, not an eye. We ran the lamps through every band we have left. It stayed the colour it arrived. On the ground afterward it walked away briskly, as if it had been holding a pose out of politeness and was glad that was over.'},
{n:18,t:'SF',h:'SUBJECT 0102, TOAD, NOT THE TARGET',b:'A misfire. Round and unimpressed and far too heavy for the tray. It did not change colour because it has no such gift, and it made this clear by sitting in the middle of the hold looking like a decision somebody else had made. We fed it. It stayed forty minutes. I am not sorry.'},
{n:19,t:'SF',h:'SUBJECT 0117, THE TAIL',b:'Arrived without its tail, which had been left behind in a bush and which we retrieved out of a sense of duty. The tail was still faintly the colour of the bush. The subject was already the colour of our tray. I have logged this as one creature holding two opinions and I expect that to be queried.'},
{n:20,t:'SF',h:'SUBJECT 0203, THE HEARTBEAT',b:'Small enough to sit in a palm. What we recorded was not the colour but the pulse: steady on the ground, steady in the lift, steady in the hold, steady on the way back. Ours were not. Six trained observers, and the calmest thing in the room weighed less than a cup of water.'},
{n:21,t:'SF',h:'SUBJECT 0250, THE SLOW BLINK',b:'It blinked at Pell. One eye, then the other, unhurried. Pell blinked back, which is not procedure, and the subject did it again. Twelve minutes of this. No colour change in either party. Pell has written it up as contact. The captain has written it up as Pell being tired. Both entries stand.'},
{n:22,t:'SF',h:'SUBJECT 0311, TAKEN IN RAIN',b:'Rain confuses the lift and it arrived with a small storm around it. It shook itself, examined the puddle it had brought aboard, and turned the colour of wet floor, which is a colour we do not have a name for and which I am recording as a new band. The band is grey. It is a very good grey.'},
{n:23,t:'SF',h:'SUBJECT 0400, THE ONE WE LOST TRACK OF',b:'Aboard nineteen minutes, of which we can account for six. It was on the rail, and then it was not, and then a search of the hold turned up nothing but a slightly wrong shade of wall near the kettle. We found it eventually. I have not written down where, because I do not want it read out at a briefing.'},
{n:24,t:'SF',h:'SUBJECT 0455, THE FIRST REFUSAL',b:'Placed on a bright tile, it turned grey. Placed on a grey tile, it turned brighter. Placed on the tile from home, it went still and stayed exactly itself for the whole eleven minutes. The log requires a category. There is no category for a creature declining to answer a question, so I have invented one.'},
{n:25,t:'SF',h:'SUBJECT 0501, THE HITCHHIKER',b:'We lifted a chameleon and a beetle at the same time, the beetle being on the chameleon. The beetle disembarked immediately and lived in the hold for a season. It is not a subject and has no number and everyone knows exactly which panel it lives behind. It is the only crew member with no opinion about the mission.'},
{n:26,t:'SF',h:'SUBJECT 0620, THE SUNBATHER',b:'Would not be observed until it had finished warming itself, and could not be hurried, and made this obvious. We waited fifty minutes. Then it performed the change three times in a row, cleanly, as though repaying us. We recorded everything and understood none of it and thanked it, out loud, which is also not procedure.'},
{n:27,t:'SF',h:'SUBJECT 0704, EYES GOING SEPARATE WAYS',b:'One eye watched me and one eye watched the door. I do not know what to do with a creature that can consider two futures at once. It matched the tray perfectly while doing so. The universe has handed out its gifts unevenly and I have made peace with roughly none of it.'},
{n:28,t:'SF',h:'SUBJECT 0777, THE LONG ONE',b:'Longer than the tray, so it draped, and having draped it matched both the tray and the shadow the tray was casting, in two different shades, at once. Renn asked whether that counted as one change or two. I have logged it as two. I have also stopped pretending our categories are about the animals.'},
{n:29,t:'SF',h:'SUBJECT 0812, RETURNED EARLY',b:'It began to change and then stopped, and the amber patches stayed amber, and it sat down. We put it back at once. Nobody argued. On the ground it recovered its colour within a minute and went up its branch and did not look back at the ship, which I have decided is a kindness.'},
{n:30,t:'SF',h:'SUBJECT 0900, THE ONE WE ALL REMEMBER',b:'Nine minutes, no drama, and near the end it climbed the rail and matched the observation glass so exactly that for a moment the hold appeared to contain one fewer thing than it did. Six of us, holding our instruments, looking at a piece of empty air where the answer was sitting. Then it moved and was a creature again.'},

/* ── HW: the world we come from ────────────────────────────────────────── */
{n:31,t:'HW',h:'WHAT A VELL LOOKS LIKE',b:'Tall, pale, and the same on Tuesday as on any other day. Our skin does not consult the weather. When we describe ourselves to a subject, and yes some of us have tried, there is nothing to point at. We are the only thing in the room that has never chosen a colour, and we have crossed a great deal of space to say so.'},
{n:32,t:'HW',h:'THE BANDS WE HAVE LOST',b:'Nineteen, at last count, though the count is disputed because you cannot miss what you can no longer imagine. The archive keeps sealed samples so that we can at least confirm a loss. Opening one is a formal occasion. Children are brought. Afterward everyone is quiet on the walk home and nobody explains why to the children.'},
{n:33,t:'HW',h:'THE FOUNDING ORDER',b:'Six lines, still posted in every hold. Find the creatures who choose their colour. Learn the choosing. Bring it home. Do no harm in the learning. Return what you take. Report honestly. The fourth and fifth lines are why our lift is gentle. The sixth is why this log is so long and so unhelpful.'},
{n:34,t:'HW',h:'WHY IT IS CALLED A DROUGHT',b:'Because the first committee hoped it would rain. A drought ends. A drought is a thing you wait out with dignity, storing what you have, telling the young ones about the wet years. Four centuries in, the word has stopped meaning weather and started meaning us, and we still use it, because the alternative is a word nobody wants to sign.'},
{n:35,t:'HW',h:'THE GREY IS NOT UGLY',b:'This surprises visitors, when we had visitors. It is a soft world, warm in its way, and a person can live a whole good life in it. That is the difficulty. If it were hideous we would have solved it or died. Instead it is merely less, slightly more every year, and pleasant enough that arguing feels rude.'},
{n:36,t:'HW',h:'THE MORAL ART',b:'To change your own colour, with intent, is the highest act our philosophy describes, and it describes it at enormous length for something none of us has ever done. Eleven volumes. Diagrams. A prize, unclaimed for two hundred years. And then a creature the length of a spoon does it on a branch because the branch is brown.'},
{n:37,t:'HW',h:'WHO PAYS FOR THIS',b:'A trust, established by the founding committee, invested well, and older now than the institution that manages it. No living Vell has met a person who voted for the mission. The money simply arrives, and the barge stays fuelled, and once a cycle a form asks whether we require anything. We require an answer. There is no box for it.'},
{n:38,t:'HW',h:'THE ANNIVERSARY SAMPLE',b:'One sealed square of true green, opened for an hour every hundred years, on the ship as at home. It is the only green any of us will see. Crew rotate past it in silence. Afterward there is a mandatory rest period, because the founding committee understood something about hope that the rest of the paperwork does not.'},
{n:39,t:'HW',h:'WHAT WE TELL THE YOUNG',b:'That there is a fleet. That it is patient and careful and kind to the creatures it studies. That the answer is a matter of time. Every part of that is true, which is what makes saying it so hard. I was told it. I believed it. I am now the part that is a matter of time.'},
{n:40,t:'HW',h:'THE ARGUMENT NOBODY WINS',b:'One side says the drought is something happening to us. The other says it is something we are doing. The first requires a cure. The second requires a confession. Four centuries of committees have preferred the cure, and the survey exists because a cure can be searched for at a distance, and a confession cannot.'},

/* ── IW: the other side of the glass ──────────────────────────────────── */
{n:41,t:'IW',h:'THE RULE ABOUT BEING LIFTED',b:'If the ground leaves, do not fight the ground. Fold your feet. Go the colour of nothing much. You will be somewhere bright and quiet and there will be crickets, and then you will be home on the same stone, warmer than when you left. This has happened to my grandmother twice and she speaks of it the way one speaks of a long queue.'},
{n:42,t:'IW',h:'ON THE PALE ONES',b:'They are the same colour always, which among us would be considered a great sorrow, so we are gentle with them. They lean very close and make a small noise when you change. My mother said the kindest thing you can do for a pale one is to do it slowly so they can watch. My mother was softer than me.'},
{n:43,t:'IW',h:'WHY WE DO NOT TELL THEM',b:'Because there is nothing to tell. You do not decide to be the colour of the branch any more than you decide to be tired. They want a method. We have a branch. Every time one of them leans in with its instrument, hoping, I feel the way you feel when a guest asks to see something you do not own.'},
{n:44,t:'IW',h:'THE BEETLE WHO WENT UP AND STAYED',b:'It went up on somebody\'s back by accident and it never came down. We tell the young ones it lives behind a warm panel and is fed and has opinions about nothing, and that when the lights pass over the valley it does not look out, because it is already exactly where it wants to be. We are not sure this story is a warning.'},
{n:45,t:'IW',h:'THE LIGHTS ARE POLITE',b:'This is the whole of what we know. They hover, they hum, they do not chase, and they put you back. A thing that meant harm would be quicker and would not apologise with its whole body the way they do. So we are not afraid of the lights. We are only careful, the way you are careful with anything that wants something from you.'},
{n:46,t:'IW',h:'WHAT THE STONE KNOWS',b:'Sit on a stone long enough and you will be the colour of the stone, and the stone will be the temperature of you, and neither of you did anything on purpose. This is the closest thing we have to an explanation, and we would give it to the pale ones if they had a word for it, and they do not, and they have eleven volumes.'},
{n:47,t:'IW',h:'ADVICE FOR THE VERY GREEN',b:'You are young and you are bright and you will want to show it off. Do not do this near the lights. Not because they are dangerous. Because they will follow you home and hover for an hour and their hovering knocks the dew off everything, and then you are a young thing on a dry branch with nothing to drink.'},
{n:48,t:'IW',h:'THE ONE WHO CAME BACK DIFFERENT',b:'Not harmed. Not changed in the body. Only quieter, and slower to match, as if the matching had become a thing to think about. The old ones say that is what looking at the pale ones does: it makes a plain gift feel like a performance. She lived a long while after and she was well. She just took her time about the branch.'},
{n:49,t:'IW',h:'WHAT WE OWE THEM, IF ANYTHING',b:'Nothing, says my uncle, who has been lifted four times and considers it a nuisance. Something, says the old one on the west rock, who says a creature that puts you back has already paid. The argument goes on. Meanwhile the lights come, and we go dull, and afterward there are crickets, and nobody has ever gone hungry over principles.'},
{n:50,t:'IW',h:'THE THING WE HAVE NEVER SAID ALOUD',b:'They are looking for a way to be what we are. All that quiet leaning in, all that light. If they ever find it, they will not need the valley, and the lights will stop, and the dew will stay on the branches, and it will be the same as before. I do not know why that sits so heavily with me. I mention it to no one.'},

/* ── the mixed pages that only make sense out of order ────────────────── */
{n:51,t:'FR',h:'AN OBSERVATION I AM NOT FILING',b:'They match our floor within seconds. They match our glass within a minute. Not one of them, in four hundred years, has ever matched a Vell. I have checked the whole archive. Either we are the only surface here that is not worth becoming, or they are being tactful, and I no longer know which answer I would prefer.'},
{n:52,t:'SF',h:'SUBJECT 0958, WHO CHOSE THE KETTLE',b:'Given the run of the observation table and a choice of nine surfaces, it crossed all nine and settled on the kettle, which is copper, which is the warmest thing aboard and the only object here that came from home. It matched the kettle. Renn had to leave the hold. I stayed and wrote copper in the log and then sat with it a while.'},
{n:53,t:'HW',h:'THE PRIZE',b:'Two hundred years unclaimed, held in trust, awarded to the first Vell who changes their own colour by intent under observation. The sum is now absurd. The conditions are eleven pages. There is a clause about witnesses and a clause about lighting and no clause at all about what the winner is supposed to do the following morning.'},
{n:54,t:'IW',h:'ON THE HUM',b:'They hum before they hover and they hum after. The young think it is a warning. The old say it is not for us at all, that a thing that big cannot hold still without saying something, and the hum is only the sound of an effort. If you listen from under a leaf it is almost companionable.'},
{n:55,t:'FR',h:'THE PART OF THE JOB I LIKE',b:'The valley at first light, before the lift is warm, when nothing is required of me for eleven minutes. There is a stone down there that is a slightly different colour every morning depending on who is sitting on it, and I have never once managed to catch the change happening, and I look forward to failing at it again tomorrow.'},
{n:56,t:'SF',h:'SUBJECT 1000, PENDING',b:'The number has been reserved for two cycles now because Renn wants it to be something. A ceremony. A breakthrough. I have explained that the thousandth subject will be whatever is sitting on whatever it is sitting on when we happen to be overhead, and that this is the whole nature of the work, and Renn has reserved it anyway.'},
{n:57,t:'HW',h:'A NOTE FROM THE ARCHIVE, UNSIGNED',b:'Found tucked in volume six of the moral art, in a hand nobody recognises. It reads: we have written eleven books about choosing and none about being chosen. Consider that the creatures are choosing the branch, and the branch does not consult. Consider what we are, in that arrangement. Then it stops. There is no page after it.'},
{n:58,t:'IW',h:'THE VALLEY IS NOT AFRAID',b:'This is worth saying plainly, since the pale ones seem to worry about it. The birds still nest. The toads still shout all night about nothing. Nobody has moved away over the lights. A thing that comes, hovers, takes one of us politely and returns us warm is, in the accounting of a valley, weather.'},
{n:59,t:'FR',h:'WHAT I WOULD WRITE IF THE FORM ALLOWED',b:'That the mission is beautiful and mistaken. That we crossed a great deal of dark to ask a small green creature how to be ourselves. That it answered, immediately and repeatedly, by sitting on a brown branch and being brown. And that the answer being simple has not made it any easier to carry home.'},
{n:60,t:'HW',h:'IF IT ENDS',b:'Say we learn it. Say a Vell stands in the archive and turns, on purpose, the colour of the wall, and the prize is paid and the drought is over. There will still be nineteen bands nobody can name, and a barge four centuries out, and a valley full of creatures who never once needed us. I would like to see it anyway.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
