/* THE ABDUCTION FILES — bank 10 (pages 641 to 720).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES. */
;(function () {
  var P = [

/* ── FR ───────────────────────────────────────────────────────────────── */
{n:641,t:'FR',h:'THE SECOND YEAR OF THE STONE',b:'We put it out again at the same hour on the same ground. Eleven visits across forty days, six of them the same individual by mark. Nothing was taken. Nothing was left. My predecessor would have called this a null result and filed it under weather, and I have given it eleven pages.'},
{n:642,t:'FR',h:'ON REPEATING AN EXPERIMENT',b:'Renn says once is an anecdote and twice is a habit and that we should stop before it becomes a ritual. He is right about the risk and wrong about the timing. A survey that stopped things because they might become sacred would have stopped the log, the lamps, and most of what this fleet is now for.'},
{n:643,t:'FR',h:'LETTER FROM PELL',b:'Lieutenant Pell has transferred to the third survey and writes that their hold is quiet and their kettle is worse. She asked, at the end and in smaller handwriting, whether the stone had been visited again. I have written back with the number and nothing else, because she will know what eleven means.'},
{n:644,t:'FR',h:'THE JOINT VESSEL, FIRST FRAME',b:'Laid down this cycle at the visitors\' yards with two of our engineers aboard as guests and a shape neither fleet would have drawn alone. It carries no lift array. When I read that line in the specification I put the page down and went and stood in the hold for a while, which the crew has learned to leave alone.'},
{n:645,t:'FR',h:'WHAT A SHIP WITHOUT A LIFT IS FOR',b:'Sitting still, mostly. Recording, leaving things, waiting to be approached, and going home with less than it came for. Our founding order has no word for such a vessel and the visitors have four, which tells you something about which of us has been doing this longer and which has been doing it better.'},
{n:646,t:'FR',h:'EXTRACTIONS THIS YEAR: FOUR',b:'Down from nine, and every one written up with a reason the crew would sign in front of the individual concerned, which is the test I have adopted and not yet put in the manual. Two were injured animals that came back to the same slope healed. The other two I would not authorise again.'},
{n:647,t:'FR',h:'ON THE TWO I REGRET',b:'Ordinary subjects, ordinary weather, and a reason on the form that reads well and means nothing. I signed both. I have kept the forms out of the sealed cabinet and on the shelf by the door where I have to walk past them, which Renn thinks is theatre and which has worked twice already.'},
{n:648,t:'FR',h:'CAPTAIN VESSEL WRITES',b:'From the port district, where she has a room over a repair yard and complains about the noise in a way that means she likes it. She asked whether the hold still smells of the pond. I told her it does. She wrote back one line saying good, and that is the entire correspondence of a woman who commanded twelve ships.'},
{n:649,t:'FR',h:'THE NEW CAPTAIN',b:'Young, from the third survey, and she has read the whole log including the century everybody skips. In her first week she asked why the sealed cabinet is sealed. I gave her the historical answer. She said she understood the history and repeated the question, and I have not yet found a second answer.'},
{n:650,t:'FR',h:'ON BEING ASKED A SECOND TIME',b:'It is how her generation argues and it is effective and I dislike it, which is a fact about me. The samples are sealed because they are irreplaceable. They are irreplaceable because we stopped making them. We stopped making them because the spectrum went. None of that is a reason to keep them in a box.'},
{n:651,t:'FR',h:'THIRTY SIX LEFT',b:'Counted this morning with the captain present because she asked to see them counted. Forty went into the cabinet four centuries ago and thirty six remain, which is a rate of loss so slow it looks like preservation. At the current rate the last one opens in nine hundred years and nobody alive will be embarrassed.'},
{n:652,t:'FR',h:'THE PROPOSAL NOBODY WOULD SIGN',b:'That we open one a season rather than one a year and put the light on open ground where anything can look at it. It went round the crew for a month and came back unsigned by everyone including me. I am recording that it was refused, and by whom, and that the refusal was unanimous and unargued.'},
{n:653,t:'FR',h:'ON UNANIMOUS AND UNARGUED',b:'Those are the dangerous ones. A crew that argues has thought. A crew that agrees instantly has felt something and dressed it as judgement, and I have been aboard long enough to know I did exactly that and signed nothing and called it prudence.'},
{n:654,t:'FR',h:'WE LEFT A MARK',b:'Not an object. A shape scratched into the flat rock by the stone place, four lines, the one the girl at home keeps writing. No warmth, no light, nothing to take. If the point is to be answered rather than to give, then the thing we leave has to be useless.'},
{n:655,t:'FR',h:'DAY ELEVEN OF THE MARK',b:'Weather, weather, a bird, weather. The recorder is patient in a way this crew is learning from. Two of the younger technicians have started watching the feed on their own time, which I have not encouraged and will not discourage, and which is how every good habit on this ship began.'},
{n:656,t:'FR',h:'DAY TWENTY TWO',b:'A subject stopped at the rock, moved along the four lines with its head, and stayed one minute and forty seconds. It did not touch. It did not colour. Then it went up the slope. I have watched it enough times that Renn has taken the recorder away from me for a day, and he was right to.'},
{n:657,t:'FR',h:'WHAT I WILL NOT WRITE',b:'That it read the mark. It looked at a scratched rock for a minute and forty seconds and every word past that is mine and not the animal\'s. The archive is four hundred years of people not writing that sentence and I am not going to be the one who breaks it in my tenth year.'},
{n:658,t:'FR',h:'WHAT I WILL WRITE',b:'That something in this valley now spends time on things we put there, and did not before we started putting them there, and that the difference between that and an answer is a difference I can live with for the rest of my service. The finding is unchanged. The relationship is not.'},
{n:659,t:'FR',h:'ON THE WORD RELATIONSHIP',b:'It is not in the founding order either. I have used it once, above, and I will not use it again in this log, because it is the kind of word that a later cataloguer will find and build a century on. Whoever you are: I meant it narrowly and I was tired and the mark was still there in the morning.'},
{n:660,t:'FR',h:'TENTH YEAR, CLOSING NOTE',b:'Four extractions, eleven stone visits, one mark, thirty six samples, a ship being built that cannot lift anything. My predecessor waited five years before changing a thing. I have waited ten and changed less than I meant to and more than I intended, and both of those are true and I am leaving them both in.'},

/* ── SF ───────────────────────────────────────────────────────────────── */
{n:661,t:'SF',h:'SUBJECT 17204, THE ONE THAT LOOKED',b:'Marked at the stone in the first season and again in the second, six times across forty days, always alone and always at the flat hour before the light goes. Ridge count puts her in her middle years. She has never been lifted and under my hand she will not be, and I have written that in the file rather than the margin.'},
{n:662,t:'SF',h:'ON PUTTING IT IN THE FILE',b:'The margin is where a cataloguer puts the thing she is not sure she is allowed to feel. Four centuries of this archive has a second archive running down its right hand edge. I am moving mine inward, one entry at a time, and the form has not objected yet.'},
{n:663,t:'SF',h:'SUBJECT 17211',b:'Adult, unremarkable, warm slope, four days. Came within nine lengths of the mark on the second day and did not stop. I am recording the not stopping because an archive that only writes down the animals that do the interesting thing is not an archive, it is an argument.'},
{n:664,t:'SF',h:'SUBJECT 17218, INJURED',b:'Foreleg, old break badly set, favouring it on rock. Lifted at the eleventh hour, splinted, held nine days, returned to the same slope. Came back onto the mark ground three weeks later moving better. This is the only kind of extraction I can still sign without reading the form twice.'},
{n:665,t:'SF',h:'ON THE ONLY KIND',b:'Take an animal that is suffering, mend it, put it back where you found it, write down what you did. If four hundred years of this fleet has produced one defensible sentence about lifting, it is that one, and it took us until the fifth century to say it plainly.'},
{n:666,t:'SF',h:'SUBJECT 17222',b:'Juvenile, first year, extremely bold, approached a technician on open ground to within two lengths and had to be walked away from. Not lifted. Filed under the same number as its parent by mark comparison, which is a thing this archive could not have done a century ago and now does routinely.'},
{n:667,t:'SF',h:'A FILE FOR A CREATURE WE LEFT ALONE',b:'Seventeen thousand two hundred and twenty two entries, and the ones I reread are the ones where the finding column says observed and returned. There is no instrument on this ship that measures why that is, and I have stopped pretending it is a scientific preference.'},
{n:668,t:'SF',h:'SUBJECT 17230, THE COUSIN VALLEY',b:'From over the ridge, second population, first individual of theirs recorded on our ground. Slightly darker, slightly larger, same behaviour at the mark: stop, look, leave. Two valleys that have never mixed doing the identical incomprehensible thing is either very important or nothing at all.'},
{n:669,t:'SF',h:'ON WHICH OF THOSE IT IS',b:'I do not know and neither will you, whoever reads this. What I can tell you is that the crew argued about it for six evenings and nobody raised their voice, and that a hundred years ago the same argument ended a friendship, and that this is the only measurable progress in the file.'},
{n:670,t:'SF',h:'SUBJECT 17241',b:'Old female, very old, ridge count near the ceiling of the method. Sits on the same warm rock every flat hour. Has been in this archive under three numbers across two centuries because three cataloguers did not have mark comparison and each thought they had found her first.'},
{n:671,t:'SF',h:'MERGING THREE FILES INTO ONE',b:'Two hundred years of separate observations about the same animal, now one entry, and the entry is longer than most of our species have written about themselves. She has outlived four cataloguers and will outlive me and has never once done anything the founding order considers data.'},
{n:672,t:'SF',h:'SUBJECT 17250',b:'Adult male, ordinary, four days, returned. I am putting him here at the round number on purpose so that whoever shuffles these pages finds an unremarkable creature at a milestone. The archive should not teach anybody that the interesting ones are the ones that count.'},
{n:673,t:'SF',h:'ON ROUND NUMBERS',b:'My predecessor put the six hundredth page on a small green animal that never asked to be described. I have put subject seventeen thousand two hundred and fifty on a male who did nothing for four days. We are not a subtle profession but we are a consistent one.'},
{n:674,t:'SF',h:'SUBJECT 17258, NOT FOUND',b:'Marked eleven years ago, expected on the warm slope, absent for three seasons. No body, no signal, nothing. The form has no column for this so I have written absent in the finding and left the file open, and I will leave it open until somebody after me decides it is unkind to.'},
{n:675,t:'SF',h:'ON LEAVING A FILE OPEN',b:'It costs a line in the index and it means the archive contains a creature we have not accounted for. Four centuries of tidy closing entries and I am starting a habit of not closing them, which the manual would call sloppy and which I would call honest about what we actually know.'},
{n:676,t:'SF',h:'SUBJECT 17263',b:'Juvenile, born on the mark ground, first individual in this archive whose entire recorded life has happened within sight of something we put there. She does not treat the rock as remarkable. That is either the most important sentence in this bank or a sentence about a young animal and a rock.'},
{n:677,t:'SF',h:'THE GENERATION THAT GREW UP WITH IT',b:'Four of them now, all juveniles, all born since the stone. None of them stop at the mark the way the older ones do. Renn thinks this means the older ones find it strange and the young ones do not. I think it means we have been here long enough to change what ordinary looks like down there.'},
{n:678,t:'SF',h:'ON HAVING CHANGED SOMETHING',b:'Four hundred years of extraction changed nothing we could measure. Two seasons of leaving a warm rock in the open may have changed what a generation of animals considers unremarkable. If that is true it is the most consequential thing this fleet has ever done and it was designed in an afternoon.'},
{n:679,t:'SF',h:'SUBJECT 17271',b:'Adult, warm slope, four days, observed and returned, unremarkable in every column. Filed at the end of my tenth year. The finding is unchanged, it has been unchanged since the first entry, and the archive is now four hundred years of careful attention to that fact.'},
{n:680,t:'SF',h:'WHAT THE FILES ARE FOR NOW',b:'Not proving anything. Keeping track of who is out there, one animal at a time, so that when somebody eventually understands what we have been looking at they will find that we wrote down the individuals rather than the totals. Seventeen thousand names for a thing that has no use for names.'},

/* ── HW ───────────────────────────────────────────────────────────────── */
{n:681,t:'HW',h:'THE JOINT VESSEL IS FUNDED',b:'Passed in a single session with an argument that lasted forty minutes, which for this ministry is a formality. The dissenting member asked what it would bring back. The answering member said nothing, and meant it literally, and the vote carried anyway. I have never seen that happen in my lifetime.'},
{n:682,t:'HW',h:'ON A SHIP THAT BRINGS NOTHING BACK',b:'Two centuries ago the question would have ended it. Our whole space effort was justified by return: samples, subjects, data, eventually the spectrum. A vessel whose purpose is to sit somewhere and be available is not a compromise on that. It is a different species answering a different question.'},
{n:683,t:'HW',h:'THE GIRL IS NINETEEN',b:'She still writes four lines. There are now people who write four lines and call it her form and she has asked them politely to stop, on the grounds that four lines was how much she had to say at eleven and is not a rule. The request has been widely ignored, which is what happens.'},
{n:684,t:'HW',h:'WHAT SHE ACTUALLY DOES NOW',b:'Works in the archive, in the miscellaneous room, cataloguing the margins that made her famous. She has refused the ministry twice. Somebody asked her in public why and she said the margins were written by people doing the ordinary part of the job and she would like to do the ordinary part of the job.'},
{n:685,t:'HW',h:'THE DISSENT, ANSWERED PROPERLY',b:'A reply published this season, thirty pages, and the strongest thing in it is that it concedes most of the argument. Yes we have made a mood out of a search. Yes our grandchildren will inherit a beige world. It contests only the conclusion that this is a failure, and it does so on the evidence of who we became.'},
{n:686,t:'HW',h:'ON CONCEDING MOST OF AN ARGUMENT',b:'It has done more for the position than four decades of defending it did. Two of the original dissenters have written that they were answered. One has not and says the reply is elegant surrender. All three are now on the joint vessel committee, which is either institutional wisdom or an excellent joke.'},
{n:687,t:'HW',h:'THE VIGIL, TWENTY YEARS ON',b:'Still a word people use without thinking about where it came from. My nephew used it about waiting for exam results and was surprised to learn it entered the language from a historian writing about a fleet. That is what a word doing its job looks like and the historian would be pleased and would not say so.'},
{n:688,t:'HW',h:'THE EXHIBITION',b:'Four rooms. Columns in the first, margins in the second, the four day feed running in the third, and the fourth is empty with one bench and a window. Attendance is beyond anything the ministry projected and the room people talk about afterwards is the fourth one, which cost nothing.'},
{n:689,t:'HW',h:'ON THE EMPTY ROOM',b:'The curator has been asked repeatedly to put something in it. She has refused each time and her stated reason is that the fleet spent four hundred years learning that the important part is the waiting and it would be strange to teach that in a room full of exhibits.'},
{n:690,t:'HW',h:'A QUESTION FROM A SCHOOL',b:'Sent to the ministry, signed by a class of nine year olds: if the chameleons could send us one thing, what would we want it to be. The ministry answered honestly that it had never asked itself that and would think about it. That answer was reported everywhere and I think it was the right one.'},
{n:691,t:'HW',h:'WHAT PEOPLE SAID THEY WOULD WANT',b:'An informal count from the letters that followed. Very few said the spectrum. Most said an explanation, and a large minority said nothing at all, and a small persistent group said they would want to be asked something back. That last group is younger than the vigil.'},
{n:692,t:'HW',h:'THE SAMPLE QUESTION AT HOME',b:'Thirty six left in the fleet cabinet and eleven in the ministry vault and a proposal to open one publicly. It has been raised in four consecutive sessions and deferred in four consecutive sessions and nobody has voted against it. We are a species that has learned to postpone rather than refuse.'},
{n:693,t:'HW',h:'ON POSTPONING RATHER THAN REFUSING',b:'It looks like cowardice and it may be. It is also how the lamps arrived, and the field for the ordinary, and the margins, and the joint vessel. Every one of those was deferred for decades and then done. Our institutions do not say no. They say later, for a very long time, and then act.'},
{n:694,t:'HW',h:'FUNDING, SECOND RISE IN NINETY YEARS',b:'Smaller than the first and carried without a joke this time. The case was made on the archive rather than on the search: that we hold the longest continuous record of another living species anywhere in known space, and that this is worth money whether or not it ever becomes an answer.'},
{n:695,t:'HW',h:'THE ARGUMENT THAT FINALLY WORKED',b:'Not hope. Custody. We are the only people keeping this record and if we stop it does not pass to anyone else, it simply ends. A member who has voted against every increase for thirty years voted for that one and said afterwards that custody was a word he could take home.'},
{n:696,t:'HW',h:'MY MOTHER\'S SHELF',b:'Her forty years of descriptions of shades she never saw are now the fourth most requested item in the archive, behind the margins, the feed, and the four lines. There is a note beside them explaining who she was. I did not write it and I do not know who did and I have not asked.'},
{n:697,t:'HW',h:'ON NOT ASKING WHO WROTE IT',b:'Because I would like it to have been an ordinary reader who looked her up, and if I ask I might find it was the ministry. Four centuries of this project has taught our whole species to be careful about which questions we insist on the answer to, and I am applying it to a note on a shelf.'},
{n:698,t:'HW',h:'WHAT THE VISITORS THINK OF US',b:'Their delegation published an account of a year in our institutions and the phrase that travelled was that we are a people who have organised our entire public life around an absence. They meant it descriptively. It has been read here as praise, as insult, and most often as a simple fact.'},
{n:699,t:'HW',h:'A BEIGE WORLD AND A GOOD VOCABULARY',b:'The dissenter\'s phrase, now used affectionately by the people it was aimed at, printed on things, taught in schools. She has said publicly that she resents this and that being agreed with cheerfully is worse than being argued with. I have some sympathy and I still print it.'},
{n:700,t:'HW',h:'THE SEVEN HUNDREDTH PAGE',b:'Written from a world that has been grey for four centuries by somebody who has never seen otherwise and does not expect to. If you are reading this out of order, and you are, then the page you read before it and the page after are both about the same small animal, and none of us have ever met it.'},

/* ── IW ───────────────────────────────────────────────────────────────── */
{n:701,t:'IW',h:'THE THING LEFT IN THE OPEN',b:'A new entry, and the old ones argued about it for two seasons before allowing it. Something was put on the flat ground at the low hour and nothing came for it and nothing wanted anything. The entry does not say what it means. The old ones say an account that explains things stops being an account.'},
{n:702,t:'IW',h:'WHY IT TOOK TWO SEASONS',b:'Because for four hundred years everything from up there arrived attached to a taking. A thing that arrives and asks for nothing had no place in an account built entirely out of warnings, and the old ones had to decide whether the account was a warning or a record before they could add a line.'},
{n:703,t:'IW',h:'WHAT THEY DECIDED IT WAS',b:'A record. It was not unanimous. The ones who wanted a warning are not wrong that the liftings still happen and that four in a year is four. They lost on the argument that an account which only holds the bad parts will eventually be believed only by people who have seen them.'},
{n:704,t:'IW',h:'THE ONE WHO WENT AND LOOKED',b:'She is not named. She went at the flat hour, stood at four lengths, stayed the length of two long breaths, and came back up the slope and said nothing to anybody for a season. When she did speak she said it was warm and that this was all she was going to say about it.'},
{n:705,t:'IW',h:'ON IT WAS WARM',b:'The old ones have kept those three words exactly as they were given, without a lesson attached, which is now the second time they have done this and it is becoming a practice. A thing said plainly by somebody who was there is harder to argue with and harder to use, and both of those are the point.'},
{n:706,t:'IW',h:'THE MARKS ON THE ROCK',b:'Four lines scratched into the flat stone by the same hands that left the warm thing. They were not there before. They do nothing. The old ones have added them to the account as an observation and have specifically declined to add an interpretation, and two of them argued for leaving them out entirely.'},
{n:707,t:'IW',h:'THE ARGUMENT FOR LEAVING THEM OUT',b:'That the moment we record marks made by them, we start reading marks, and a people that reads marks made by something it cannot ask will read whatever it already believes. It is the best argument anybody made and it lost by one, and the one who made it agreed to be recorded as having made it.'},
{n:708,t:'IW',h:'WHO GOES TO LOOK NOW',b:'Anybody. It is not forbidden and it is not encouraged and nobody has been told what to do when they get there. Several of the young have gone. Two came back with opinions and the old ones listened and did not write them down, which the young found insulting and will understand later.'},
{n:709,t:'IW',h:'THE YOUNG WHO WERE BORN AFTER',b:'They do not find the flat rock strange. To them it has always been on that ground, like weather or the ridge. The old ones find this the most difficult thing that has happened in a century, because an account of instructions cannot instruct people who do not feel the danger it was built from.'},
{n:710,t:'IW',h:'ON A DANGER YOU CANNOT FEEL',b:'Four hundred years of being taken made the four instructions obvious. Eleven years of fewer takings and a warm stone has made them a story. The old ones say the instructions must stay exactly as they are and be repeated exactly as they are, precisely because nobody in the valley now feels why.'},
{n:711,t:'IW',h:'THE INSTRUCTIONS, UNCHANGED',b:'Do not go up. Do not follow the light. Do not answer. Come back down the way you went up. Four, as they have always been, and the third one now sits oddly beside a rock people go and stand at, and the old ones have refused every request to soften it.'},
{n:712,t:'IW',h:'ON REFUSING TO SOFTEN THE THIRD',b:'Because standing near a thing is not answering it, and the distance between those two is the whole account. The moment do not answer becomes answer carefully, we have agreed to a conversation on terms set by whatever is up there, and we have never once been able to see who is setting them.'},
{n:713,t:'IW',h:'THE QUESTION NOBODY WILL REPEAT',b:'Still not repeated. The old chameleon who asked it is dead now, three winters, and the two who heard it are old themselves and have both said separately that they will take it with them. Nobody has pressed them. There is a growing view among the young that this is precious and cowardly at once.'},
{n:714,t:'IW',h:'THE YOUNG ARE PARTLY RIGHT',b:'An account that keeps its hardest line out of itself is protecting somebody, and it is probably protecting us. The old ones do not dispute this. They say only that they have watched what happens to a question when everybody has it, and that they would rather be called cowards by people who are safe.'},
{n:715,t:'IW',h:'WHAT WE WOULD LEAVE BACK',b:'It has been raised for the first time in the account\'s history. Not an answer and not a message. Something on the flat rock at the low hour that is ours and is useless, so that whatever comes for it learns nothing except that we were there. The old ones have not ruled and are not hurrying.'},
{n:716,t:'IW',h:'THE ARGUMENT AGAINST LEAVING ANYTHING',b:'That it is answering, and the third instruction is four hundred years old and has kept a valley alive. That is not a small objection and nobody has treated it as one. The reply is that a thing which says nothing is not an answer, and the reply to that is who decides what says nothing.'},
{n:717,t:'IW',h:'ON WHO DECIDES',b:'Not us, is the honest answer. Whatever is up there will read a stone we leave however it reads it, and we will never be told. Four hundred years of being unable to ask is the fact underneath every line of this account, and the old ones repeat it whenever a discussion starts to feel clever.'},
{n:718,t:'IW',h:'THE COUSINS OVER THE RIDGE',b:'They have the account now, all four instructions and most of the entries, carried across by the ones who go between. Their old ones have added a fifth instruction of their own that ours have declined to adopt. Neither group has suggested the other is wrong, which took a century and one bad winter.'},
{n:719,t:'IW',h:'THEIR FIFTH INSTRUCTION',b:'Tell it to the young before they are old enough to be curious. Ours say the opposite, that curiosity is when it matters and a warning given too early is furniture. Both valleys have lost people. Neither can prove anything. It is recorded that the disagreement exists and that both sides are careful.'},
{n:720,t:'IW',h:'THE ACCOUNT AT THE SEVEN HUNDREDTH',b:'Four instructions. Sixteen entries. One song. One question nobody will repeat. One old creature left out. One warm thing, one flat rock, four lines that nobody will interpret. Smaller than it was, doing more, and still no way of knowing whether any of it has ever been heard.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
