/* THE ABDUCTION FILES — bank 9 (pages 561 to 640).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES. */
;(function () {
  var P = [

/* ── FR ───────────────────────────────────────────────────────────────── */
{n:561,t:'FR',h:'THE VISITORS ARRIVE NEXT SEASON',b:'Four scientists from a world with a full spectrum, coming aboard for a year. I have read their published work and it is excellent and entirely unlike ours: they ask questions that can be answered. The crew is nervous in a way I have not seen and I include myself and I have not said so aloud until this line.'},
{n:562,t:'FR',h:'ON PREPARING THE SHIP',b:'We have cleaned the hold for the first time in a century and I have stopped it. The pond smell from cycle two hundred and nine is part of this vessel and hiding it from people who came to see what we do would be the beginning of performing for them. The hold stays as it is.'},
{n:563,t:'FR',h:'WHAT THEY SAID ON THE FIRST DAY',b:'That the valley was beautiful, which we knew, and that our four day observations were the most careful field work they had read, which we did not. Their lead asked to see the margins before the columns. Renn had bet on this. Nobody took the bet, which tells you what this crew already suspected.'},
{n:564,t:'FR',h:'THE QUESTION THEY ASKED FIRST',b:'Why we hover at four hundred lengths. I explained the downdraft and the resolution limit. Their lead said that was a good answer and then asked why we had never simply asked the creatures to come to us. I said they would not. She said we did not know that, and I checked four centuries of files, and we do not.'},
{n:565,t:'FR',h:'ON NEVER HAVING ASKED',b:'Four hundred years, twelve vessels, fifteen thousand extractions, and not one recorded attempt to put something down there and wait. It is not in the founding order. It is not forbidden. Nobody thought of it, or everybody assumed somebody had, and a visitor asked in her first hour and I have not slept well since.'},
{n:566,t:'FR',h:'THE PROPOSAL, WRITTEN',b:'A warm stone from the sealed cabinet, placed on open ground at the eleventh hour, and a recorder, and nothing else. No lift, no hold, no lamps. Four days. If nothing comes we have lost a stone. I have submitted it to the captain and she signed it in the time it took to read.'},
{n:567,t:'FR',h:'WHAT THE VISITORS THOUGHT OF THAT',b:'Their lead read the proposal and said it was the first experiment this fleet had designed in three centuries. I said that was unkind. She said it was not meant unkindly, and that a survey which has been answering the same question for four hundred years is not doing science, it is doing devotion, and that she did not mean that unkindly either.'},
{n:568,t:'FR',h:'ON THE WORD DEVOTION',b:'I have turned it over for a season. She is right and the word is right and it is not an insult in her language or, I have decided, in ours. Four hundred years of careful attention to something that will not explain itself. If there is a better word I cannot find it and the historian at home would probably approve.'},
{n:569,t:'FR',h:'THE STONE IS PLACED',b:'At the eleventh hour, on open ground, with the flat light coming across the ridge. A crew of six and four visitors watched a technician set down a piece of home in a valley on the far side of the sky and walk away. Nobody spoke. It is the least scientific sentence I have written and it is what happened.'},
{n:570,t:'FR',h:'DAY ONE, NOTHING',b:'The recorder shows a stone on open ground and eleven hours of weather. Two of the visitors watched the whole feed. Renn watched the whole feed. I watched the whole feed and would have watched it twice. Four hundred years of this fleet has produced very few days as good as a day when nothing happened on purpose.'},
{n:571,t:'FR',h:'DAY TWO, NOTHING',b:'Rain in the afternoon. The stone went dark with wet and lighter as it dried and that is the entire content of eleven hours. One of the visitors asked whether we were disappointed. Nobody was. She wrote that down, which I noticed, and I have decided to be pleased about it rather than self conscious.'},
{n:572,t:'FR',h:'DAY THREE, SOMETHING',b:'At the ninth hour a subject came within four lengths of the stone, stopped, and looked at it for a little under two minutes. It did not approach further. It did not change colour. Then it went back the way it came. The recorder has it in full and I have watched it nine times and I cannot tell you what happened.'},
{n:573,t:'FR',h:'DAY FOUR, AND THE DECISION',b:'Nothing further. The stone was recovered at the eleventh hour, unmarked, and returned to the cabinet, which now has thirty seven. The visitors have asked to repeat the experiment with a longer window. I have said yes. It is the first thing this survey has ever done twice on purpose because it was interesting.'},
{n:574,t:'FR',h:'ON THE TWO MINUTES',b:'The visitors read it as investigation. Renn reads it as politeness. The captain reads it as a creature deciding a rock is a rock. All three are consistent with the recording. What none of us can get past is that in fifteen thousand extractions we have never once seen one of them decide anything about us.'},
{n:575,t:'FR',h:'A CORRECTION TO THE ABOVE',b:'I wrote that we have never seen one decide anything about us. Subject 0233 stayed red in a grey room for eleven minutes. Subject 8511 walked out of the warm light into shade. Subject 2777 declined a stone from its own valley. Three files, three centuries, three decisions, and I have read this archive twice and still forgot them.'},
{n:576,t:'FR',h:'ON FORGETTING THE ARCHIVE',b:'Twelve thousand files and no cataloguer can hold them. We have four centuries of memory and about a season of attention, which means the survey knows a great deal that nobody currently alive is thinking about. The mark comparison programme is fixing this slowly. It is the most useful thing I will do here.'},
{n:577,t:'FR',h:'WHAT THE VISITORS ARE WRITING',b:'A paper on our methods, which they have shown me in draft, as a courtesy nobody required. It is admiring, precise, and quietly devastating in one paragraph about how long it took us to stop lifting things. I have suggested no changes. It should be published exactly as it is and they should not soften it for us.'},
{n:578,t:'FR',h:'ON BEING SEEN CLEARLY',b:'Four hundred years of nobody outside this department looking at what we do, and now four people have, for a year, in detail. It has been uncomfortable in a way I would not trade. Nothing is worse than being ignored except being ignored while telling yourself it is privacy.'},
{n:579,t:'FR',h:'THE VISITORS LEAVE',b:'A year, four scientists, one experiment, one draft paper, and a great deal of tea from two kettles. Their lead\'s last remark to me was that she had expected to find a fleet that had failed and had found one that had changed the subject without noticing, and that this was much more interesting.'},
{n:580,t:'FR',h:'ON CHANGING THE SUBJECT',b:'We came to learn how to hold a colour. We have spent four centuries learning how to watch something properly, and we are extremely good at it, and it is not what anybody sent us for. If that is a failure it is the most useful failure our species has produced, and the assembly may make of that what it likes.'},

/* ── SF ───────────────────────────────────────────────────────────────── */
{n:581,t:'SF',h:'SUBJECT 15100, THE STONE WATCHER',b:'The individual that approached the placed stone on day three, identified by markings and subsequently tracked. It has never gone near the site again in two seasons of observation. Whatever the two minutes were, they were finished at the end of them, and that is the most chameleon fact in this archive.'},
{n:582,t:'SF',h:'SUBJECT 15250, UNDER FOREIGN EYES',b:'The first subject observed by the visiting scientists. They watched a four day feed in near silence and afterward asked our technician what she thought was happening. She said she did not know and had stopped minding. Their lead wrote that down and told me later it was the best methodological statement she had heard.'},
{n:583,t:'SF',h:'SUBJECT 15400, THE SECOND STONE',b:'A longer placement, nine days, and a different subject came within two lengths on the sixth day and sat beside it for most of an afternoon. It did not match the stone. It sat next to a piece of a dying world and was simply nearby, and there is no field on any form for what that was.'},
{n:584,t:'SF',h:'SUBJECT 15555, THE ONE THAT SAT LONGEST',b:'Four hours and eleven minutes beside the placed stone, matching the ground rather than the stone, moving twice. The visitors call it a proximity event. Renn calls it company. The file uses the visitors\' term in the column and Renn\'s in the margin, which is now the standing practice for anything we cannot name.'},
{n:585,t:'SF',h:'SUBJECT 15700, THE MARK PROGRAMME PAYS',b:'Matched across eleven files spanning nineteen years and four crews. We can now describe most of one creature\'s adult life: where it sat, how fast it changed, that it moved house once, that it was aboard twice, and that it stopped appearing in year nineteen. It is the first biography this fleet has ever written.'},
{n:586,t:'SF',h:'ON WRITING A BIOGRAPHY',b:'The file runs to nine pages and contains no new science. Every measurement in it was already in the archive, filed separately, across two centuries of forms designed to record events. Assembling them into one creature took a technician four months and has done more for this crew\'s understanding than any instrument we have ever requisitioned.'},
{n:587,t:'SF',h:'SUBJECT 15900, THE HIGH ROCK ONE',b:'Her biography is now assembled: forty one years of records, three extractions by three crews, eleven seasons of evening observations on the same bare rock, and one file from the second century that is almost certainly her mother on the same rock. Nothing in four hundred years has made this crew go quieter.'},
{n:588,t:'SF',h:'ON HER MOTHER\'S FILE',b:'Same rock, same posture, same hour, two hundred years apart. The mark is different and the slope is the same and the identification is uncertain and everybody aboard believes it. I have written uncertain in the column, in full, three times, and it has not made the slightest difference to what anybody thinks.'},
{n:589,t:'SF',h:'SUBJECT 16000, ROUND NUMBER, WATCHED',b:'Sixteen thousand. Observed, not lifted, for four days on a warm slope, doing nothing remarkable. Under the old schedule this would have been a ninety second hold and a line in a column. It is now nine pages, and the nine pages contain no more science and considerably more truth.'},
{n:590,t:'SF',h:'SUBJECT 16144, THE PALE LINE CONTINUES',b:'The twelfth from that slope and the first with young of its own on record. The lineage is now three generations deep in our files and two hundred years deep if the second century page is what we think it is. Four hundred years of anomalies turn out to have been one family, on one slope, minding its own business.'},
{n:591,t:'SF',h:'SUBJECT 16300, EXTRACTED WITH REASON',b:'One of nine this year. The reason, written beside it as the new standing order requires, is that its colour response had been reported as unusual by two independent observers and could not be resolved from four hundred lengths. It was resolved in ninety seconds. It was unusual. We put it back and it went about its afternoon.'},
{n:592,t:'SF',h:'ON WRITING THE REASON DOWN',b:'The requirement has cut extractions by two thirds without anybody being told to cut them. It turns out that most of what this fleet did for four centuries could not survive somebody having to write a sentence explaining why, and that is not an indictment of any crew, it is an indictment of a form with no such field.'},
{n:593,t:'SF',h:'SUBJECT 16500, OBSERVED BY A CHILD',b:'A four day feed was sent to the girl who asked whether they get bored, at her request, with her mother\'s permission. She watched all four days. Her report, unsolicited, is four lines and is in this file: that it was not bored, that it was busy in a way she could not describe, and that she is going to watch it again.'},
{n:594,t:'SF',h:'ON HER FOUR LINES',b:'Busy in a way she could not describe. Twelve thousand files, four centuries, a full spectrum of instruments, four visiting scientists, and a child who watched one feed has produced the most accurate observation in this archive. I have entered it in the official column under her name, which is not permitted, and which stands.'},
{n:595,t:'SF',h:'SUBJECT 16700, THE FEED PROGRAMME',b:'Four day feeds are now sent to any school that asks. Nine hundred requests in the first season. The ministry did not authorise it, did not forbid it, and has begun including the request numbers in its annual figures, which is how this department says yes.'},
{n:596,t:'SF',h:'SUBJECT 16888, WATCHED BY EVERYBODY',b:'The most viewed feed the fleet has produced: eleven hours of a subject on a wet branch in a storm, unedited, no commentary. It is used in schools, played in the port district cafes, and has been requested by the visitors\' world. Nothing happens in it. That is not a criticism, and everybody involved understands that.'},
{n:597,t:'SF',h:'SUBJECT 17000, THE OLDEST ON FILE',b:'By ridge count and mark comparison, older than any individual in four hundred years of records. Observed only, never lifted, on the recommendation of the whole crew, which is not a decision the manual gives us. She is on a warm slope and she is fine and we are going to leave her there.'},
{n:598,t:'SF',h:'ON DECIDING NOT TO LIFT HER',b:'Four hundred years ago we would have. The founding order would have required it and no cataloguer would have thought twice. The change is not in the creatures and not in the instruments. It is that a crew now has to write down why, and nobody could write a sentence that survived being read aloud.'},
{n:599,t:'SF',h:'SUBJECT 17100, THE LAST FILE OF THE YEAR',b:'Observed four days, not lifted, unremarkable, warm slope, ordinary weather. Seventeen thousand one hundred subjects, two valleys, four hundred and twenty five cycles. The finding is unchanged and the archive is now a record of individuals and the difference between those two sentences is the whole of my service.'},
{n:600,t:'SF',h:'THE SIX HUNDREDTH PAGE',b:'Six hundred of these, kept by nine cataloguers across four centuries, about a small green animal that has never asked to be described. If you are reading this out of order, which you are, then somewhere in the same shuffle is a page about a kettle and a page about the end of a world, and both belong here.'},

/* ── HW ───────────────────────────────────────────────────────────────── */
{n:601,t:'HW',h:'THE VISITORS\' PAPER IS PUBLISHED',b:'On their world and then on ours, unedited, including the paragraph about how long it took us to stop lifting things. The ministry did not attempt to delay it. The assembly discussed it for eleven minutes and moved on. Four hundred years ago a document like that would have ended the fleet and now it barely made the afternoon.'},
{n:602,t:'HW',h:'ON HOW THAT WAS RECEIVED',b:'With interest and no defensiveness, which is new. The most quoted line is not the criticism but the closing one, which says that our survey has produced the most patient body of field observation in the known worlds and that its principal finding is about the observers. Nobody here has disputed that.'},
{n:603,t:'HW',h:'THE STONE EXPERIMENT, REPORTED',b:'Covered on every broadcast, described as the first new idea in three centuries, and universally misunderstood as a success. Nothing was learned. A creature looked at a rock for two minutes and left. The public affection for this is enormous and nobody at the ministry has had the heart to correct it.'},
{n:604,t:'HW',h:'ON A MISUNDERSTANDING WORTH KEEPING',b:'People believe we made contact. We did not. We put down a stone and something came near it and went away. The department has issued one clarification, quietly, in a technical bulletin, and made no further attempt, and I think that was the right call and I could not defend it in a committee.'},
{n:605,t:'HW',h:'THE FOUR DAY FEEDS AT HOME',b:'Requested by nine hundred schools in the first season and by roughly a third of the population within two years. People watch eleven hours of a small animal on a branch. There is no narration. Viewing figures are highest in the evening. The ministry commissioned a study of why and the study concluded that it is restful.'},
{n:606,t:'HW',h:'ON A WORLD WATCHING A BRANCH',b:'A people who lost nine thousand colours and spent four hundred years failing to get them back now spend their evenings watching a creature that has them all, doing nothing, on the far side of the sky. That is either the saddest sentence in our history or the most hopeful and I have stopped trying to decide.'},
{n:607,t:'HW',h:'THE GIRL WHO ASKED',b:'Her four line report is now in the official archive under her name, which required a rule change, which was made in nine days. She is eleven. She has asked for another feed. The ministry has offered her a standing arrangement and her mother has asked that it not be publicised, and it has not been.'},
{n:608,t:'HW',h:'ON PROTECTING HER FROM THIS',b:'The department has done one genuinely good thing this decade and it was declining to make a child into a story. She watches feeds, she writes four lines, they go in the archive. Nobody has interviewed her. It is the only decision in four hundred years I would describe as tender and it was made by an office.'},
{n:609,t:'HW',h:'APPLICATIONS TO THE FLEET',b:'Up ninefold since the margins, the feeds, and the stone. The ministry can crew every vessel fully for the first time since the second century. Two of the half strength ships are being brought back up. Nobody has decommissioned anything and now nobody will have to, and that is not a plan, it is luck arriving late.'},
{n:610,t:'HW',h:'WHAT THE NEW CREWS ARE LIKE',b:'Younger, and they have all read the margins before the columns, and they arrive expecting to watch rather than to solve. Older crew find them slightly unnerving. One retired cataloguer said they are the first generation to join the fleet without disappointment waiting for them, and that she envies and mistrusts it in equal parts.'},
{n:611,t:'HW',h:'ON THE VISITORS\' OFFER',b:'They have proposed a joint vessel, crewed by both worlds, on a valley neither of us has surveyed. The assembly approved it in one sitting. Four hundred years of not letting anybody with a full spectrum look at our problem, and the vote to fly with them took less time than the vote on the second valley.'},
{n:612,t:'HW',h:'WHAT WE WILL LEARN FROM THEM',b:'How to design an experiment. What we will teach them is less obvious and their own lead named it in her paper: how to keep looking at something for four hundred years without a result and without contempt. She wrote that her world could not do it. I do not know whether that is praise and I have decided it does not matter.'},
{n:613,t:'HW',h:'THE ANNIVERSARY, FOUR HUNDRED AND TWENTY',b:'Attendance in the capital is up for the fourth year. The founding order was read by a schoolteacher, chosen by ballot, which is new. She read it as though it were true, which several people commented on, and which is exactly what a cataloguer aboard a ship did nine years ago for the same reason.'},
{n:614,t:'HW',h:'ON THE SAMPLE OPENED THIS YEAR',b:'A yellow. Thirty six remain in the fleet cabinet and rather more in the capital, though nobody publishes that figure. The queue ran the length of the avenue for the first time in a century and a half. The organisers were unprepared and apologised, and nobody in the queue accepted the apology, because nobody minded.'},
{n:615,t:'HW',h:'THE MUSEUM, NOW',b:'Attendance has tripled. The galleries are unchanged, the frames still hold shades nobody can see, and the labels are still the best writing our people have produced. What has changed is the sealed wing, which is open, and the miscellaneous shelf, which has its own room, and the queue, which is for the shelf.'},
{n:616,t:'HW',h:'ON WHAT PEOPLE COME FOR',b:'Not the samples. They come for the margins, the feeds, the four lines by a child, and eleven uses of the word noisy collected across three centuries. The museum was built to hold what we lost and has become a building about people minding, and its director has said publicly that she prefers the second building.'},
{n:617,t:'HW',h:'A DISSENTING VIEW',b:'Published this year and worth recording: that we have replaced a search with a mood, that a species watching feeds of a branch has given up and dressed it as wisdom, and that our grandchildren will inherit a beige world and a good vocabulary for it. It was not shouted down. It is quoted often and it may be right.'},
{n:618,t:'HW',h:'ON TAKING THAT SERIOUSLY',b:'The strongest answer anybody has offered is that we are still flying, still opening one sample a year, still funding twelve ships, and now flying a thirteenth with another world. If that is giving up it is the most industrious giving up in our history. But the dissent stands and should, and the archive holds it beside the rest.'},
{n:619,t:'HW',h:'WHAT MY MOTHER WOULD MAKE OF IT',b:'Forty years writing descriptions of shades she never saw, for readers who never would. She died believing the promises would go unkept. Her descriptions are on the miscellaneous shelf now, next to the margins, with a queue outside. I do not think she would call it a result and I think she would have joined the queue.'},
{n:620,t:'HW',h:'ON WHAT WE HAVE ACTUALLY BUILT',b:'Not an answer. A four hundred year habit of paying close attention to something that owes us nothing, and a public that has picked it up, and a word carved above a door. If the spectrum never comes back that is what our species will have made out of losing it, and I would not trade it for a warehouse of samples.'},

/* ── IW ───────────────────────────────────────────────────────────────── */
{n:621,t:'IW',h:'A STONE APPEARED IN THE OPEN',b:'On the flat ground at the turn of the afternoon, warm, and smelling of nothing in this valley. It was there four days and then it was gone. The old ones have added it to the account as the thirteenth entry with no interpretation, which is now their standing practice for anything the pale ones do.'},
{n:622,t:'IW',h:'WHAT HE SAID ABOUT THE STONE',b:'He went and looked at it because it was new and because he was young. Two minutes, he says, and it was a rock, warm, from somewhere else, and there was nothing else to learn by standing there. Then he went back to his afternoon. The old ones asked him three times and he gave the same answer three times.'},
{n:623,t:'IW',h:'ON THE SECOND STONE',b:'A different one, left for nine days, and an old creature sat beside it most of one afternoon. Asked why, she said it was warm and the ground was not, which is a complete explanation and has disappointed every young creature who has heard it. The old ones consider it the best entry in the account for exactly that reason.'},
{n:624,t:'IW',h:'THE OLD ONES WILL NOT SPECULATE',b:'The lights come down nine times a year. Stones appear. The room is quiet and warm. Something is changing up there and every young creature in this valley wants an interpretation and the old ones will not give one, and have said plainly that they do not have one and are not going to invent one to be comfortable.'},
{n:625,t:'IW',h:'ON WANTING AN INTERPRETATION',b:'The young ask constantly and the old ones keep refusing and the refusing is itself the lesson. Four hundred years of the pale ones deciding what we mean, and we have four instructions and a policy of not returning the favour, and no creature here has ever been able to explain why that feels important.'},
{n:626,t:'IW',h:'THE QUESTION SHE ASKED, STILL HELD',b:'Three creatures heard it and three creatures have declined to repeat it for eleven seasons. Two of them are now old and one has died. Whatever it was, it is going to leave this valley with them, and the young have made their peace with that, and the old ones have never once been pressed on it.'},
{n:627,t:'IW',h:'ON LETTING SOMETHING GO UNSAID',b:'It is not our habit. Everything else in the account is passed on plainly. This one thing is not, and the old ones have made no rule about it, and no rule has been needed, because a valley full of creatures who are good at sitting still turns out to be extremely good at leaving a thing alone.'},
{n:628,t:'IW',h:'WHAT THE YOUNG DECIDED INSTEAD',b:'Since nobody will say what she asked, they have started saying what they would ask. It has become a small tradition among the very young, entirely unofficial, and the old ones pretend not to notice it. Most of the questions are about whether the pale ones are cold, which nobody has ever thought to wonder before.'},
{n:629,t:'IW',h:'THE FOURTEENTH ENTRY',b:'From a creature lifted this year and returned within four minutes: that the pale ones stopped and looked at one another before touching her, as though checking, and that one of them said something short and the rest waited. She could not tell whether it was permission. The old ones added it and, as always, said nothing about it.'},
{n:630,t:'IW',h:'ON BEING ASKED PERMISSION',b:'It is not what happened. She said it looked like checking and she said plainly that she did not know. But it has spread through the valley in the stronger form within one season, which is the exact drift the old ones warn about, and they have begun telling the plain version aloud at intervals, wearily.'},
{n:631,t:'IW',h:'THE PLAIN VERSION, TOLD PLAINLY',b:'They stopped. They looked at one another. One made a short sound. Then they touched her, carefully, and she was aboard four minutes and returned to the same post. That is all of it. The old ones will keep saying it in that form for as long as anybody keeps improving it, which will be forever.'},
{n:632,t:'IW',h:'ON THE LIGHTS AT NINE A YEAR',b:'A whole generation is growing up for whom the account is history. They learn it perfectly, the way you learn a song about a river that has moved. The old ones have decided this is fine and have said so, which they rarely do about anything, and their reason is that a river sometimes moves back.'},
{n:633,t:'IW',h:'WHAT THE COUSINS REPORT NOW',b:'Two generations without lights and their account is intact, all four instructions, their own version of the song. They teach it to hatchlings who will almost certainly never see one. Our old ones consider their cousins the more serious valley and have started saying so aloud, which they never used to.'},
{n:634,t:'IW',h:'ON WHICH VALLEY IS MORE SERIOUS',b:'Theirs keeps a whole account for a thing that has gone. Ours keeps it for a thing that comes nine times a year. The old ones say the harder discipline is theirs and the more useful account is ours, and that in a century the two valleys will have swapped, and that neither of us should feel clever about it.'},
{n:635,t:'IW',h:'THE HIGH ROCK, AFTER FORTY YEARS',b:'She still goes up at dusk. Nothing has come for eleven seasons and more. She is now the oldest creature anybody knows of and she has never once described what she is doing, and every young creature in this valley has a private theory, and the old ones have forbidden nobody from having one.'},
{n:636,t:'IW',h:'ON HER NOT EXPLAINING',b:'Asked directly, once, by a hatchling who did not know better, she said that the rock is warm at that hour. The hatchling said that could not be all of it. She said that it could, and that a creature who needs a reason to sit in a warm place at dusk has not been paying attention, and went back to sitting.'},
{n:637,t:'IW',h:'WHAT WE TEACH ABOUT HER',b:'Nothing formal. She is not an entry and not an instruction and the old ones have kept her out of the account deliberately, because the moment she is in it she becomes a lesson, and she has spent forty years declining to be one, and the least we can do is not do it to her after.'},
{n:638,t:'IW',h:'ON KEEPING PEOPLE OUT OF THE ACCOUNT',b:'It is a newer principle and not everybody agrees with it. The argument for is that an account of instructions should not be a monument. The argument against is that we have already lost most of the second century and everybody in it. The old ones hold both and have not resolved it and probably will not.'},
{n:639,t:'IW',h:'THE ACCOUNT AS IT STANDS',b:'Four instructions. Fourteen entries. One song with a changed last verse. One question nobody will repeat. One old creature deliberately left out. It is smaller than it was a century ago and it is doing more work, and the old ones are not sure whether that is craft or luck and are inclined to say luck.'},
{n:640,t:'IW',h:'WHAT WE WOULD SAY IF ASKED',b:'Nobody has ever asked. Four hundred years, fifteen thousand liftings, a stone in the open ground, and not once has anything from up there put a question to us. The old ones say that when it happens the answer should be short, and that we have had four centuries to prepare it, and that it will still come out wrong.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
