/* THE ABDUCTION FILES — bank 7 (pages 401 to 480).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES. */
;(function () {
  var P = [

/* ── FR ───────────────────────────────────────────────────────────────── */
{n:401,t:'FR',h:'YEAR TWO, AND I HAVE OPINIONS',b:'I promised myself five years of no changes. I am eighteen months in and holding, barely. The list is written down and locked and I read it once a season to check whether it has got shorter, which it has, twice, because two of the things on it turned out to be answered already in the margins by somebody dead.'},
{n:402,t:'FR',h:'ON READING THE WHOLE ARCHIVE',b:'Six thousand nine hundred files in fourteen months, which nobody has done since the second century. The columns taught me the timings. The margins taught me the job. And the ninety lost pages taught me the most, because I had to invent them, and what I invented says a great deal about me and nothing about them.'},
{n:403,t:'FR',h:'A LETTER TO MY PREDECESSOR',b:'Sent to the district near the port where retired crew settle. I asked one question: what did he never write down. He replied in four lines, and three of them were about the kettle, and the fourth said that on his last day he had wanted to stay and had been ashamed of it. I have not replied yet.'},
{n:404,t:'FR',h:'THE SILENCE IN THE HOLD',b:'A year of it now. Observation quality is unchanged by any measure the ministry recognises. What has changed is that people come to the hold when they are not rostered. Renn was there twice this season with no duty to perform. I have not asked why and I am not going to.'},
{n:405,t:'FR',h:'WHAT PELL ASKED ME',b:'The same question he asked my predecessor, thirty years ago, which is in the log: what would we do if we found it. I gave the same answer and he told me so. Then he said he asks every new cataloguer, and that in nine years nobody has answered differently, and that he intends to keep asking until somebody does.'},
{n:406,t:'FR',h:'ON THE UNOFFICIAL FORM, CONTINUED',b:'Two hundred and ninety cycles of ordinary afternoons now, his two hundred and my ninety. I have kept his headings and his handwriting conventions so that a reader cannot tell where he stops and I begin. That was not humility. It was that the document is better as one voice and neither of us is the point of it.'},
{n:407,t:'FR',h:'CALIBRATION NOTE, COLD DRIFT',b:'Fixed. Nine minutes of work by engineering, requested by me in writing, granted without comment. The lift no longer pulls left below nine degrees. Four hundred years of a fault with a story attached, and the story is now over, and I find I am sorry about it and I have logged that I am sorry about it.'},
{n:408,t:'FR',h:'THE CAPTAIN IS RETIRING',b:'Vessel goes at the end of this season, after twenty two years. She has asked for no ceremony, which there is no procedure for anyway. She has also asked that the founding order be read at the next anniversary by somebody who has not read it before, which is the only instruction she has ever given about a ceremony.'},
{n:409,t:'FR',h:'ON BEING ASKED TO READ IT',b:'She asked me. I said yes before I had thought about it and I have thought about it since. Four hundred and two years of that document being read aloud by people who did not believe it, to a crew who did not believe it, and I am about to join them, and I understand now that this is what a tradition is for.'},
{n:410,t:'FR',h:'THE ANNIVERSARY, AND THE READING',b:'I read the founding order aloud in the hold to five people and a covered observation pen. It promises a solution within a generation. Nobody laughed and nobody looked away. Afterward Renn said I had read it as though it were true, and I said I had, and she said good, and that was the entire ceremony.'},
{n:411,t:'FR',h:'A NEW CAPTAIN',b:'Younger than me, from the third survey, competent and quiet. Her first act was to read the whole log, which no incoming captain has done in two centuries. Her second was to ask why we hover at four hundred lengths. I explained. She said it was the best answer anybody had given her that week and went to the bridge.'},
{n:412,t:'FR',h:'ON THINGS THAT ONLY LIVE IN PEOPLE',b:'My predecessor wrote that a tradition held only in heads leaves when the heads do. He was right and he was also the reason I know the eleventh hour matters, and he never wrote that down either, he simply told me. Some things do not survive being written and I have stopped trying to fix that.'},
{n:413,t:'FR',h:'THE THIRD SURVEY HAS STOPPED',b:'Not decommissioned, not recalled, simply not filing. Their last observation season was eleven years ago and their vessel is on station and crewed. The ministry lists them as active. Nobody has been sent. I have written to their cataloguer twice and had one reply, which said only that the valley was fine.'},
{n:414,t:'FR',h:'REGARDING THAT REPLY',b:'The valley is fine. Four words from a ship that has filed nothing in eleven years. I have read it as a resignation, as a rebuke, and as the most complete observation report ever submitted, and I have been unable to settle on one, and I have pinned it above the form.'},
{n:415,t:'FR',h:'ON DECIDING NOT TO REPORT IT',b:'I could tell the ministry that the third survey has quietly stopped. It would end them, and a crew would come home, and nothing would be gained by anybody. I have decided not to, which is a serious breach, and I have logged it here in the official column rather than the margin, on purpose, so that it is not deniable.'},
{n:416,t:'FR',h:'WHAT THE NEW CAPTAIN SAID ABOUT THAT',b:'She read the entry, which she was entitled to do, and did not raise it for a season. Then she said that a log which records its own breaches is worth more than one which does not, and that she would be signing the season without comment. I have served under two captains now and both of them were better than the fleet deserved.'},
{n:417,t:'FR',h:'CYCLE FOUR HUNDRED AND SIXTEEN',b:'Weather clear, lift calibrated and no longer drifting, warm lamps installed, hold silent, second valley steady, field for the ordinary in use. Everything my predecessor wanted has arrived within four years of his leaving. I have written to tell him. He replied that it was probably a coincidence and that I should keep the kettle.'},
{n:418,t:'FR',h:'ON THE PART THAT DOES NOT IMPROVE',b:'Better lamps, better lift, better forms, better silence. Six thousand nine hundred files and the finding has not moved a single degree in four hundred years. Everything about how we watch has improved and nothing about what we see has changed, and I am beginning to suspect that is the actual result of this survey.'},
{n:419,t:'FR',h:'A THOUGHT I HAVE NOT DEVELOPED',b:'That the trick is not a skill but a relationship, and that you cannot take a relationship aboard a ship in a specimen jar. I have not written this up. It is unprovable, it is close to sentiment, and it explains four hundred years of clean data and no progress better than anything in the literature.'},
{n:420,t:'FR',h:'ENTRY FOR MY OWN SUCCESSOR',b:'Whoever you are, and you are probably not born yet: the drift is fixed, the lamps are warm, the hold is quiet, and the margins are where the survey actually lives. Read them first. And when Pell or whoever replaces him asks you what we would do if we found it, take longer over the answer than I did.'},

/* ── SF ───────────────────────────────────────────────────────────────── */
{n:421,t:'SF',h:'SUBJECT 9444, THE PALE FILE GROWS',b:'The fourth pale one this year, from the same slope of the same valley. Four in one year after four in four centuries. Either something has changed on that slope or four hundred years of cataloguers were not looking for it, and the second explanation is more likely and considerably more embarrassing.'},
{n:422,t:'SF',h:'SUBJECT 9600, UNDER SILENCE',b:'The first subject logged entirely without a spoken word in the hold. Ninety seconds, correct match, clean return. What the file cannot record is that four people watched an ordinary event closely for the first time, and that two of them mentioned it afterward, unprompted, in almost the same words.'},
{n:423,t:'SF',h:'SUBJECT 9755, ON THE FIXED LIFT',b:'First extraction after the cold drift was corrected. Came aboard slightly differently positioned in the column and matched in the usual time. Four hundred years of subjects arriving fractionally off centre and not one file mentions it, because it was normal, and normal is the hardest thing for a survey to see.'},
{n:424,t:'SF',h:'SUBJECT 9900, THE CAPTAIN WATCHED',b:'Captain Vessel came to the rail on her last day and watched one lift, one hold, one return. She said nothing during and nothing after. The technician logged it as routine and then added, in the margin, that the captain had stayed a further nine minutes at the rail after the pen was empty.'},
{n:425,t:'SF',h:'SUBJECT 10000, THE ROUND NUMBER AGAIN',b:'Ten thousand subjects across two valleys and four centuries. No ceremony, by the standing agreement. Eighty seconds, correct match, clean return. In the margin somebody has written the number by hand, very large, and nobody has claimed it, and the handwriting matches nobody currently aboard.'},
{n:426,t:'SF',h:'SUBJECT 10111, THE THIRD SURVEY\'S VALLEY',b:'Lifted during a courtesy pass over the silent survey\'s valley, with their permission, which they granted in six words. It matched in seventy seconds. Their pen was covered and their lamps were off and their crew watched from the rail, all six of them, which is more attention than the observation deserved.'},
{n:427,t:'SF',h:'SUBJECT 10250, ELDERLY AND UNBOTHERED',b:'Very old, slow, and entirely uninterested in matching anything. Sat in the warm light in whatever colour it had arrived in for the whole eleven minutes. The old ones down there evidently stop bothering, and we have finally caught one at it, and the file records it as reduced responsiveness because there is no better field.'},
{n:428,t:'SF',h:'SUBJECT 10400, ON A SAMPLE AGAIN',b:'The second homeworld sample opened for observation, by the new captain, who asked first and was told the precedent. It matched a green that has not existed at home for two hundred and eleven years and held it for six minutes. Thirty seven samples remain. Nobody has proposed a third and everybody has thought about it.'},
{n:429,t:'SF',h:'SUBJECT 10555, TWO PALE ONES TOGETHER',b:'Both from the same slope, lifted together, matching pattern without depth in the same way at the same rate. Almost certainly related. The standing pale file now has a family in it, which turns an anomaly into a lineage, and turns four centuries of missed observation into a specific missed slope.'},
{n:430,t:'SF',h:'SUBJECT 10700, DURING THE READING',b:'Held during the anniversary while the founding order was read aloud nearby. It matched the wall and slept through the entire promise of a solution within a generation. The technician has logged the coincidence in the margin with no comment attached, which is the funniest thing in this archive and is not marked as a joke.'},
{n:431,t:'SF',h:'SUBJECT 10888, THE LONGEST WAIT',b:'Nine hours of observation from the rail before extraction, because it was in the open and moving and the standing order is to take them settled. It settled at the ninth hour. We lifted it, held it eleven minutes, and returned it. Nine hours of patience for ninety seconds of the ordinary, and that ratio is the whole survey.'},
{n:432,t:'SF',h:'SUBJECT 11000, A FAILURE OF MINE',b:'I authorised a second observation within the same season on the same individual, identified by markings, which is not forbidden and should be. It matched more slowly than the first time. I do not know whether that means anything and I should not have created the question. The standing order now forbids it, on my recommendation.'},
{n:433,t:'SF',h:'SUBJECT 11144, IN FULL DARK AGAIN',b:'Lamps off deliberately, with the captain\'s authority, repeating an accidental observation from the second century. It changed in the dark, three values, verified by recorder, with nothing to see. Two centuries apart, two subjects, same result. It is the only finding in this archive that has ever been independently replicated and nobody knows what it means.'},
{n:434,t:'SF',h:'SUBJECT 11300, ON THE COVERED PEN',b:'Escaped during transfer and was found on the covered observation pen, being the cover, which is canvas, which nothing in its valley resembles. It had been there four hours. The search party had leaned on that pen twice. This is the second time in four hundred years and it will not be the last.'},
{n:435,t:'SF',h:'SUBJECT 11455, SECOND VALLEY ELDER',b:'The oldest subject on file by ridge count, from the second valley, matching in eleven minutes, which is longer than most holds last. We extended the observation rather than return it mid change, which is a decision the manual does not cover. It finished. It was returned. Nobody spoke for the whole eleven minutes.'},
{n:436,t:'SF',h:'SUBJECT 11600, THE HUNDREDTH PALE ONE',b:'Not the hundredth. The eleventh. The heading is a mistake I have chosen to leave in the file, because I made it while tired and correcting it would hide that a cataloguer can be tired, and four hundred years of impeccable headings have made this archive look more certain than it is.'},
{n:437,t:'SF',h:'SUBJECT 11750, RETURNED IN RAIN',b:'Extracted in clear weather and returned in heavy rain, which the standing orders do not address. It went dark on the post within a minute, exactly as it would have without us, and sat there getting wet in the ordinary way. Nothing about the encounter had made any difference to its afternoon.'},
{n:438,t:'SF',h:'SUBJECT 11900, MY THOUSANDTH',b:'The thousandth subject I have personally logged. Ninety seconds, correct match, clean return, unremarkable. I had intended to write something about it and I find there is nothing to write, which my predecessor warned me about in the handover document, in a line I did not understand at the time and now do.'},
{n:439,t:'SF',h:'SUBJECT 12000, ON THE FIXED EVERYTHING',b:'Warm lamps, silent hold, corrected lift, ordinary field, second valley, better forms. This subject received the best observation this fleet has ever been able to give. It matched in eighty seconds, which is exactly the median of four hundred years of worse observations, and I have put that sentence in the official column.'},
{n:440,t:'SF',h:'SUBJECT 12111, END OF THE SEASON',b:'Clean lift, clean hold, clean return. The pen is covered and the lamps are off and the log is closed for the interval. Twelve thousand files across two valleys and four centuries, and if you read them in any order you will find the same afternoon happening over and over, beautifully, without us.'},

/* ── HW ───────────────────────────────────────────────────────────────── */
{n:441,t:'HW',h:'ON THE THIRD SURVEY\'S SILENCE',b:'Eleven years without a filing and the ministry lists them as active. Somebody in a building at home has been ticking a box for eleven years. This is either negligence or mercy and the people who know are not saying, and the fleet has quietly decided it is mercy, and the fleet is probably right.'},
{n:442,t:'HW',h:'A CHANGE IN THE FORM, NOTICED',b:'The field for the ordinary has produced nine thousand entries in four years across the fleet, and an analyst at the ministry has written the first paper in a century that anybody outside the department has read. Its finding is that the valleys are extremely pleasant. It has been cited eleven times, all of them approvingly, none of them scientifically.'},
{n:443,t:'HW',h:'ON THE PAPER ABOUT PLEASANTNESS',b:'It describes weather, light, the behaviour of small animals in the absence of observation, and the length of an afternoon. It contains no result. It has been read aloud on public broadcast twice and put into two school curricula, and the ministry does not know what to do with a document it cannot classify.'},
{n:444,t:'HW',h:'WHAT THE CHILDREN NOW ASK',b:'Since the pleasantness paper, the letters to the ships have changed. They used to ask whether we had solved it. They now ask what the valley smells like, and whether the creatures have names, and whether it is warm there. Crews report answering these letters more readily and at greater length, which the ministry has not commented on.'},
{n:445,t:'HW',h:'THE DISTRICT NEAR THE PORT',b:'Where retired crew settle, one day\'s travel from the field. Property there is cheap and the cafes are quiet and everybody has flown. A journalist lived there for a season and wrote that it was the least ambitious place she had ever been and the only one where nobody seemed to be waiting for anything.'},
{n:446,t:'HW',h:'ON CAPTAIN VESSEL AT HOME',b:'Twenty two years in command and she moved to the port district within the month. Interviewed once, briefly, she said the hardest part of coming back was that nothing at home holds still long enough to be worth looking at properly. The interviewer asked whether that was a criticism. She said it was a description.'},
{n:447,t:'HW',h:'THE ARCHIVE OF MARGINS',b:'One ship\'s margins, copied by one archivist, catalogued under miscellaneous, and now the most requested holding in the building. Eleven other vessels have since been asked for theirs and all eleven agreed immediately. The columns of four centuries sit unread beside them and nobody at the ministry finds this uncomfortable, which is itself remarkable.'},
{n:448,t:'HW',h:'ON WHAT THE MARGINS DO',b:'They are not evidence and they are not literature. They are four hundred years of ordinary people recording that they were affected by something they were sent to measure. There is no discipline for that. The archivists have invented a shelf for it, and the shelf has a name, and the name is the miscellaneous shelf.'},
{n:449,t:'HW',h:'A PROPOSAL TO PUBLISH THEM',b:'Advanced by the archivist who took them, refused twice, and granted on the third attempt with conditions. The conditions are that no crew member be named and that the columns be published alongside. Both conditions were met. The columns have sold four copies. The margins are in a ninth printing.'},
{n:450,t:'HW',h:'ON READING THEM AT HOME',b:'A people who have never seen the valley now know that the lift drifts left in cold, that there was a contested kettle, and that at the eleventh hour everything down there turns the same gold for about nine minutes. None of that is data. All of it has done more for the fleet\'s standing than four centuries of columns.'},
{n:451,t:'HW',h:'FUNDING, AFTER THE MARGINS',b:'The first increase in ninety years, small, unanimous, and justified in the assembly on grounds that nobody wrote down properly. The speech that carried it quoted a margin note about a kettle. Four hundred years of scientific argument had never moved a vote and a joke about hot water moved eleven.'},
{n:452,t:'HW',h:'WHAT THE MINISTRY LEARNED',b:'Nothing about colour. A great deal about attention. There is now a small section of that department whose entire function is to look after the margins, staffed by four people, and it is the only part of the building with a waiting list for transfers into it.'},
{n:453,t:'HW',h:'ON THE SEALED WING, REVISITED',b:'The nine painters\' canvases have been in the dark for three centuries under instruction that they not be shown until the spectrum returns. A motion to open the wing anyway was defeated this year by a wide margin. The strongest argument against was one sentence: they painted them for a room we do not have yet.'},
{n:454,t:'HW',h:'THE COLOUR NAMED AFTER A CREW MEMBER',b:'A shade in the archive, catalogued in the second century, bears a survey cataloguer\'s name. Nobody knows why. He is not otherwise recorded and the sample is sealed and the entry is one line. It is the only thing any crew member has ever had named after them and it is almost certainly a filing error.'},
{n:455,t:'HW',h:'ON HOPE BECOMING A HABIT',b:'The fleet is funded, the archive is kept, the anniversary is marked, the samples are rationed. None of it is done in expectation any more. It is done the way a household keeps a room ready for somebody who is not coming, and everybody knows, and the room stays ready, and that is not stupidity.'},
{n:456,t:'HW',h:'THE SECOND OPENED SAMPLE',b:'A green, opened aboard a survey vessel rather than in the capital, which required an authority nobody had used in ninety years. The assembly debated it afterward and declined to censure. The recorded reason is that the fleet has custody of forty samples and has opened two in four hundred years, and has therefore earned the benefit of the doubt.'},
{n:457,t:'HW',h:'WHAT WE ARE ACTUALLY DOING',b:'A historian wrote this year that we are not searching, we are keeping vigil, and that the difference is that a search can fail. The paper was unpopular in the ministry and is now quoted in the ministry constantly, usually by people who objected to it, which is how an idea gets accepted here.'},
{n:458,t:'HW',h:'ON THE WORD VIGIL',b:'It has entered ordinary speech within a year. People say the vigil now, meaning the fleet, and mean it warmly. No department authorised the change and no campaign produced it. A species that could not name what it was doing for four hundred years was handed a word by a historian and adopted it in a season.'},
{n:459,t:'HW',h:'THE SCHOOLS AFTER THE MARGINS',b:'The creature lesson has been extended and the drought lesson shortened, on the recommendation of teachers rather than the ministry. Children now spend more time on a small green animal on a fence post than on the loss of nine thousand shades, and the teachers who proposed it did so on the grounds that the children were happier.'},
{n:460,t:'HW',h:'WHAT MY GRANDMOTHER WOULD SAY',b:'She described the orchards as noisy and meant it as praise. She has been dead for thirty years and I have finally understood her, not from a sample or a paper, but from a margin note about nine minutes of gold light at the eleventh hour. It is the only inheritance that has ever reached me.'},

/* ── IW ───────────────────────────────────────────────────────────────── */
{n:461,t:'IW',h:'ON THE LIGHTS BEING FEWER',b:'One valley over the hovering has stopped entirely, and has been stopped for years, and the cousins there report that they miss it. The old ones here received this without surprise. They said a thing that has been overhead your whole life is part of the sky, and you do not get to choose which parts you miss.'},
{n:462,t:'IW',h:'WHAT THE COUSINS DO NOW',b:'Nothing differently. They sit, they eat, they change colour, they teach their young four words. The lights left and the afternoons stayed exactly the same, which everybody here found reassuring and which one old one found unbearable, and she is the only one who has said so aloud.'},
{n:463,t:'IW',h:'THE ONE WHO WATCHES FOR THEM',b:'She has sat on the same high rock every clear evening for eleven seasons since the lights went from her valley. She is not waiting, she says. She is simply in the habit of the sky at that hour. The old ones repeat this without comment and every young creature who hears it goes quiet.'},
{n:464,t:'IW',h:'ON WARMTH IN THE ROOM',b:'Every account for a season now mentions it. The room is warm and the light is kind and the pale ones are quiet. Something up there changed and we have no way to ask why. The old ones have decided to record it as a gift rather than a development, which is generous and may be wrong.'},
{n:465,t:'IW',h:'A YOUNG ONE ASKED TO BE TAKEN',b:'Sat in the open at the turn of the afternoon, brightly coloured, deliberately, for two days. Nothing came. The old ones did not stop her and did not comfort her afterward. They said that a creature who wants to be looked at will meet this eventually and it is better met at four seasons than at forty.'},
{n:466,t:'IW',h:'THE INSTRUCTION THAT WAS DROPPED',b:'Do not sit on stone when the lights are out. It was in the account for three hundred years and has been quietly removed, because the returned kept reporting that they had been taken off wood. The old ones cut it without announcement. Nobody noticed for a season and nobody has objected since.'},
{n:467,t:'IW',h:'ON CUTTING THE ACCOUNT',b:'They removed their own commentary first, then a whole instruction, and they intend to keep going. An old one explained it: everything we add makes the account harder to carry, and a young creature under a light has room for four words. Four hundred years of a species editing itself down to what fits under pressure.'},
{n:468,t:'IW',h:'WHAT WE KEPT INSTEAD',b:'The stories. Every instruction is under review and none of the tales are, because a tale survives being retold badly and an instruction does not. The old ones know this without having a word for it, and they are better at it than anybody who has a word for it.'},
{n:469,t:'IW',h:'THE ELEVENTH ENTRY',b:'Added this season, from a returning creature: that one of the pale ones held her briefly on its own arm, and did not move for a long time, and that she matched the arm because it was there. The old ones added it in full. It is the only entry in which one of them touches one of us gently.'},
{n:470,t:'IW',h:'ON THAT ENTRY BEING REPEATED',b:'It is told more than any other now, which the old ones have noticed and are uneasy about. A favourite entry becomes a favourite version, and a favourite version drifts. They have begun telling the plainest possible form of it and refusing to embellish, and the young find the plain version disappointing, which is the point.'},
{n:471,t:'IW',h:'WHAT THE PALE ONES DO NOT KNOW',b:'That we teach about them. That there is an account, and instructions, and a song with a changed last verse. Four hundred years of them writing about us and we have never once let them see that we write back, and the old ones say this is not deception, it is simply that nobody asked.'},
{n:472,t:'IW',h:'ADVICE FOR THE VERY BRIGHT',b:'Some of us run bright and cannot help it, the way some run pale. The old ones do not tell them to hide harder. They tell them to sit near somebody dull, which works, and which requires the dull one to agree, and which is therefore the only instruction in the account that involves two creatures.'},
{n:473,t:'IW',h:'ON THE DULL ONES AGREEING',b:'They always do. In four hundred years the account records no instance of a creature refusing to sit beside a bright one under a light. The old ones mention this rarely and only to the young, and never as a moral, and always as a plain fact about what our kind does when asked.'},
{n:474,t:'IW',h:'THE SONG, AS SUNG NOW',b:'Four verses about a light that cannot find anybody. In the cousins\' version it goes away alone. In ours an old creature waits on a bare rock and is found. The two versions are sung a ridge apart on the same evenings and neither valley has ever proposed that the other change.'},
{n:475,t:'IW',h:'WHY WE LET OURSELVES BE FOUND',b:'The old ones say it is not kindness and not courage. They say that after enough seasons the light is simply part of the evening, and an old creature who sits still is not making a sacrifice, she is having an ordinary evening in the ordinary way, and that anybody who calls it more than that has misunderstood us entirely.'},
{n:476,t:'IW',h:'ON BEING MISUNDERSTOOD',b:'Four hundred years of being lifted, written about, and put back, and the old ones are certain the pale ones have got us wrong in some specific way they cannot name. They are not offended. They say that being misunderstood by somebody who keeps coming back is a considerably better arrangement than most creatures get.'},
{n:477,t:'IW',h:'WHAT THE OLDEST ONE SAID',b:'Asked what she would tell them if she could, she thought for a long time and said: come down. Not as advice, and not as an invitation. She said it the way you would say it to somebody hovering a long way off who you had been aware of your whole life, and then she went back to eating.'},
{n:478,t:'IW',h:'ON THE HOUR WE ARE ALL THE SAME',b:'When the flat light crosses the ridge the whole valley turns one colour, us included, without effort. The old ones say it is the only honest hour of the day. They also say it is the only hour we do not need any of this, and that if the pale ones came at that hour they would learn nothing and might be happier.'},
{n:479,t:'IW',h:'THE ACCOUNT, AT ITS SHORTEST',b:'They have cut it again. Four instructions, eleven entries, one song. Everything else has gone, including two stories the old ones liked. When the young protested, one said that a thing worth keeping will come back on its own, told by somebody who could not stand to lose it, and that this had already happened twice.'},
{n:480,t:'IW',h:'WHAT COMES BACK ON ITS OWN',b:'Both times it was a story about somebody who did not do what the account says. The one who stayed red. The one who climbed out of the light early. The old ones cut them for being bad advice and both were back within a generation, retold by creatures who needed them, and the old ones have stopped cutting those.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
