/* THE ABDUCTION FILES — bank 4 (pages 161 to 240).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES. */
;(function () {
  var P = [

/* ── FR: the cataloguer, further in ───────────────────────────────────── */
{n:161,t:'FR',h:'THE SECOND KETTLE ARRIVED',b:'Requisitions has sent a second kettle without explanation, four hundred cycles after the first request. Renn wept, briefly and angrily. Pell has proposed we keep one sealed as a monument. The captain has ruled that we will use both, because a monument to a kettle is where a crew stops being a crew. She is right and everyone is disappointed.'},
{n:162,t:'FR',h:'INSTRUCTIONS FOR THE COLD AIR DRIFT',b:'Below nine degrees the lift pulls left by roughly the width of a subject. Nobody has fixed it in two hundred cycles because the correction is easy once you know, and the knowing is passed down rather than written. I am writing it down. Traditions that only live in people are traditions that leave with them.'},
{n:163,t:'FR',h:'A VISITOR FROM THE THIRD SURVEY',b:'Their cataloguer came aboard for one cycle and read our logs without asking permission, which is the friendliest thing anyone has done here in years. She said ours were the only ones with a person in them. Then she said that was a criticism, and then she took a copy anyway.'},
{n:164,t:'FR',h:'ON THE HABIT OF NAMING SUBJECTS',b:'It is forbidden and everybody does it. The one that ate first. The loud one. The slow one. Officially each is a number and a colour value. Unofficially there is not a crew member aboard who could not tell you which was which, four hundred cycles later, without looking at the file.'},
{n:165,t:'FR',h:'MY HANDS HAVE STOPPED SHAKING',b:'For the first eighty cycles the lift made them shake. Then it did not. I noted the change at the time as an improvement in professional composure. I now think it was simply the point at which the extraordinary became the job, and I would like the shaking back, and I do not know how to ask for that in a requisition.'},
{n:166,t:'FR',h:'THE VALLEY WE STOPPED VISITING',b:'A good valley, well populated, ideal weather. We left it after cycle three hundred and twelve and the log does not say why. I have asked the three crew old enough to remember. Two changed the subject. The third said only that we had been going there too long and the subjects had begun to sit still when we arrived.'},
{n:167,t:'FR',h:'WHAT THE FORM CALLS AN INCIDENT',b:'An incident is any event requiring a written narrative. In four hundred cycles we have filed nine. Six are equipment. Two are the bicycle. The ninth is a single line filed by my predecessor which reads, in full, that on the eleventh hour a subject was observed to be waiting. No further narrative was provided.'},
{n:168,t:'FR',h:'REGARDING SLEEP ABOARD',b:'None of us sleeps properly and it is not the hours. It is that the hold is the quietest room any of us has stood in, and quiet on a ship four hundred years old is not restful, it is expectant. Renn plays the emitter hum through the mess at night. Nobody has asked her to stop.'},
{n:169,t:'FR',h:'THE DAY NOTHING HAPPENED',b:'Clear weather, full crew, lift calibrated, valley busy. We observed for eleven hours and lifted nothing, because every subject we selected was already exactly where it wanted to be and there is no procedure for that. Pell called it a wasted cycle. I have logged it as the most honest day of the survey.'},
{n:170,t:'FR',h:'ON WRITING THE WORD ALMOST',b:'I have counted. The word almost appears in this log one thousand four hundred and six times. Almost matched. Almost held. Almost understood. It is the most used word in four hundred years of records and no founding document contains it once, which tells you everything about the distance between a plan and a survey.'},
{n:171,t:'FR',h:'CAPTAIN VESSEL HAS PUT IN FOR TRANSFER',b:'She withdrew it the same day. I found the withdrawal in the outgoing queue and I have not mentioned it and I will not. A captain is allowed one afternoon of wanting to be elsewhere. Four hundred years of this ship is built on afternoons like that, quietly withdrawn.'},
{n:172,t:'FR',h:'THE PROBLEM WITH GOOD DATA',b:'We have six thousand clean observations. Every one is correct, repeatable, and useless, because they all say the same thing: the creature becomes the surface. What we lack is not data. What we lack is a question worth asking of it, and no instrument on this ship can be requisitioned to produce one.'},
{n:173,t:'FR',h:'PROCEDURE FOR A DEAD SUBJECT',b:'It has happened twice, both from age, both aboard. The procedure is four lines long and ends with return to point of origin. We have followed it exactly on both occasions and on both occasions the whole crew came to the rail, which is not in the four lines and is the only part anyone remembers.'},
{n:174,t:'FR',h:'ENGINEERING HAS FIXED THE HUM',b:'Without being asked, during a routine sweep, in nine minutes. Emitter two is now silent and correct. Renn has not spoken since the shift change. I have logged the repair as satisfactory because it is, and I have also logged that the mess is quieter at night, because that is a fact about this ship.'},
{n:175,t:'FR',h:'ON BEING ASKED WHAT I DO',b:'A relief pilot asked. I said I record what small animals do when they are frightened, except they are not frightened, so I record what they do. He waited for the rest. There is no rest. He said it sounded peaceful. I have thought about that word for eleven cycles and I still cannot get it to fit.'},
{n:176,t:'FR',h:'THE MARGIN NOTES',b:'Every cataloguer before me wrote in the margins, and every one of them wrote the same kind of thing: a doubt, a joke, a name they were not allowed to use. The official column is four hundred years of colour values. The margin is four hundred years of people. Only one of those columns has ever been read twice.'},
{n:177,t:'FR',h:'WEATHER HOLDING, MORALE FIVE',b:'I wrote five again. Then I crossed it out and wrote six, and looked at the six for some time, and could not defend it, and put five back. The form does not ask why. Four hundred years of fives and not one line anywhere asking a single person on this ship why.'},
{n:178,t:'FR',h:'A CORRECTION CONCERNING PELL',b:'I have described Ensign Pell in this log as unserious eleven times. He has been aboard nine years, which is longer than any officer I have served with, and he asked the only question in four hundred years that nobody could answer. The unserious one is the one who kept writing unserious. I withdraw it.'},
{n:179,t:'FR',h:'IF THIS LOG IS EVER READ IN FULL',b:'You will find a survey that did not succeed and did not stop. Please do not read that as tragedy. We ate together, we argued about a kettle, we hovered over something beautiful for four hundred years and put it back gently every time. There are worse uses of a fleet and I can name several.'},
{n:180,t:'FR',h:'ORDERS RECEIVED THIS CYCLE',b:'We are to continue. That is the entire content. Nine words from a ministry that has been sending nine words for two centuries. The captain read it aloud in the mess and Renn said it sounded like a blessing if you did not think about it, and we agreed not to think about it, and we continued.'},

/* ── SF: the creatures ────────────────────────────────────────────────── */
{n:181,t:'SF',h:'SUBJECT 2101, ON WET BARK',b:'Lifted after rain from bark so dark it read as black. Aboard it held that darkness for six minutes, then lightened by degrees as it dried, tracking a surface that was no longer under it. The finding is unavoidable and nobody wanted to write it: it was still matching the branch from memory.'},
{n:182,t:'SF',h:'SUBJECT 2244, WHICH CLIMBED THE LAMP',b:'Ignored the rail, ignored the wall, went directly up the observation lamp and sat in the hottest part of it. Matched nothing at all for the duration, being simply and unapologetically warm. Renn has filed it as a thermal preference. I have filed it as the first subject to find something aboard this ship worth having.'},
{n:183,t:'SF',h:'SUBJECT 2390, TWO MINUTES',b:'The shortest hold on record. Lifted, examined, and returned inside two minutes because the technician looked at it and said, aloud, that it did not want to be here. That is not a reason permitted by the manual. It is the reason in the file, signed, and the captain countersigned it without comment.'},
{n:184,t:'SF',h:'SUBJECT 2501, WITH A FULL BELLY',b:'Recently fed and entirely uninterested in the proceedings. Took ninety seconds to match, then closed one eye and kept the other on the technician for the whole eleven minutes. We have six thousand files and this is the only one where the observation ran in both directions and both parties knew it.'},
{n:185,t:'SF',h:'SUBJECT 2666, IN THE DARK',b:'Lamps failed during the hold. In total darkness the subject continued to change, verified afterward by the recorder, moving through three distinct values with nothing to see and nothing to see it. Renn asked what it was matching. Nobody has answered. The file records only that it did not stop.'},
{n:186,t:'SF',h:'SUBJECT 2777, DECLINED THE STONE',b:'Offered a warm stone from its own valley, the most generous thing this ship has ever done, and walked past it to sit on the cold rail. Matched the rail. The stone went back in the crate. Pell says it did not recognise it. I say it recognised it perfectly and had opinions.'},
{n:187,t:'SF',h:'SUBJECT 2810, THE FASTEST',b:'Full match in eleven seconds, a record that has stood for ninety cycles and will probably stand forever. Young, small, and evidently in a hurry about something. Returned to a fence post where it immediately became the fence post again, in eleven seconds, as though the whole encounter had been an interruption.'},
{n:188,t:'SF',h:'SUBJECT 2944, ON THE CATALOGUER',b:'Placed briefly on my sleeve during a transfer. Matched the sleeve. I stood entirely still for four minutes with a small green animal being the colour of my uniform and I did not log it at the time, and I am logging it now, eleven cycles later, because it is the only observation I have ever been part of.'},
{n:189,t:'SF',h:'SUBJECT 3000, GROUP OBSERVATION',b:'Five lifted together for a comparative study. In the hold they arranged themselves at even spacing without contact and matched five slightly different greys, none of them the wall exactly. The study concluded nothing. The mess has argued about the spacing for two hundred cycles and the spacing is in every retelling.'},
{n:190,t:'SF',h:'SUBJECT 3130, ELDERLY AND SLOW',b:'Nine minutes to complete a change a young one does in ninety seconds, and it completed it, and then held it longer than any subject on file. There is a note in the margin of this file in my predecessor\'s hand which reads simply: she is not slower, she is more certain. I have left it there.'},
{n:191,t:'SF',h:'SUBJECT 3288, DAMAGED LIFT',b:'The lift stuttered during extraction and the subject was held mid column for four seconds. It matched the light. Not the ship, not the valley, the light of the column itself, which has no surface and no colour anybody can name. The recorder captured it. Nobody has been able to look at the recording twice.'},
{n:192,t:'SF',h:'SUBJECT 3400, RETURNED WRONG',b:'Put back on a post forty paces from the one it was taken from, the only recorded error of its kind. It walked the forty paces. It took most of an afternoon and it did not hurry and it did not deviate. Six of us watched the whole thing from four hundred lengths up, saying nothing.'},
{n:193,t:'SF',h:'SUBJECT 3555, DURING A STORM',b:'Lifted between two lightning strikes because the schedule said so. Aboard, it matched the hold as usual, then flickered twice, matching the flash through the observation glass with a delay of less than a breath. Nothing in four hundred years has moved that fast. Nothing in four hundred years has been that impossible to write up.'},
{n:194,t:'SF',h:'SUBJECT 3690, ASLEEP AND DREAMING',b:'Rapid eye movement observed throughout, colour cycling gently in a range of greens not present anywhere aboard this ship. It was matching something that was not there. The technician logged it as involuntary. I have logged it as the closest thing to a homeworld sample any of us has seen in ninety years.'},
{n:195,t:'SF',h:'SUBJECT 3800, THE ONE THAT HID',b:'Escaped the observation pen and was not found for two hours. Discovered eventually on the file cabinet, being the file cabinet. The search party had opened and closed that cabinet four times. It is in the file as a containment failure. It is in the mess as the best thing that has ever happened.'},
{n:196,t:'SF',h:'SUBJECT 3911, DELIBERATELY MISMATCHED',b:'Set on a green cloth, it went red. Set on red, it went green. Eleven repetitions, consistent, deliberate, and utterly outside anything we understand. The study was halted by the captain, who said we had begun playing a game with something that was better at it. The file ends there and I agree with her.'},
{n:197,t:'SF',h:'SUBJECT 4000, UNREMARKABLE AGAIN',b:'Lifted, held, matched in seventy seconds, returned. I record the ordinary ones on purpose and at intervals, because a file of only marvels is a lie about a valley that is mostly full of small green animals doing very little, extremely well, without an audience, whether or not we ever arrive.'},
{n:198,t:'SF',h:'SUBJECT 4144, THE SECOND MIRROR TEST',b:'Authorised against my written objection. Placed on a mirror, it did not match itself this time. It went the colour of the room behind the mirror, which it could not see, and which was grey, and which was correct. The technician resigned the following cycle. The mirror has been put beyond use.'},
{n:199,t:'SF',h:'SUBJECT 4290, IN COMPANY',b:'Observed alongside a second subject with a healed tail, previously catalogued. They matched each other rather than the wall, converging over nine minutes on a shade neither had arrived with. Nothing in our science accounts for it. Everything in the mess does, immediately, and nobody will write down what they said.'},
{n:200,t:'SF',h:'SUBJECT 4400, THE LAST OF THIS SEASON',b:'A clean lift, a clean hold, a clean return, and the end of the observation season. The pen has been cleaned and the lamps covered. Six thousand files and counting, all of them true, none of them enough. Somewhere below us it is on a fence post being exactly the right colour and we will be back.'},

/* ── HW: the homeworld ────────────────────────────────────────────────── */
{n:201,t:'HW',h:'THE MUSEUM OF THE FULL SPECTRUM',b:'Built in the second century of the drought to hold what remained, and now the largest empty building on the continent. The galleries are lit and staffed and open. The frames are there. The labels are there, describing each shade at length, beautifully written. Attendance is steady. It is the most visited museum we have.'},
{n:202,t:'HW',h:'A DEBATE IN THE ASSEMBLY',b:'The motion was to teach the drought as history rather than as an ongoing event, on the grounds that four hundred years is no longer news. It failed by a wide margin. The speech that killed it was two sentences long: we are not finished losing it. Please do not put it in the past tense while it is still happening.'},
{n:203,t:'HW',h:'WHAT THE SURVEYS SEND BACK',b:'Colour values, thousands of them, catalogued and stored and useless, because a value is a description and we have plenty of descriptions. Twice a fleet has been tempted to bring back a living subject. Twice the proposal has been refused, by wide margins, on grounds nobody at home is entirely able to articulate.'},
{n:204,t:'HW',h:'ON THE CHILDREN WHO DO NOT BELIEVE',b:'There is a generation now that treats the full spectrum as a story their elders enjoy telling. They are not cynical. They have simply never had evidence, and a child who has only ever heard about red is right to be careful with it. We are one generation from the drought becoming a legend about itself.'},
{n:205,t:'HW',h:'THE COST OF THE FLEET',b:'Published every decade and never disputed. It is the largest single line in the budget and it has never been the largest political argument, which is remarkable, and which every historian explains differently. My own view is that a people will fund almost anything rather than hold a vote on whether to give up.'},
{n:206,t:'HW',h:'WEDDINGS, AS THEY ARE NOW',b:'The old form required the couple to name a colour they would keep between them. The form still requires it. Roughly half now name one from the archive, unseen, chosen from the description alone. The registrars report that these marriages are no less durable, which is either very moving or very bleak and is probably both.'},
{n:207,t:'HW',h:'THE PAINTERS WHO CONTINUED',b:'Nine of them, working through the worst decades, producing canvases nobody could properly see. Their work is held in the museum in a sealed wing under instruction that it not be displayed until the spectrum returns. Eleven of the twelve galleries are open to visitors. That wing is the one people ask about.'},
{n:208,t:'HW',h:'A PROPOSAL TO STOP LOOKING',b:'Advanced quietly in the third century by a respected physician, on the grounds that the ache of noticing was doing more measurable harm than the loss itself. It was not voted down. It was simply never scheduled, cycle after cycle, until the physician died, and it has never been raised again by anyone.'},
{n:209,t:'HW',h:'WHY THE FOUNDING ORDER SURVIVED',b:'Because it is short, and confident, and wrong in a way that flatters everybody who reads it. A generation, it says. Every reader for four hundred years has silently assumed it meant somebody else\'s generation. That is the whole trick of it and it has held a fleet together for longer than any true document could.'},
{n:210,t:'HW',h:'ON THE WORD BEIGE',b:'It was a neutral term once, one shade among nine thousand, with a sample and a name and nothing sad about it. It is now the word people use for the thing that happened. The archive has a note appended by an archivist two centuries ago asking that the original meaning be preserved. It has not been.'},
{n:211,t:'HW',h:'THE ANNUAL SAMPLE OPENING',b:'One sealed shade, opened in the capital, viewed for a count of sixty, then resealed. The queue used to run the length of the avenue. It now takes an hour to clear. The organisers have stopped publishing attendance and started publishing the name of the shade, which is a better decision than it sounds.'},
{n:212,t:'HW',h:'WHAT WE TELL OTHER WORLDS',b:'Very little. The standard brief describes an environmental variance under active study. It does not say drought. It does not say four hundred years. Two of our neighbours have worked it out anyway and have been notably kind about it, which our diplomats find harder to manage than hostility.'},
{n:213,t:'HW',h:'THE ORCHARD RECONSTRUCTION',b:'Planted in the second century from surviving stock, tended for ninety years, and abandoned. The trees grew. The fruit came. It was all the same careful, honest, exhausted shade, and standing in it was worse than standing in a field, because a field has never promised you anything. The site is a park now.'},
{n:214,t:'HW',h:'ON HOPE AS A PUBLIC UTILITY',b:'The fleet is not maintained because anyone expects it to succeed. It is maintained because a world needs somewhere to put the belief that this is temporary, and four hundred years ago we decided to put it in ships. It is expensive and it is dishonest and I have not heard a better proposal.'},
{n:215,t:'HW',h:'MY MOTHER AT THE ARCHIVE',b:'She worked forty years cataloguing shades she had never seen, writing descriptions for people who would never see them either. I asked once whether it was hard. She said the hard part was that the descriptions kept getting better. We were becoming a people who could write about colour beautifully, which is not the same as having it.'},
{n:216,t:'HW',h:'THE STATISTIC NOBODY QUOTES',b:'Rate of loss has been effectively flat for one hundred and ten years. Nothing has gone in a century. The drought is not advancing. It is simply not receding, and a stable catastrophe is the hardest kind to keep a fleet funded against, because there is no crisis to point at, only an absence that stays exactly where it is.'},
{n:217,t:'HW',h:'ON RETURNING FROM A SURVEY',b:'You come back with your eyes recalibrated by a valley and it takes about nine days to lose. Veterans describe those nine days the same way and none of them describe them as happy. A returning crew is given leave and privacy and nobody schedules them for anything, and that policy is two hundred years old.'},
{n:218,t:'HW',h:'THE LETTER THE MINISTRY DID NOT SEND',b:'Drafted in the third century, found in the archive, never dispatched. It thanks the fleet, releases it from the founding order, and instructs all vessels to come home. It is signed. It is stamped. Somebody carried it as far as the outgoing queue and then carried it back, and we have been flying ever since.'},
{n:219,t:'HW',h:'WHAT A CHILD ASKED ME',b:'Whether the creatures know. Whether, down there, on the fence posts, they have any idea that a world crossed the sky to watch them. I said no. She asked whether we should tell them. I have been a cataloguer for thirty years and I could not think of a single procedure that covers it.'},
{n:220,t:'HW',h:'IF IT CAME BACK TOMORROW',b:'The contingency exists. Nine pages, mostly logistics, written in the first century and never revised. Its final line instructs that the fleet be recalled and the ships preserved intact. Not scrapped. Preserved. Somebody four hundred years ago understood that we would want to be able to look at them.'},

/* ── IW: the whispers ─────────────────────────────────────────────────── */
{n:221,t:'IW',h:'ON THE HOUR THE LIGHTS PREFER',b:'They come at the turn of the afternoon, when the shadows are moving fastest and a careless creature is caught halfway between two colours. The old ones say this is not cunning on the part of the lights. They say it is the only hour anything is easy to see, including us, including them.'},
{n:222,t:'IW',h:'THE ADVICE THAT IS ONLY FOR ELDERS',b:'When you are old and your colour comes slowly, do not sit where the young sit. Take the deep shade, where slow is enough. There is no shame in it and every young creature will pretend not to have noticed, and that pretending is the most careful thing our kind does.'},
{n:223,t:'IW',h:'WHY THE STORY IS TOLD AT DUSK',b:'Because the lights do not come at dusk, and because a story about being taken is easier when the sky is closing. The old ones are firm on the timing and vague on the reason. The young work it out eventually, usually while telling it to somebody smaller.'},
{n:224,t:'IW',h:'WHAT THEY DO WITH THE COLOURS',b:'Nothing, say the old ones. They look at them and write something down and put you back on your post. Four hundred years of looking and writing. If it were theft we would be short of something by now, and we are short of nothing, and that is the strangest part of the whole arrangement.'},
{n:225,t:'IW',h:'THE ONE WHO COUNTED THE HOVERS',b:'Kept a tally on a fence post with her claws for eleven seasons and found no pattern anybody could use. The old ones tell it as a lesson about wasted effort. She told it, before she died, as a lesson about the pleasure of a long project, and her version is the one the young actually repeat.'},
{n:226,t:'IW',h:'ON NOT LOOKING UP',b:'A raised head is a shape and shapes are what they read. Every instinct says look, and the old ones say do not, and every one of us looks anyway at least once. Those who have been taken almost always report that they were looking up at the time, which proves the old ones right and changes nothing.'},
{n:227,t:'IW',h:'THE THING THEY LEAVE BEHIND',b:'A warmth on the post, gone within the hour, and a faint smell of old water. The old ones say do not follow it and do not sit in it. Everybody sits in it. It is the only trace of somewhere else any of us will ever touch, and a warm post is a warm post.'},
{n:228,t:'IW',h:'ADVICE FOR A CROWDED BRANCH',b:'If several of you share a branch when the light comes, do not all take the same colour. The old ones are very clear. A row of identical creatures is a pattern and a pattern is the one thing that stands out from four hundred lengths up. Disagree with each other. It is the only time it is required.'},
{n:229,t:'IW',h:'WHAT THE LIGHTS SOUND LIKE',b:'Not a sound exactly. A pressure at the base of the skull, like the moment before rain. The old ones teach the young to name it early so that it is a signal and not a fright. Those who have been up say the ship itself makes a hum, and that the hum is the same feeling, from inside.'},
{n:230,t:'IW',h:'THE TALE OF THE TWO ON THE ROOF',b:'Taken together, put back together, on the same tile, facing the same way. They did not speak of it for a season. Then one of them said that up there they had matched each other rather than the room, and the other said yes, and that was the entire conversation, and both were content with it.'},
{n:231,t:'IW',h:'ON THE FEAR THAT PASSES',b:'The first time the pressure comes you will freeze wrongly, in the open, badly coloured, and nothing will happen. This is normal. The old ones say a creature that has been frightened once and survived it is worth two that have not, and they say it kindly, and they say it to everybody, and it is mostly true.'},
{n:232,t:'IW',h:'WHY WE DO NOT LEAVE THE VALLEY',b:'The lights follow. Two generations tried it, moved three ridges over, and within a season the hovering began there too. The old ones took this as proof that we are the subject and not the place. The young took it as proof that running is expensive. Both lessons are taught and only one of them is ever used.'},
{n:233,t:'IW',h:'THE OLDEST INSTRUCTION WE HAVE',b:'Be where you are. Four words, taught before hunting, before hiding, before anything. The old ones say it is advice about colour. Everyone eventually works out that it is advice about everything, and that our whole reputation across the sky rests on a species that simply never wanted to be somewhere else.'},
{n:234,t:'IW',h:'WHAT WE OWE THOSE WHO CAME BACK',b:'One question each, and no more, and never the same question twice. It is a courtesy. A creature that has been in the grey room does not want to hold court about it, and the old ones ration our curiosity so that the returned are not turned into a story while they are still standing there.'},
{n:235,t:'IW',h:'ON THE SMELL OF THE ROOM',b:'Old water, and something sweet, and a burnt edge underneath. Every account agrees and no account can place it. The old ones say it is the smell of somewhere that has been away from home for longer than anything should be. They say it without triumph. They have made us, over four hundred years, oddly sympathetic.'},
{n:236,t:'IW',h:'THE ONE WHO WOULD NOT BE PUT BACK',b:'She climbed out of the light before it finished lowering, dropped the last of the way, and walked off. The old ones tell it as defiance. Those who were there say she simply did not care to wait, which is not the same thing, and which is more like us, and which nobody has ever managed to make into a song.'},
{n:237,t:'IW',h:'HOW TO TEACH THE VERY SMALL',b:'Not with the stories. With a warm rock and an afternoon and no instruction at all. The stories come later, once they can already do it, so that the lights are a curiosity rather than a terror. The old ones are inflexible about this order and it is the wisest thing they do.'},
{n:238,t:'IW',h:'WHAT IS SAID OF THE PALE ONES',b:'That they are pale all the way through and cannot help it. That their rooms are pale and their light is pale and even their voices are described by the returned as somehow without colour. The old ones do not mock them for it. Nothing our kind believes is stranger than the pity we have for a fleet.'},
{n:239,t:'IW',h:'A THING THE OLD ONES DO NOT SAY',b:'They never once say that the lights will stop. In four hundred years of advice, warning, folklore and song, there is no line anywhere promising an end to it. The young notice this eventually and ask, and the old ones look at them, and change the subject, and the young understand.'},
{n:240,t:'IW',h:'THE LAST THING TAUGHT',b:'When you are too old to hold a colour, sit somewhere the light can find you easily and let it. You will be looked at, and written down, and put back. It is not a bad ending. Somewhere very far away a tired creature will make a note about you, and be kinder about it than you would expect.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
