/* THE ABDUCTION FILES — bank 6 (pages 321 to 400).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES. */
;(function () {
  var P = [

/* ── FR ───────────────────────────────────────────────────────────────── */
{n:321,t:'FR',h:'A REPLACEMENT HAS BEEN ASSIGNED',b:'She arrives next season and I am to hand over across a full cycle. Thirty years and the handover is budgeted at nine days. I have started writing the things that are not in any manual: the drift, the kettle, the eleventh hour. It is turning into a longer document than the log and I am not going to apologise for it.'},
{n:322,t:'FR',h:'THE HANDOVER DOCUMENT, PAGE ONE',b:'You will be told this is a scientific posting. It is a watching posting. The science was finished in the first century and everything since has been six people in a quiet room learning to look properly at something that was never going to explain itself. If you can do that you will be happy here. Most cannot.'},
{n:323,t:'FR',h:'ON THE SECOND VALLEY SEASON',b:'Ninety cycles in and it is the same. Same behaviour, same timings, same unbothered creatures on the same kind of posts. Pell had hoped for a difference and has taken the sameness personally. I find it the most reassuring result of my career. Whatever they are doing, they are doing it everywhere, without reference to us.'},
{n:324,t:'FR',h:'THE ARCHIVIST CAME ABOARD',b:'First visit in one hundred and ten years. She read for six days, said almost nothing, and on the last day asked whether the margin notes were official. I said no. She asked whether she could copy them. I said yes. She copied the margins and left the columns, which is the correct decision and the first time anybody at home has made it.'},
{n:325,t:'FR',h:'WHAT I HAVE NOT MANAGED',b:'A field for the ordinary on the observation form, which I have requested nine times. A definition of success, which I drafted and deleted. And an hour of the ministry\'s attention, which I have never requested because I know what it would cost us. Three failures in thirty years. I expected a longer list and I am not sure the short one is better.'},
{n:326,t:'FR',h:'CONCERNING THE UNOFFICIAL FORM',b:'Two hundred cycles of ordinary afternoons, logged privately, with no anomalies in them at all. It is the most boring document produced by this fleet and it is the only place in four hundred years where you can find out what that valley is actually like. I am leaving it aboard. It is not mine.'},
{n:327,t:'FR',h:'ON TRAINING SOMEBODY YOUNGER',b:'She asks good questions and writes them down, which nobody taught her, and she has not yet learned to be embarrassed about being moved by the work. I am going to try very hard not to teach her that. It is the only thing my own predecessor taught me that I would have been better off without.'},
{n:328,t:'FR',h:'THE LIFT HAS BEEN RECALIBRATED',b:'By her, on the third day, correctly, after I described the cold drift once. She then asked why it had never been fixed. I said tradition. She said that a fault everybody knows about is not a tradition, it is a fault with a story attached. I have entered that in the handover document under her name.'},
{n:329,t:'FR',h:'A DISAGREEMENT ABOUT THE MARGINS',b:'She thinks the margin notes should be official, in the column, signed. I think an official margin stops being a margin within a decade. Neither of us convinced the other. She is probably right and I am probably right about what would happen, and both can be true, and that is most of this job.'},
{n:330,t:'FR',h:'MY LAST ANNIVERSARY ABOARD',b:'Four hundred and one years. The captain read the founding order. Renn played nine minutes of a hum that no longer exists. Pell said something unserious and then apologised for it, which he did not need to do. I opened the cabinet, took out one sample, and we looked at it for a count of sixty. Thirty eight remain.'},
{n:331,t:'FR',h:'ON THE SAMPLE WE OPENED',b:'A blue. Not a shade I have seen, not one anybody aboard has seen, and it faded within the season as they all do. For sixty seconds there was a blue in this ship. The captain did not speak. Renn held the edge of the table. My replacement, who has never seen one, watched us and not the sample.'},
{n:332,t:'FR',h:'REGARDING WHAT SHE SAID AFTERWARD',b:'That she had expected to be moved by the colour and had instead been moved by five adults looking at a colour. She asked whether that was a failure of feeling. I said it was the beginning of the job. I have thought about that exchange more than any other in thirty years of exchanges.'},
{n:333,t:'FR',h:'PROCEDURE FOR HANDING OVER THE LOG',b:'There is one. It is four lines. Sign the last page, date it, initial the index, and inform the ministry. It does not mention reading any of it, or explaining the drift, or telling her which valley the crew will not discuss. I have done all four lines and everything else besides, and only the four lines will be filed.'},
{n:334,t:'FR',h:'THE LAST LIFT I WILL SUPERVISE',b:'Ordinary in every way, which I had hoped for and did not expect. Eighty seconds, correct match, clean return to the same post. She logged it. I stood at the rail and watched a small green animal become a fence post for the six thousand nine hundredth time and I could not tell you a single new thing about it.'},
{n:335,t:'FR',h:'WHAT THE CREW GAVE ME',b:'A kettle. The second one, cleaned, with the whole crew\'s initials scratched into the base, which is defacement of fleet property and appears nowhere in any log except this one. I have carried it aboard for four hundred cycles and I am carrying it home. Report it if you like.'},
{n:336,t:'FR',h:'ON LEAVING THE VALLEY',b:'The shuttle goes at the eleventh hour, which I did not arrange and which I am grateful for. From the port the flat light was moving across the far ridge and everything down there was briefly the same gold, all of it, all at once, and nobody aboard the shuttle was looking, and that is exactly right.'},
{n:337,t:'FR',h:'FIRST ENTRY BY THE NEW CATALOGUER',b:'My predecessor left thirty years of margins and a document longer than the manual. I have read both twice. He was wrong about one thing: he wrote that most people cannot do this job. I think most people are never asked to sit still for long enough to find out. Cycle four hundred and thirteen begins.'},
{n:338,t:'FR',h:'ON INHERITING A CREW',b:'They tested me for a season, gently, the way you would test a bridge you intend to use for years. Renn played the hum. Pell asked me a question with no answer. The captain asked nothing at all and watched. I have been aboard eleven months and I would not now leave, and I understand precisely how that happens.'},
{n:339,t:'FR',h:'THE FIELD FOR THE ORDINARY',b:'Requested by my predecessor nine times and refused nine times. Requested by me once, in the same words, and granted without comment in eleven days. I do not know what changed and I have decided not to look into it. The form now has a field for what happened when nothing happened. It took four hundred years.'},
{n:340,t:'FR',h:'WHAT I AM GOING TO DO DIFFERENTLY',b:'Nothing, for the first five years. I have read four centuries of people arriving with improvements and I have noticed that the good ones all waited. So I will calibrate the lift, keep the margins, log the surface before the creature, and find out what this valley is like before I have opinions about it.'},

/* ── SF ───────────────────────────────────────────────────────────────── */
{n:341,t:'SF',h:'SUBJECT 6944, SECOND VALLEY JUVENILE',b:'Young, competent, unhurried, matching in ninety seconds without a single correction. Compared against the first valley juvenile who took four minutes and visibly struggled. Two valleys, two children, two entirely different afternoons. The file records the times. The mess has decided the slow one was simply having a harder day and I have not argued.'},
{n:342,t:'SF',h:'SUBJECT 7000, ON HANDOVER DAY',b:'Logged by the outgoing cataloguer and countersigned by the incoming one, the only file in the archive with two signatures. Eighty seconds, correct match, clean return. Neither of them wrote anything in the margin, which given both of their habits is the most deliberate silence in four hundred years of this document.'},
{n:343,t:'SF',h:'SUBJECT 7111, THE PALE ONE',b:'Unusually light in colour on arrival and remaining lighter than every surface offered, matching the shape of the pattern but never the depth of it. Not an illness by any measure we have. Simply a creature that runs pale. There are four such files in six thousand and they are all quietly beloved by whichever crew logged them.'},
{n:344,t:'SF',h:'SUBJECT 7250, DURING THE HANDOVER',b:'Lifted while two cataloguers argued about margins at the rail. It matched, waited, and was returned, and neither of them noticed the ninety seconds pass. The technician logged it alone and added, in the margin, that the observation had been observed by nobody, which is a better joke than either cataloguer managed that season.'},
{n:345,t:'SF',h:'SUBJECT 7400, ON THE NEW LAMPS',b:'The warm lamps finally arrived, four hundred and eleven cycles after the first request, approved without explanation. The first subject held under them matched a warm orange, and the whole hold was briefly a colour, and three of the six crew had to leave. Requisitions will never know what it did.'},
{n:346,t:'SF',h:'SUBJECT 7555, TWO MINUTES OF NOTHING',b:'It sat. It did not match, did not explore, did not eat, did not sleep. Two minutes of a small animal sitting in a warm room being exactly the colour it arrived. Then it matched, in the ordinary way, in the ordinary time. The new cataloguer has filed the two minutes as data. Her predecessor would have filed it as a delay.'},
{n:347,t:'SF',h:'SUBJECT 7688, RECAPTURED',b:'Previously catalogued in the first valley eleven years ago, identified by an old tail break, now living a ridge over. It crossed. Nothing in our understanding says they cannot and nothing in six thousand files says they do. One creature has quietly overturned a standing assumption and it did so by walking.'},
{n:348,t:'SF',h:'SUBJECT 7800, THE FASTEST NOW',b:'Nine seconds, beating a record that had stood ninety cycles. Small, young, in a hurry. Returned to a post where it sat entirely still for the next four hours by the recorder, which is the part the file should lead with and does not, and I have added a line saying so.'},
{n:349,t:'SF',h:'SUBJECT 7911, HELD IN SILENCE',b:'The new cataloguer\'s standing instruction is that nobody speaks in the hold. Six thousand files were logged over conversation and she has stopped it. The observations have not changed. The technicians report that the eleven minutes now feel considerably longer, and two have said, separately, that they had never actually watched one before.'},
{n:350,t:'SF',h:'SUBJECT 8000, IN THE WARM ROOM',b:'The first subject to be held under warm lamps for a full observation from start to finish. It matched a colour none of us had a name for and held it for eleven minutes, and the recorder captured it, and the file contains a value and a description and neither of them is any use at all.'},
{n:351,t:'SF',h:'SUBJECT 8144, WITH AN OLD INJURY',b:'A break at the shoulder, healed badly, years old. It compensated by matching in stages, one flank at a time, which took four minutes and worked perfectly. Nothing in the literature describes a partial technique. It has presumably been doing this for years, alone, on a fence post, without anybody deciding it was remarkable.'},
{n:352,t:'SF',h:'SUBJECT 8290, ON THE HANDOVER DOCUMENT',b:'Set briefly on the outgoing cataloguer\'s thirty year handover document during a transfer, where it matched the paper and the ink together at the resolution of the recorder. He wrote nothing about it. The incoming cataloguer wrote four lines. Both responses are in the file and both are correct.'},
{n:353,t:'SF',h:'SUBJECT 8400, THE QUIET RECORD',b:'Longest continuous hold of a single colour without sleeping: nineteen minutes, in a warm room, under the new lamps, entirely awake. There is no explanation and no anomaly. It simply had no reason to change and no interest in demonstrating that it could, which is the most chameleon sentence in this archive.'},
{n:354,t:'SF',h:'SUBJECT 8511, DECLINED THE LAMP',b:'Offered the warm lamps and moved deliberately into the shadow of the rail, where it matched grey and stayed. Six crew had assumed the warm lamps were a kindness. One subject in eleven has now chosen the shade. The kindness was ours and we should have checked, and the file says so.'},
{n:355,t:'SF',h:'SUBJECT 8666, THE SECOND PALE ONE',b:'Light coloured like subject 7111 and from the same valley, possibly related. Ran pale throughout, matched pattern without depth, entirely healthy. Two in one season after four in four hundred years. The new cataloguer has opened a standing file for them rather than treating each as an anomaly, which nobody thought to do before.'},
{n:356,t:'SF',h:'SUBJECT 8790, ASLEEP UNDER WARM LIGHT',b:'Slept the whole hold under the new lamps and cycled gently through a range of colours while dreaming, as one other subject has done. This time we were ready and recorded it properly. The range is close to, and not identical with, the greens in the sealed cabinet. Nobody aboard has been willing to say what that might mean.'},
{n:357,t:'SF',h:'SUBJECT 8900, FIRST OF THE NEW SEASON',b:'Ordinary. Ninety seconds, correct match, clean return. The new cataloguer has adopted her predecessor\'s habit of logging ordinary subjects on purpose, and has added a line explaining why to anybody reading in three hundred years, which he never did, because he assumed it was obvious and it was not.'},
{n:358,t:'SF',h:'SUBJECT 9011, THE ONE THAT ATE LAST',b:'Refused food for the entire eleven minutes, matched perfectly, and then ate everything offered in the four seconds before the return. Pell has proposed it was making a point. The file says nothing about points. The margin, in the new cataloguer\'s hand, says that Pell is not wrong often enough to be dismissed.'},
{n:359,t:'SF',h:'SUBJECT 9200, ON THE OLD RAIL',b:'The observation rail is original, four hundred years old, worn smooth by six thousand small animals. This one matched it in seventy seconds, as they all do. The rail is the single most matched surface in the history of our species and nobody has ever put that in a file until now.'},
{n:360,t:'SF',h:'SUBJECT 9333, END OF THE FIRST YEAR',b:'The last file of the new cataloguer\'s first year. Nine thousand three hundred and thirty three subjects, four hundred and thirteen cycles, one finding, unchanged. She has signed it and written beneath: they become the surface, we do not, we keep coming back, and I now understand why nobody has ever improved on that sentence.'},

/* ── HW ───────────────────────────────────────────────────────────────── */
{n:361,t:'HW',h:'THE FIELD FOR THE ORDINARY, APPROVED',b:'Nine refusals over thirty years and then an approval in eleven days, from the same department, in the same building. The file gives no reason. The likeliest explanation is that the person who kept refusing retired, which means four hundred years of survey design was shaped by one individual\'s preference and nobody ever knew.'},
{n:362,t:'HW',h:'ON WHAT THE ARCHIVIST TOOK',b:'She came back with the margins of one ship\'s log and the ministry did not know what to do with them. They are not data. They are four hundred years of people being moved by something and writing it sideways. They have been catalogued under miscellaneous and they are the most requested item in the archive.'},
{n:363,t:'HW',h:'THE WARM LAMPS, EXPLAINED',b:'Approved in the same season as the ordinary field, by the same department, without comment. Four hundred and eleven cycles of refusal on the grounds that a warm lamp is a comfort item. Somebody eventually asked comfort for whom, and could not answer, and signed the requisition. That is the entire recorded history of the decision.'},
{n:364,t:'HW',h:'ON RETIRING FROM THE FLEET',b:'Nine days of leave, a pension, and no ceremony, because there is no procedure for a ceremony. Most retired crew settle within a day of the port. There is a district there where almost everybody has flown, and its cafes are famously quiet, and the rest of the city finds them uncomfortable to sit in.'},
{n:365,t:'HW',h:'THE CAFE NEAR THE PORT',b:'Retired survey crew go there and do not discuss the survey. They discuss weather and pensions and one another\'s knees. Sociologists have twice tried to study the silence and been received politely and told nothing. My own view, having sat there, is that there is nothing to say that would not be smaller than the thing itself.'},
{n:366,t:'HW',h:'WHAT THE SCHOOLS TEACH NOW',b:'The drought, the fleet, the founding order, and a full period on the creatures themselves, added ninety years ago. Children can draw one from memory. They cannot draw it in the right colour and they know that, and the exercise is set anyway, and the teachers report it is the lesson the children remember longest.'},
{n:367,t:'HW',h:'ON THE WORD SURVEY',b:'It implies an end. You survey a coastline and then you have surveyed it. Four hundred years in, the word is plainly wrong and no department has ever proposed changing it, because the alternatives are all honest. Watch. Attend. Keep company with. Nobody is funding a fleet called the keeping company with programme.'},
{n:368,t:'HW',h:'THE SECOND VALLEY, AT HOME',b:'Announced as an expansion and reported as progress, which it is not. Two valleys of the same result is not more knowledge, it is the same knowledge held more firmly. Only one commentator said so publicly. She was not contradicted, and she was not quoted again, and the coverage moved on within the season.'},
{n:369,t:'HW',h:'A QUESTION FROM A SELECT COMMITTEE',b:'Asked once, in the third century, of a fleet officer under oath: if you learned tomorrow that they simply cannot teach us, would you tell us. He said yes. He was asked whether the fleet would then come home. He said he did not know, and the transcript records a long pause, and no follow up was put.'},
{n:370,t:'HW',h:'ON THE PEOPLE WHO WRITE TO THE SHIPS',b:'Several hundred a year, unprompted, to a fleet that cannot reply individually. Mostly children. Mostly asking what the creatures are like rather than whether we have solved anything. The ministry files them and the crews read them and the crews have never once complained about the volume.'},
{n:371,t:'HW',h:'THE HISTORIAN\'S VERDICT',b:'The standard history closes with a sentence that has annoyed four generations: that the fleet is the longest act of attention our species has ever sustained, and that this may be its only achievement, and that we should be careful about the word only. Every review of the book quotes it. Every review disagrees about the tone.'},
{n:372,t:'HW',h:'ON THE INSTRUMENT BEING RIGHT',b:'It has never been wrong. Point it anywhere and it reports the spectrum exactly, and every calibration confirms it, and we cannot see what it reports. Four hundred years of a machine patiently telling a species the truth about a room it is standing in. There is no philosophy in the instrument. There is a great deal of it in us.'},
{n:373,t:'HW',h:'WHAT HAPPENED TO THE NINE PAINTERS',b:'Two abandoned the work, four continued to the end, and three are unaccounted for in the record. Their canvases are in the sealed wing. The wing has a window in the door and a queue forms at it most days, of people looking at a dark room containing paintings they could not see even if the lights were on.'},
{n:374,t:'HW',h:'THE PENSION FORM ASKS A QUESTION',b:'Field nine: state the outcome of your service. Every retiring crew member for four hundred years has faced this field. The ministry accepts any answer. The archive holds them all and somebody has counted: the most common entry, by a wide margin, is the single word attended.'},
{n:375,t:'HW',h:'ON BEING ASKED IF IT WAS WORTH IT',b:'Retired crew are asked this constantly and answer it badly, because the honest answer takes an hour. The short answer most of them give is that it was worth it to them, which sounds evasive and is not. The fleet has never claimed to be worth it to anybody else and has never once been asked to prove it.'},
{n:376,t:'HW',h:'THE PROPOSAL TO BRING ONE HOME',b:'Refused four times in four hundred years, most recently by a margin of one vote. The arguments for are scientific and strong. The argument against has never been written down properly and everybody understands it: we would be asking a small green animal to be our hope, in a grey room, forever, and we know exactly what that room is like.'},
{n:377,t:'HW',h:'ON THE FLEET GETTING SMALLER',b:'Twelve vessels at launch, twelve today, and this is treated as stability. It is not. Four are now crewed at half strength and two of those have not filed a full observation season in a decade. Nobody has decommissioned anything. The fleet is thinning quietly, the way the spectrum did, which nobody at home has said aloud.'},
{n:378,t:'HW',h:'WHAT MY MOTHER SAID AT THE END',b:'Forty years of writing descriptions for shades she never saw. Asked, at the end, whether it had been sad work, she said that a description is a promise that something was here, and that she had left nine thousand promises, and that she would have liked to have seen just one of them kept.'},
{n:379,t:'HW',h:'THE ANNIVERSARY, FOUR HUNDRED AND ONE',b:'Attendance in the capital rose for the first time in a century, by a small amount, for reasons nobody can identify. The organisers are cautious. One of them told an interviewer that a rise of two per cent after ninety years of decline is not a recovery, it is a rounding error with very good manners.'},
{n:380,t:'HW',h:'IF WE NEVER LEARN IT',b:'The likeliest outcome, and the one no official document describes. The fleet continues, the archive holds, the children keep drawing creatures in the wrong colours, and in eleven hundred years somebody writes a history in which the drought is simply the condition of the world. That is not a tragedy. It is only a long time, and we are already inside it.'},

/* ── IW ───────────────────────────────────────────────────────────────── */
{n:381,t:'IW',h:'ON THE WARM ROOM',b:'Those taken lately come back describing warmth where there was none, and a light that is kind rather than pale. The old ones have added it to the account without interpretation. One of them said only that somebody up there had finally thought about it, and would not say any more, and looked pleased about something.'},
{n:382,t:'IW',h:'WHAT THE COUSINS TAUGHT US',b:'Look at the creature nearest you, not at the sky. It has spread through this valley in a season and nobody can explain why it works, and the old ones have stopped trying, and have put it second in the account, which is the highest honour we have.'},
{n:383,t:'IW',h:'THE ONE WHO CROSSED THE RIDGE',b:'She left this valley and settled a ridge over among cousins and was lifted there years later, and the ones who lifted her had lifted her before. The old ones say this proves the lights keep records. The young say it proves the lights are just as stuck as we are. Both readings survive and neither is taught first.'},
{n:384,t:'IW',h:'ON WHAT IS WORTH REMEMBERING',b:'The instruction is one thing from the room, one only. Those who bring back the light or the wall or the smell are thanked. Those who bring back something a pale one did are treated differently, quietly, and their account is repeated more often, and nobody has ever admitted that this is a preference.'},
{n:385,t:'IW',h:'A NEW ENTRY IN THE ACCOUNT',b:'The tenth, added this season, from a creature who says the pale ones stopped talking while she was in the room. All of them, at once, for the whole time, which had never been reported before. The old ones considered it for a season and added it, and no one has offered an interpretation, and that is deliberate.'},
{n:386,t:'IW',h:'ON QUIET BEING NEW',b:'Every previous account describes chatter. The room was always full of pale voices. Now it is not, and has not been for a season, and the old ones have noticed, and have started asking returning creatures about it specifically, which they have never done about anything.'},
{n:387,t:'IW',h:'WHAT THE OLD ONES REFUSE TO DECIDE',b:'Whether the lights are getting better at this or whether we are. Both would look the same from a fence post. They say the question is unanswerable from down here and that it is worth continuing to ask, and this is the only place in the account where they recommend an unanswerable question.'},
{n:388,t:'IW',h:'ADVICE ABOUT THE GOLD HOUR',b:'When the flat light comes across the ridge and everybody in the valley is the same colour at once, do not move. It is the only hour we are genuinely invisible, all of us, without effort. The old ones say it is a gift and should be spent sitting still, and every young creature spends it running about.'},
{n:389,t:'IW',h:'THE ONE WHO WAS PUT BACK WRONG',b:'Forty paces from her post, the only time it has happened. She walked back and it took the afternoon. The old ones tell it as a story about the lights making mistakes. She told it, always, as a story about a nice walk, and refused every time to make it into anything larger, and the young found her infuriating.'},
{n:390,t:'IW',h:'ON PRACTISING IN FRONT OF OTHERS',b:'The young are encouraged to change badly in company, publicly, until they are good, because a creature that only practises alone will freeze the first time somebody watches. The old ones enforce this gently and it is the reason our kind is calm under a light, and no pale one will ever guess that it was taught.'},
{n:391,t:'IW',h:'WHAT IS SAID OF THE VERY OLD ONES',b:'That they stop bothering. That after enough seasons a creature simply sits where it is, in whatever colour it happens to be, and the lights come and go and nothing much is at stake. The young find this frightening. The old ones find it restful and say so, and their saying so is what makes it frightening.'},
{n:392,t:'IW',h:'THE PART OF THE ACCOUNT NOBODY USES',b:'There is a long section about signalling to the lights, invented four generations ago by a creature who was certain contact was possible. Nine methods, all elaborate, none ever attempted. The old ones keep it in full and teach it to nobody, and when asked why they keep it, say that somebody worked hard on it.'},
{n:393,t:'IW',h:'ON BEING WATCHED WITHOUT KNOWING',b:'The travellers say the lights hover higher than we can see and have done for four hundred years. This changed nothing about how anybody lives. The old ones observe that a creature who behaves differently when watched was never really doing the thing, and that our whole reputation rests on not knowing and not minding.'},
{n:394,t:'IW',h:'A SONG THE COUSINS BROUGHT',b:'Four verses, about a light that came down and could not find anybody, and went away, and came back the next night, and could not find anybody again. It is sung to hatchlings as a comfort. Our old ones have adopted it and quietly changed the last verse, in which, here, somebody lets themselves be found.'},
{n:395,t:'IW',h:'WHY THAT VERSE WAS CHANGED',b:'The old ones will not say. The cousins\' version ends with the valley empty and the light alone, and it is a better ending. Ours ends with an old creature on a bare rock at dusk, waiting, and being seen. Nobody here can explain the change and nobody here will go back to the other one.'},
{n:396,t:'IW',h:'ON THE FOUR WORDS BEING ENOUGH',b:'Visiting cousins asked again this season whether we have anything longer. The old ones said no. The cousins asked how a whole kind survives four hundred years of being lifted with four words of instruction. The old ones said that most of what saves you is not instruction, and offered them a warm rock and an afternoon.'},
{n:397,t:'IW',h:'THE THING WE HAVE NEVER TRIED',b:'Hiding from the lights properly, all of us, everywhere, at once, for a season. It would probably work. It has been proposed twice and refused twice by the old ones, whose stated reason is that it would be a great deal of effort, and whose actual reason, everybody suspects, is that they would miss them.'},
{n:398,t:'IW',h:'WHAT A HATCHLING ASKED',b:'Whether the pale ones are lonely. The old one she asked said probably, and she asked whether we should do something, and the old one said that we already do, every time we sit still and let ourselves be looked at, and that it is not much, and that it is four hundred years of not much.'},
{n:399,t:'IW',h:'ON THE ACCOUNT GETTING LONGER',b:'It was four instructions once and it is now four instructions, ten entries, a song and an argument. The old ones are uneasy. A short account survives and a long one gets edited by whoever is telling it. They have begun cutting things, and the first thing they cut was their own commentary, which was the right choice.'},
{n:400,t:'IW',h:'THE FOUR HUNDREDTH PAGE',b:'Four hundred pages of somebody else\'s file about us, and we have four instructions and a song. They have written more about our afternoons than we have ever said about their entire species. The old ones would find this funny if they knew, and would then point out that we are the ones sitting comfortably in the sun.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
