/* THE ABDUCTION FILES — bank 3 (pages 101 to 160).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES. */
;(function () {
  var P = [

/* ── FR: the work grinds on, and the cataloguer keeps noticing things ──── */
{n:101,t:'FR',h:'REQUISITION 9012, DENIED',b:'My ninth request for warmer lamps has been denied on the grounds that the previous eight were denied. I have read the reasoning four times. It is a circle, and it is a very tidy one, and somewhere at home a person was paid to close it. I am going to keep asking. A circle only holds while everyone agrees to walk it.'},
{n:102,t:'FR',h:'ENSIGN PELL HAS BEEN COUNTING',b:'Pell informs me that in four hundred and eleven cycles we have lifted six thousand and four subjects and returned six thousand and four. He offered this as an achievement. I asked what we had learned. He said we had learned we are very good at putting things back. I have entered that in the log as a finding, because it is one.'},
{n:103,t:'FR',h:'ON THE SMELL OF THE HOLD',b:'Four hundred years of borrowed weather has settled into the walls. Pond from cycle two hundred and nine. Woodsmoke from a valley we no longer visit. Something sweet from the season of the orchards. The crew complains. I have stopped complaining, because it is the only part of this ship that remembers where it has been.'},
{n:104,t:'FR',h:'A DISPUTE ABOUT THE KETTLE',b:'The kettle is contested because there is one kettle and six of us and no procedure. Renn proposes a roster. Pell proposes seniority. The captain proposes we requisition a second kettle, which will be denied, because a kettle is a comfort item. We have crossed a great deal of empty space to argue about hot water and I find that oddly reassuring.'},
{n:105,t:'FR',h:'WEATHER OVER THE TARGET VALLEY',b:'Rain since the third hour. The subjects do not mind rain. They go darker, slower, and entirely undramatic about it. We hover above the cloud because the lift does not like water in the column, so we spend the day watching grey from above grey. I have written the word grey four times in one entry. That is the report.'},
{n:106,t:'FR',h:'I HAVE READ THE FOUNDING ORDER AGAIN',b:'It promises a solution within a generation. It was written by people who had seen the drought start and could not imagine it finishing without them. Every line is confident. Every line is wrong. I do not think they lied. I think they simply could not picture a problem that outlives the person describing it, and now here we all are, picturing it.'},
{n:107,t:'FR',h:'CONCERNING THE HUM IN EMITTER TWO',b:'The hum has become a note. The note has become, according to Renn, roughly the pitch of a homeworld field cricket, which nobody aboard has heard, because the field crickets went with the greens. Renn is certain anyway. I have logged the hum as a fault and quietly asked engineering not to fix it yet.'},
{n:108,t:'FR',h:'WHY THE LOG IS KEPT IN ORDER',b:'Regulation says entries must be sequential so that a reader can follow the survey from first day to last. Nobody reads it that way. The archivists dip in, take a page, and put it back. So the order is a courtesy to a reader who has never existed, and I maintain it every day, and I have started to find that funny rather than sad.'},
{n:109,t:'FR',h:'THE CAPTAIN CAME TO THE RAIL',b:'She stood at the observation rail for an hour without speaking, watching a subject on a fence post do absolutely nothing. Then she said: it is not hiding from anything. It just prefers to look like that today. Then she went back to the bridge. I have never heard an officer of this fleet get closer to the point.'},
{n:110,t:'FR',h:'AN ERROR IN MY OWN HANDWRITING',b:'Cycle three hundred and ninety, I wrote that a subject turned the colour of fear. There is no such colour. It turned the colour of the crate beside it, and I was tired, and I made the crate into a feeling. I am correcting it now because a false observation in a true log is worse than an empty page.'},
{n:111,t:'FR',h:'GUIDANCE FOR NEW CATALOGUERS',b:'You will want to write that the subject is calm. Do not. Calm is what you feel about it. Write what it did, how long it took, and what colour it settled on. The feelings are yours to carry and the record is not the place to put them down. I have broken this rule in nearly every entry and I stand by the rule.'},
{n:112,t:'FR',h:'SIX OF US, DOWN FROM THIRTY',b:'The others were not lost. They were reassigned, one at a time, to surveys with clearer objectives. Nobody blames them. A person can only hover over an answer for so long before somebody offers them a question they can finish. Some cycles I catch myself drafting the transfer and then I go and look at the valley instead.'},
{n:113,t:'FR',h:'PROCEDURE WHEN A SUBJECT SLEEPS',b:'Do not wake it. Log the time, log the surface, log the colour, and wait. A sleeping subject holds its colour for hours, which is the single most useful thing this survey has ever recorded and it took us two hundred cycles to stop poking them long enough to see it.'},
{n:114,t:'FR',h:'REGARDING THE LOCKED CABINET',b:'It holds forty samples of colour from home, sealed, from before. We may open it on the anniversary. This cycle nobody asked. I stood by it for a while with the key in my hand and decided that a colour you can only look at forty times is a thing you spend, and I did not want to spend one on a bad day.'},
{n:115,t:'FR',h:'MY REPLACEMENT WILL READ THIS',b:'Whoever you are: the lift drifts left in cold air. Renn takes the kettle at the sixth hour and it is not worth the fight. The subjects are not puzzles. If you come here to solve them you will be unhappy, and if you come here to watch them you will still be unhappy, but you will be better company.'},

/* ── SF: one creature, one page, and the file keeps failing to stay clinical ── */
{n:116,t:'SF',h:'SUBJECT 0107, THE SLOW ONE',b:'Taken from a hanging branch after a wait of six hours, during which it moved the length of my hand. Aboard, it matched the rail, then the glove of the technician holding it, then the rail again, apparently to check. Renn calls this a comparison. The file will record it as sequential colour change with no observable stimulus.'},
{n:117,t:'SF',h:'SUBJECT 0233, WHICH REFUSED',b:'Lifted from a red roof tile and held for eleven minutes in a grey hold under grey lamps, where it remained red. Every previous subject matched within ninety seconds. This one did not, and looked at us throughout. We returned it to the tile. It is the only entry in six thousand where the finding is simply that it did not feel like it.'},
{n:118,t:'SF',h:'SUBJECT 0400, THE SMALLEST',b:'No longer than a thumb and not remotely concerned about that. Matched the seam of a glove so exactly that the technician set it down twice believing his hand was empty. We found it on the third search by its breathing. It had not moved. It had simply become part of the equipment, and the equipment had not objected.'},
{n:119,t:'SF',h:'SUBJECT 0512, PREGNANT',b:'Observed, logged, and released within four minutes under standing orders. She matched nothing aboard. She stayed the colour of the branch we took her from, which is either an inability or a decision, and I have written the word decision and then crossed it out and then written it again in the margin where the archivists will not look.'},
{n:120,t:'SF',h:'SUBJECT 0655, WITH A HEALED TAIL',b:'Old break, well knitted, curled tight. Matched the hold in a leisurely forty seconds and then went a shade paler than the wall, which is not matching, which is not in the manual. Renn suggests it was cold. I suggest we have spent four hundred years assuming everything they do is about us.'},
{n:121,t:'SF',h:'SUBJECT 0781, THE LOUD ONE',b:'Hissed at the lift, hissed at the hold, hissed at the lamp, and matched the wall perfectly the entire time. This is the file that finally settled the argument in the mess: the colour is not a mood. A creature can be furious and beige simultaneously. Several of the crew found this personally relevant.'},
{n:122,t:'SF',h:'SUBJECT 0902, ASLEEP THROUGHOUT',b:'Lifted from a sun warmed stone without waking. Slept for the entire observation. Held the exact colour of that stone for two hours in a hold that looked nothing like it, then woke, looked around, and changed. The finding is that the trick does not require attention. It runs while they dream, and ours does not run at all.'},
{n:123,t:'SF',h:'SUBJECT 1000, CEREMONIAL',b:'The thousandth subject was given a small ceremony, a warm lamp borrowed without permission, and eleven minutes of everyone being quiet. It matched the warm lamp. For eleven minutes there was an orange creature in a grey room and six adults stood very still. The file records the colour value. It does not record what the room was like.'},
{n:124,t:'SF',h:'SUBJECT 1144, ON GLASS',b:'Placed on the observation glass, through which the valley was visible. It matched the valley. Not the glass, the valley, seen through it, including the movement of the cloud shadow across the far ridge. The technician logged an equipment fault. I have logged no fault. I have logged what happened.'},
{n:125,t:'SF',h:'SUBJECT 1290, TWO OF THEM',b:'Lifted together by accident, one on the other. In the hold they separated, took different walls, and matched different greys. Two creatures in one room choosing two answers to one question. The mess argued about it for a season. Renn says it proves nothing. Renn also has not slept properly since.'},
{n:126,t:'SF',h:'SUBJECT 1401, WOUNDED',b:'Damaged foot, recent, not by us. Matched the hold slowly and imperfectly, the colour arriving in patches. It is the only time this survey has watched the trick struggle, and the whole crew found it unbearable. We treated the foot, which is outside our remit, and returned it early, which is also outside our remit.'},
{n:127,t:'SF',h:'SUBJECT 1555, ON A MIRROR',b:'An experiment I authorised and would not authorise again. Placed on a mirror, the subject was faced with itself and matched itself, which is a sentence that has caused four hundred hours of argument in the mess and one resignation. It then walked off the mirror and became the floor and was, I think, finished with us.'},
{n:128,t:'SF',h:'SUBJECT 1700, ELDERLY',b:'Considerable age, judged by the ridges. Colour change slower than any subject on file, taking nine minutes to do what a young one does in ninety seconds. It got there. That is the entry. In four hundred years of records that is the first time this survey has written the words it got there with any warmth in them.'},
{n:129,t:'SF',h:'SUBJECT 1888, RELEASED IN ERROR',b:'A technician opened the wrong panel and the subject left into the ship. It was found eleven hours later on the mess table being the exact colour of the mess table, six of us having eaten around it. Nobody had noticed. It was returned to the valley. Nobody has stopped thinking about it.'},
{n:130,t:'SF',h:'SUBJECT 2000, THE LAST IN THIS BANK',b:'Unremarkable in every measurable way. Lifted, held, matched, returned, four minutes, no incident. I record it here because a survey that only writes down the strange ones will eventually believe the world is strange, and most of them are like this: small, green, entirely content, and not in the least interested in being our answer.'},

/* ── HW: home, and what a colour drought actually takes ────────────────── */
{n:131,t:'HW',h:'THE ARCHIVE OF NAMED SHADES',b:'Nine thousand names, alphabetical, each with a sealed sample. Roughly half now open onto something the eye reads as the same beige. The archivists still read the names aloud on the appointed days. It is not a ceremony for the colours. It is a ceremony for the names, which are all we have left that were made on purpose.'},
{n:132,t:'HW',h:'WHAT THE CHILDREN ARE TAUGHT',b:'They learn the spectrum from a chart with descriptions where the samples used to be. Warm like a hand. Cold like deep water. Loud, quiet, kind. They test well. Then a survey ship comes home with a lifted stone and one of them sees an actual red and has to sit down, and no chart has ever prepared anybody for that.'},
{n:133,t:'HW',h:'THE FIRST SHADE TO GO',b:'A green nobody could name afterward, which is the detail that frightens people most. It did not vanish overnight. It thinned, and everyone assumed it was the light, or their eyes, or the season. By the time it was accepted as gone there was no sample left to argue with, and the argument about whether it had existed is still running.'},
{n:134,t:'HW',h:'ON THE HONESTY OF OUR BUILDINGS',b:'We stopped painting eighty years ago. A painted wall is a promise that the paint will still mean something next year, and we could not keep it. So we build in the colour of the material and call it honesty, and the young think we chose it, and we let them think so.'},
{n:135,t:'HW',h:'THE FLEET AS A NATIONAL PROJECT',b:'Four hundred years of ships hovering politely over other people\'s valleys, funded without interruption through three governments and one collapse. No other project in our history has been protected like this. Historians say it is because it might work. I think it is because a world that cancels its last hope has to be a world that has run out, and nobody wants to sign that.'},
{n:136,t:'HW',h:'THE ORCHARDS BEFORE',b:'My grandmother described them as noisy. Not the sound, she said, the look of them. Everything shouting at once, a hundred greens arguing about which was correct, and fruit so loud you found it with your eyes closed. She used the word noisy as praise. I have never heard anyone under sixty use it that way.'},
{n:137,t:'HW',h:'A LETTER FROM THE MINISTRY',b:'Received this cycle, addressed to the survey, thanking us for four hundred years of service and asking, in the final paragraph, whether a projected completion date could be provided for planning purposes. The captain read it twice and laughed once and filed it. She has not drafted a reply. I do not believe one exists.'},
{n:138,t:'HW',h:'WHY WE DID NOT SIMPLY MAKE MORE',b:'We tried. Pigment can be manufactured, and it was, in enormous quantity, and it looked correct in every instrument and wrong to every eye. Nobody has satisfactorily explained why. The best account we have is from a technician who said it looked like a colour that had been told to be a colour, which is not science and is the only description anyone repeats.'},
{n:139,t:'HW',h:'THE THEORY THAT IT IS OUR FAULT',b:'It is popular, it is unprovable, and it will not go away. The reasoning is that a world which stopped looking properly at itself would lose what it stopped looking at. No mechanism, no evidence, and yet three of the six of us aboard believe it privately, including me on the longer cycles.'},
{n:140,t:'HW',h:'WHAT THE DROUGHT DID NOT TAKE',b:'It did not take the light, or the shapes, or the seasons, or the way water moves. Everything that ever mattered is still there and still working. This is the cruel part and it is why nobody at home can quite call it a tragedy. We are not ruined. We are simply less, in a way that only shows when you try to describe something.'},
{n:141,t:'HW',h:'THE ANNIVERSARY AT HOME',b:'They mark it too. Four hundred years, a reading of the founding order, and in the capital they open one sealed sample in public for a count of sixty. Attendance has fallen every decade for a century. Not from despair, the surveys say, but from something worse and quieter: people have found they can get through the year without it.'},
{n:142,t:'HW',h:'ON SENDING THE YOUNG',b:'Every survey ship carries at least one crew member born after the last named shade was lost. The regulation is deliberate. Somebody aboard has to be unable to remember, so that the rest of us are describing it rather than reminiscing. It is the single cruelest sensible rule we have and I have never argued against it.'},
{n:143,t:'HW',h:'THE WORD FOR THIS FEELING',b:'We had one. It meant the specific ache of seeing a colour you know is not what it used to be. It fell out of use about ninety years ago, because a word that everybody needs constantly stops being worth saying. I have looked for it in the archive twice. It is there, with a sealed sample beside it, which is somebody\'s idea of a joke.'},
{n:144,t:'HW',h:'PROPOSALS TO END THE SURVEY',b:'Fourteen in four hundred years, each one reasonable, each one defeated. The strongest was the ninth, which argued that a fleet searching forever is a monument, not a project, and that we should admit which one we are building. It lost by eleven votes. I keep a copy. It is the best thing ever written about us and it was written by our enemy.'},
{n:145,t:'HW',h:'WHAT WE WOULD DO WITH THE ANSWER',b:'Assume we learn it tomorrow. Assume every one of us can hold a colour the way they do. Nobody at home has published a plan for the following day. Four hundred years of preparation for the moment, and not one page about the afternoon after it. I find that more frightening than the drought.'},

/* ── IW: what the old ones say, passed down and getting bent in the telling ── */
{n:146,t:'IW',h:'ON WHAT THE LIGHTS ARE FOR',b:'The old ones say the lights are collecting. Not us, they say, and not our bodies, which they have had and given back. They are collecting the moment where you decide. Go limp, be dull, and give them a boring decision, and they will put you down disappointed and unharmed, which is the best any of us can ask of weather.'},
{n:147,t:'IW',h:'THE ADVICE ABOUT FENCE POSTS',b:'Sit on wood, not stone, when the lights are out. Stone is honest and holds one colour all day, so a stone tells them where to look. Wood changes with the wet and the hour, and a creature on wood is already halfway to being an argument. The old ones are very firm about this and no one has ever explained it.'},
{n:148,t:'IW',h:'A SONG FOR THE HOLD',b:'There is a rhythm the old ones teach for when you are taken. It is four beats, the length of a slow breath, and you are meant to think it rather than sing it. It does nothing. Everyone who has been up there says it does nothing, and everyone who has been up there taught it to somebody afterward.'},
{n:149,t:'IW',h:'WHAT THE OLD ONES SAY ABOUT MIRRORS',b:'Never settle on one. A mirror asks you what you are and then shows you your own answer, and the old ones say a creature that gets into that argument is still in it at nightfall. One of us was taken to a mirror by the lights and came back changed in a way nobody can point at. That is the whole story. Nobody tells it twice.'},
{n:150,t:'IW',h:'THE TALE OF THE ONE WHO STAYED RED',b:'Lifted from a roof and held in the grey room and simply did not change, because, she said afterward, she had been red all morning and saw no reason to stop. The old ones tell this to the young as a story about courage. The young mostly hear it as a story about being stubborn, which she was, and which is the point.'},
{n:151,t:'IW',h:'WHY WE DO NOT WARN EACH OTHER',b:'When the lights come, nobody calls out. It is not cowardice. A call is a movement and a movement is a shape and the lights read shapes better than colours. So we go still and let the one who is nearest be the one who is nearest, and afterward we do not speak of it, and this is the oldest and least comfortable of our arrangements.'},
{n:152,t:'IW',h:'ON BEING PUT BACK',b:'Always on the same post. Never once the wrong post in the memory of anyone living. The old ones take this as proof the lights mean no harm. The young take it as proof the lights are keeping records. Both readings are correct and the old ones know it and choose the kinder one aloud.'},
{n:153,t:'IW',h:'THE COUNTING GAME',b:'Hatchlings are taught to count the hover. If it holds steady past a slow hundred it is looking at you specifically and you should become extremely boring. If it wobbles it is looking at the valley and you may carry on. It is a nonsense and it is also the first thing any of us learns about patience.'},
{n:154,t:'IW',h:'A DISAGREEMENT AMONG THE OLD ONES',b:'One says the lights are lonely. Another says a lonely thing does not hover for four hundred years without ever landing. The first says that is exactly what a lonely thing does. They have argued this in front of the young every season for as long as anyone remembers and neither has ever offered to settle it.'},
{n:155,t:'IW',h:'ON THE SMELL THAT COMES BACK WITH YOU',b:'Those who have been up describe it the same way without comparing notes: old water, and something sweet, and a burnt edge. It fades in a day. The old ones say it is the smell of a place that has been travelling for a very long time and has not been home in any of it. They say it with more sympathy than you would expect.'},
{n:156,t:'IW',h:'THE INSTRUCTION FOR THE VERY YOUNG',b:'If you are lifted, do not fight the pull. It does not hurt and it does not stop. Look at where you are going. Remember one thing about the room, one only, and bring it back, and the old ones will add it to what we know. This is how the whole account was built, one remembered thing at a time, by creatures who were frightened.'},
{n:157,t:'IW',h:'WHAT WE THINK THEY WANT',b:'The old ones say they want the trick, and they will not get it, because it is not a trick. You do not decide to be the colour of the branch. You are on the branch. It is the least interesting thing about any of us and they have crossed the whole sky for it, and that is the part the old ones find sad rather than funny.'},
{n:158,t:'IW',h:'THE ONE WHO ASKED TO GO',b:'There is a story, probably untrue, of a chameleon who climbed a bare white rock in open ground at dusk and waited to be seen. The old ones will not say why. Some tellings have her curious. Some have her tired. In every telling the light comes down, and holds, and does not take her, and she comes back down the rock alone.'},
{n:159,t:'IW',h:'HOW TO KNOW A GOOD HIDING PLACE',b:'Not the one that matches you now. The one that will still match you when the cloud moves and the hour turns and the wet dries off the wood. The old ones say a young creature picks a place with its eyes and an old creature picks it with the afternoon, and this is the only piece of their advice that has ever been proven.'},
{n:160,t:'IW',h:'WHAT I WOULD ASK THEM',b:'If the lights could hear, I would not ask them to stop. I would ask what it is like up there, whether it is really as grey as those who came back describe, and whether they know that the branch does most of it. Somebody should tell them. Four hundred years is a long time to be almost right about something so small.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
