/* THE ABDUCTION FILES — bank 5 (pages 241 to 320).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES. */
;(function () {
  var P = [

/* ── FR ───────────────────────────────────────────────────────────────── */
{n:241,t:'FR',h:'ON THE COUNTING OF CYCLES',b:'A cycle is one pass over the valley, which is a unit invented by people who assumed the passes would run out. We are at four hundred and eleven. The founding order allocates space on its final page for the number, and the space is large enough for three digits, and we are going to need a fourth within my service.'},
{n:242,t:'FR',h:'RENN HAS RECORDED THE HUM',b:'Before engineering silenced emitter two she made a recording of nine minutes, which she plays in the mess at the eighth hour. Nobody has asked her to stop and nobody has asked her why. It is the only sound aboard this ship that we made by accident and decided to keep, and that is not nothing.'},
{n:243,t:'FR',h:'INVENTORY, FULL, FOURTH CENTURY',b:'Two kettles. One lift, functioning, drifting left in cold. Two emitters, one silent. Six crew. Six thousand four hundred files. Forty sealed colour samples in a cabinet nobody opens. Nine written incidents, of which two are a bicycle. And four hundred and eleven cycles of a log that its own authors describe, repeatedly, as almost useful.'},
{n:244,t:'FR',h:'PELL HAS BEEN PROMOTED',b:'To lieutenant, effective this cycle, with no ceremony because there is no procedure for a ceremony aboard a survey vessel. We used the second kettle. The captain said nine words. He asked, afterward, whether the promotion meant he had to stop asking questions. She said it meant the opposite and left the mess quickly.'},
{n:245,t:'FR',h:'A NOTE ON THE OBSERVATION GLASS',b:'It has been cleaned three times in four hundred years and the third time was this cycle, by me, because I wanted to know whether the valley was greener than I remembered or whether I was looking through four hundred years of hold weather. It was the glass. I am obscurely relieved and I have not told the crew.'},
{n:246,t:'FR',h:'THE ARGUMENT ABOUT PROCEDURE ELEVEN',b:'Procedure eleven requires that a subject be returned to the exact point of origin. Pell argued that a fence post is not a home and that we could return them anywhere convenient. Renn said the post is where it decided to be, and deciding is the whole thing we came for. Procedure eleven stands, unamended, on Renn\'s argument.'},
{n:247,t:'FR',h:'ON KEEPING A LOG NOBODY NEEDS',b:'Two hundred cycles ago I stopped writing for the archivists. I now write for whoever ends up in this chair, and the log has improved, and it has also become useless to the ministry, and no one at home has noticed either change. That is the most complete description of this posting that I can offer.'},
{n:248,t:'FR',h:'CYCLE FOUR HUNDRED AND TWELVE BEGINS',b:'The valley is unchanged. The subjects are unchanged. The crew is one promotion different. I have calibrated the lift, checked the lamps, opened a new page and written the date, and I find that after thirty years the beginning of a cycle is still the best hour of the year, and I have never told anybody that.'},
{n:249,t:'FR',h:'WHY WE HOVER AT FOUR HUNDRED LENGTHS',b:'Lower and the downdraft moves the grass, which moves the light, which moves them. Higher and we cannot resolve a subject against bark. Four hundred is the only altitude where we can see them and they cannot feel us. Everything this survey knows was learned from inside that narrow band and we found it by accident in the first decade.'},
{n:250,t:'FR',h:'THE THING I DID NOT RECORD',b:'In cycle three hundred and eighty a subject on the rail turned toward the observation glass and held still while I stood behind it, and I did not log the duration because I did not want a number attached to it. That is a professional failure. It is also the only minute of thirty years I have kept for myself.'},
{n:251,t:'FR',h:'REGARDING NEW EQUIPMENT',b:'A finer lift has been offered, capable of extraction from twice the altitude with no downdraft. The captain has declined it. Her stated reason is calibration cost. Her actual reason, given in the mess, is that if we can take them without them ever knowing we were there, we will, and she does not want to find out what that turns us into.'},
{n:252,t:'FR',h:'ON THE PHRASE STANDING ORDERS',b:'Standing orders are the ones nobody signed recently. Do not lift the wounded. Do not lift the gravid. Return within the hour. They were written by the first crew, who had no data and no experience and were entirely correct, and four centuries of better informed people have not improved a single line of them.'},
{n:253,t:'FR',h:'THE SEASON THE LOG WAS LOST',b:'Ninety pages missing from the second century, water damage, unrecoverable. What survives is the index, so we know their headings and not their contents. Every cataloguer since has read that index and invented the pages privately. Mine are better than the real ones almost certainly were, and I would give a great deal for the real ones.'},
{n:254,t:'FR',h:'A COMPLAINT ABOUT THE FORM',b:'The observation form has a field for anomalies and no field for the ordinary. In four hundred years this has quietly taught every cataloguer that only the strange is worth writing, which is how a survey ends up with six thousand files and no idea what a normal afternoon in that valley looks like. I have started a second, unofficial form.'},
{n:255,t:'FR',h:'ON BEING THE ONLY ONE AWAKE',b:'Third watch, the ship dark, the valley dark, the instruments idling. This is when the survey makes sense to me, and it makes no sense at all by daylight, and I have never been able to write down the difference in a way that would survive a reading by anybody who has not stood here.'},
{n:256,t:'FR',h:'CAPTAIN VESSEL ON THE FOUNDING ORDER',b:'She read it aloud at the anniversary as required, and afterward, privately, said that a generation is a unit of hope rather than time, and that ours has simply turned out to be a long one. I have written that down because it is the only reading of the order that lets a person keep working.'},
{n:257,t:'FR',h:'THE FIRST THING I WAS TAUGHT',b:'Log the surface before the creature. My predecessor was insistent about it. I thought it was pedantry for two years and then I understood: put the surface first and the colour reads as a description of the world. Put the creature first and it reads as a trick. The order of two words has held this survey honest for four centuries.'},
{n:258,t:'FR',h:'ORDERS TO SURVEY A SECOND VALLEY',b:'Received and acknowledged. A ridge over, similar climate, populated. We will begin next cycle. Every crew member has independently asked whether we are giving up on this one. We are not. I have said so four times and I have believed it three of them.'},
{n:259,t:'FR',h:'WHAT I WILL MISS',b:'Not the ship, not the work, not the ministry. The eleventh hour, when the light comes flat across the far ridge and every subject in the valley is briefly the same gold, all of them, at once, whether or not anybody is watching. It lasts about nine minutes. It is in no report because there is no field for it.'},
{n:260,t:'FR',h:'ENTRY WRITTEN AND NOT SENT',b:'I drafted a request this cycle asking the ministry to define success, so that we would know if we ever reached it. I read it back, and deleted it, because a survey that has to ask is a survey that already knows, and I would rather keep hovering than have that answered in writing by somebody who has never seen the valley.'},

/* ── SF ───────────────────────────────────────────────────────────────── */
{n:261,t:'SF',h:'SUBJECT 4511, THE SECOND VALLEY',b:'First lift from the new valley, a ridge over. Identical behaviour in every measurable respect, which disappointed a crew that had been quietly hoping for a difference. Matched the hold in eighty seconds. The only novelty is in the file header, where a new place name appears for the first time in four hundred years.'},
{n:262,t:'SF',h:'SUBJECT 4644, ON THE COLD RAIL',b:'Held during a heating fault at four degrees. Colour change slowed to a crawl and then stopped halfway, leaving it two colours at once, front and back, for eleven minutes. Nobody had seen a partial before. The technician wanted to continue the observation. The captain restored the heat instead and I have never agreed with an order more.'},
{n:263,t:'SF',h:'SUBJECT 4790, WHICH WAITED',b:'The only file in six thousand where the subject was already on the extraction point when the lift arrived. It had been there, by the recorder, for two hours. There is no explanation permitted by our understanding. There is a note in this file, in my hand, which reads: it is a fence post, they sit on it, stop this.'},
{n:264,t:'SF',h:'SUBJECT 4900, WITH YOUNG NEARBY',b:'Not lifted. Observed at range for four hours per standing orders and released from the schedule. The file consists entirely of a description of a small green animal doing nothing on a branch above three smaller ones. It is the longest observation we have and the only one where nobody touched anything.'},
{n:265,t:'SF',h:'SUBJECT 5000, THE ROUND NUMBER',b:'Marked in the log with an extra line and nothing else, because the crew agreed beforehand that a ceremony for the thousandth had been enough and a ceremony for every round number would make a religion of it. Lifted, held, matched in sixty seconds, returned. The extra line reads: five thousand, and still nobody has explained it.'},
{n:266,t:'SF',h:'SUBJECT 5122, ON A PRINTED PAGE',b:'Set on a page of the log during a transfer, it matched the page, including, at the resolution of the recorder, a suggestion of the lines of text. The technician insists this is an artefact. The recorder is very good. I have sealed the frame and filed it and I have not looked at it since the second viewing.'},
{n:267,t:'SF',h:'SUBJECT 5288, ABOARD ELEVEN HOURS',b:'A scheduling error, not a decision. Eleven hours in the hold, well past any standing order, during which it matched the wall, slept, ate what was offered, and matched the wall again. Returned in good condition. The whole crew was relieved and every one of us privately noted that it had not seemed to mind, and that this was worse.'},
{n:268,t:'SF',h:'SUBJECT 5400, THE OLD VALLEY',b:'Taken during a single return pass to the valley we abandoned in cycle three hundred and twelve. It matched in forty seconds, unremarkably. What is remarkable is that four of six crew found a reason to be in the hold, and that the file was written by three different hands, and that we have not been back since.'},
{n:269,t:'SF',h:'SUBJECT 5555, THE LOUDEST YET',b:'Hissed for the full eleven minutes without pause, matched the wall perfectly throughout, ate nothing, and bit a glove on the way out. Returned to its post where it hissed at the sky for a further hour by the recorder. My predecessor would have filed this as aggressive. I have filed it as entirely reasonable.'},
{n:270,t:'SF',h:'SUBJECT 5690, DURING THE GOLD HOUR',b:'Lifted at the eleventh hour when the flat light turns the whole valley one colour. It came aboard gold, and stayed gold in a grey hold for four minutes before it began to change, which is longer than any subject has ever held an outside colour. Renn thinks it was tired. I think it was reluctant.'},
{n:271,t:'SF',h:'SUBJECT 5801, NO CHANGE RECORDED',b:'The instrument failed and recorded nothing for the whole hold. The technician wrote up the observation from memory, in longhand, at length, and it is the best written file in the entire archive: the pauses, the order, the exact moment it settled. Instruments have never produced anything like it. We have not repeated the experiment.'},
{n:272,t:'SF',h:'SUBJECT 5944, JUVENILE',b:'Very young, quick, and hopeless at it. Overshot the wall colour twice, corrected, overshot again, and finally arrived somewhere approximately correct after four minutes of visible effort. Six adults watched a child practise. Nobody in the hold spoke. The file records four minutes and gives no indication of what those four minutes were like.'},
{n:273,t:'SF',h:'SUBJECT 6000, THE ANNIVERSARY LIFT',b:'Taken on the four hundredth anniversary and given the warm lamp again by unanimous and undocumented agreement. It matched the lamp. Renn asked whether we do this for the subject or for ourselves. Pell said both, which is the only correct answer anyone has given aboard this ship in my service.'},
{n:274,t:'SF',h:'SUBJECT 6108, ON METAL',b:'Placed on polished steel, which no surface in its valley resembles. It attempted the reflection, failed, attempted the underlying grey, succeeded, and then went back to attempting the reflection. Three cycles of trying and correcting. The file calls it iterative approximation. The mess calls it stubbornness and the mess is closer.'},
{n:275,t:'SF',h:'SUBJECT 6244, RELEASED EARLY',b:'The lamps flickered and it went entirely still in a way none of the crew had seen. The technician stopped the observation at ninety seconds and returned it without asking. She was reprimanded in writing by me, formally, and thanked by me, privately, in the same hour, and I would do both again.'},
{n:276,t:'SF',h:'SUBJECT 6390, THE LONGEST HOLD OF COLOUR',b:'Matched a sample of homeworld stone from the sealed cabinet, opened for the purpose under the captain\'s authority, and held that shade for nine minutes. For nine minutes there was a colour in this ship that has not existed at home for two hundred years, on the back of an animal that did not know. The cabinet has thirty nine samples left.'},
{n:277,t:'SF',h:'SUBJECT 6500, ROUTINE',b:'Nothing to report beyond the numbers, which is the report. Eighty seconds, correct match, calm return. I record these deliberately at intervals so that the archive cannot be read as a catalogue of wonders. Most of them are like this. That is what makes the rest of it strange rather than what makes it ordinary.'},
{n:278,t:'SF',h:'SUBJECT 6611, TWO VALLEYS',b:'Lifted in the new valley and, through an error in the return schedule, put down in the old one. It was recovered nine days later, alive, well fed, on a post, matching. It had not attempted to cross the ridge. The finding is that they are not attached to a valley. They are attached to wherever they currently are.'},
{n:279,t:'SF',h:'SUBJECT 6788, THE ONE PELL NAMED',b:'Against regulation, aloud, in front of the recorder. He called it Small. It matched in seventy seconds and was returned in four minutes and there is nothing else to say about the observation. The file is remembered entirely because of the name, which is how every crew member on this ship has always known it would work.'},
{n:280,t:'SF',h:'SUBJECT 6900, END OF SEASON AGAIN',b:'The last of the second valley\'s first season. Clean lift, clean hold, clean return. The pen is covered, the lamps are off, the log is closed for the interval. Six thousand nine hundred files and the finding has not moved since the first one: they become the surface, and we do not, and we keep coming back.'},

/* ── HW ───────────────────────────────────────────────────────────────── */
{n:281,t:'HW',h:'ON THE SECOND VALLEY DECISION',b:'Taken by the ministry, not the fleet, and announced without consultation. The stated reasoning is breadth of sample. The actual reasoning, according to two people who were in the room, is that a survey which has looked at one valley for four hundred years is easier to cancel than one that is expanding. I find that oddly comforting.'},
{n:282,t:'HW',h:'A CHILD\'S DESCRIPTION OF GREEN',b:'Collected for the archive from a school in the capital. She wrote: it is the colour of being outside when nothing is wrong. There is no sample attached to the entry and there does not need to be. Nine thousand professional descriptions in that archive and the archivists have started reading hers first.'},
{n:283,t:'HW',h:'THE INSTRUMENT THAT SEES IT ALL',b:'Built in the first century, still working, still correct. Point it at any surface and it reports the full spectrum exactly as it was. We have never once doubted the instrument. We simply cannot see what it tells us, and after four hundred years there is a serious body of opinion that says we should stop building it.'},
{n:284,t:'HW',h:'ON THE PEOPLE WHO LEFT',b:'Eleven thousand emigrated in the second century to a neighbouring world with a full spectrum. Their descendants write occasionally. The letters are careful and warm and always slightly wrong, in the way that a letter from somebody who is no longer short of something is wrong, and they cannot help it and neither can we.'},
{n:285,t:'HW',h:'WHY THERE IS NO MONUMENT',b:'Four hundred years and no memorial anywhere to the drought. Three have been commissioned and all three were abandoned during design, each time for the same reason given in slightly different words: a monument is for a thing that has finished. We are extremely good at not finishing and we have nothing to show for it.'},
{n:286,t:'HW',h:'THE SONG THEY STOPPED SINGING',b:'It listed the nine thousand shades by name, took four hours, and was performed once a year by anybody who wanted to. It was abandoned in the third century, not by decision, simply by attrition, when the last chorus that knew it whole came apart. Fragments survive. Nobody has assembled them and everybody knows somebody who intends to.'},
{n:287,t:'HW',h:'ON PHOTOGRAPHS FROM BEFORE',b:'They exist in enormous number and they are all correct and they show us nothing, because the eye that reads them is the eye that lost it. Looking at one is like being told a joke in a language you used to speak. The archive keeps them anyway, in perfect condition, at considerable expense, and nobody has ever proposed otherwise.'},
{n:288,t:'HW',h:'THE MINISTRY OF THE SURVEY',b:'Nine hundred staff, four buildings, and a mandate to support twelve vessels. It is the oldest continuous department in our government and it has never once produced a result. Its internal culture is famously gentle. People join at twenty and stay, and nobody in four centuries has been dismissed for failure, because there is no standard to fail against.'},
{n:289,t:'HW',h:'WHAT THE NEIGHBOURS OFFERED',b:'Twice, formally, a neighbouring world has offered to send their own scientists to help. Twice we have declined with thanks. The published reason is sovereignty over the survey. The real reason is that we would have to watch somebody with a full spectrum look at our problem, and no government has ever survived scheduling that.'},
{n:290,t:'HW',h:'ON THE COLOUR OF OUR FLAG',b:'It was two shades once. It is now one shade and a slightly different one shade, and the design office has quietly redrawn it four times to keep the two distinguishable. The fifth redraw was refused by the assembly on the grounds that at some point you are simply drawing a different flag. It has not been redrawn since.'},
{n:291,t:'HW',h:'THE PHYSICIANS ON NOTICING',b:'Long term studies find no measurable harm from the drought and a consistent, low, unfixable dissatisfaction in every cohort ever surveyed. It is not depression. It has no clinical name. The best description in the literature is from a nurse rather than a physician: everyone is fine, and everyone is slightly disappointed by something they cannot point at.'},
{n:292,t:'HW',h:'WHY WE KEEP THE ARCHIVE SEALED',b:'Because an opened sample fades within a season and there are nine thousand and no more coming. The rule is one public opening a year and the rule is obeyed, universally, by a people not otherwise famous for discipline. It is the single most successful piece of legislation in our history and nobody has ever needed to enforce it.'},
{n:293,t:'HW',h:'A SPEECH FROM THE FIRST CENTURY',b:'Delivered when the fleet launched, and quoted since by everybody who wants funding. It promises that we will not become a people who forget what we are missing. Four hundred years on we have not forgotten. We have done something the speaker did not consider, which is get used to it, and there is no line in the speech about that.'},
{n:294,t:'HW',h:'ON NAMING CHILDREN AFTER SHADES',b:'It came back into fashion in the third century and never left. There are more people named for colours now than at any point before the drought, and none of them have seen the thing they are named for. The registrars report the practice as stable. I think it is the most hopeful statistic we produce.'},
{n:295,t:'HW',h:'THE ARGUMENT THAT IT IS NOT REAL',b:'Advanced periodically by serious people: that the spectrum is intact and the change is in us, in our seeing, and that we have spent four hundred years sending ships to look for something we are carrying. It cannot be disproved. The instrument disagrees, and the instrument is not an eye, and that is exactly the gap the argument lives in.'},
{n:296,t:'HW',h:'MY FATHER WOULD NOT DISCUSS IT',b:'He grew up during the worst decade of losses and he treated the subject the way other families treat a death. Not forbidden. Simply not raised. I learned the whole history from school and the archive and never once from him, and when he died I found nine sealed samples in his effects, bought over forty years, never opened.'},
{n:297,t:'HW',h:'ON THE FLEET AS EMPLOYMENT',b:'Twelve vessels, seventy two crew, nine hundred ministry staff, and an industry of suppliers. It is a small economy built around a question. If the answer arrived tomorrow every one of those people would be delighted and unemployed, and no plan exists for the second part, and pointing this out in public is considered poor taste.'},
{n:298,t:'HW',h:'THE PLACE WHERE IT IS WORST',b:'The northern coast, where the rock was famously red. It is now a colour the locals describe with a shrug. Tourism there increased for two centuries and has now stopped entirely. The towns are fine. The people are fine. There is simply nothing to come for, and they say so themselves, without much bitterness, which is the hard part.'},
{n:299,t:'HW',h:'WHAT SURVEY CREWS ARE NOT TOLD',b:'That the ministry stopped expecting a result in the second century, and that every mandate renewed since has been renewed on other grounds. Crews find out eventually, usually around year nine, usually from an older cataloguer. Almost none of them resign. That fact is in the ministry\'s own internal literature and it is not explained there either.'},
{n:300,t:'HW',h:'THE THREE HUNDREDTH PAGE',b:'The archivists have asked that this number be marked. I have marked it. Three hundred pages of a survey that has not succeeded, kept by people who mostly did not know each other, about a small green animal that has never asked to be described. Read them in any order. That is the only instruction that has ever mattered.'},

/* ── IW ───────────────────────────────────────────────────────────────── */
{n:301,t:'IW',h:'ON THE NEW LIGHTS OVER THE RIDGE',b:'They have started hovering a ridge over, where our cousins are, and the news came back with a traveller. The old ones received it calmly. They said the lights were always going to run out of us eventually and go looking for more, and that our cousins have their own old ones, and will manage.'},
{n:302,t:'IW',h:'WHAT TO DO IF THE LIGHT WOBBLES',b:'Nothing. A wobbling light is looking at the valley and not at you, and every young creature who bolts at a wobble teaches it that we bolt. The old ones say the hardest lesson we teach is the one where the correct action is to keep eating, and it is the lesson that saves the most of us.'},
{n:303,t:'IW',h:'THE COUSINS SENT A MESSAGE',b:'Word came over the ridge asking what we do. The old ones sent back four words and nothing else, which caused an argument here that lasted a season, half of us feeling we had been unhelpful. The old ones said anything longer would have been advice, and advice about the lights is worth less than an afternoon of practice.'},
{n:304,t:'IW',h:'ON THE ONE WHO WENT UP TWICE',b:'It happens rarely and it happened to him. The old ones say a creature taken twice should be listened to and not pitied. He said the second room was the same as the first, that they had not learned anything in the meantime, and that he found that sad. He was seven seasons old and nobody argued with him.'},
{n:305,t:'IW',h:'WHY THE ADVICE IS ALWAYS SHORT',b:'Because you will be recalling it while frightened, and a frightened creature can hold four words. Be where you are. Do not look up. Go limp, be dull. Every long piece of teaching our kind has produced was cut down within a generation by somebody who had actually been under a light.'},
{n:306,t:'IW',h:'THE OLD ONES ON GRATITUDE',b:'They say we should be grateful the lights are gentle, and then they say we should not be grateful to anything that takes you without asking, and they hold both at once and teach both, and the young find this maddening until the first time they are under one, and then they do not find it maddening at all.'},
{n:307,t:'IW',h:'A MEMORY BROUGHT BACK',b:'The instruction is to remember one thing about the room. She remembered a small tired creature holding a stick and making marks, and looking at her the whole time, and not once looking away. The old ones added it to the account under the heading of what they do up there, which now has nine entries in four hundred years.'},
{n:308,t:'IW',h:'ON THE POST BEING WARM AFTERWARD',b:'Everyone sits in it and the old ones have given up saying otherwise. What they say now is: sit in it, and then move, because a warm post is the one place the light already knows how to find. This is the only piece of advice in the whole account that was changed after being wrong.'},
{n:309,t:'IW',h:'HOW THE ACCOUNT IS KEPT',b:'Nobody writes anything. It is nine entries, four instructions and a handful of stories, held in the heads of whoever is oldest and taught to whoever is nearest. It has survived four hundred years. It has also certainly changed in that time, and the old ones know it, and say that a thing which cannot change cannot last.'},
{n:310,t:'IW',h:'THE ARGUMENT ABOUT SITTING STILL',b:'Some say the lights come more often now because we sit still when they arrive and they have learned we are easy. Others say we have always sat still and the lights have always come. The old ones do not adjudicate. They point out that both sides have been arguing this for longer than any light has hovered.'},
{n:311,t:'IW',h:'WHAT IS NEVER TAUGHT TO THE YOUNG',b:'That some do not come back. It is four in four hundred years, all of them very old, all of them almost certainly from age rather than harm. The old ones carry those four privately and the young learn about them at their own first grey hair, from somebody who has just learned it themselves.'},
{n:312,t:'IW',h:'ON BEING THE COLOUR OF NOTHING',b:'There is a trick the old ones can do and cannot explain, where a creature holds no colour at all and simply reads as absence. It takes decades. Nobody has ever done it under a light, because by the time you can do it you are too old to care, and the old ones find this extremely funny.'},
{n:313,t:'IW',h:'THE STORY THE COUSINS TELL',b:'Over the ridge they say the lights are looking for a lost one of their own, and that every creature they lift is checked and set down again with disappointment. It is a better story than ours. The old ones here have declined to adopt it, on the grounds that a story you prefer is the one to be most careful with.'},
{n:314,t:'IW',h:'ADVICE CONCERNING WATER',b:'Do not be on water when the pressure comes. The light does not manage water and neither will you, and the old ones say a creature lifted wet arrives cold and is returned cold and remembers nothing useful. There is a season of accounts from long ago in which the whole room apparently smelled of pond.'},
{n:315,t:'IW',h:'WHAT THE VERY OLD SAY LAST',b:'Asked, at the end, what they would pass on, most of them say some version of the same thing: it was a good valley and I was mostly the right colour. The old ones treat this as a formula. Those who have sat with somebody at the end say it is not a formula and that they mean it exactly.'},
{n:316,t:'IW',h:'ON TEACHING THE COUSINS',b:'A delegation went over the ridge to share the account and came back having mostly listened. Our cousins had worked out three of the four instructions independently, in different words, and had one we did not: when the light comes, look at the creature nearest you, not at the sky. Nobody here has explained why that works and everybody has adopted it.'},
{n:317,t:'IW',h:'THE HOUR WE DO NOT SPEAK OF',b:'Once, a long time ago, a light came down and did not lift anything, and stayed low over the valley through a whole night, and left at dawn. Nothing happened. The old ones include it in the account with no interpretation attached, which is the only entry treated that way, and the young always ask, and are always told there is no more.'},
{n:318,t:'IW',h:'WHY THE STORIES HAVE NO ENDINGS',b:'Every tale in the account stops where the creature is put back. Nobody follows them home, nobody says what became of them. The old ones do this deliberately. A story with an ending is about the ending. Ours are all about the middle, where you are held up in a light and have to decide what colour to be.'},
{n:319,t:'IW',h:'THE FOUR WORDS, AGAIN',b:'Be where you are. It is taught first, repeated at every stage, and said last. Visiting cousins find it thin. Our old ones do not defend it. They wait, because every creature who has been under a light comes down understanding it, and no explanation has ever worked as well as four hundred lengths of empty air.'},
{n:320,t:'IW',h:'WHAT WE WOULD TELL THEM IF WE COULD',b:'That it is not kept anywhere. Not in the skin, not in the eye, not in anything they could lift and carry home. It is the branch, and the hour, and having no particular wish to be elsewhere. The old ones say they will never accept that, because they have come too far for an answer that small, and the old ones are probably right.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
