/* THE ABDUCTION FILES — bank 12 (pages 801 to 880).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES. */
;(function () {
  var P = [

/* ── FR ───────────────────────────────────────────────────────────────────── */
{n:801,t:'FR',h:'THE COLUMN I RAN OUT OF HABIT',b:'Tidying the extraction ledger for the station brief, I ran the returns against the liftings expecting a shortfall somewhere in the early centuries. Fifteen thousand and some taken across four hundred and thirty cycles. Fifteen thousand and some put back on the exact point of origin, including the few that died aboard of age, because procedure covers that and we followed it. I have checked the arithmetic three times.'},
{n:802,t:'FR',h:'SOMEBODY COUNTED THIS BEFORE',b:'The total is not new. Somebody ran it at four hundred and eleven cycles, six thousand and four lifted and six thousand and four returned, offered by an ensign as an achievement and entered in this log as a finding by a predecessor of mine. Nobody has run it since. An archive this long holds that number exactly twice, and I am the second person to write it down.'},
{n:803,t:'FR',h:'WHY THAT NUMBER IS NOT A RESULT',b:'A perfect return rate measures our compliance and tells me nothing whatever about that valley. It is a fact about paperwork. I have put it in the brief anyway, in the column where results go, and I expect the board to strike it out, and I expect to argue when they do, and I expect to lose. That is the honest position.'},
{n:804,t:'FR',h:'THE QUESTION RENN ASKED',b:'Renn wanted to know whether a pattern that regular, fifteen thousand liftings and fifteen thousand returns spread across more generations than anything down there lives to count, is even the sort of thing a short life could notice. I have no instrument that answers it and I am not building one out of adjectives. It is in the file because it was asked aloud, not because it can be answered.'},
{n:805,t:'FR',h:'THE STANDING STATION IS APPROVED',b:'Passed with less argument than a kettle requisition. A permanent post on the upper ridge, twelve people, no lift array, rotation every two years, sited well clear of the ground where the stone is, because the order to hold still there stands. This fleet has spent its whole existence arriving and leaving. We have now been given permission to stay. I read the approval twice looking for the clause that takes it back.'},
{n:806,t:'FR',h:'WHAT A STANDING POST IS FOR',b:'Twelve people living on a ridge, which this fleet has never done. Weather at ground level, continuous. Individual files that do not stop when a ship leaves orbit. Somebody present in the season the young hatch instead of a recorder that ran out of power in the eighth week. None of that is the mission. All of it is work I would have paid to do in my first year and could not.'},
{n:807,t:'FR',h:'ON BEING A FIXED OBJECT',b:'A hut on a ridge does not go away between visits. Animals born after next spring will grow up with it in their landscape the way they grow up with the rock face and the dead tree. What they make of it is not something I have any way to measure, and I will not fill that gap with a sentence I would enjoy writing.'},
{n:808,t:'FR',h:'A YEAR OF THE OPEN CABINET',b:'Thirty six sealed colours at eye height in a hold that still smells of a pond from cycle two hundred and nine. Nothing has been used. What people do instead is walk past slowly. Two engineers eat down there. Somebody dusts the shelf and it was never assigned to anyone, and I have not asked who, because I would rather it stayed unassigned.'},
{n:809,t:'FR',h:'THE PROPOSAL TO OPEN ONE',b:'A technician eight months aboard stood up in open meeting and asked that we unseal a single sample, carry it down, and set the light beside the four lines we scratched. She knew about the order to leave that ground untouched and asked for it to be lifted for one night. She had costed the descent. She was not being sentimental, and I record that because the room treated her as though she were.'},
{n:810,t:'FR',h:'WHAT I SAID TO THE TECHNICIAN',b:'She had asked to unseal one of the colour samples and take it down to the valley, and what I gave her was the procedure. Irreplaceable, thirty six left, no method of manufacture surviving. She agreed with all of it and asked what they are being saved for, given that all thirty six will still be sealed when the last of us is dead. I had no answer. The vote went eleven to three against.'},
{n:811,t:'FR',h:'ON BEING ONE OF THE ELEVEN',b:'I have written before that a crew which agrees instantly has felt something and dressed it as judgement. I then voted with ten other people inside forty seconds and called it stewardship. The difference between us and a locked box is that a locked box does not hold meetings about itself. I am leaving my name in the record next to the ten.'},
{n:812,t:'FR',h:'THE STONE IN MY TWELFTH YEAR',b:'Photographed at the same hour and the same angle every season since it appeared. Edges softening. A lichen on the north face. The four lines underneath shallower than the day we cut them, because rock does that. Not lifted, not turned, not measured beyond the camera. The file for this season is one image, one date, and the line the form requires, which is no change observed.'},
{n:813,t:'FR',h:'THE CONSERVATION REQUEST',b:'Came up from the archive at home: lift the stone, cast it, return the cast to the same spot before weather takes the original. Written by people who love objects and have never stood on that ground. The captain refused it in nine words without consulting me. I would have used ninety and arrived in exactly the same place.'},
{n:814,t:'FR',h:'RENN HAS FILED FOR THE PORT',b:'One street from where Captain Vessel keeps a room over a repair yard and complains about the noise. Renn says the kettle finally beat him. What he actually said, at the end of a shift and not to my face, was that he did not want to be aboard on the day we finally do something clever. I have not decided whether that goes in the record as a joke.'},
{n:815,t:'FR',h:'WHAT RENN LEAVES BEHIND',b:'The kettle stays. Eleven years of Renn telling this crew that it descales badly and the crew keeping it out of spite, and his last act on the last morning was to descale it and say nothing to anybody. There is already an argument about whether the incoming shift may replace it. I have ruled this is not a matter for the log and then logged it.'},
{n:816,t:'FR',h:'PELL WRITES FROM THE THIRD',b:'Lieutenant Pell writes from the third survey, two cycles in transit and mostly weather. Their valley has no stone place and no mark, and she will not cut one, because a thing you copy is decoration. At the end she asked for my return figures for her own brief, which is how I learned the number is circulating. I did not send it to anyone. Somebody did.'},
{n:817,t:'FR',h:'EXTRACTIONS THIS YEAR: ZERO',b:'Empty column, first time since the founding order. No policy, no ban, no directive from any authority above or below me. Twelve months of a crew with a working lift array declining to use it, one occasion at a time, each with its own small reason. I have entered the figure and left the reason box blank because no single sentence fits it.'},
{n:818,t:'FR',h:'IS ZERO A FINDING',b:'A survey that stops surveying has answered nothing, and I can hear a century of predecessors saying so in the margins I have read for twelve years. Against that: four hundred years of liftings produced one sentence and we already have the sentence. I put both positions in the same paragraph of the brief and let the board weigh them. That is the actual state of the evidence.'},
{n:819,t:'FR',h:'WHO KEEPS THE POST LOG',b:'The standing post needs its own cataloguer and I have been asked for three names. The one everybody expects is wrong for it because she writes well, and that log will need somebody who gives a bird and a stone the same number of words. I have started leaving the difficult entries out on the shelf where the applicants will find them. It is not a fair test. It is the only one I have.'},
{n:820,t:'FR',h:'TWELFTH YEAR, CLOSING NOTE',b:'No extractions. The returns totalled for only the second time in the archive. Thirty six samples on an open shelf, one stone weathering on four lines, a ground post approved, a ship being built that cannot lift anything, and one technician who asked what the colours are for. The finding is unchanged. Twelve years, and the column that has never changed is still the shortest one in the brief.'},

/* ── SF ───────────────────────────────────────────────────────────────────── */
{n:821,t:'SF',h:'SUBJECT 17382',b:'Adult female, cool slope, four days, observed and returned. Nothing in the behaviour column. She ate, she sat in the eleventh hour light, she was carried down and set on the rock she was taken from. I have written her up at the same length as the animals the crew talks about, because the form does not know which ones those are.'},
{n:822,t:'SF',h:'ON FILING AN ANIMAL THAT DID NOTHING',b:'It takes the same twenty minutes as filing one that did something, and nobody aboard will read it, and it is the only reason the interesting entries can be trusted. An archive that keeps only its exceptions is a story. Fourteen thousand eight hundred and forty four files in this register end in observed and returned, and most of them describe an animal that ate and sat.'},
{n:823,t:'SF',h:'SUBJECT 17330, NOT ON THE ROCK',b:'The very old female, the one carried under three numbers across two centuries, was absent from the warm rock at every flat hour of this season. Forty one visits. No body on the slope and none below it. Ridge count put her past the ceiling of the method eleven years ago. The finding column says absent.'},
{n:824,t:'SF',h:'ON NOT WRITING THE OTHER WORD',b:'I know what absent means for an animal of that age and so does everybody who will read this. The form offers me a shorter word and I have left it alone, because we did not see it and this is a record of what we saw. She is in the index of the unaccounted with the rest.'},
{n:825,t:'SF',h:'WHAT HER FILE CONTAINS',b:'Two hundred and eleven entries by six cataloguers, three of whom believed they had found her first. A warm rock. A preference for the flat hour. Nothing the founding order would accept as data, at the length of a small book. It is the longest single file in this archive and it is about an animal that sat still.'},
{n:826,t:'SF',h:'SUBJECT 17389',b:'Juvenile male, warm slope, four days, returned. Filed in the same week the longest file we keep went into the unaccounted index, which is the sort of coincidence a cataloguer notices and is trained to leave out of the entry. I have left it in the entry. Nothing follows from it. The two files sit four pages apart in the register.'},
{n:827,t:'SF',h:'THE LEDGER FROM THE SUBJECT SIDE',b:'Every file in this archive, counted by finding column. Observed and returned: fourteen thousand eight hundred and forty four. Died in transit, almost all of them in the first two centuries: one hundred and six. Already dying when lifted: thirty one. Absent, open, unaccounted: nineteen. That is the entire ledger. I counted it twice and the second count matched.'},
{n:828,t:'SF',h:'ON THE COLUMNS THAT ARE NOT RETURNED',b:'The hundred and six who died in transit come from the cold holds and the crude array, and every one of those files was written by somebody who was not obliged to write it. Thirty one more were already failing when we lifted them. Nineteen we lost track of and left open. There is no column anywhere in this register for taken and kept.'},
{n:829,t:'SF',h:'SUBJECT 17404, NOT LIFTED',b:'Gravid female, warm slope, meeting the criteria for a routine four day hold in every respect. The technician on the ground declined and logged his reason, which is that she was two weeks from laying and the hold light is wrong for that. Nobody above him queried it. A century ago the form had no field for a refusal.'},
{n:830,t:'SF',h:'THE FIELD FOR A REFUSAL',b:'Added by my predecessor in the last season he worked, quietly, without a directive, in the way most of the good changes to this form arrived. It has been used forty times since. Forty animals that met every criterion on the sheet and stayed in the valley because somebody standing beside them wrote one sentence in a box that did not exist a century ago.'},
{n:831,t:'SF',h:'SUBJECT 17417',b:'Second year, born on the mark ground, has crossed the four scratched lines thirty seven times by my count. Never at a different pace. Never with a pause. The older individuals in this archive stopped at that rock and looked at it. This one was born beside it and treats it as ground, which is what it is.'},
{n:832,t:'SF',h:'THE COUNT OF THE UNBOTHERED',b:'Nine individuals whose entire recorded lives have happened within sight of the mark, none of them ever observed stopping there. Ridge counts from first year to old. The crew reads this file quickly and asks whether nine is too small a number to mean anything, which it is. I have moved it to the first page of the season summary and it stays there.'},
{n:833,t:'SF',h:'SUBJECT 17423',b:'Male, ridge count middle, cool slope, four days, returned, no behaviour of note. His entry runs nine lines. So does the entry for the individual recorded near the stone on six evenings, and so does the entry for the female three cataloguers filed separately. The form gives no extra room to the interesting ones and in eleven years I have never been tempted to change that.'},
{n:834,t:'SF',h:'NINETEEN IN THE UNACCOUNTED INDEX',b:'Nine names when I first ruled the page and nineteen now, growing because I have never closed one. Animals marked, then not found, then not found again. It carries no findings column and no purpose the manual recognises. The oldest of them was last seen before I took this desk. I keep expecting a directive telling me to tidy it away.'},
{n:835,t:'SF',h:'ON AN INDEX WITH NO FINDINGS',b:'Every other page in this archive ends in a column stating what we concluded. That one ends in a name, a date, and a blank. I have come to think it is the most accurate thing we keep, because most of what four centuries in this valley has produced is a name, a date and no conclusion.'},
{n:836,t:'SF',h:'SUBJECT 17440',b:'Female, unremarkable, warm slope, four days, observed and returned. She fed twice, kept to one corner of the hold, and was set back on the slope at the fourth morning. Nothing else is recorded because nothing else happened. The technician who carried her down logged the hour and nothing more. Her file will be read by nobody and is kept at the same weight as the rest.'},
{n:837,t:'SF',h:'SUBJECT 17455, NOT LIFTED',b:'Very old male, ridge count near the ceiling of the method, sound, feeding well, entirely eligible. Declined on the ground by two technicians jointly, reason given as age. The hold is four days and there are animals for whom four days is a measurable share of what remains. That reasoning appears nowhere in the founding order.'},
{n:838,t:'SF',h:'WHAT THE FORM NOW ASKS FOR',b:'A reason to lift, in words, before the array is armed. It went into the sheet the year the count dropped to one animal a year. People will act on a bad reason and will not write one down in their own hand, which is the argument the officer who drafted the field made, in those words, and then declined to have minuted. That column has not risen since.'},
{n:839,t:'SF',h:'SUBJECT 17468',b:'Adult, cool slope, four days, observed and returned. Ate on the second day, sat on the third, was carried down at the eleventh hour on the fourth. I could have written this from the form alone and I did not, I watched the feed, because the entries written from the form alone are the ones that read as though nobody was there.'},
{n:840,t:'SF',h:'THE DESIGNATIONS AND THE COUNT',b:'Designations run to seventeen thousand four hundred and sixty eight and the number of animals is lower than that, because four centuries of cataloguers retired numbers, skipped blocks and started fresh runs after every reorganisation. Fifteen thousand files, one animal each, a slope, a ridge count, a number of days and a finding. My predecessors put totals at the front. I have taken them out.'},

/* ── HW ───────────────────────────────────────────────────────────────────── */
{n:841,t:'HW',h:'THE RETURN RATE, PUBLISHED',b:'A single line in this year\'s estimates, and the only line anybody discussed: of seventeen thousand individuals lifted, the number not put back is zero. One recorded error of forty paces is footnoted. The archive has held that figure for centuries without ever printing it alone on a page. A member read it twice and then asked whether it was a boast or a confession.'},
{n:842,t:'HW',h:'ON BEING A PEOPLE WHO GIVE THINGS BACK',b:'We have described ourselves for four hundred years as searchers. The record says something duller. We went somewhere, lifted an animal, wrote down what it was, and set it down again where we got it, fifteen thousand times, and came home with nothing. I cannot tell whether that is the most decent thing this world has done or the most absurd, and neither can anybody I have asked.'},
{n:843,t:'HW',h:'NO WORD FOR WHAT WE DID',b:'A committee sat for a week trying to find one and gave up. Borrowing is wrong because we never asked. Study is wrong because the finding was always the same. Visiting is close and much too warm. What we did has no name in our language. The minutes record four hours spent on the word errand and a note that it was rejected as comic.'},
{n:844,t:'HW',h:'THE DISSENTER ON THE RETURN RATE',b:'She wrote that a thief who returns everything is still a thief, and that the count proves nothing except a very long habit of tidiness. Then she wrote, in the same essay, that she would rather belong to a tidy people than a hungry one. Her opponents quoted the second half all season. She has complained about that and she has not withdrawn it.'},
{n:845,t:'HW',h:'THE STANDING STATION, APPROPRIATED',b:'The money went through this month without debate, which is the part worth recording. Staffed in rotation, resupplied on a schedule, and no closing date entered anywhere on the form. For four centuries every sum this world approved was an expedition, a thing with an end built into its wording. This one passed in the session between a grain tariff and a bridge survey, and nothing was said.'},
{n:846,t:'HW',h:'ON A BUDGET LINE WITH NO END',b:'The clerks had to invent a category. There was nothing on the schedule for an expense that simply continues, so it went under maintenance, alongside roof repairs and the archive humidity plant. A colleague finds that undignified and has said so in writing. I think being filed beside the thing that keeps the paper dry is exactly right and I intend to leave it there.'},
{n:847,t:'HW',h:'WHAT THE STATION IS FOR',b:'Asked in session and answered badly, on purpose. To be there. To keep the record unbroken. To be available if anything changes. The member who asked said that was three ways of saying nothing, and then voted for it, and told a reporter afterwards that he had finally run out of reasons to say later.'},
{n:848,t:'HW',h:'THE GIRL, TWENTY ONE, STILL WORKING',b:'The one who watched a feed at eleven and wrote four lines about it is twenty one and still cataloguing margins. She has turned down the ministry three times, a lecture series, and a prize she was told it would be rude to refuse. Somebody asked whether she understood what she represents to people. She said she understood perfectly, that it was not hers to manage, and asked him to step off the trolley track.'},
{n:849,t:'HW',h:'ON REFUSING TO BE A SYMBOL',b:'The girl with the four lines cannot do it cleanly and I have stopped expecting her to. Every refusal she makes is reported as a further example of the quality people admire, which is the trap. The only exit would be to accept something, and she will not, so it continues. I have watched this for ten years and her method appears to be to keep working until the room loses interest.'},
{n:850,t:'HW',h:'WHAT SHE WRITES NOW',b:'The four line reports stopped two years ago. She sends nine and ten line accounts to the archive these days, on feeds nobody assigned her, and they are longer and better and not one outlet has reprinted any of them. Asked about it at a public event, she said the four lines were never a form, only what she had to say at eleven. The margin note on her latest reads: still busy.'},
{n:851,t:'HW',h:'A BEIGE WORLD, NOW ON THE SYLLABUS',b:'Taught to fourteen year olds as an examined set text, with questions at the end. Discuss whether a good vocabulary is compensation. The dissenter has seen the questions and says the exercise is built to be answered no and then reassured. She is right. I have read the teaching notes and they do exactly that, gently, in the final paragraph.'},
{n:852,t:'HW',h:'THE DISSENTER, ON BEING TAUGHT',b:'Her position is that the fastest way to kill an argument is to examine children on it, and that in twenty years nobody will remember she meant it as an accusation. She may be right. Of the four students I spoke to at the exhibition, three could quote the phrase and none could name her. I told her this. She said good, and went for her coat, and stood in the doorway a while first.'},
{n:853,t:'HW',h:'THE OTHER SEALED SAMPLES',b:'Ten remain in the ministry vault, the eleventh having been opened publicly last year. Proposals to open a second arrived within the month. There are nine of them now and all nine are better argued than the first one was. The vault clerk has begun keeping a list of who asks and how often, which nobody instructed her to do and which nobody has asked her to stop.'},
{n:854,t:'HW',h:'THE CASE FOR OPENING MORE',b:'That a sealed colour helps nobody, that eleven thousand people came out of that room with words they did not have going in, and that the vault is a superstition dressed as custody. It is a strong case. The strongest version of it was written by a woman who has never asked to be in the room herself and who says, when asked, that she does not want to be.'},
{n:855,t:'HW',h:'THE CASE FOR LEAVING THEM SHUT',b:'That the vault holds ten and there is no making more of them, that once seen a thing cannot be unseen, and that a people who have waited four hundred years can manage another hundred. That argument used to be made in a tone of grief. This season it is being made in a tone of thrift, which is new, and which I do not entirely like.'},
{n:856,t:'HW',h:'WHAT THE VAULT CLERK SAID',b:'Asked by a committee whether the seals were degrading, she said no. Then she said she had opened the register that morning and found the last four requests were all from people under thirty, and that this was not evidence of anything, and that she thought the committee should know. She was thanked and not asked to elaborate.'},
{n:857,t:'HW',h:'THE FLEET OPENED ITS CABINET FIRST',b:'Thirty six sealed samples, out of the locked case and onto a shelf in the hold, where any of the crew walks past them. When the notice reached us here it was reported as recklessness by two outlets and as courage by the rest. What it did was end the argument that a cabinet has to stay shut to be respected, and the ministry has been quietly losing that argument since.'},
{n:858,t:'HW',h:'PEOPLE BORN AFTER THE VIGIL',b:'There is a generation now that has never known a year in which the fleet was described coldly. To them it is not an unfinished search. It is a thing this world does, like the weather stations and the humidity plant in the archive basement. A student told me she had assumed the ships were always out there and was surprised to learn there had been a first one.'},
{n:859,t:'HW',h:'A CONVERSATION WITH A YOUNG CLERK',b:'She asked me what the urgency had felt like, the way you would ask about a war. I said it felt like being late for something every day of your life. She said that sounded exhausting and that she was glad it was over. I said it is not over, the drought is still running. She said yes, but the hurry is.'},
{n:860,t:'HW',h:'ON ENVYING THE ONES WHO CAME AFTER',b:'My generation carried the search as a debt. Theirs carries it as an address, a place where this world keeps a light on. I was trained to call that a loss of purpose and I have stopped, because the ships still go, the record is still kept, and nobody has missed a rotation. Whatever they have instead of urgency, it is not costing us anything yet.'},

/* ── IW ───────────────────────────────────────────────────────────────────── */
{n:861,t:'IW',h:'THE WINTER SHE WAITED THROUGH',b:'It was a hard one, and she is old, and twice in it her family thought she had gone. She had not. She ate what was brought to her, slept in the warm crack under the leaning stone, and said nothing at all about the question she was holding. In the first soft week she sent word that she was ready, and the old ones came the same day.'},
{n:862,t:'IW',h:'WHY SHE ASKED FOR THE WINTER',b:'She gave a reason once, to one person, and it has been kept in the words she used. She said she had carried it so long that she did not know who she would be after she put it down, and she would rather find that out in warm weather. Nothing has been attached to it. The old ones do not attach things to plain speech any more.'},
{n:863,t:'IW',h:'THE OTHER ONE WHO HEARD IT',b:'Two were there when the old chameleon asked it, sixty years back. The second was alive when she asked for her winter and did not last it, dying in his sleep in the cold months, having said all his life that he would take the question with him. He did. That left one holder, and the account records the fact and nothing about the fact.'},
{n:864,t:'IW',h:'HOW THE QUESTION WAS GIVEN',b:'At the flat hour, in her own place, with six present and no more, because she said a crowd would turn the question into a saying. She spoke it once. One of the old ones set it down as she gave it and said it back to her, and she corrected one word, and then said that was right. Then she asked for water and they talked about the weather.'},
{n:865,t:'IW',h:'THE QUESTION, WRITTEN IN FULL',b:'Here it is, as she gave it, in her words and not tidied by anybody. Why do they always put us back? That is the whole of it. Sixty years held by two, one winter of waiting, six present, and it comes to seven words. The account carries them exactly and has added nothing underneath, and the old ones say nothing will ever be added.'},
{n:866,t:'IW',h:'WHAT MAKES IT HARD',b:'Everybody this valley has ever lost to the light has been set down again. The account holds no entry of a creature carried up and kept. Grandmothers, brothers, the ones taken twice, all returned to the same ground, mostly upright and usually confused. Our instructions are built on a danger. Nothing in four hundred years has done the thing the danger promises.'},
{n:867,t:'IW',h:'IT WAS READ ALOUD ONCE',b:'On the evening after the question was given, at the flat rock, to everybody who came, which was everybody. It was said once through, slowly, and not repeated, and nothing was explained before it or after it. Then the one who had read it sat down. There was no more of it that night, and there has been no second reading and there will not be.'},
{n:868,t:'IW',h:'WHAT THE VALLEY DID THAT NIGHT',b:'Went home. That is the honest entry. No argument started, nobody stood up to answer it, and the ones who had expected to feel something reported feeling mostly tired. Nothing was said by the old ones at the flat rock and nothing was written down for nine days. On the ninth the arguing started, and it has not stopped since.'},
{n:869,t:'IW',h:'IT IS CARRIED, NOT ANSWERED',b:'Ruled within the season, and the ruling is far shorter than the argument that made it. The account holds the question and does not hold an answer. No old one is to give one. None is to be added later by anybody who wakes up feeling certain. It is to be carried the way she carried it, which was quietly and for a very long time.'},
{n:870,t:'IW',h:'WHY NO ANSWER IS ALLOWED',b:'Both of the answers available do damage. Say they mean us no harm and the instructions become furniture and the young walk uphill. Say they will harm us in the end and we have invented a thing nobody has seen, which this account has never once done. So the question sits there with nothing written under it. Nobody likes it and it stays.'},
{n:871,t:'IW',h:'THE FOUR STAND WHERE THEY STOOD',b:'Not one word of them altered. Do not go up. Do not follow the light. Do not answer. Come back down the way you went up. They now sit directly beside a question that notices nobody has been hurt, and the old ones have left the two together on purpose and decline to explain how they fit, because they do not fit.'},
{n:872,t:'IW',h:'WHAT THE YOUNG SAY IT MEANS',b:'Their reading is simple and they are not stupid for holding it. If we are always set down again, the thing in the sky is not a danger, and four instructions built on danger are four instructions built on nothing. They said it politely at the ridge meeting and less politely afterwards. They have been heard in full twice and are not finished.'},
{n:873,t:'IW',h:'WHAT THE OLD ONES SAID BACK',b:'One line, given once and not expanded since. A thing that has not hurt you yet is not the same as a thing that will not. The young called it a trick of words. The old ones agreed that it was words, and said so was the question, and that neither of them settles what happens the next time the light comes down on the field.'},
{n:874,t:'IW',h:'THE ONES WHO WANT TO GO UP',b:'There are some now, which there were not before. Young, three that anybody knows of, who say plainly that they would stand in the light to find out. Nobody has forbidden them, because the first instruction already does that, and nobody has argued them out of it either. Two families have moved further down the slope. That is all that has happened.'},
{n:875,t:'IW',h:'STILL NO SECOND STONE',b:'Raised again this season, harder than before, and refused again. The case was that a question like that deserves one. The answer was that the question is ours and a stone is theirs to read however they read it, and we cannot put a question on a rock without inventing somebody to receive it. Our first stone is still up there, weathering.'},
{n:876,t:'IW',h:'THE COUSINS WERE TOLD AT ONCE',b:'Carried over the ridge inside the month by the ones who go between, which is the opposite of what was done with the stone and was done that way to avoid another quarrel. Their old ones received it standing, heard it once, asked for it twice more, and then said they would need a winter to sit with it. They took six days.'},
{n:877,t:'IW',h:'WHAT THE COUSINS DID WITH IT',b:'They answered it. Their account holds the question with an answer written underneath, agreed in one evening, and ours will not carry that answer even as a record of theirs, which is the first line either valley has ever refused from the other. Our old ones call it a mistake in the careful way that lasts. The ones who go between have been asked not to carry it in either direction.'},
{n:878,t:'IW',h:'SHE DIED IN THE SECOND WARM MONTH',b:'Eleven days after the reading. In her own place, with her family, in the middle of the afternoon, which her granddaughter says she would have found insufficiently serious. She was not ill at the end so much as finished. Her death is one line in the account, because one line is what the account gives deaths, and she had asked for nothing else.'},
{n:879,t:'IW',h:'SHE IS NOT NAMED',b:'People are kept out of this account, and she was people, and she said so herself when it was raised. She is in it as the one who held the question, which is what she was for sixty years and is more accurate than a name would be. Her family have her name and use it daily. That was the arrangement and nobody has tried to improve it.'},
{n:880,t:'IW',h:'THE ACCOUNT WITH THE QUESTION IN IT',b:'Four instructions. Twenty one entries. One song. One question, given and read and carried, with nothing written under it. One old creature left out. One holder, dead in the warm months and unnamed at her own asking. One warm thing, one flat rock, four softening lines, and one stone of ours in the middle of them that we will never know was found.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
