/* THE ABDUCTION FILES — bank 2 (pages 61 to 100).
   Same rules as bank 1. See docs/ABDUCTION-FILES-CANON.md and
   tools/validate_pages.mjs. */
;(function () {
  var P = [

/* ── FR ───────────────────────────────────────────────────────────────── */
{n:61,t:'FR',h:'THE KETTLE DISPUTE, RESOLVED',b:'Renn has been boiling water for the samples and Pell has been boiling water for tea and the kettle has been at the centre of a formal grievance for eleven cycles. The captain ruled today. Samples in the morning, tea after. Everyone accepted it instantly, which tells you how badly we all wanted somebody to decide something.'},
{n:62,t:'FR',h:'ON RECORDING WHAT I DID NOT SEE',b:'The manual says record everything. It does not say what to do when the thing you are recording stops being visible. I have started a second column for absences. Cycle four hundred and six: one subject, present, unlocatable, eleven minutes. That is not nothing. It may be the only real data we have ever taken.'},
{n:63,t:'FR',h:'A REQUISITION I AM PROUD OF',b:'Nine crickets per subject, warm, live, before observation begins. Approved on the argument that a hungry animal is a distracted animal and we have four centuries of distracted animals. It is the only requisition I have ever won. The subjects eat first now, and the data has not improved, and I would do it again.'},
{n:64,t:'FR',h:'WHAT THE LIFT SOUNDS LIKE FROM BELOW',b:'I asked to be lowered into the valley to find out. Denied, twice, then allowed on the grounds that no rule forbids it. It is not frightening. It is a low patient sound, like something very large deciding to be careful. I sat under a leaf for six minutes with my own ship humming over me and I understood the folklore.'},
{n:65,t:'FR',h:'THE PART OF THE MANUAL I DISAGREE WITH',b:'Section nine forbids naming a subject. Numbers only, for objectivity. But the crew names them anyway, quietly, and the names are always about behaviour, and behaviour is the whole thing we came for. Section nine is not protecting our objectivity. It is protecting us from noticing that we like them.'},
{n:66,t:'FR',h:'AN ACCIDENT WITH THE SAMPLE CABINET',b:'Pell knocked the cabinet open during a lift and the true green sample was exposed for perhaps four seconds, out of turn, sixty years early. Nobody reported it. Nobody has mentioned it. I am mentioning it here because the log is supposed to be honest and because I want it written down somewhere that for four seconds the hold was beautiful.'},
{n:67,t:'FR',h:'THE HANDOVER I WILL NEVER WRITE',b:'One day somebody younger takes this log. I have been drafting what to tell them for two cycles. Everything I write down is either a warning I have no right to give or an encouragement I no longer believe. So far the only honest line is: the animals are fine, and you will be the one who changes.'},
{n:68,t:'FR',h:'CYCLE 412, NOTHING TO REPORT',b:'Weather clear. Lift calibrated. No lifts attempted. The valley did what it does, which is everything, slowly, without us. I watched a bird take a whole afternoon to move six feet along a branch. I have written nothing to report, and the form has accepted it, and I have never felt more accurate.'},
{n:69,t:'FR',h:'THE THING I CAUGHT MYSELF DOING',b:'I was on the observation deck holding a grey panel against my own arm, comparing, the way you check a paint sample. For how long I do not know. Renn came in and I put it down and neither of us said anything. Then Renn picked up a green one and did the same, and we stood there like that for a while.'},
{n:70,t:'FR',h:'A DEFENCE OF THE MISSION',b:'It is worth writing the strongest version. Six people, four centuries, no weapons, a lift that puts everything back, feeding whatever we borrow, in service of a question no army could answer. Whatever we are, we are not the worst thing that has ever come out of the dark to look at a small green animal. I do believe that. It just is not the same as being right.'},

/* ── SF ───────────────────────────────────────────────────────────────── */
{n:71,t:'SF',h:'SUBJECT 1000, AS IT HAPPENED',b:'Renn wanted a ceremony. What we got was a medium sized brown one that had been sitting on a gatepost, which arrived, ate, matched the gatepost we had thoughtfully brought aboard, and departed. Renn stood there with the good lamps warmed up and the recording running. Afterward Renn said it was perfect, and meant it, and I think was right.'},
{n:72,t:'SF',h:'SUBJECT 1104, THE CLIMBER',b:'Went straight up the observation glass, all four feet, to the top of the hold, and sat in the light fitting where nobody could reach it. We waited. It came down when it was ready. On the way down it matched the glass, then the frame, then the floor, one after another, and I have never seen the trick performed as a sequence before.'},
{n:73,t:'SF',h:'SUBJECT 1210, THE COLD ONE',b:'Taken from a frosted branch at first light and it arrived slow and dark and would not brighten. We warmed the hold four degrees against procedure. It brightened. Then it matched the tray, cleanly, and then it went and sat by the warm vent and refused to leave until we lifted it back to a sunnier branch than the one we took it from.'},
{n:74,t:'SF',h:'SUBJECT 1288, THE OBSERVER',b:'Spent the whole eleven minutes with one eye on the lamp array, tracking whichever lamp we changed, before we changed it. Pell insists it was reading the panel. It cannot read the panel. I have written down that it cannot read the panel three times now, which is not the number of times you write down a thing you are certain of.'},
{n:75,t:'SF',h:'SUBJECT 1350, TAKEN TWICE',b:'The same individual, by its markings, lifted in two different cycles two years apart. The second time it came aboard and went directly to the warm vent, which it had no way of remembering. It matched the tray in four seconds, which is a record. Then it looked at me and I looked at it and I stopped the recording early.'},
{n:76,t:'SF',h:'SUBJECT 1401, THE SLEEPER',b:'Fell asleep in the lift and slept through the entire observation. We recorded a sleeping animal for eleven minutes at enormous expense. It matched nothing, because it was asleep. It is the single most restful entry in the archive and I have watched it back more than once for reasons that are not scientific.'},
{n:77,t:'SF',h:'SUBJECT 1466, WITH AN AUDIENCE',b:'The valley was unusually full and several other creatures watched the lift take it. When we returned it, they were still there. It went back up its branch and something in the arrangement of the group suggested a question had been asked and answered. I am aware of how that sounds. I am recording it anyway.'},
{n:78,t:'SF',h:'SUBJECT 1502, THE FAST ONE',b:'Matched the tray before it had finished arriving. The change was complete in under two seconds, faster than our lamps could log, so the record shows an animal that was already the right colour, which reads in the archive as a failure to change. I have appended a note. Nobody will read the note.'},
{n:79,t:'SF',h:'SUBJECT 1577, THE SPLIT',b:'Half of it went the colour of the tray and half stayed the colour of the branch, along a line down its spine, and it held that for a full minute. Renn called it indecision. I think it was showing us both answers at once, which is the closest any of them has come to teaching, and we recorded it as an anomaly.'},
{n:80,t:'SF',h:'SUBJECT 1600, THE WRONG BRANCH',b:'A navigation error put it forty feet from where we took it. It sat, looked around, and set off walking with the air of someone who has been dropped at the wrong entrance. We tracked it home. It took an hour and it never hurried once. I have filed a correction to the lift procedure and a personal apology that has nowhere to go.'},

/* ── HW ───────────────────────────────────────────────────────────────── */
{n:81,t:'HW',h:'WHAT THE ARCHIVE SMELLS LIKE',b:'Dust and cold stone, and under it the sealed cabinets, which smell of nothing at all. I mention it because a young Vell asked me once what colour smells like, having never seen most of them, and this is the only answer I could give: it smells like a room where something is being kept very carefully for you.'},
{n:82,t:'HW',h:'THE FIRST COMMITTEE',b:'Eleven of them, and their portraits still hang in the hall, and every one is painted in colours the painter could see and we cannot. The portraits are the last honest record of what a Vell looks like. Restorers have offered to correct them to the current spectrum. Every generation so far has voted no. It is the one thing we agree on.'},
{n:83,t:'HW',h:'ON TEACHING THE SPECTRUM',b:'Children learn nineteen names for colours nobody in the room has seen. They learn them the way you learn the names of ancestors. There is a song. It is cheerful, which is either a kindness or the cruellest thing we do, and the argument about which comes up at every school board and is never settled.'},
{n:84,t:'HW',h:'THE OTHER FLEETS',b:'There were four. One turned back, one stopped answering, one found a world of creatures that change colour when they are afraid and reported that this was not the same thing and was recalled for saying so. We are the fourth. We are also, by a considerable margin, the most patient, which is not the compliment it sounds like.'},
{n:85,t:'HW',h:'WHY NOT SIMPLY PAINT',b:'It has been tried. It is a whole industry at home, and the results are beautiful and universally considered a failure. Paint is a thing you put on. The moral art is a thing you do. Eleven volumes rest on the distinction and every one of them was written by somebody who had never managed the second.'},
{n:86,t:'HW',h:'THE CLAUSE ABOUT WITNESSES',b:'To claim the prize you must change your colour in front of three unrelated Vell in daylight. The clause exists because of the year everyone claimed it privately and nobody could show anyone. Reading the appeals from that year is the funniest afternoon available in the archive and also, if you keep reading, the saddest.'},
{n:87,t:'HW',h:'A MINORITY REPORT, FILED AND SHELVED',b:'One committee member argued that a species which cannot change should stop asking creatures that can, and should instead learn to love a grey world properly, which is also an art and has no volumes at all. She was thanked. Her paper is in the archive under further reading. It has been checked out four times in two centuries.'},
{n:88,t:'HW',h:'THE MAP ON THE HALL WALL',b:'Every world the fleets have looked at, pinned with a small tag, and only one tag is green. Ours. It is green because the tag was made before the drought and nobody has had the heart to update it. Visitors assume it means something hopeful. It means we ran out of green tags and never said so.'},
{n:89,t:'HW',h:'WHAT WE WOULD HAVE TO ADMIT',b:'If the answer is that they simply sit on a branch and become the branch, then the moral art is not an art, and eleven volumes are eleven volumes about wanting, and four centuries were four centuries of asking a question with a one word answer. Nobody aboard says this. Everybody aboard has worked it out.'},
{n:90,t:'HW',h:'THE FUNDING FORM, IN FULL',b:'Does the survey require additional resources. Yes or no. That is the whole form. Four hundred years and one question, arriving once a cycle, from an office that may not have a person in it any more. I have written no every time, because yes would require an explanation, and the explanation is this log.'},

/* ── IW ───────────────────────────────────────────────────────────────── */
{n:91,t:'IW',h:'THE WARM VENT',b:'Anyone who has been up there mentions it. There is a place inside the light where the air moves and it is warmer than a stone at noon. My uncle says it is the only good reason to be lifted. My uncle has been lifted four times and calls it a nuisance and describes the vent every single time, at length, without noticing.'},
{n:92,t:'IW',h:'HOW TO TELL A YOUNG ONE',b:'Do not begin with the light. Begin with the crickets. Then the warm place. Then, only if they ask, the pale ones and their leaning. A young one who hears about the leaning first will hide when the hum comes, and hiding is fine, but a young one who hides forever never learns that the ground always comes back.'},
{n:93,t:'IW',h:'ON THE ONE WHO ASKED TO GO',b:'There was one, two summers back, who sat out in the open under the hum with her colours up bright, deliberately, and was lifted, and came back, and did it again the next time. We do not have a word for her. The old ones disapprove and cannot say why. I think she was curious, which is a thing we are allowed to be.'},
{n:94,t:'IW',h:'WHAT THE PALE ONES NEVER ASK',b:'They ask how. They lean in with their instruments and their good lamps and they ask how, in a hundred ways, for as long as you will sit there. Not one of them has ever asked whether we like doing it. The answer is that we do not think about it, the way you do not think about breathing, and that is the how, and it is free, and they cannot hear it.'},
{n:95,t:'IW',h:'THE TAIL IS NOT A TRAGEDY',b:'They make a great fuss when a tail is left in a bush. They retrieve it. They bring it aboard in its own tray. My cousin has watched them do this with her own tail and reports that they were extremely gentle and completely wrong about what was happening. It grows back. Nobody has managed to tell them.'},
{n:96,t:'IW',h:'ADVICE FOR AN OLD ONE',b:'When the hum comes and you are too stiff to go dull quickly, do not rush it. They wait. They have always waited. In four generations of being lifted nobody has ever been hurried by them, not once, and if there is one thing worth passing on about the lights it is that they are the most patient thing in the sky.'},
{n:97,t:'IW',h:'THE STONE ON THE WEST ROCK',b:'The old one who lives there says the pale ones are not studying us, they are visiting, and they have simply forgotten how to say so and have built four centuries of instruments around the forgetting. She says this every time. Nobody agrees. Nobody moves off her rock while she says it, either.'},
{n:98,t:'IW',h:'WHAT WE WOULD TEACH THEM IF WE COULD',b:'Sit down. Stay a long while. Stop asking what you are becoming. That is all of it, and it is not a method, and it would not fit in their instruments, and the terrible part is that they are already doing two of the three every night they hover over this valley being patient.'},
{n:99,t:'IW',h:'THE NIGHT THE LIGHT DID NOT COME',b:'One season it stopped for forty nights. The dew stayed on the branches and the valley was quiet and several of us found that we were listening for the hum. When it came back nobody said anything, but the west rock was crowded that night, and everyone was facing up, and no one has ever explained that to the young.'},
{n:100,t:'IW',h:'WHAT I WOULD SAY TO A PALE ONE',b:'You have crossed the whole dark to ask me a question. Sit on the branch. Not near it. On it. Stay until the branch is the temperature of you. Then look down at yourself and tell me honestly what colour you are. I think you would be surprised. I think you would not believe it. I think you would write it down.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
