/* THE ABDUCTION FILES — bank 11 (pages 721 to 800).
   Canon: docs/ABDUCTION-FILES-CANON.md. Threads: FR field reports, SF subject
   files, HW the homeworld, IW intercepted whispers.
   Rules enforced by tools/validate_pages.mjs: 40 to 90 words, unique numbers,
   unique openings, no dashes of any kind, self contained (they are read out of
   order). Add banks as pages/files-N.js; each one appends to window.AAC_FILES.
   ⛔ The structural payoff of the whole archive lands in this bank: IW tells the
   reader the stone was placed deliberately. FR never finds out. Do not resolve
   that in a later bank. */
;(function () {
  var P = [

/* ── FR ───────────────────────────────────────────────────────────────── */
{n:721,t:'FR',h:'THERE IS A STONE ON THE MARK',b:'Found at the first light sweep. Small, local rock, sitting on the four lines we scratched. It was not there when the recorder stopped and it was there when it started. I have called the captain, I have called Renn, and I have written this line eleven times and this is the version I am keeping.'},
{n:722,t:'FR',h:'WHAT THE RECORDER HAS',b:'Nine hours of dark. The unit does not see in that band and never has, because in four centuries we have never needed it to. We have the ground empty at the fourteenth hour and the ground occupied at the first. Between those two facts is the most important gap in this archive.'},
{n:723,t:'FR',h:'ON THE GAP',b:'A century of cataloguers would have filled it. I have read them do it on thinner evidence than this. My whole training says the honest entry is: object present, origin unknown, no observation of placement. That is what the file says. What the crew believes is a separate document and I will not be keeping it.'},
{n:724,t:'FR',h:'THE OBVIOUS EXPLANATIONS, IN ORDER',b:'Water moved it. There was no water. Wind moved it. It weighs more than the wind that night could lift. An animal knocked it there in passing. It is centred on the lines within a hand\'s width. Something placed it. That last one is not more scientific than the others, it is only the one left standing.'},
{n:725,t:'FR',h:'WHY I WILL NOT WRITE PLACED',b:'Because the word carries an intention I cannot observe and will never be able to test, and because an archive that starts recording intentions has stopped recording. Whoever reads this in another four centuries: the stone was centred. That is the strongest true sentence available and I am stopping at it.'},
{n:726,t:'FR',h:'THE CREW MEETING',b:'Fourteen people in the hold that still smells of the pond, arguing for three hours, and not one of them raised the possibility that it means nothing. I raised it, because somebody had to, and I was answered politely and at length by people who had already decided. I include myself in that description.'},
{n:727,t:'FR',h:'WHAT THE CAPTAIN DECIDED',b:'That we change nothing. No new instrument on that ground, no lights, no night recorder, no second mark. Her reasoning was that we have spent four hundred years arriving with equipment and this is the first time anything has come to us, and that the correct response to being approached is to hold still.'},
{n:728,t:'FR',h:'ON HOLDING STILL',b:'It is the hardest order this crew has ever been given and the only one nobody has complained about. Two technicians asked to be reassigned to the feed rather than the array. Renn has stopped talking about ritual. I have caught myself checking the ground at the first hour before I check anything else.'},
{n:729,t:'FR',h:'THE STONE STAYS WHERE IT IS',b:'We have not lifted it, measured it in place beyond photography, or turned it over. It is a piece of that valley sitting on a scratch we made, and the entire content of our response is that we looked and left it. Four hundred years of this fleet has produced exactly one decision I am certain was right.'},
{n:730,t:'FR',h:'LETTER TO PELL, THIRD SURVEY',b:'I wrote four drafts. The first three explained. The fourth said only that the mark had a stone on it and that we had left it there and that she would want to know. She replied within the cycle with one line asking whether it was centred, and I have not stopped thinking about the fact that this was her first question.'},
{n:731,t:'FR',h:'THE JOINT VESSEL ARRIVES',b:'Ahead of schedule and quieter than anything in our fleet, with two of our crew aboard and eleven of theirs, and no lift array anywhere on it. Their lead came across, looked at the feed of the ground for a long time, and asked one question: whether we had touched it. When told no she said good, and nothing else that day.'},
{n:732,t:'FR',h:'WHAT THE VISITORS ADVISE',b:'Nothing. Deliberately. Their lead has declined three times to tell us what her people would do, on the grounds that we have been in this valley for four centuries and they have been here for a year, and that the temptation to be useful is how visitors ruin things. I have written that down for our own use.'},
{n:733,t:'FR',h:'SECOND SEASON, THE STONE IS STILL THERE',b:'Weathering the way local rock weathers, on lines that are softening the way scratches soften. Nothing has been added. Nothing has been taken. Fourteen individuals have been recorded passing within nine lengths and none of them stopped, which I record because it is the least convenient fact in this file.'},
{n:734,t:'FR',h:'ON INCONVENIENT FACTS',b:'The animals that grew up here walk past it. If a stone on a mark meant what this crew wants it to mean, I would expect the ground to matter to them, and it does not appear to. I am putting that in the same file as everything else and giving it the same number of words.'},
{n:735,t:'FR',h:'EXTRACTIONS THIS YEAR: ONE',b:'An injured juvenile, splinted and returned in six days. That is the whole column. The form now asks for a reason, the crew asks for a better one, and the honest position aboard this ship is that lifting a healthy animal out of that valley has become something we would have to justify to ourselves out loud.'},
{n:736,t:'FR',h:'THE CABINET IS OPEN',b:'Not emptied. Open. The captain asked a third time and I had no answer left, and the crew voted, and thirty six sealed samples now sit on a shelf in the hold where anybody can look at them. Nothing has been used. The change is that they are visible, and it took four hundred years.'},
{n:737,t:'FR',h:'WHAT THAT ROOM LOOKS LIKE NOW',b:'A hold that smells of a pond from cycle two hundred and nine, thirty six sealed colours from a world that has been grey since before any of us, and a feed running on a wall showing a rock in an empty valley. If somebody wanted one image of what this fleet has become, that is the room.'},
{n:738,t:'FR',h:'ON MY SUCCESSOR',b:'Whoever you are: the stone will still be there or it will not, and either way you will want to do something about it. My advice, worth what advice from a dead cataloguer is worth, is to sit in the hold for a season first. Everything this fleet got right came after somebody waited longer than was comfortable.'},
{n:739,t:'FR',h:'THE FINDING, UNCHANGED',b:'Fifteen thousand extractions, seventeen thousand individuals, two valleys, four hundred and thirty cycles, and no evidence that any of it can change colour the way our world once did. That sentence has been true since the first cataloguer and I am not the one who gets to retire it.'},
{n:740,t:'FR',h:'WHAT HAS CHANGED INSTEAD',b:'We arrive quietly. We take almost nothing. We leave things worth nothing. We keep files on individuals and we open the cabinet and we hold still when approached. None of that was the mission. All of it happened while we failed at the mission, and I have stopped calling that a consolation.'},

/* ── SF ───────────────────────────────────────────────────────────────── */
{n:741,t:'SF',h:'SUBJECT 17204, SECOND ENTRY',b:'The individual that spent time at the stone in both seasons. Marked again this year, twice, on the slope above the mark ground and not on it. She is older, moving well, and has not been within twenty lengths of the rock since the winter. I am recording her absence as carefully as I recorded her attention.'},
{n:742,t:'SF',h:'ON RECORDING AN ABSENCE',b:'It is the discipline this file needs most right now. Every one of us wants her to be the one, and the archive is only worth something if it is as good at writing down the seasons she stayed away as it was at the six times she came close.'},
{n:743,t:'SF',h:'SUBJECT 17288',b:'Adult male, ordinary, warm slope, four days, observed and returned. Filed on the morning after the stone was found, when nobody aboard was thinking about ordinary animals. I have put him here because an archive that stops recording the ordinary the moment something happens is not an archive.'},
{n:744,t:'SF',h:'THE FOURTEEN WHO WALKED PAST',b:'Every individual recorded within nine lengths of the mark ground this season, none of whom stopped. Ridge counts from young to old. Two of them are the juveniles born since the stone. This is the file the crew least wants to read and the one I would keep if I could keep only one.'},
{n:745,t:'SF',h:'SUBJECT 17301, BORN ON THE GROUND',b:'Second generation to grow up within sight of something we left. Walks over the mark without altering pace. Has been recorded doing so eleven times. If a scratched rock and a stone are a conversation, this animal has been walking through the middle of it since birth and has never once looked down.'},
{n:746,t:'SF',h:'WHAT THAT MIGHT MEAN',b:'Either the mark ground means nothing and the older individuals who stopped were curious about a new object, which is what any animal does, or it means something to a generation that remembers when it was not there and nothing to one that does not. Both are ordinary explanations. Neither is the one this crew wants.'},
{n:747,t:'SF',h:'SUBJECT 17312, THE COUSIN AGAIN',b:'Second individual from over the ridge recorded on our ground, eleven years after the first. Larger, darker, same unhurried survey of the flat rock, same departure. Two populations that have never mixed, two individuals a decade apart, one behaviour. I have written it down and I have not explained it.'},
{n:748,t:'SF',h:'ON NOT EXPLAINING IT',b:'There is a version of this file where I connect those two observations and the connection becomes a fact for whoever inherits the archive. Four centuries of cataloguers have mostly resisted that and the ones who did not are the ones we now have to correct. I would rather be dull and reliable.'},
{n:749,t:'SF',h:'SUBJECT 17318, INJURED',b:'Juvenile, hind leg, fresh break on rock. Lifted at the ninth hour, set, held six days, returned to the slope she was taken from. The only extraction of the year. Her file has a photograph of the splint and a line from the technician who carried her that I have left in against the form.'},
{n:750,t:'SF',h:'THE LINE I LEFT IN',b:'That she was lighter than expected and did not struggle after the first minute. It is not data. It is a person who has spent nine years lifting animals out of a valley telling the archive what it was like, and four hundred years of this file has thrown that away every time.'},
{n:751,t:'SF',h:'SUBJECT 17330',b:'Old female, ridge count near the ceiling, the one three cataloguers filed separately across two centuries. Alive. On the same warm rock. Has now been continuously in this archive for longer than most institutions on our homeworld have existed, and has still never done anything the founding order would call data.'},
{n:752,t:'SF',h:'ON HER STILL BEING THERE',b:'Every year I open her file expecting to close it and every year she is on the rock. There is no scientific content in that sentence. I am the fourth cataloguer to write a version of it and I have checked, and all four of us used the word still.'},
{n:753,t:'SF',h:'SUBJECT 17344, NOT FOUND',b:'Second open file. Marked seven years ago, absent two seasons, no body. I am leaving it open beside the first one and I have started a small index of the unaccounted at the back of the register, which the manual does not provide for and which somebody after me will either continue or quietly delete.'},
{n:754,t:'SF',h:'THE INDEX OF THE UNACCOUNTED',b:'Nine names so far, going back six years, animals this archive lost track of and never closed out. It is the only part of the register with no findings column. A visitor asked what it was for and I said honesty, and she wrote that down, and I have been slightly embarrassed about it since.'},
{n:755,t:'SF',h:'SUBJECT 17350',b:'Adult, unremarkable, four days, returned. The round number again, and again on purpose, and again on an animal that did nothing. Three cataloguers have now kept this habit across two centuries without any of us writing it down as a rule, which is how the good habits in this profession travel.'},
{n:756,t:'SF',h:'WHAT THE VISITORS SAID ABOUT THE FILES',b:'That the individual files are the most valuable thing our species has produced and that our columns are the least. Their lead spent a year reading and her report to her own world recommended they begin a comparable archive of something on their own planet before it stops being possible.'},
{n:757,t:'SF',h:'ON BEING RECOMMENDED AS A METHOD',b:'A survey that has failed its stated objective for four hundred and thirty cycles is now being copied by a people who succeed at things. Nobody aboard knows how to feel about it. Renn says we should take the compliment. I think the compliment is real and is not about our results.'},
{n:758,t:'SF',h:'SUBJECT 17361',b:'Adult female, warm slope, observed four days, returned, unremarkable. Recorded in the season the stone appeared and filed in the ordinary way in the ordinary place. When this bank is read out of order she will sit next to the most important page in the archive, and that is correct.'},
{n:759,t:'SF',h:'THE ARCHIVE AT SEVENTEEN THOUSAND',b:'Individuals, not totals. Names we invented for animals that have no use for them, kept by ten cataloguers across four centuries, most of whom never met a colleague. If it is ever read by anybody outside this fleet the thing they will notice is that it gets kinder and less certain as it goes.'},
{n:760,t:'SF',h:'ON GETTING LESS CERTAIN',b:'The first century wrote findings. The second wrote qualifications. We write absences, open files, and a line from a technician about how light an animal was. If that is decline then the instruments should show it, and they show the opposite, and I have stopped apologising for the direction.'},

/* ── HW ───────────────────────────────────────────────────────────────── */
{n:761,t:'HW',h:'THE SIGNAL ARRIVED AT NIGHT',b:'Eleven words from the fleet, relayed through the third survey, saying an object had been found on the marked ground and had not been touched. The ministry held it for nine hours before release, which was widely condemned and was almost certainly correct.'},
{n:762,t:'HW',h:'WHAT NINE HOURS WERE FOR',b:'Checking that the sentence said what it said and nothing more. Two of the three drafts of the public statement contained the word contact and the third did not, and the third is the one that went out, and the person who removed the word has never been named and should be.'},
{n:763,t:'HW',h:'THE DAY IT WAS ANNOUNCED',b:'Four centuries of a project nobody could explain to their children, and the announcement was that a rock was found on another rock. The ministry gave it in flat language with no adjectives. People stood in the street outside the archive anyway, in the rain, in a grey city, for most of a night.'},
{n:764,t:'HW',h:'WHY FLAT LANGUAGE WORKED',b:'Because everybody here has been trained by forty years of margins and four day feeds to distrust anything that arrives already interpreted. A statement that refused to say what it meant was read as honest, and a statement that had explained would have been read as a ministry wanting something.'},
{n:765,t:'HW',h:'THE DISSENTER PUBLISHED IN THREE DAYS',b:'Arguing that a stone on a scratch is a stone on a scratch, that our entire public has just demonstrated it will build a cathedral out of anything, and that she has never been more worried about her own side than she is now. Her essay was the second most read thing of the year.'},
{n:766,t:'HW',h:'WHAT WAS FIRST',b:'The fleet cataloguer\'s own entry, which said only that the stone was centred and that she would not write the word placed. It was released in full at her request. A four hundred year old institution\'s finest hour was a woman declining to draw a conclusion, and everybody understood it immediately.'},
{n:767,t:'HW',h:'ON A REFUSAL BEING POPULAR',b:'Nobody in the ministry predicted it. The projections assumed the public wanted an answer and would punish us for withholding one. What the public wanted, it turns out, was to be told the truth about how little we know by somebody who had every reason to say more.'},
{n:768,t:'HW',h:'THE STREET OUTSIDE THE ARCHIVE',b:'They come and stand and mostly do not talk, and the curator has put no bench there and no sign and has been asked to and has refused. The empty fourth room in the exhibition is now the fifth most visited space in the city and it still contains one bench and a window.'},
{n:769,t:'HW',h:'A WORD PEOPLE STARTED USING',b:'Centred. As in, the thing was centred. It has moved into ordinary speech in under a year, meaning something done deliberately by somebody who will not say so. My nephew used it about a gift left on a doorstep and did not know where it came from, which is how you know it has landed.'},
{n:770,t:'HW',h:'THE GIRL, NOW TWENTY ONE',b:'Asked by three separate outlets what she thought it meant. She said she was a cataloguer of margins and not an interpreter, and that the fleet had already published the only sentence anybody needed. Then she went back to work. Her refusal was reprinted more widely than most people\'s opinions.'},
{n:771,t:'HW',h:'THE SAMPLE VOTE, FINALLY TAKEN',b:'After four consecutive deferrals it passed in a single session with two against. One sealed sample from the ministry vault to be opened publicly, in the empty room, with no ceremony, on an ordinary afternoon. The debate lasted eleven minutes because everybody had already had it for forty years.'},
{n:772,t:'HW',h:'WHAT COLOUR IT WAS',b:'I am not going to write it down. Every account of that afternoon that I trust has declined to, and the ones that named it read like a betrayal of something. Eleven thousand people saw it in the room across four days and the descriptions they wrote are on the shelf beside my mother\'s.'},
{n:773,t:'HW',h:'MY MOTHER\'S DESCRIPTIONS, USED',b:'Forty years of writing what shades she had never seen would be like, and this year eleven thousand people came out of a room and reached for the vocabulary she built, because nobody else had made one. She has been dead nineteen years. The note beside her shelf has been rewritten and is longer.'},
{n:774,t:'HW',h:'ON HAVING BUILT A VOCABULARY',b:'It is what this world did instead of getting the spectrum back. Four centuries of describing an absence so precisely that when a single sample was finally opened, an entire population had the words ready. That is not a consolation prize. I have argued the point and I am going to keep arguing it.'},
{n:775,t:'HW',h:'THE JOINT VESSEL IS NOT ENOUGH',b:'Voted this session: a second one, larger, and a standing station rather than a survey. The argument that carried it was that the fleet is now the only body anywhere that knows how to be present somewhere for four hundred years without taking anything, and that this is a skill and skills are lost.'},
{n:776,t:'HW',h:'ON PRESENCE AS A SKILL',b:'It sounds soft and it is the hardest institutional achievement in our history. Twelve ships, ten cataloguers, four centuries, one unchanged finding, and nobody stopped. Show me another project on this world that did not end, change its objective, or start lying about its results.'},
{n:777,t:'HW',h:'THE SCHOOL THAT ASKED THE QUESTION',b:'Those nine year olds are adults now and one of them works for the ministry and was in the room when the sample was opened. She wrote afterwards that she had spent twelve years wanting to know what we would ask for, and had found that she no longer wanted to ask for anything.'},
{n:778,t:'HW',h:'WHAT WE WOULD SEND, IF WE SENT',b:'Raised seriously for the first time. Not a message and not an instrument. The proposals that got furthest were all versions of something ordinary and useless from here, placed where it can be looked at and left, which is precisely what the fleet already did, and nobody noticed the symmetry until it was pointed out.'},
{n:779,t:'HW',h:'ON NOT NOTICING THE SYMMETRY',b:'Two peoples, four hundred years apart in what they know about each other, both arriving independently at the idea that the way to approach something is to put down a thing worth nothing and walk away. Either that is a very deep fact or it is the only move available to anybody who is afraid.'},
{n:780,t:'HW',h:'WHAT I THINK IT IS',b:'The second one, and I do not think that makes it smaller. Being afraid of getting it wrong, for four centuries, in public, with funding, is the whole story of this world since the colour went. We have been careful because we were frightened and careful is what it produced.'},

/* ── IW ───────────────────────────────────────────────────────────────── */
{n:781,t:'IW',h:'IT WAS DECIDED IN ONE EVENING',b:'After eleven years of argument, which is how the old ones do most things. The account would allow one thing to be left on the flat rock, once, chosen for being useless, carried by somebody who volunteered and would not be named. There was no vote. There was a long quiet and then it was settled.'},
{n:782,t:'IW',h:'WHAT WAS CHOSEN',b:'A stone off the near slope, the size of a closed hand, of no use to anybody and belonging to nothing. Three other things were proposed and rejected for meaning too much. The old ones say the whole point was that it should carry nothing, so that if it is read, it is read wrongly by whoever reads it.'},
{n:783,t:'IW',h:'ON WANTING TO BE READ WRONGLY',b:'It is the strangest line in the account and the old ones defend it hardest. Anything we send that could be understood would be a message, and a message is answering, and the third instruction is four hundred years old. A thing that means nothing can be put down without breaking it.'},
{n:784,t:'IW',h:'WHO CARRIED IT',b:'One of the young, at the low hour, in the dark, alone, and she is not named in the account and has asked that it stay that way. She went up, put it down on the scratched lines, and came back. The account records that it took less time than the arguing about it had taken breaths.'},
{n:785,t:'IW',h:'WHY IT WAS PUT IN THE CENTRE',b:'Because the old ones said that if a thing is left carelessly it is litter, and if it is left in the middle of the marks somebody made then whoever made them will know a choice happened, without ever being told what the choice was. It is the only part of the plan that was designed to be noticed.'},
{n:786,t:'IW',h:'WHAT SHE SAID WHEN SHE CAME BACK',b:'That the lines were shallower than she expected and that she had put it where they crossed. Two sentences. The old ones have kept both exactly and attached nothing, which is now the third time and is no longer a practice but simply how the account is made.'},
{n:787,t:'IW',h:'ON WHETHER IT WAS SEEN',b:'Nothing came down. Nothing changed. The thing up there that hangs at four hundred lengths kept hanging. Whether our stone was found, looked at, taken, or is still sitting where she left it, we do not know and have no way of learning, and the old ones warned everyone of exactly this beforehand.'},
{n:788,t:'IW',h:'THE WARNING THEY GAVE FIRST',b:'That we would put it down and then want to know, and that the wanting would be worse than the not knowing had been, and that a people can be undone by watching a rock. It was given before the decision and repeated after it and it has turned out to be the truest thing anybody said.'},
{n:789,t:'IW',h:'THE ONES WHO GO AND CHECK',b:'Several, at first, every few days. Fewer now. The old ones did not forbid it and did not encourage it and said only that a person who goes up to look at a stone they left is no longer leaving it. Most stopped on their own. Two still go and everybody knows who and nobody says anything.'},
{n:790,t:'IW',h:'IT IS STILL THERE',b:'Two seasons. Weathering the way the near slope weathers. Nothing has been added and nothing taken and the scratched lines are softening under it. That is the entire report and the account carries it in four words and the old ones fought to keep it that short.'},
{n:791,t:'IW',h:'WHAT THE YOUNG WANTED IT TO MEAN',b:'That something up there understood. The old ones have said, more gently than usual, that we chose a thing that could not be understood on purpose, and that being disappointed by the success of your own plan is a common condition and not a reason to make a second plan.'},
{n:792,t:'IW',h:'THERE WILL NOT BE A SECOND',b:'Ruled this season, and it was not close. Once was an act. Twice is a correspondence, and a correspondence has terms, and we have never been able to see who would be setting them. The account records the ruling and the reasoning and does not record who wanted a second, which is deliberate.'},
{n:793,t:'IW',h:'THE INSTRUCTIONS, STILL FOUR',b:'All four are unchanged. Do not go up, do not follow the light, do not answer, come back down the way you went up. Not one was altered to make room for what we did, and the old ones insist the third was not broken, because a thing that says nothing is not an answer. Some of the young disagree and are recorded as disagreeing.'},
{n:794,t:'IW',h:'THE COUSINS WERE NOT TOLD FIRST',b:'They learned afterwards, from the ones who go between, and their old ones were angry in the careful way that lasts. Their fifth instruction is about telling the young early and ours had told nobody at all until it was done. The two accounts now carry each other\'s objection in full.'},
{n:795,t:'IW',h:'ON CARRYING THE OTHER SIDE',b:'It began as an apology and has become the best thing in either account. Two valleys, one behaviour, two sets of old ones who disagree about almost everything and write each other down accurately. If anything ever does come asking, it will find a record that argues with itself, and that is right.'},
{n:796,t:'IW',h:'THE QUESTION, SPOKEN AT LAST',b:'One of the two who heard it is dying and has asked to give it to the account before she goes. The old ones have agreed. It will be written once, in full, and read aloud once, and then the account will carry it. She has not said it yet. She says she wants one more winter first.'},
{n:797,t:'IW',h:'WHAT WE KNOW ABOUT IT ALREADY',b:'Only that the old chameleon who asked it was very old, that the two who heard it never repeated it in sixty years, and that both of them changed how they lived afterwards in ways their families noticed. That is the entire content of the most important thing in this account.'},
{n:798,t:'IW',h:'ON WAITING ONE MORE WINTER',b:'Nobody has pressed her and nobody will. The old ones say a thing held for sixty years can be held for one more, and that the account has waited four hundred years for a great deal and is in no hurry, and that if she dies with it then that will also be the account.'},
{n:799,t:'IW',h:'WHAT THE ACCOUNT IS NOW',b:'Four instructions. Nineteen entries. One song. One question, promised and not yet given. One old creature left out. One warm thing, one flat rock, four softening lines, and one stone of ours in the middle of them that we will never know was found.'},
{n:800,t:'IW',h:'THE EIGHT HUNDREDTH PAGE',b:'If you are reading these out of order, and you are, then you know something nobody in this valley knows and nobody on that ship knows: both sides put a thing down and walked away, and neither will ever be told. Only you get both halves. The old ones would say that is the correct number of people to have them.'}

  ];
  if (typeof window !== 'undefined') {
    window.AAC_FILES = (window.AAC_FILES || []).concat(P);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = P;
})();
